matrix-org/matrix-js-sdk

src/client.js
Callers assume that if the account data isn't there, the method will
return null rather than throw an exception. This meant that this only
actually worked in these cases when the sync had completed and it was
using the locally stored account data, so this ceased to be a
problem in practice when we made it wait for the initial sync to finish
before entering the security setup flow.
Fixes https://github.com/vector-im/riot-web/issues/13169
=> Make getAccountDataFromServer return null if not found

src/client.js, src/store/memory.js
The not-found scenario was broken, as the server returns status code 400 instead of 404. This was not triggered before, but since https://github.com/matrix-org/matrix-js-sdk/pull/1332 it did, because the deep comparison failed because limit is now set on the filter. This caused "undefined" to be stored in the store, triggering the not-found scenario on reload.
While at it I rewrote `getOrCreateFilter` to use `await` rather than chaining `then(...)`.
Please also review release PR at https://github.com/matrix-org/matrix-js-sdk/pull/1341
=> Fix: handle filter not found

src/crypto/index.js, src/crypto/olmlib.js
The cause of this I've seen is us sending keyshare reqiests when
we didn't have keys but them arriving when we do, and us replying to
ourseles with keys, so exclude that explicity.
Also catch this lower down to catch any other code paths that
mistaklenly try this. Hopefully the comment explains enough as to why
it won't work.
=> Prevent attempts to send olm messages to ourselves

src/crypto/algorithms/megolm.js, src/models/event.js
I think this was attempting to remove the events from _pendingEvents
but a) it wasn't and b) it probably shouldn't be because the retry
itself will re-add them when the decryption attempt starts and remove
them if it succeeds.
Also fix what was presumably a c+p fail.
=> Remove some dead code from _retryDecryption

src/crypto/index.js
Bootstrap was creating key backup versions twice due to some code duplication we missed in
previous refactorings.
Fixes https://github.com/vector-im/riot-web/issues/13423
=> Remove redundant key backup setup path

src/client.js
local echo events were only given the sender in v1 form, which is fine when using the `getSender` event abstraction but when we're looking at the `unsigned.redacted_because` lets ensure both v2 and v1 forms are there for consistency.
Part of https://github.com/matrix-org/matrix-react-sdk/pull/4484
=> Fix sender of local echo events in unsigned redactions

CHANGELOG.md, src/client.js, src/crypto/DeviceList.js, src/crypto/SecretStorage.js, src/crypto/index.js, src/crypto/verification/Base.js, src/crypto/verification/QRCode.js, src/models/room.js
Add an event fired before devices are updated, so apps can monitor
changes in devices by observing the state before and after.
BREAKING CHANGE:
Make getStoredDevices/getStoredDevicesForUser synchronous so they
can safely be called from the event listener without racing with
the data being updated. They didn't do any async work so didn't need
to be async.
Add doc for crypto.devicesUpdated
=> Add crypto.willUpdateDevices event and make getStoredDevices/getStoredDevicesForUser synchronous

src/crypto/verification/Base.js, src/crypto/verification/request/VerificationRequest.js
This came up during the last cross-signing smoke test, where the verification just stalls with a spinner because the .key event of the other party was ignored while still sending the .accept event.
Fix this by looking in the received events Map in the verification request first.
=> Handle race between sending and await next event from other party

src/crypto/index.js
This should not be a problem for verification in DM as the event we sent ourselves would always create the verification request first before processing the .ready. As to_device doesn't have remote echo, we need this mitigation.
=> Fix race between sending .request and receiving .ready over to_device

src/client.js, src/crypto/index.js
This allows distinguishing the "unknown" case from "not present".
Part of https://github.com/vector-im/riot-web/issues/13404
Used by https://github.com/matrix-org/matrix-react-sdk/pull/4534
=> Return null for key backup state when we haven't checked yet

src/crypto/index.js
This will cause our own user trust status to change, so emit an
event to say so.
=> Emit event when a trusted self-key is stored

src/crypto/algorithms/megolm.js
The timeouts on the two phases of olm session creation are 2 and 10
seconds respectively, so sessions will fail if servers take more
than 10s to respond. Now that we have two phases, we can afford to
wait longer on the second one because the user's isn't waiting for
it to finish before the message will send, so increase it to 30s
so servers have more of a chance to respond.
=> Increase timeout for 2nd phase of Olm session creation

src/pushprocessor.js
We did this in two places: updated existing rules when the rules
were stored and then added new ones every time we computed push
action for an event. Just do both when the rules are saved.
The two different methods appeared in https://github.com/matrix-org/matrix-js-sdk/pull/1006 and https://github.com/matrix-org/matrix-js-sdk/pull/860
=> Combine the two places we processed client-level default push rules

src/crypto/index.js
This check was meant to filter out key sharing requests from ourselves. Accidentally, it filtered out sharing requests from anyone *but* ourselves.
Signed-off-by: Sorunome <mail@sorunome.de>
=> Fix replying to key share requests

spec/unit/interactive-auth.spec.js, src/base-apis.js, src/interactive-auth.js, src/utils.ts
This fix has a companion PR over at react-sdk. https://github.com/matrix-org/matrix-react-sdk/pull/4347
This fix is tested with synapse and works fine on matrix.org!
This fix is required for https://git.koesters.xyz/timo/matrixserver which implements the r0.6.0 spec. In that spec version it says that auth shouldn't be `auth: {}` but rather not be present. This fix should fix this. I tested it both with synapse and the linked server to check that everything still works
Signed-off-by: Marcel Radzio<mtrnord1@gmail.com>
=> Make auth argument in the register request compliant with r0.6.0

src/client.js
Cache expiration is still not implemented here.
(the failures are because I've failed to configure a media repo correctly)
=> Batch up URL previews to prevent excessive requests

src/client.js
Presence lists were [removed in r0.5.0](https://github.com/matrix-org/matrix-doc/pull/1817). I don't believe Riot makes use of these, though I cannot vouch for other apps. I assume removing this would require a major version bump though.
=> Drop presence list methods

spec/unit/crypto/verification/verification_request.spec.js, src/crypto/verification/request/VerificationRequest.js
Fixes https://github.com/vector-im/riot-web/issues/12430
Implements https://matrix.org/docs/spec/client_server/latest#key-verification-framework
> The prompt for Bob to accept/reject Alice's request (or the unsupported method prompt) should be automatically dismissed 10 minutes after the timestamp field or 2 minutes after Bob's client receives the message, whichever comes first, if Bob does not interact with the prompt. The prompt should additionally be hidden if an appropriate m.key.verification.cancel
=> Fix verification request timeouts to match spec

src/crypto/SecretStorage.js
Should give a more informative error message when something like https://github.com/vector-im/riot-web/issues/13105 happens.
=> Fix: more informative error message when we cant find a key to decrypt with

spec/unit/crypto/secrets.spec.js, src/client.js, src/crypto/index.js
Introduced in https://github.com/matrix-org/matrix-js-sdk/pull/1311 and removed in https://github.com/matrix-org/matrix-js-sdk/pull/1375 because thought not needed anymore.
Turns out this migration only seems to run on new logins or when restoring a backup, things users (like myself) might not have done since the format bug was introduced, so this can still cause problems for users trying out cross-signing on develop.
An alternative would be to tell all users that have this problem and tried cross-signing on develop to reset their key backup and 4S.
=> Bring back backup key format migration

src/interactive-auth.js
Fixes https://github.com/vector-im/riot-web/issues/13990
Regression caused by https://github.com/matrix-org/matrix-js-sdk/commit/bebeec7d84295a994036502974e76f3327ef842f
=> Use existing session id for fetching flows as to not get a new session

spec/unit/crypto/backup.spec.js, spec/unit/crypto/cross-signing.spec.js, spec/unit/crypto/crypto-utils.js, spec/unit/crypto/secrets.spec.js, spec/unit/crypto/verification/sas.spec.js, src/client.js, src/crypto/CrossSigning.js, src/crypto/EncryptionSetup.js, src/crypto/index.js
Part of https://github.com/vector-im/riot-web/issues/13581
Isolate encryption bootstrap side-effects into an `EncrypionSetupOperation` and run them all at once, as a step towards a retry-able bootstrap operation.
Left to do:
This contains **breaking changes**:
- `resetCrossSigningKeys` method is removed.
- `authUploadDeviceSigningKeys` parameter of `bootstrapSecretStorage` is now required.
=> Isolate encryption bootstrap side-effects

src/client.js, src/crypto/EncryptionSetup.js, src/models/room-state.js, src/models/room.js, src/sync.js
This is to better support the react-sdk in trying to identify what actually changed in settings instead of re-firing everything. 
Overall this change differs from `prev_content` semantics as it's the last known *stored* event, not whatever the server thinks may or may not have changed.
For https://github.com/matrix-org/matrix-react-sdk/pull/4803
=> Raise the last known account data / state event for an update

src/models/room.js
It's common to add listeners for every displayed Matrix event, so this increases
the default to remove some log noise.
=> Increase max event listeners for rooms

src/crypto/EncryptionSetup.js, src/crypto/index.js
Fixes https://github.com/vector-im/riot-web/issues/14113
If 4S already exists during bootstrapping, the adapter crypto callbacks won't have the privkey yet, and 4S operations start failing. To fix, delegate to the general crypto callbacks.
=> Ask general crypto callbacks for 4S privkey if operation adapter doesn't have it yet

examples/node/app.js, src/models/room-state.js
**Requires https://github.com/matrix-org/matrix-react-sdk/pull/4936**
**We probably do not want to land this until after an RC as it is very high risk.**
Though the dictionary format works fine, it's slow. Access times are around the 1ms range for rooms like HQ, which doesn't seem like much, but when compared to the Map's access time of 0.05ms it's slow.
Converting things to a map means we lose index access and have to instead use `.keys()` and `.values()`, both of which return iterables and not arrays. Even doing the `Array.from()` conversion we see times in the 0.05ms range. This is also what makes this a breaking change.
Memory-wise there does not appear to be any measurable impact for a large account.
=> [BREAKING] Convert RoomState's stored state map to a real map

src/client.js, src/models/event.js
This allows the app to access an identifier on the event which does not change as the event gets sent, helps with Element accessibility (and less remounting)
=> Properly support txnId

src/client.js, src/crypto/index.js
Useful to see the number of keys waiting for backup (it's exposed
via events but you couldn't get it directly). Also clarify doc on
the return value of `flagAllGroupSessionsForBackup` which was not
technically incorrect...
=> Expose countSessionsNeedingBackup

.eslintrc.js, package.json, yarn.lock
These are no longer needed with the new standard lint repo.
=> Remove redundant lint dependencies

README.md
It seems that with ES6 Promises being apparently used, the reference to `done()` is outdated (ES6 Promises [do not implement `done`](https://stackoverflow.com/questions/26667598/will-javascript-es6-promise-support-done-api)).
Also clarifies that it is "problematic" to discard the results of promises rather than it being an "error" .
=> Update on Promises

spec/unit/crypto/cross-signing.spec.js, src/crypto/EncryptionSetup.js, src/crypto/index.js
In order to handle auth errors (such as incorrect passwords), we need to ensure
we only try to upload cross-signing keys from within the auth flow helper
function.
This rearranges things to store that function in the builder to use it when the
actual upload happens.
Noticed while working on https://github.com/vector-im/element-web/issues/14954
=> Handle auth errors during cross-signing key upload

src/client.js
This allows clearly detecting whether we have _ever_ fetched .well-known at all.
Without this, it's hard to be sure whether the value is `undefined` because the
fetch has not been attempted yet or because an error occurred.
Part of https://github.com/vector-im/element-web/issues/14954
Used by https://github.com/matrix-org/matrix-react-sdk/pull/5130
=> Add method to check whether client .well-known has been fetched

src/models/event.js
State events are never encrypted, so we can ignore them here.
=> Add state event check

spec/unit/crypto/cross-signing.spec.js, spec/unit/crypto/secrets.spec.js, src/client.js, src/crypto/CrossSigning.js, src/crypto/EncryptionSetup.js, src/crypto/index.js
This untangles cross-signing and secret storage setup into separate path that
can be invoked independently. There is no functional change with this patch, but
instead this just separates one giant monster API into two.
Part of https://github.com/vector-im/element-web/issues/13895
Used by https://github.com/matrix-org/matrix-react-sdk/pull/5149
=> Untangle cross-signing and secret storage

src/crypto/CrossSigning.js, src/crypto/index.js
This improves several error paths when cross-signing keys aren't available, such as when verifying a new device.
Part of https://github.com/vector-im/element-web/issues/14970
=> Handle missing cross-signing keys gracefully

src/matrix.ts
This makes the examples in the README actually compile.
=> Add missing options in ICreateClientOpts

src/base-apis.js
We only inject if needed to avoid potentially overwriting the value with something unknown. The docs in the react-sdk imply this was supposed to happen.
Fixes https://github.com/vector-im/element-web/issues/14814
=> Inject identity server token for 3pid invites on createRoom

src/client.js
matrix-js-sdk will block attempts to send events to encrypted rooms by default if you've not enabled the crypto parts of the library. There are special reasons for which I need to use Pantalaimon as a proxy for some bridge work, so I need the SDK to not block attempts in this case, as the upstream library will take care of it.
I'd like to propose this flag to let developers opt to ignore such warnings. I also couldn't really decide upon a flag name, so suggestions welcome!
=> Add option to allow users of pantialaimon to use the SDK

src/crypto/CrossSigning.js, src/crypto/index.js
This includes changes to avoid an error when resetting if secret storage if you only have some but not all cross-signing keys. It also changes the path for caching from secret storage so it will try to cache private keys whenever they are missing as well as on private key change.
Fixes https://github.com/vector-im/element-web/issues/15230
=> Repair secret storage reset, cache keys when missing

src/crypto/index.js
This was triggering security prompts at random times (after any device list
update).
Fixes https://github.com/vector-im/element-web/issues/15250
=> Undo attempts to cache private keys aggressively

src/http-api.js
=> If there are extraParams set, ensure that queryParams is defined

src/crypto/CrossSigning.js, src/crypto/index.js
This changes the key backup setup step to only sign with cross-signing keys when
both the public and private keys are already available without prompting. In
many cases down these paths, the cross-signing keys either may not exist or may
not be accessible. We always sign the key backup with your device key as well,
so there is always a route to trust the key backup even if this is skipped.
Fixes https://github.com/vector-im/element-web/issues/15230
=> Only sign key backup with cross-signing keys when available

src/client.js
Otherwise they leak out ot the sync loop. It's unfortunate that
exceptions from event handlers leak out to the emitter, and this
seems a bit clumsy, but having to wrap eveery event emit in a try
block seems worse.
=> Catch exception from call event handler

src/client.js
This implements passing a reason for the redaction as per https://matrix.org/docs/spec/client_server/r0.6.1#id254
Disclaimer: @fridtjof, @mythozz and @badgateway666 made me do this :p
=> extend method redactEvent with reason

.eslintrc.js, spec/olm-loader.js, spec/unit/crypto/CrossSigningInfo.spec.js, spec/unit/crypto/cross-signing.spec.js, spec/unit/crypto/secrets.spec.js, spec/unit/crypto/verification/util.js, src/client.js, src/crypto/CrossSigning.js, src/crypto/OlmDevice.js, src/crypto/SecretStorage.js, src/crypto/index.js, src/crypto/verification/QRCode.js, src/http-api.js, src/logger.js, src/models/relations.js, src/pushprocessor.js
This adds lint rules (and fixes various errors) to ensure we use the `logger`
intermediary module, rather than accessing the console directly.
=> Enforce logger module via lint rules

spec/unit/crypto/DeviceList.spec.js, src/crypto/DeviceList.js
This change ensure we always keep the local device in the device list, even if
the server claims it doesn't exist. This is important for initial startup, as it
is possible the device key upload takes a while to apply, and thus might not
appear in the first device list sync.
Fixes https://github.com/vector-im/element-web/issues/15319
=> Keep local device after processing device list sync

src/client.js, src/models/event.js
The one listener in react-sdk listens on the MatrixClient and it never gets re-emitted there.
It isn't very useful on Room as during app-launch we do not have the Room available to bind the re-emmission
=> Fix re-emit of Event.replaced to be on client and not room

src/webrtc/call.ts
It's deprecated so generally nothing should be passing it
=> Make 'options' parameter optional

spec/unit/sync-accumulator.spec.js, src/models/event.js, src/store/indexeddb-local-backend.js, src/sync-accumulator.js
We've always had 'age' in events but it's never really been an
accurate representation of the event's age because we never did
anything with it. This transforms it into a local clock timestamp
when the event arives and when it comes out of the sync store, and
changes getLocalAge() to use it.
react-sdk doesn't appear to use getLocalAge() but any 3rd party apps
that do may notice a slight change in bahaviour.
=> Make an accurate version of 'age' for events

package.json, spec/unit/crypto/secrets.spec.js, src/client.js, src/crypto/EncryptionSetup.js, src/crypto/SecretStorage.js, src/crypto/index.js, src/matrix.ts
Various small tweaks and alignments to match React SDK as part of TypeScript
conversion.
Part of https://github.com/vector-im/element-web/issues/15350
Used by https://github.com/matrix-org/matrix-react-sdk/pull/5307
=> Adjust types and APIs to match React SDK

src/client.js, src/webrtc/call.ts, src/webrtc/callEventHandler.ts
* Split out call event handling into its own class
* Convert it to TypeScript
* Update to use getLocalAge()
* Add grace period to avoid ringing unless the user will actually have time to accept the call
First 3 commits are the extraction / TS conversion: the actual change is in the last commit.
=> Use new local timestamp for calls

src/client.js, src/webrtc/call.ts, src/webrtc/callEventHandler.ts
* Set 'connecting' state before sending answer, otherwise it can
race with ICE connecting
* Ignore completed ice connection state: connected is what we care about
* Null-check remotestream when stopping media
* Comments
Based on https://github.com/matrix-org/matrix-js-sdk/pull/1499
Actual diff: https://github.com/matrix-org/matrix-js-sdk/compare/pull/1499/head...pull/1503/head
=> Fixes for call state machine

.gitignore
=> Remove specbuild from .gitignore

src/@types/event.ts, src/webrtc/call.ts, src/webrtc/callEventHandler.ts
Start the migration to v1 VoIP by supporting m.call.reject, which
we'll send if the caller says they're v1. Our version stays as v0
for now, until we speak the rest of v1.
Honour the default reaosn in a hangup being user_hangup.
=> Support m.call.reject

spec/TestClient.js, spec/unit/webrtc/call.spec.js, src/@types/event.ts, src/webrtc/call.ts, src/webrtc/callEventHandler.ts
Send party_id on events and check the party_id of incoming events matches
Includes a basic test to assert that it actually does: we should
build out a decent test suite for calls as there's a lot of edge-case
functionality that can break and slip through the cracks (eg. glare).
This is a start (although it would be nice if we could write the tests
in TypeScript).
Fixes #1511
Based on: https://github.com/matrix-org/matrix-js-sdk/pull/1510 (https://github.com/matrix-org/matrix-js-sdk/compare/pull/1510/head...pull/1512/head)
=> Support party_id

package.json, spec/TestClient.js, spec/unit/webrtc/call.spec.js, spec/unit/webrtc/call.spec.ts, src/@types/event.ts, src/webrtc/call.ts, src/webrtc/callEventHandler.ts, yarn.lock
Typescript tests basically just appear to work, apart from needing
the jest types imported so the typescript checker knows what's what.
Convert the webrtc test to typescript, which actually mostly just
serves to point out that we're not mocking the whole of `document`,
but oh well.
Based on: https://github.com/matrix-org/matrix-js-sdk/pull/1512 (https://github.com/matrix-org/matrix-js-sdk/compare/pull/1512/head...pull/1516/head)
=> Convert call test to TypeScript

release.sh
The merges are never edited, and even with this change they will still abort if
there are conflicts.
=> Skip editor prompts for merges

src/models/room.js
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/1504
It is called in 3 places which assumed it would not throw, IMO its a little bit strict for it to throw.
=> [Breaking] Change hasPendingEvent to return false if pending ordering !detached

release.sh
This ensures we always install (without running build scripts) as the first step
of release process, as otherwise it may fail later due to mismatched types or
any number of other errors.
=> Install deps first as part of release

src/client.js
Otherwise we never recover
Fixes https://github.com/vector-im/element-web/issues/15509
=> Don't cache failures when fetching /versions

spec/unit/webrtc/call.spec.ts, src/@types/event.ts, src/webrtc/call.ts, src/webrtc/callEventHandler.ts
Only send one if the answer has a party_id set
Also change some event types to the enum and rename receivedAnswer
to be more consistent
=> Support m.call.select_answer

src/sync.js
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine
https://developer.mozilla.org/en-US/docs/Web/API/Document/ononline
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events
Even though the event should bubble up to the window from the body, in testing I could only ever see it fire on the window directly. Tested in Chrome and Firefox latest stable
=> bind online listener to window instead of document

src/crypto/index.js
`isStoredInKeyCache` is async, so we need to await the result to know whether to
proceed. In addition, this wraps the block in a try / catch, since signing the
key backup is an optional step.
**Reviewer:** Maybe review commit by commit for easier reading
Fixes https://github.com/vector-im/element-web/issues/15530
=> Await key cache check to avoid prompts

src/client.js
https://github.com/matrix-org/matrix-js-sdk/pull/1537 changed some dehydration
method names, but one call site was missed.
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/1543
=> Fix dehydration method name

src/webrtc/call.ts
This function is *always* called when a MatrixClient is created, e.g. in
an appservice. If the environment does not support WebRTC, this is not
necessarily an error; it is expected in many situations.
=> Don't log error when environment does not support WebRTC

package.json
Now that the pipeline has been updated to build for tests, we can remove this
temporary build in the test script.
Related to https://github.com/matrix-org/pipelines/pull/113
=> Remove temporary build step for tests

src/webrtc/call.ts
if we're in the ringing state
Fixes https://github.com/vector-im/element-web/issues/15933
=> A hangup from another client is still valid

package.json
It seems I misunderstood the `postinstall` script and had thought it would only
run when installing the project root. Instead, it seems to run also as a
dependency as well.
This change should be fine for release, but it does mean when developing
the JS SDK, you'll need to manually build. CI pipelines may also need to be
changed to call an extra build step.
=> Remove `postinstall` script which also runs as a dependency

package.json, release.sh
This changes the JS SDK to point `main` to TypeScript source and remove any
indication of `typings`. For local development and CI workflows, it means many
steps can run without building first, which saves lots of time.
During release, we still build for Node and browsers as before. The release
script adjusts the `main` and `typings` fields before publishing and
distribution to point to the built output for those that use them.
Summary of improvements:
* `yarn install` no longer runs a build step
* Linting and (most) tests don't need a build step either
* CI runs are faster by several minutes as a result
Part of https://github.com/vector-im/element-web/issues/15987
=> Use TypeScript source for development, swap to build during release

src/client.js
This is needed for https://github.com/matrix-org/matrix-react-sdk/pull/4897.
Synapse PR: https://github.com/matrix-org/synapse/pull/7785
MSC: matrix-org/matrix-doc#2666
=> Add _unstable_getSharedRooms

src/webrtc/call.ts
as hopefully explained in comment
=> Don't log if no WebRTC

src/client.js
If we're not allowed to have TURN access, there's no reason to ask in a loop.
=> Stop retrying TURN access when forbidden

src/crypto/algorithms/megolm.js, src/crypto/index.js
We may not have managed to set up the backup yet when we get keys.  So we should unconditionally queue up the keys for backup, so that when the backup is set up, they will be sent instead of dropped.
=> Queue keys for backup even if backup isn't enabled yet

spec/unit/matrix-client.spec.js, src/client.js
Expose the `getPresence` endpoint in the client server API through `MatrixClient`:
https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-presence-userid-status
Currently only the `setPresence` endpoint is exposed.
Signed-off-by: tzyl <tim95@hotmail.co.uk>
=> Expose getPresence endpoint

src/crypto/algorithms/megolm.js
This extra debug logs may help isolate the cause of https://github.com/vector-im/element-web/issues/16194.
These changes also fix a related (but most likely different) failure mode: if a failure occurred in the `encryptionPreparation` async task, we would skip trying to prepare in all future attempts for that room. This change ensures prep failures are logged and we resume prep attempts on the next call from the application.
=> Add debug logs to encryption prep

src/webrtc/call.ts
Hopefully explained by the comments: Firefox sees that it's been
put on hold and tries to negotiate itself off hold again.
Fixes https://github.com/vector-im/element-web/issues/16190
=> Fix extra negotiate message in Firefox

src/webrtc/call.ts
Should make the logs a bit clearer
=> Log the call ID when logging that we've received VoIP events

src/webrtc/call.ts
https://github.com/matrix-org/matrix-js-sdk/pull/1567 introduced a
bug where we'd leave opponentPartyId undefined, but we compared it
to null later when testing for its presence.
Fixes https://github.com/vector-im/element-web/issues/16239
=> Fix compatibility with v0 calls

src/crypto/index.js, src/models/event.js
This PR adds support for decrypting redaction events. This is useful for displaying encrypted redaction reasons
=> Decrypt redaction events

src/scheduler.js
If a server happens to give a negative retry time, this would be passed to
`setTimeout`, and browsers interpret negative values as `0`, meaning "as soon as
possible", so we then start looping infinitely with no delay.
=> Guard against confused server retry times

src/webrtc/call.ts
Regressed by [#1570](https://github.com/matrix-org/matrix-js-sdk/pull/1570)
=> Fix browser screen share

src/@types/global.d.ts
This changes to an interface for Electron types so that other layers can merge
in further APIs as needed.
Related to https://github.com/vector-im/element-web/pull/16405
=> Fix Electron type merging

src/webrtc/call.ts
We were seeing call IDs of NaN in the wild somehow... hopefully this
should make sure they're all actually strings.
=> Fix call ID NaN

src/webrtc/call.ts
Apparently this is perfectly valid javascript and somehow casts
this.callId to a number... possibly it's ignoring the whitespace
and treating it as `++this.callId`?
=> Remove rogue plus character

spec/unit/ReEmitter.spec.ts, src/ReEmitter.ts
As hopefully explained by lengthy comment
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/1569
=> ReEmitter: Don't throw if no error handler is attached

src/webrtc/call.ts
Accompanied by [#5632](https://github.com/matrix-org/matrix-react-sdk/pull/5632)
Hopefully explained by the comment
Without this, a call could fail without the `CallView` disappearing from the room
=> Handle undefined peerconn

src/webrtc/call.ts
This avoids an error which would otherwise appear if no desktop capturer source was selected
=> Cancel call if no source was selected

src/crypto/algorithms/megolm.js, src/crypto/olmlib.js
This continues work from https://github.com/matrix-org/matrix-js-sdk/pull/1580 and adds more logging, including specialised logging for a potential cause of https://github.com/vector-im/element-web/issues/16194.
So far, it seems clear that something's going wrong in the "sharing keys with new Olm session" step.
=> Add more debug logs to encryption prep

src/models/room-state.js, src/models/room.js
Subset of https://github.com/matrix-org/matrix-js-sdk/pull/1563
=> Room helpers for invite permissions and join rules

spec/unit/webrtc/call.spec.ts, src/webrtc/call.ts
The main bug here was a race on the callee side because we await-ed
on setRemoteDescription before setting the opponent party ID, and
while we were await-ing, the callEventHandler could give us candidate
events which we'd duly ignore because we thought the party ID didn't
match.
This also meant that any candidates that arrived before the answer
would have been ignored. Save these up by party ID and then add the
ones from the party ID that we pick once the answer comes in.
Also fix the confusion on party IDs where we weren't sure whether
we hadn't picked an opponent or we'd picked an opponent without a
party ID. It's now undefined for the former and null for the latter,
as it claims to be in the comment.
Oh yes, and also remove the 'msg' member from call which does
indeed appear to be …
=> Don't ignore ICE candidates received before offer/answer

src/matrix.ts
This was previously exporting a promise, since it called the import function manually but didn't await the result. However, since we have Babel we can just use the new export … as … from syntax instead.
=> Fix ContentHelpers export

src/client.js
We currently don't support edits from other senders, but the server may not
filter them, so we filter them here on the client.
=> Filter out edits from other senders in history

package.json, spec/unit/crypto/algorithms/olm.spec.js, src/crypto/olmlib.js
This reworks tracking the Olm sessions a particular task is updating to avoid deadlocks. By ensuring we synchronously mark all sessions a task cares about as in progress from the start, we know that no other tasks will own updating a session in common, which avoids deadlocks across multiple tasks that might be working on a shared set of devices.
The potential for deadlocks first appeared with https://github.com/matrix-org/matrix-js-sdk/pull/857 (2 years ago), but I believe it would be unlikely for most users to trigger this deadlock during normal usage. The app would need to be sluggish enough to permit stacking up several messages in different rooms with devices in common, which is most likely only possible on larger accounts. In any case, with this change, this process should now avoid …
=> Avoid deadlocks when ensuring Olm sessions for devices

src/models/room-member.js
This changes to constant patterns for calculating display names, which cuts out ~18% of the time spent and reduces GC pressure as well.
=> Extract display name patterns to constants

src/webrtc/call.ts
This is an _attempt_ to make the handling of constraints a bit cleaner. It should also be useful for implementing midcall device changes.
@dbkr is probably the best reviewer for this.
=> An attempt to  cleanup how constraints are handled in calls

src/@types/global.d.ts
As far as I can tell this shouldn't be here... I accidentally copied the `export` keyword along with the rest of the declarations when I wrote this
=> Remove export keyword from global.d.ts 

src/webrtc/call.ts
When we get user media, don't forget to close the streams if the
call's ended by the time we got media.
=> Stop streams if the call has ended

src/client.js
Added as the final argument to `invite` in order to keep backwards compatibility.
=> Support sending invite reasons

spec/unit/webrtc/call.spec.ts, src/client.js, src/webrtc/call.ts, src/webrtc/callEventHandler.ts
Hopefully this should make our turn-credential checking code a bit
more robust (and possibly fix a seconds / ms mismatch).
See also https://github.com/matrix-org/matrix-react-sdk/pull/5730
=> Check TURN servers periodically, and at start of calls

src/webrtc/call.ts
Web apps shouldn't be forced to provide a callback since they don'ŧ need it
=> Make selectDesktopCapturerSource param optional

src/webrtc/call.ts
* Don't ignore other candidates when we see a null one (continue
rather than return)
* await on addICECandidate()
* Don't add ice candidates until we've set a remote description
* More & better logging
=> More VoIP connectivity fixes

spec/unit/crypto/DeviceList.spec.js, spec/unit/utils.spec.js, src/crypto/DeviceList.js, src/utils.ts
As described in #1619, the server might overload if the number of users in the key request is too large. To prevent this, the download is broken into chunks of 250 users each. Responses are processed once all chunks have been downloaded.
I picked the chunk size more or less arbitrarily following the observations in #1619. Happy to change it if a different value seems more appropriate.
Also, this is my first ever contribution so I'm hoping I at least didn't screw it up totally. :see_no_evil: 
Signed-off-by: Johannes Marbach <n0-0ne+github@mailbox.org>
=> Download device keys in chunks of 250

src/base-apis.js
Otherwise the client will have the default `_guest = false` and it will try to pushrules when doing the initial sync which will fail
This will set `client._guest = true` on the client even if it fails to register as a guest.
I could wrap the callback in some fancy logic (help needed)... buuut I guess people shouldn't rely on `.registerGuest()` failing and not having side-effects
Signed-off-by: Nicolai Søborg <matrix@xn--sb-lka.org>
=> docs: registerGuest()

src/webrtc/call.ts
Don't send `m.call.hangup` if `m.call.invite` wasn't sent either (this happens when getting user media fails before sending an invite)
=> Don't send m.call.hangup if m.call.invite wasn't sent either

spec/unit/crypto/cross-signing.spec.js, src/crypto/index.js
This is a revised version of https://github.com/matrix-org/matrix-js-sdk/pull/1472 which was previously reverted for causing security prompts to appear on device list sync. In this version, we only allow private key requests (which are likely to trigger user dialogs) if we are coming from the bootstrap path.
This allows sessions that have already synced cross-signing public keys but never got the private keys for some reason to make forward progress when e.g. the user triggers bootstrap from security settings.
=> Cache cross-signing private keys if needed on bootstrap

src/client.js, src/crypto/OlmDevice.js, src/crypto/algorithms/megolm.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/memory-crypto-store.js
Implements https://github.com/matrix-org/matrix-doc/pull/3061
=> Add function to share megolm keys for historical messages, take 2

src/webrtc/call.ts
Fixes vector-im/element-web/issues/16747
Switched `CallType` before async function calls  in `/src/webrtc/call.ts` that were causing the `showMediaCaptureError` in `matrix-react-sdk/src/CallHandler.tsx` to skip all the conditions and hence causing a generic error.
Signed-off-by: Ayush Pratap Singh ayushpratap16@gmail.com
=> Fixed the media fail error on caller's side

src/crypto/index.js
This removes some catch blocks originally added by https://github.com/matrix-org/matrix-js-sdk/pull/1472 so that higher level operations can handle them as needed.
Part of https://github.com/vector-im/element-web/issues/15584
Needed for https://github.com/matrix-org/matrix-react-sdk/pull/5812
=> Remove catch handlers in private key retrieval

src/crypto/index.js
This tweaks https://github.com/matrix-org/matrix-js-sdk/pull/1649 to only try caching private keys locally once we've confirmed they exist first. This most likely only an issue in tests, where we sometimes create only some but not all keys.
=> Only try to cache private keys we know exist

spec/unit/room.spec.js, src/models/room.js
Fixes vector-im/element-web#7177
This pull requests hooks into the `Room#_pendingEventList` flow to store a serialised version of an unsent `MatrixEvent`.
The storage key is: `mx_pending_events_${roomId}`
Upon instanciation the `Room` model will query the storage and populate `_pendingEventList` if required. Element then picks up the unsent messages and display the `RoomStatusBar` and a user can decide whether to send or cancel the queued messages
=> Persist unsent messages for subsequent sessions

src/sync.js
Some platforms (e.g. React Native) register global.window, but do not have global.window.addEventListener. In this case, this function should not be called.
Signed-off-by: Jan Pawellek <jpawellek@churchtools.de>
=> Fix calling addEventListener if it does not exist

src/models/event.js, src/models/room.js
Fixes vector-im/element-web#16914
Regression introduced by matrix-org/matrix-js-sdk#1655
I incorrectly tried to remove pending events in `updatePendingEvent` when this reconciliation is the responsability of that transaction ID. This PR sets that `txnId` attribute properly and remove the need to explicitely call `removePendingEvent` as the event is now going through the usual timeline flow
@t3chguy raised an [interesting comment](https://github.com/matrix-org/matrix-js-sdk/pull/1655#discussion_r611412326) in my previous pull request that is adressed here. The `txnId` is now persisted in storage and re-used at a later stage to ensure idempotency
=> Fix timeline jumpiness by setting correct txnId

src/pushprocessor.js
A user had some misconfigured push rules, where `pattern` was not set. This lead to the following error during sync:
```
ERROR  Caught /sync error TypeError: Cannot read property 'replace' of undefined
at escapeRegExp
at globToRegexp
at createCachedRegex
at eventFulfillsEventMatchCondition
at eventFulfillsCondition
at anonymous
at matchingRuleFromKindSet
at matchingRuleForEventWithRulesets
at pushActionsForEventAndRulesets
```
the push rule looks like this:
```json
{"actions": ["notify", {"set_tweak": "highlight", "value": false}], "conditions": [{"key": "type", "kind": "event_match"}], "rule_id": "undefined"} env: {"content": {"join_rule": "invite"}, "event_id": undefined, "origin_server_ts": undefined, "room_id": "!yPQVkxldbDQFVCFqcY:redacted.com", "sender": …
```
=> Fix sync with misconfigured push rules

src/models/room-state.js
Fixes vector-im/element-web#16967
The `RoomState.members` event was propagated for every single room member even though their power level was not impacted.
This was tested on a room on a local synapse instance with 2000 members
The frame takes **90% less time** to process you can see in the two recording screenshots below
=> Restrict event emit for room members that had power levels changed

spec/unit/webrtc/call.spec.ts, src/@types/event.ts, src/client.js, src/webrtc/call.ts, src/webrtc/callEventHandler.ts
Adds support for receiving MSC3086 Asserted Identity events & emitting event from the call object.
Also moves the method for creating new calls to the client so it can be stubbed out when testing applications using the js-sdk (the client was passed in before so I'm not sure what the benefit was of it being separate).
=> Support MSC3086 asserted identity

package.json
This makes it clear to how collect basic test coverage when desired.
See also https://github.com/matrix-org/matrix-react-sdk/pull/5937
=> Add test coverage collection script

spec/integ/megolm-integ.spec.js, spec/test-utils.js, src/client.js, src/crypto/algorithms/megolm.js, src/models/event.js, src/models/room.js, src/sync.js
Related to vector-im/element-web#13266
To review alongside matrix-org/matrix-react-sdk#5980
When loading element, it will either read from cache the entire `/sync` blob that has been persisted or will query that information from Synapse.
The idea is to implement a priority queue that will cap the maximum of events that will be decrypted on application startup. Everything else will be lazily decrypted when a user views a room
At the moment, from clicking on a tile to having all messages displayed on screen it takes roughly a second. With lazy decryption it will approximately take 2 seconds but the most recent messages will start to appear on screen from the first second.
This pull request brings the concept of critical events. These are the events that a client requires to have decrypted …
=> Prioritise and reduce the amount of events decrypted on application startup

src/client.js, src/crypto/index.js, src/models/event-timeline-set.js, src/models/relations.js, src/webrtc/callEventHandler.ts
Fixes vector-im/element-web#17290
Related to vector-im/element-web#13266
Regressed by matrix-org/matrix-js-sdk#1684
The code was expecting events to already be decrypted when it reaches that block of code. I have added a bit of logic to wait for relations to be decrypted before it mutates the target event
=> Decrypt relations before applying them to target event

src/client.js, src/webrtc/callEventHandler.ts
Fixes vector-im/element-web#17393
Regressed by matrix-org/matrix-js-sdk#1684
The call event handler was expecting all messages to be decrypted or in the process of being decrypted and would not process any call events until everything has been processed.
The fix is to ignore all historical data by setting the listeners only after initial client sync
=> Change call event handlers to adapt to undecrypted events

src/models/room.js, src/utils.ts
Fixes vector-im/element-web#17370
Approximatly divides the function execution time by three. Here is the difference of the two call stacks
=> Cache normalized room name

src/models/room.js
Currently my account is logging ~20,000 warnings a minute about getType() being called
on invites which have no m.room.create events, which crashes my inspector and makes
my console unusable.  We still want the logline though, as it helps diagnose
space invite problems.  So instead, log this only once.  (Untested).
=> Only log once if a Room lacks an m.room.create event

src/webrtc/call.ts
This disables a common log message to cut down the test log size and make it easier to read messages specific to each test.
=> Reduce noise in tests

src/http-api.js
This was causing an `/upload` 500 ISE to resolve and thus send broken media events into rooms
=> Fix uploadContent not rejecting promise when http status code >= 400

spec/unit/relations.spec.ts, src/models/event-timeline-set.js, src/models/relations.js
This changes the "relations created" event to ensure it is properly emitted even if the target event is added to the timeline after the relation event. There was perhaps always a risk of this happening in the past, but is seems more likely to bite now with delayed decryption.
Part of https://github.com/vector-im/element-web/issues/17461
Related to https://github.com/matrix-org/matrix-react-sdk/pull/6106
=> Emit relations created when target event added later

src/webrtc/call.ts
And fix hangup reasons in reject events
=> Add user_busy call hangup reason

src/models/room-state.js
Signed-off-by: Lars Richard <lars.richard@iserv.eu>
Closes #1722
=> Ignore power_levels events with unknown state_key on room-state initialization

src/webrtc/call.ts
'Replaced' is special cased so the media isn't torn down, but we
were passing Replaced for calls we transferred off elsewhere which
meant we never closed the media capture. Calls transferred elsewhere
aren't really replaced: they may as well have their own code.
=> Add separate reason code for transferred calls

spec/MockBlob.ts, spec/unit/NamespacedValue.spec.ts, spec/unit/matrix-client.spec.js, spec/unit/models/MSC3089Branch.spec.ts, spec/unit/models/MSC3089TreeSpace.spec.ts, spec/unit/utils.spec.js, spec/unit/utils.spec.ts, src/@types/event.ts, src/@types/requests.ts, src/NamespacedValue.ts, src/client.ts, src/models/MSC3089Branch.ts, src/models/MSC3089TreeSpace.ts, src/utils.ts
This is a ***heavily opinionated*** set of classes to help downstream projects implement file trees. There is no UI component to this (for now). As an unstable implementation, this has known gaps that will be filled (eventually, probably). 
This has a very specific usecase (managed file trees) and is not entirely ready for usecases like Element or bridges yet - its opinions are formed out of this usecase.
Such opinionated code is a bit of a first in the js-sdk stack, but for this sort of downstream project it helps with development. The downstream project using this is even more opinionated, and it is expected that the before dropping the unstable flag that this implementation would be refactored to match whatever structure the js-sdk has at that time. Please ping me on Matrix for more …
=> Unstable implementation of MSC3089: File Trees

src/client.ts, src/filter-component.ts, src/filter.ts
Fixes https://github.com/vector-im/element-web/issues/17753#event-4952613253
Also no longer sends `filter_json` redundantly, this halves the size of the filter GET field being sent, yay?
=> Fix broken /messages filtering due to internal field changes in FilterComponent

src/crypto/CrossSigning.ts
Use a plain async function rather than a promise, so we don't
have to squelch the lint warning.
=> Tidy up secret requesting code

src/crypto/index.ts
If the account has both a key backup and SSSS enabled but the key
backup key isn't stored in SSSS, try to save it there by getting
it from either the cache or the user (if perhaps it's the same as
their security passphrase but lost a passthrough entry).
Fixes https://github.com/vector-im/element-web/issues/17886
=> Attempt to fix megolm key not being in SSSS

src/models/event.ts
For https://github.com/vector-im/element-web/issues/17615
For https://github.com/matrix-org/matrix-react-sdk/pull/6371
=> Expose MatrixEvent's internal clearEvent as a function

src/store/indexeddb-remote-backend.ts, src/store/indexeddb.ts
Switches to a more generic approach to passing a worker to the indexeddb remote backend by means of a factory
=> Use webpack worker-loader instead of homegrown hack

CHANGELOG.md, src/client.ts, src/http-api.js, src/interactive-auth.js, src/service-types.ts
This PR standardises the spelling and casing of the following terms, across the codebase, as per vector-im/element-web/issues/10569:
- homeserver
- identity server
- integration manager
While the issue mentions only user-visible text, this PR changes all instances of the terms, regardless of whether they're user-visible or not. I think there's value in standardising these terms even in non-user-visible text, so I went ahead and applied the changes to all text.
For reference, here's the script I used to find candidates for replacement:
https://gist.github.com/psrpinto/b3787bae212d5d99649b517e2efd4dce
=> Standardise spelling and casing of homeserver, identity server, and integration manager

src/client.ts
We should be using an unstable prefix as per [`a4e5b45` (#2285)](https://github.com/matrix-org/matrix-doc/pull/2285/commits/a4e5b45204b243b6b23226a0fcf5cf8a9b10cdc0)
=> Use an unstable prefix for MSC2885: Hidden read receipts  

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Feedback welcome!
If this looks sensible, I'll add similar to the other projects, probably customised for each.
=> Contributing guidelines for new changelog generation

src/webrtc/callEventHandler.ts
so that it doesn't end up processing ephemerals, account data, remote echoes, etc etc
This was causing remote-echoes to be pointlessly decrypted
=> Switch callEventHandler from listening on `event` to `Room.timeline`

package.json, yarn.lock
Whilst it is down, make the most of it!
Notes: none
=> Update matrix-org-eslint-plugin and tighten max warning limit

src/models/room-member.ts, src/utils.ts
The work on improving disambiguation in Element-Web made it obvious that we were only applying it to `name` where we should be applying it to the raw variant too, to prevent users making invisible displaynames as we once did.
Also for good measure, bundle in yet another BiDi char into the regexp.
=> Apply hidden char check to rawDisplayName too

src/crypto/aes.ts
If we got the IV from somewhere else, we should just use it as-is, rather than trying to re-clear the bit.
This fixes compatibility with other clients that happen to clear different bits.
=> Only clear bit 63 when we create the IV

src/webrtc/call.ts, src/webrtc/callEventHandler.ts, src/webrtc/callEventTypes.ts
For the review: Please review this carefully, as it could lead to regressions. The pull request should be reviewable commit by commit
=> Clean-up some VoIP code

package.json, src/matrix.ts, yarn.lock
As per matrix-org/eslint-plugin-matrix-org#15
this caused a bunch of silly indenting to creep in, so this fixes it
back to the previous style.
=> Update eslint plugin & fix silly indenting

package.json, spec/unit/models/MSC3089Branch.spec.ts, spec/unit/models/MSC3089TreeSpace.spec.ts, spec/unit/relations.spec.ts, src/models/room-state.ts, tsconfig-build.json, tsconfig.json
Fixes vector-im/element-web#17743
The package @types/jest was not discovered because if types is specified, only packages listed will be included in the global scope.
=> Include all TypeScript @types listed in project dependency

spec/unit/matrix-client.spec.js, src/client.ts
If a tree space was deleted then it'll still hold a Room object for us, which is not much help if we're effectively trying to get the joined trees.
---
* Fix conditional on returning file tree spaces ([\#1841](https://github.com/matrix-org/matrix-js-sdk/pull/1841)).
=> Fix conditional on returning file tree spaces

package.json, tsconfig-build.json, tsconfig.json
1829 added the spec files to 'src', presumably because they just
were't type checked otherwise, but this chaqnged the implicit rootDir
so the lib directory we shipped has types in src/ and spec/ which
meant lib/index.d.ts was at lib/src/index.d.ts.
Specify the rootDir on the build tsconfig to put it back in the
right place, and also try to make the base tsconfig never emit
to avoid it ever generating .d.ts files in silly places. Move all
the options related to emitting to -build since they aren't relevant
in the main one.
Is this a sensible way to do this? It doesn't feel terribly elegant.
Fixes https://github.com/vector-im/element-web/issues/18503
Regressed in https://github.com/matrix-org/matrix-js-sdk/pull/1829
---
* Fix the types in …
=> Fix the types in shipped package

src/webrtc/call.ts, src/webrtc/callEventHandler.ts
In cases where a rogue client, or just a simple bug, sends a temporary call message, like CallNegotiate the messages should just be discarded if there's no actual p2p connection created.
=> Fix temporary call messages being handled without call 

src/crypto/EncryptionSetup.ts
Fixes #1848
If no result is found, the function may reach the last line without `return` ever being called.
Note: SSSSCryptoCallbacks.getSecretStorageKey now returns Promise<null> instead of Promise<void>, if no key was found.
---
Add one of: `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is plus `X-Breaking-Change` if it's a breaking change.
=> SSSSCryptoCallbacks.getSecretStorageKey return Promise<null> if no key was found

src/client.ts, src/models/group.js, src/store/index.ts, src/store/memory.ts, src/store/stub.ts
Notes: Deprecate the groups APIs. Groups are no longer supported, only Synapse has support. They are being replaced by Spaces which build off of Rooms and are far more flexible.
---
=> Deprecate groups APIs

src/models/event.ts
This highlights the current consumers of the event's JSON format.
---
=> Clarify usages of event's toJSON

src/webrtc/call.ts, src/webrtc/callEventHandler.ts
Fixes https://github.com/vector-im/element-web/issues/18538
Requires https://github.com/matrix-org/matrix-react-sdk/pull/6614
Type: defect
(will make a PR to release after approval)
---
* Fix glare related regressions ([\#1851](https://github.com/matrix-org/matrix-js-sdk/pull/1851)). Fixes vector-im/element-web#18538 and vector-im/element-web#18538. Contributed by [SimonBrandner](https://github.com/SimonBrandner).
=> Fix glare related regressions

release.sh
We now use the file for stuff other than just the signing ID, so
the file may be present but with no signing ID: handle this case.
---
=> Fix release script to handle no signing ID

src/crypto/EncryptionSetup.ts
https://github.com/matrix-org/matrix-js-sdk/blob/a69d9a9f20b680e3710e0f43cca68a2ce31ba030/src/client.ts#L315
`cryptoCallbacks` may be undefined but the constructor of `EncryptionSetupBuilder` requires it to be defined.
https://github.com/matrix-org/matrix-js-sdk/blob/a69d9a9f20b680e3710e0f43cca68a2ce31ba030/src/crypto/index.ts#L616-L620
---
=> Make delegateCryptoCallbacks an optional parameter of EncryptionSetupBuilder and SSSSCryptoCallbacks

src/models/MSC3089TreeSpace.ts
We ultimately need this to include things like `info` and other metadata in a specific environment.
---
* Add method for including extra fields when uploading to a tree space ([\#1850](https://github.com/matrix-org/matrix-js-sdk/pull/1850)).
=> Add method for including extra fields when uploading to a tree space

src/@types/spaces.ts, src/client.ts, src/room-hierarchy.ts
=> Add support for /hierarchy API and fall back to /spaces API if needed

src/crypto/EncryptionSetup.ts
Fixes #1845 
Notes: Fix a JavaScript error on matrixClient.bootstrapSecretStorage() if matrixClient.cryptoCallbacks.getSecretStorageKey is not defined.
---
=> SSSSCryptoCallbacks.getSecretStorageKey: Test if delegateCryptoCallbacks has getSecretStorageKey

src/@types/global.d.ts, src/webrtc/callFeed.ts
Type: enhancement 
For https://github.com/matrix-org/matrix-react-sdk/pull/6639
<hr>
To be transparent, I have no idea what I am doing but it seems to work :sweat_smile: 
---
* Give `CallFeed` the capability to emit on volume changes ([\#1865](https://github.com/matrix-org/matrix-js-sdk/pull/1865)). Contributed by [SimonBrandner](https://github.com/SimonBrandner).
=> Give `CallFeed` the capability to emit on volume changes

examples/browser/browserTest.js, examples/browser/index.html
Fix errors in the console when running the [browser example](https://github.com/matrix-org/matrix-js-sdk/tree/develop/examples/browser), and use HTTPS instead of HTTP.
---
**Before:**
**After:**
---
* Improve browser example ([\#1875](https://github.com/matrix-org/matrix-js-sdk/pull/1875)). Contributed by [psrpinto](https://github.com/psrpinto).
=> Improve browser example

src/@types/event.ts, src/models/event.ts, src/sync.ts
As part of  vector-im/element-web#18717
Adds an unstable hint for clients to know whether to render an event in the room timeline or in a thread
There are currently no MSC associated with that unstable "io.element.in_thread" property as I am only experimenting before settling on a specific approach
---
=> Add reply events rendering hint

src/webrtc/call.ts
For https://github.com/matrix-org/matrix-react-sdk/pull/6700
---
* Give `MatrixCall` the capability to emit `LengthChanged` events ([\#1873](https://github.com/matrix-org/matrix-js-sdk/pull/1873)). Contributed by [SimonBrandner](https://github.com/SimonBrandner).
=> Give `MatrixCall` the capability to emit `LengthChanged` events

src/models/event.ts, src/models/room.ts, src/models/thread.ts, src/sync.ts
Some threads were still holding a reference to the original thread models they were assigned to, leading to some unexpected timeline rendering
---
=> Improve thread deduplication thread process

src/sync.ts
Some platforms (e.g. React Native) register global.window, but do not have global.window.removeEventListener. In this case, this function should not be called.
This has already been fixed for addEventListener (https://github.com/matrix-org/matrix-js-sdk/pull/1661), however not yet for removeEventListener.
Signed-off-by: Jan Pawellek jpawellek@churchtools.de
---
=> Fix calling removeEventListener if it does not exist

spec/unit/crypto/verification/request.spec.js, spec/unit/crypto/verification/secret_request.spec.js, src/client.ts, src/crypto/CrossSigning.ts, src/crypto/deviceinfo.ts, src/crypto/index.ts, src/crypto/verification/Base.ts, src/crypto/verification/Error.ts, src/crypto/verification/IllegalMethod.ts, src/crypto/verification/QRCode.ts, src/crypto/verification/SAS.ts, src/crypto/verification/request/Channel.ts, src/crypto/verification/request/InRoomChannel.ts, src/crypto/verification/request/ToDeviceChannel.ts, src/crypto/verification/request/VerificationRequest.ts
This has highlighted some real looking bugs in our code, will need some more insight from those who know the code better
We expect some structure containing a deviceId but instead are given just deviceIds, this check will always pick the first device as `undefined === undefined` and thus always return true if both device lists contain at least a single element.
We pass an object where a string type is expected, what would the type be for these two? Looks like it should be CANCEL_TYPE based on the type being actually sent.
This one was `__device` where all others were `_device` so would always possibly false-positive on the cancel edge of the if - presumably this is safe to update to the right field name
---
This change is marked as an *internal change* (Task), so will not be included in …
=> Convert crypto/verification/* to Typescript

src/crypto/index.ts
This is needed for the system which is meant to be monitoring this metadata. See https://github.com/matrix-org/matrix-react-sdk/pull/6766
***Required by https://github.com/matrix-org/matrix-react-sdk/pull/6766***
---
* Exclude opt-in Element performance metrics from encryption ([\#1897](https://github.com/matrix-org/matrix-js-sdk/pull/1897)).
=> Exclude opt-in Element performance metrics from encryption

src/client.ts, src/models/room.ts, src/models/thread.ts
Pre-requisite for vector-im/element-web#18947
- Make timelineSet public readonly
- Add helper to check threads support
- Disable pending events for threads
---
=> Disable pending events for threads temporarily

src/@types/global.d.ts, src/webrtc/call.ts
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/1645
**Requires https://github.com/matrix-org/matrix-react-sdk/pull/6727**
Type: task
<hr>
Notes: This changes the `selectDesktopCapturerSource` callback in `setScreensharingEnabled()` to a `string` parameter `desktopCapturerSourceId`. This way you can handle choosing a source more easily on your side and just pass the id of the chosen source. This also removes the `getDesktopCapturerSources()` method which was Element specific and shouldn't have been in the `js-sdk` in the first place.
<hr>
This fixes some of my awful 8 months old code.
---
=> Remove Element-specifc screen-sharing code out of the js-sdk 

src/webrtc/call.ts, src/webrtc/callFeed.ts
A `setTimeout` loop was recently added to the `CallFeed` class to poll volume levels. When we remove call feeds we never clean it up. This PR properly disposes of call feeds by immediately calling `clearTimeout` when they are removed.
---
=> Properly dispose of CallFeeds

src/client.ts
Added types for the `MatrixClient` `register()` method. Typescript projects importing matrix-js-sdk that don't set all of the fields don't pass type checking.
If there's a better place for the types to be converted to type or interface definitions, let me know. I could just put them at the top of `client.ts` if that works?
---
=> Add types for the MatrixClient register method

src/client.ts, src/matrix.ts, src/webrtc/call.ts, src/webrtc/mediaHandler.ts
Type: task
Split out of https://github.com/matrix-org/matrix-js-sdk/pull/1827
**Requires https://github.com/matrix-org/matrix-react-sdk/pull/6781**
<hr>
Notes: This PR removes `setMatrixCallAudioInput()` and `setMatrixCallVideoInput()` in favour of `MediaHandler::setAudioInput()` and `MediaHandler::setVideoInput()`. The `MediaHandler` can be accessed through the `MatrixClient` using `MatrixClient::getMediaHandler()`
---
=> Improve `MatrixCall` media handling and internally remove `CallType`s

src/client.ts, src/crypto/api.ts, src/crypto/index.ts
- Type fixes for CreateSecretStorageDialog TS migration
- Types fixes for CreateKeyBackupDialog TS migration
---
=> Type fixes for security dialogs TS migration

src/errors.js
Reverts part of https://github.com/matrix-org/matrix-js-sdk/pull/1907
We need to migrate these errors to Typescript by converting them to actual typescript types; until then Typescript doesn't consider them types so the previous migration is causing the following error in matrix-react-sdk
```
src/Lifecycle.ts:241:44 - error TS2709: Cannot use namespace 'InvalidStoreError' as a type.
241 export function handleInvalidStoreError(e: InvalidStoreError): Promise<void> {
```
---
=> Revert "Migrate errors to TypeScript"

src/webrtc/call.ts
Type: task
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/1921
<hr>
The issue seems to be no longer present on Chromium 90
<hr>
Blocked on more testing - just to be sure
---
=> Remove RTX codec hack 

src/webrtc/call.ts
Reverts matrix-org/matrix-js-sdk#1923
Due to https://github.com/matrix-org/matrix-js-sdk/issues/1921#issuecomment-920109928
---
=> Revert "Remove RTX codec hack "

src/@types/global.d.ts
Type: task
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/1921
---
=> Add `setCodecPreferences()` to `global.d.ts`

src/webrtc/call.ts, src/webrtc/mediaHandler.ts
This PR is an addition to #1911 that clones the local usermedia stream or screensharing stream instead of calling getUserMedia again when there is already an active stream. This addresses a bug on iOS where multiple calls to `getUserMedia()` will disable existing media streams. You need to call `mediaStream.clone()` instead. This is important for group calls (#1902) where we need to initiate `RTCPeerConnection`s to multiple group call participants. This PR also keeps track of the active streams so that they can be explicitly stopped when leaving a call. For group calls this means that we can call `stopAllStreams()` and ensure that all local media streams are stopped. This will also ensure that the webcam/microphone indicators will be turned off.
---
This change is marked as an *internal …
=> Clone and stop local media streams from mediaHandler

src/webrtc/call.ts
This PR adds WebRTC Datachannels to `MatrixCall`. Having the `datachannel` event emitted by the call lets you easily manage datachannels when the call is replaced.
Notes: Added `createDataChannel()` and `CallEvent.DataChannel` to `MatrixCall` for creating and listening for WebRTC datachannels.
---
* Added `createDataChannel()` and `CallEvent.DataChannel` to `MatrixCall` for creating and listening for WebRTC datachannels. ([\#1929](https://github.com/matrix-org/matrix-js-sdk/pull/1929)). Contributed by [robertlong](https://github.com/robertlong).
=> Add WebRTC DataChannels to MatrixCall

src/models/event.ts, src/models/room.ts, src/models/thread.ts
Move stringly typed events to enum, so it's harder to make a development mistake
---
=> Typescriptify thread events a bit

src/crypto/CrossSigning.ts
We forgot to await the saving of the backup key, so there was a race
where it would fail to get the backup key because it hadn't been saved
yet, so the backup wouldn't be restored automatically.
Fixes https://github.com/vector-im/element-web/issues/17781
---
* Fix race on automatic backup restore ([\#1936](https://github.com/matrix-org/matrix-js-sdk/pull/1936)). Fixes vector-im/element-web#17781.
=> Fix race on automatic backup restore

CONTRIBUTING.md
Update PR guidelines for easier review.
This is spawning from me going over the [`matrix-react-sdk`](https://github.com/matrix-org/matrix-react-sdk) PR backlog and trying to get things less design-blocked.
---
=> Update PR guidelines for easier review

src/crypto/backup.ts
Type: enhancement 
For https://github.com/matrix-org/matrix-react-sdk/pull/6843
---
* Add `trusted_locally` to `TrustInfo` ([\#1942](https://github.com/matrix-org/matrix-js-sdk/pull/1942)). Contributed by [SimonBrandner](https://github.com/SimonBrandner).
=> Add `trusted_locally` to `TrustInfo`

src/models/event.ts
Fixes https://github.com/vector-im/element-web/issues/19062
---
* Ensure unencrypted fields get exposed by getEffectiveEvent() ([\#1938](https://github.com/matrix-org/matrix-js-sdk/pull/1938)). Fixes vector-im/element-web#19062.
=> Ensure unencrypted fields get exposed by getEffectiveEvent()

spec/unit/room.spec.js, src/models/event-timeline-set.ts, src/models/event-timeline.ts, src/models/room.ts, src/models/thread.ts
Fixes vector-im/element-web#18719
Events created in a thread do not receive the correct meta data, resulting in an incomplete sender profile as you can see on the screenshot below
The reason is that when an event is added to the timeline, the `event-timeline-set` looks for room state events. This works perfectly well for events in the room's timeline, however threaded events are part of their own timelines which contains no state events.
This pull request adds a way to pass the room's state events down so that the event metadata can be set the same way they would be in the room timeline.
The approach looks a bit odd but at this stage I'm not entirely sure about alternative approaches hence why this is a draft.
Keen to hear your ideas/alternatives to what I'm doing here
---
This change is …
=> Share room state events with thread's timelines

src/sync.ts
The logic was correct, but accessing the wrong property member, thus failing always
---
* Fix event partitioning from non threading ready clients ([\#1948](https://github.com/matrix-org/matrix-js-sdk/pull/1948)).
=> Fix event partitioning from non threading ready clients

src/models/room-state.ts
=> Make RoomState::hasSufficientPowerLevelFor public

spec/unit/models/MSC3089Branch.spec.ts, spec/unit/models/MSC3089TreeSpace.spec.ts, src/models/MSC3089Branch.ts, src/models/MSC3089TreeSpace.ts
The diff isn't super clear on how this works, but the general idea is that the MSC3089Branches (files) now know which directory they came from, and the directories (MSC3089TreeSpace) can tell when files are triggering uploads referencing themselves so it can add all the replacement metadata onto the event.
There's a few challenges with how relations work in the js-sdk which has shaped the API surface exposed by this change. Specifically, there is a `getVersionHistory()` function instead of a function to get a certain prior version: the js-sdk doesn't track parent events in the relation structures so cannot determine what the event could have replaced. 
In order to trigger the built-in relations structures, we must trigger decryption with `emit: true`. This is so an internal listener in …
=> Implement file versioning for tree spaces

src/client.ts, src/webrtc/call.ts, src/webrtc/callEventHandler.ts, src/webrtc/groupCall.ts, src/webrtc/groupCallEventHandler.ts
Changes:
+ Use to-device messages for VoIP signalling (for now, they're not encrypted)
+ Don't duplicate local call feeds and add more flexible ways to start/answer calls
+ And bunch of smaller improvements
---
=> Use to-device events for group calls and other improvements

src/webrtc/call.ts
Hopefully, fixes https://github.com/vector-im/element-web/issues/19221
Type: defect
---
* Make sure to set `callLengthInterval` only once ([\#1958](https://github.com/matrix-org/matrix-js-sdk/pull/1958)). Fixes vector-im/element-web#19221. Contributed by @SimonBrandner.
=> Make sure to set `callLengthInterval` only once

src/client.ts
[`_matrix/client/r0/joined_rooms`](https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-joined-rooms) returns an object with a single `joined_rooms` property, which is an array of strings:
```json
{
"joined_rooms": [
"!foo:example.com"
]
}
```
However, the [`getJoinedRooms()` function](https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/client.ts#L6677) returns a promised array of strings:
```
public getJoinedRooms(): Promise<string[]> {
```
This PR changes the return value to `Promise<IJoinedRoomsResponse>`, with `IJoinedRoomsResponse` being:
```typescript
interface IJoinedRoomsResponse {
joined_rooms: string[];
}
```
---
* Fix incorrect return value type in getJoinedRooms() …
=> Fix incorrect return value type in getJoinedRooms()

src/models/event.ts, src/models/room.ts
Mitigates vector-im/element-web#19229
Pending events are currently disabled for threaded messages as we have to rework a lot of things to make them work properly.
It makes for a better user experience that is not required at this stage of development. This will be taken care of before the P0 release.
---
=> Prevent redactions to be sent as pending events

src/webrtc/call.ts, src/webrtc/callFeed.ts
Notes: Use `ICallFeedOpts` in the `CallFeed` constructor. To construct a new `CallFeed` object you have to pass `ICallFeedOpts` e.g. `const callFeed = new CallFeed({client: new MatrixClient(...), roomId: "!roomId:example", audioMuted: false, videoMuted: false, userId: "@example:example.org", stream: await navigator.mediaDevices.getUserMedia(), purpose: "m.usermedia"});`
<hr>
This is much more flexible
---
* Use `ICallFeedOpts` in the `CallFeed` constructor. To construct a new `CallFeed` object you have to pass `ICallFeedOpts` e.g. `const callFeed = new CallFeed({client ([\#1964](https://github.com/matrix-org/matrix-js-sdk/pull/1964)). Contributed by @SimonBrandner.
=> Use `ICallFeedOpts` in the `CallFeed` constructor

src/webrtc/call.ts, src/webrtc/groupCall.ts
+ Avoid creating a call feed in each call and instead creates one for the whole group call
+ Adds handling for joining call where someone is already screen-sharing
---
=> Improvements to screen-sharing in group calls

tsconfig-build.json
This allows go-to-definition to reach the original .ts files for consumers of the package. It emits .d.ts.map files alongside the regular .d.ts files
e.g. in sdk.createClient go-to-definition on createClient will place the cursor at the function in src/matrix.ts rather than inside a definition file lib/matrix.d.ts
---
* Enable TypeScript declaration maps ([\#1966](https://github.com/matrix-org/matrix-js-sdk/pull/1966)). Contributed by @Alexendoo.
=> Enable TypeScript declaration maps

src/models/room.ts
Fixes https://github.com/vector-im/element-web/issues/19581
---
=> Fetch thread root event if it's missing from the sync

src/client.ts, src/sync.ts
Fixes https://github.com/vector-im/element-web/issues/19587
Possible will do the trick for https://github.com/vector-im/element-web/issues/19607 & https://github.com/vector-im/element-web/issues/19603
---
* Make events pagination responses parse threads ([\#2011](https://github.com/matrix-org/matrix-js-sdk/pull/2011)). Fixes vector-im/element-web#19587.
=> Make events pagination responses parse threads

src/client.ts
Fixes https://github.com/vector-im/element-web/issues/19651
---
* Fix edit history being broken after editing an unencrypted event with an encrypted event ([\#2013](https://github.com/matrix-org/matrix-js-sdk/pull/2013)). Fixes vector-im/element-web#19651. Contributed by @aaronraimist.
=> Fix edit history being broken after editing an unencrypted event with an encrypted event

src/client.ts
Fixes https://github.com/vector-im/element-web/issues/19677
Not quite sure why TypeScript did not shout at me here
---
=> Fix check supportExperimentalThreads

src/interactive-auth.ts
As proposed in [MSC3231](https://github.com/matrix-org/matrix-doc/blob/main/proposals/3231-token-authenticated-registration.md)
Signed-off-by: Callum Brown <callum@calcuode.com>
---
=> Add registration token UIA type

src/models/base-model.ts, src/models/thread.ts
We're using stringly typed events everywhere, this is the first step for
better typescript support with our event emitters before we replace it
with something much better for React support.
---
=> Implement BaseModel for better TS support

src/store/local-storage-events-emitter.ts
Add a way to listen to LocalStorage error events from element-web and matrix-react-sdk in the same manner.
Related: https://github.com/vector-im/element-web/issues/18423
Required by later implementations in `matrix-react-sdk` and `element-web`.
Requires https://github.com/matrix-org/matrix-js-sdk/pull/2018 to be merged in first.
---
=> Add LocalStorageErrorEventListener

src/sync.ts
Currently the sync state doesn't change when sync fails due to an invalid auth token. This PR ensures that the sync state changes to error when we abort the sync so we can ask the user to login again.
---
=> Update sync state to error when aborting due to invalid auth token

src/crypto/index.ts
This is useful for debugging crypto where Element's `/discardsession` doesn't reset the Olm session.
---
* Add optional force parameter when ensuring Olm sessions ([\#2027](https://github.com/matrix-org/matrix-js-sdk/pull/2027)).
=> Add optional force parameter when ensuring Olm sessions

src/webrtc/call.ts, src/webrtc/callFeed.ts
Type: defect
<hr>
Due to `CallFeed`s mute state being set to muted based on their tracks at the time of their creation we can get stuck with them being muted. This happens because the code that determines if a `CallFeed` is muted looks like this: 
```
return this.stream.getVideoTracks().length === 0 || this.videoMuted;
```
This means that if `videoMuted` is `true` the feed will be muted no matter the present tracks. The `videoMuted` property should only work as an override based on the remote `SPDStreamMetadata`
---
* Fix call upgrades ([\#2024](https://github.com/matrix-org/matrix-js-sdk/pull/2024)). Contributed by @SimonBrandner.
=> Fix call upgrades

src/client.ts
getStateEvent returns the content of an event, not the whole state event as per https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-rooms-roomid-state-eventtype-statekey
---
=> getStateEvent should return any

spec/integ/matrix-client-retrying.spec.ts, src/client.ts, src/models/event-timeline-set.ts, src/models/room.ts, src/models/thread.ts
Related to https://github.com/vector-im/element-web/issues/19616
- Use PendingEventOrdering enum rather than hardcoded values
- Make local echo work for threads
---
=> Make local echo work for threads 

src/crypto/key_passphrase.ts
Implementation of key derivation from passphrase using `crypto`.
Notes: Support for password-based backup on Node.js
---
* Support for password-based backup on Node.js ([\#2021](https://github.com/matrix-org/matrix-js-sdk/pull/2021)). Contributed by @hughns.
=> Implementation of passphrase deriveKey() for Node.js

src/models/room.ts, src/models/thread.ts
Fixes https://github.com/vector-im/element-web/issues/19723
Fixes https://github.com/vector-im/element-web/issues/19910
---
=> Emit thread update after event decryption

src/client.ts
---
* Add method to fetch /account/whoami ([\#2046](https://github.com/matrix-org/matrix-js-sdk/pull/2046)).
=> Add method to fetch /account/whoami

src/index.ts, src/matrix.ts
webpack couldn't retrieve the previous import structure
https://github.com/matrix-org/matrix-js-sdk/pull/2023
---
=> FIX exports type

src/models/MSC3089Branch.ts, src/models/MSC3089TreeSpace.ts
---
* Fix incorrect MSC3089 typings and add null checks ([\#2049](https://github.com/matrix-org/matrix-js-sdk/pull/2049)). Contributed by @hughns.
=> Fix incorrect MSC3089 typings and add null checks

src/filter.ts
As they are described in MSC3440. Useful to fetch all threads in a room
---
* Add new room event filter fields ([\#2051](https://github.com/matrix-org/matrix-js-sdk/pull/2051)).
=> Add new room event filter fields

src/client.ts, src/models/room.ts, src/models/thread.ts
Related to https://github.com/vector-im/element-web/issues/19126
- Allow for push actions refresh for event decryption
- Emit event when a new reply is added to a thread
---
=> Threads notifications after app startup

src/@types/requests.ts, src/client.ts
Paves the way for https://github.com/vector-im/element-web/issues/19961
According to MSC2675, relationType and eventType are both optional.
This also creates typing for the request options and the response format
---
=> Allow to omit optional params for /relations calls

src/client.ts
Earlier paginateEventTimeline used to resolve to  chunk instead of resolving to boolean. Now it resolve to boolean as specified in doc.
Signed-off-by: Ajay Bura <ajbura@gmail.com>
---
* Fix paginateEventTimeline resolve to boolean ([\#2054](https://github.com/matrix-org/matrix-js-sdk/pull/2054)). Contributed by @ajbura.
=> Fix paginateEventTimeline resolve to boolean

package.json, src/crypto/OlmDevice.ts, src/crypto/index.ts, src/sync.ts
- tracks whether the fallback key has already been published
- clear out old fallback key some time after it's been replaced
~Note: do not merge until libolm 3.2.7 is released.  (Also, needs a change to `package.json` to use the newer libolm) (test failures are due to this)~ Done
---
* Improve fallback key behaviour ([\#2037](https://github.com/matrix-org/matrix-js-sdk/pull/2037)).
=> Improve fallback key behaviour

yarn.lock
Broken by https://github.com/matrix-org/matrix-js-sdk/pull/2037/files
---
=> Update olm in yarn.lock

spec/unit/utils.spec.ts, src/@types/requests.ts, src/client.ts, src/utils.ts
Fixes https://github.com/vector-im/element-web/issues/20137
---
* Filter out falsey opts in /relations API hits ([\#2059](https://github.com/matrix-org/matrix-js-sdk/pull/2059)). Fixes vector-im/element-web#20137.
=> Filter out falsey opts in /relations API hits

src/models/room.ts
This makes the docs more accessible from IDEs. However, will this impact the auto-generated JSDoc docset negatively?
---
=> Move Room properties JSDoc into more usable comments on actual props

src/@types/extensible_events.ts, src/@types/location.ts, src/@types/polls.ts
Add constants for location sharing, and even a little bonus one for extensible events.
---
=> Add consts for location and extensible events types

src/@types/event.ts, src/models/thread.ts
Related to https://github.com/vector-im/element-web/issues/19615 and https://github.com/vector-im/element-web/issues/19996
Will work flawlessly when https://github.com/matrix-org/synapse/pull/11577 has landed
---
=> Track if user has participated in a thread or not 

src/client.ts
Partial revert of https://github.com/matrix-org/matrix-js-sdk/pull/2022
See https://github.com/vector-im/element-web/issues/19738#issuecomment-996804209
---
=> Stop using v1-prefixed /hierarchy API due to Synapse bugs

src/client.ts, src/crypto/SecretStorage.ts, src/crypto/index.ts
I have found a number of functions can return null values even through the TS types say it is non-nullable. These changes make it so that the TS types match those in the JS Doc and the implementation.
---
* Fix incorrect TS return type for secret storage and key backup functions ([\#2082](https://github.com/matrix-org/matrix-js-sdk/pull/2082)). Contributed by @hughns.
=> Fix incorrect TS return type for secret storage and key backup functions

examples/voip/browserTest.js
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/2083
Type: defect
---
* Set a `deviceId` for VoIP example and use `const`/`let` ([\#2090](https://github.com/matrix-org/matrix-js-sdk/pull/2090)). Fixes #2083. Contributed by @SimonBrandner.
=> Set a `deviceId` for VoIP example and use `const`/`let`

src/client.ts
These typings should now match JSDoc and the implementation.
---
* Fix more function typings relating to key backup ([\#2086](https://github.com/matrix-org/matrix-js-sdk/pull/2086)). Contributed by @hughns.
=> Fix more function typings relating to key backup

spec/unit/matrix-client.spec.js, src/client.ts, src/models/event.ts
Fixes https://github.com/vector-im/element-web/issues/20460
---
* Stop encrypting redactions as it isn't spec compliant ([\#2098](https://github.com/matrix-org/matrix-js-sdk/pull/2098)). Fixes vector-im/element-web#20460.
=> Stop encrypting redactions as it isn't spec compliant

spec/unit/room.spec.js, src/models/room.ts
Fixes https://github.com/vector-im/element-web/issues/13887
---
* Don't consider alt_aliases when calculating room name ([\#2094](https://github.com/matrix-org/matrix-js-sdk/pull/2094)). Fixes vector-im/element-web#13887.
=> Don't consider alt_aliases when calculating room name

spec/TestClient.js, spec/browserify/sync-browserify.spec.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-event-emitter.spec.js, spec/integ/matrix-client-event-timeline.spec.js, spec/integ/matrix-client-opts.spec.js, spec/integ/matrix-client-room-timeline.spec.js, spec/integ/matrix-client-syncing.spec.js, spec/test-utils.js, spec/unit/crypto/cross-signing.spec.js, spec/unit/matrix-client.spec.js, src/client.ts
For https://github.com/vector-im/element-web/issues/20408
---
=> Fetch server capabilities during client initialisation

spec/unit/matrix-client.spec.js, src/client.ts
Regressed by https://github.com/matrix-org/matrix-js-sdk/pull/2093
Capabilities requires authentication and therefore can not be called for guests, https://spec.matrix.org/v1.1/client-server-api/#capabilities-negotiation
---
=> Remove getCapabilities call for guest users

src/@types/event.ts, src/event-mapper.ts, src/models/event.ts, src/models/room-state.ts, src/models/room.ts, src/sync.ts
Matrix-js-sdk-level support for hiding messages.
This is my first patch in matrix-js-sdk, please accept my apologies for anything I have done wrong.
MSC: https://github.com/matrix-org/matrix-doc/pull/3531
Signed-off-by: David Teller <davidt@element.io>
---
=> Implement MSC3531: Hiding messages during moderation

src/models/room.ts
We should only check whether a redacted event is a visibility event *if the redacted event is not null*.
Notes: none
---
=> [Fix] Nullcheck redactedEvent

src/client.ts
This also properly handles `m.new_content` to also be extensible.
Fixes https://github.com/vector-im/element-web/issues/20542
Regressed by https://github.com/matrix-org/matrix-js-sdk/pull/2091
---
=> Keep unknown fields when adding extensible formats

src/webrtc/call.ts
If a renogotiation ends up with one track being removed, we removed
the whole stream, which would cause us to lose, for example, audio
rather than just video.
---
* Don't remove streams that still have tracks ([\#2104](https://github.com/matrix-org/matrix-js-sdk/pull/2104)).
=> Don't remove streams that still have tracks

spec/unit/matrix-client.spec.js, src/client.ts
This reverts commit bd47667e63289011d9f86ae9e3c59a681ec370c6 / https://github.com/matrix-org/matrix-js-sdk/pull/2100
---
* Revert "Remove getCapabilities call for guest users (#2100)" ([\#2107](https://github.com/matrix-org/matrix-js-sdk/pull/2107)).
=> Revert "Remove getCapabilities call for guest users (#2100)"

src/client.ts, src/webrtc/call.ts, src/webrtc/callEventTypes.ts, src/webrtc/groupCall.ts
This PR is a fix for #1902 that resolves split-brains when a client refreshes before they have answered an incoming call.
---
=> Use session ids to resolve refresh during invite/answer

spec/unit/location.spec.ts, src/@types/location.ts, src/content-helpers.ts
See https://github.com/matrix-org/matrix-doc/blob/matthew/location/proposals/3488-location.md - we have a new requirement to support a `m.asset` property in location event content.
---
* Support m.asset in m.location event content ([\#2109](https://github.com/matrix-org/matrix-js-sdk/pull/2109)). Contributed by @andybalaam.
=> Support m.asset in m.location event content

src/client.ts
Presumbaly casts left over from typescript migration.
---
=> Add eslint camelcase ignores & remove unnecessary casts

src/client.ts
=> Improve signature of MatrixClient::isUsernameAvailable to not rely on throwing

src/client.ts, src/models/event.ts, src/models/relations.ts, src/models/room.ts, src/models/thread.ts, src/sync-accumulator.ts, src/sync.ts
Fixes https://github.com/vector-im/element-web/issues/20708
Fixes https://github.com/vector-im/element-web/issues/20709
Fixes https://github.com/vector-im/element-web/issues/20607
Fixes https://github.com/vector-im/element-web/issues/20605
Fixes https://github.com/vector-im/element-web/issues/20633
- Make threadRootId work for relation of thread relations
- Avoid race conditions creating multiple thread of the same type
- Improve typing for server side aggregated relations
- Use bundled relationships for thread reply count
- Count all events when threads has not server support'
- Improved thread root detection using server side aggregated relations
The tackles three main things that were the root of a lot of recent bugs we have seen in threads
- Better leverages bundled relationships way …
=> Improved threads reliability with/without server side support

src/http-api.ts
Fixes https://github.com/vector-im/element-web/issues/20680
=> Fix http-api butchering idServer requests

src/filter-component.ts, src/filter.ts
Fixes https://github.com/vector-im/element-web/issues/20707
- Implement local relation types filter
- Add filtering for current user relation sender
- add public identifier to filter-component methods
---
=> Implement local relation types filter

yarn.lock
https://github.com/matrix-org/matrix-js-sdk/pull/2140 to release branch
Original description follows:
Bumps [node-fetch](https://github.com/node-fetch/node-fetch) from 2.6.6 to 2.6.7.
- [Release notes](https://github.com/node-fetch/node-fetch/releases)
- [Commits](https://github.com/node-fetch/node-fetch/compare/v2.6.6...v2.6.7)
---
updated-dependencies:
- dependency-name: node-fetch
dependency-type: indirect
...
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
---
=> Bump node-fetch from 2.6.6 to 2.6.7 (#2140)

src/@types/requests.ts, src/models/event.ts, src/models/room.ts, src/models/thread.ts
To review alongside https://github.com/matrix-org/matrix-react-sdk/pull/7670
- Refactor thread model to be created from the root event
- Integrate threads with the /relations API
---
=> Refactor thread model to be created from the root event

src/client.ts, src/models/thread.ts
Fixes https://github.com/vector-im/element-web/issues/20641
---
=> Add thread relation to sticker message

src/models/room.ts
Related to https://github.com/vector-im/element-web/issues/20555
---
=> Keep a reference to the latest thread created

src/models/event.ts
Part of #2035
I don't consider this a breaking change as it's just being more honest about the return types, even though this change will make it a pain to upgrade this dependency in TypeScript projects.
---
=> Type annotation: MatrixEvent.getRoomId can return undefined

src/client.ts
I've been calling `client.startClient()` without its parameter a lot.
As stated in the JSDocs, the `opts` parameter should be optional.
`Object.assign({}, opts)` is safe with `opts = undefined` and returns an empty object.
---
=> TypeScript: opts parameter of client.startClient() is optional

src/models/room.ts, src/models/thread.ts
Fixes https://github.com/vector-im/element-web/issues/20862
---
* Fix initial sync fail when event fetching unsuccessful ([\#2150](https://github.com/matrix-org/matrix-js-sdk/pull/2150)). Fixes vector-im/element-web#20862.
=> Fix initial sync fail when event fetching unsuccessful

src/event-mapper.ts, src/models/event.ts, src/models/thread.ts
Fixes https://github.com/vector-im/element-web/issues/20873
- Fix localTimestamp for local event
- Initialise thread after determining the root ID
- Re-use existing MatrixEvent if it's already known locally
---
=> Out of sync thread summary in main timeline

spec/integ/matrix-client-methods.spec.js, src/client.ts
Helps a bit with https://github.com/vector-im/element-web/issues/20282
---
* Send references to thread root to threads, even out of order ([\#2156](https://github.com/matrix-org/matrix-js-sdk/pull/2156)). Contributed by @andybalaam.
=> Send references to thread root to threads, even out of order

spec/unit/room.spec.js, src/models/room.ts
Type: defect
---
* Account for encryption in `maySendMessage()` ([\#2159](https://github.com/matrix-org/matrix-js-sdk/pull/2159)). Contributed by @SimonBrandner.
=> Account for encryption in `maySendMessage()`

src/models/room.ts
Fixes https://github.com/vector-im/element-web/issues/20922
---
* Fix edge cases around RR calculations ([\#2160](https://github.com/matrix-org/matrix-js-sdk/pull/2160)). Fixes vector-im/element-web#20922.
=> Fix edge cases around RR calculations

src/webrtc/call.ts, src/webrtc/mediaHandler.ts
Type: defect
Notes element-web: Fix enabling video in voice calls working only once
Fixes https://github.com/vector-im/element-web/issues/20932
<hr>
Without this `MediaHandler` would always push the stream we used to get a new track while upgrading a call. We don't keep track of that stream in the call itself, so we never call `stopUserMediaStream()` for it but we `stop()` its tracks. When trying to upgrade a call again `MediaHandler` would try to re-use the stream but its tracks would be empty. Therefore we avoid pushing the stream so that it doesn't get re-used
---
* Don't store streams that are only used once ([\#2157](https://github.com/matrix-org/matrix-js-sdk/pull/2157)). Fixes vector-im/element-web#20932. Contributed by …
=> Don't store streams that are only used once

src/models/room.ts
Fixes https://github.com/vector-im/element-web/issues/20971
---
* Fix issue with rooms not getting marked as unread ([\#2163](https://github.com/matrix-org/matrix-js-sdk/pull/2163)). Fixes vector-im/element-web#20971.
=> Fix issue with rooms not getting marked as unread

src/client.ts, src/crypto/backup.ts
Warning: not tested yet
Fixes https://github.com/vector-im/element-web/issues/13151
---
* Back up keys before logging out ([\#2158](https://github.com/matrix-org/matrix-js-sdk/pull/2158)). Fixes vector-im/element-web#13151.
=> Back up keys before logging out

src/crypto/backup.ts
Currently, when checking if the key backup is trusted, it checks if the stored trusted public key matches the public key in the backup.  This has two problems: 1) we never actually store a trusted public key anywhere, and 2) this would not work for when we switch to symmetric backup.  Instead, this patch checks the cached private key, and checks if the backup info matches the private key, using the algorithm-specific method for checking the key.
---
* Check the backup info against the stored private key when determining trust. ([\#2167](https://github.com/matrix-org/matrix-js-sdk/pull/2167)).
=> Check the backup info against the stored private key when determining trust.

spec/integ/matrix-client-methods.spec.js, src/@types/event.ts, src/client.ts, src/models/event-timeline-set.ts, src/models/event.ts, src/models/relations.ts, src/models/room.ts, src/models/thread.ts, src/sync.ts
Fixes https://github.com/vector-im/element-web/issues/20966
Fixes https://github.com/vector-im/element-web/issues/20915
Fixes https://github.com/vector-im/element-web/issues/20921
Fixes https://github.com/vector-im/element-web/issues/20282
Fixes https://github.com/vector-im/element-web/issues/20848
- Cater for 2-nd degree relations in thread partitionning
- Fix event edits in a thread
---
=> Improve thread partitioning for 2nd degree relations

src/http-api.ts
---
* Fix error in uploadContent() when file is empty under Node.js ([\#2155](https://github.com/matrix-org/matrix-js-sdk/pull/2155)). Contributed by @hughns.
=> Fix error in uploadContent() when file is empty under Node.js

src/event-mapper.ts
Reverts what was done in https://github.com/matrix-org/matrix-js-sdk/pull/2153.
Plausible root cause of https://github.com/vector-im/element-web/issues/20981
---
=> Revert event-mapper optimisations

src/crypto/index.ts
When we reset the key backup, enable it right away.  This ensures that we remember it if `bootstrapCrossSigning` gets called, so that the `auth_data` gets signed by the master key, if a new key is created.  Without this change, `this.backupManager.backupInfo` won't get set until some time after `bootstrapCrossSigning` is called, so it will think that there's no backup, and the `auth_data` will not get signed by the new master key.
---
* Sign backup with cross-signing key when we reset it. ([\#2170](https://github.com/matrix-org/matrix-js-sdk/pull/2170)).
=> Sign backup with cross-signing key when we reset it.

src/crypto/index.ts
Reverts matrix-org/matrix-js-sdk#2170
cc @uhoreg 
This breaks react-sdk e2e test suite with an error like
```
* alice joins room "#lltest:localhost" ... failure:  TimeoutError: waiting for selector `.mx_DirectorySearchBox input` failed: timeout 20000ms exceeded
at new WaitTask (/Users/t3chguy/WebstormProjects/matrix-react-sdk/test/end-to-end-tests/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
at DOMWorld.waitForSelectorInPage (/Users/t3chguy/WebstormProjects/matrix-react-sdk/test/end-to-end-tests/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:420:26)
at Object.internalHandler.waitFor (/Users/t3chguy/WebstormProjects/matrix-react-sdk/test/end-to-end-tests/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
at DOMWorld.waitForSelector …
```
=> Revert "Sign backup with cross-signing key when we reset it."

spec/unit/room.spec.js, src/models/room.ts
Fixes https://github.com/vector-im/element-web/issues/21016
The complexity in this area of code is worth the performance gains, with more testing and comments now it should be more maintainable too.
---
* Fix synthetic read receipt handling ([\#2174](https://github.com/matrix-org/matrix-js-sdk/pull/2174)). Fixes vector-im/element-web#21016.
=> Fix synthetic read receipt handling

src/@types/auth.ts, src/client.ts, src/http-api.ts
MSC: https://github.com/matrix-org/matrix-doc/pull/2918 (stable, but not formalized)
For https://github.com/vector-im/element-web/issues/18698
For https://github.com/matrix-org/matrix-react-sdk/pull/7802
---
* Add functions to support refresh tokens ([\#2178](https://github.com/matrix-org/matrix-js-sdk/pull/2178)).
=> Add functions to support refresh tokens

src/webrtc/call.ts
No particular reason to worry about old user agents here
---
=> Enable max-bundle

src/models/room.ts
The comments near `receiptCacheByEventId` referred to `IReceipt2`, looking at the definition of the `ReceiptCache` type we see that it is actually `ICachedReceipt`:
https://github.com/matrix-org/matrix-js-sdk/blob/2910e62bb68db2e9bdf9eeb5b5d13d5bb269c424/src/models/room.ts#L99
I looked briefly and I think this has been there since it was converted to TypeScript, `git log -SIReceipt2` only brings up 7aa5a79c86d23c01a3a0212e3079cf83d30dcc0d.
---
=> Fix incorrect type referenced in receiptCacheByEventId.

src/webrtc/call.ts
The 'Replaced' error code is handled specially (for better or worse)
so was leaving the capture feeds open. Use the 'transfer' hangup
reason which is what we should be using anyway (and were, on the line
below for the other call...)
---
* Fix camera stuck on after call transfer ([\#2188](https://github.com/matrix-org/matrix-js-sdk/pull/2188)).
=> Fix camera stuck on after call transfer

src/webrtc/callEventHandler.ts
When callEventHandler passed a reject event to the call object, it assumed
that always caused the call to end and deleted it from the list, so it
never got any more events. The point of a reject is that it doesn't
end the call if it's already been picked up though. This only removes
the call if it's actually ended.
---
* Fix bug where calls could break if rejected from somewhere else ([\#2189](https://github.com/matrix-org/matrix-js-sdk/pull/2189)).
=> Fix bug where calls could break if rejected from somewhere else

src/client.ts
Related to https://github.com/vector-im/element-web/issues/20850
---
=> Update return type for client.getRoom

src/webrtc/call.ts
Seems chrome at least will give you a disabled audio track if you
already had another user media audio track and disabled it, so make
sure our tracks are enabled when we add them. We already did this
on one code path but it didn't get moved over when a new code path
was added.
On the plus side, we now know the reason for the ancient code that
had the comment asking what it was for, so update that.
---
* Fix bug with one-way audio after a transfer ([\#2193](https://github.com/matrix-org/matrix-js-sdk/pull/2193)).
=> Fix bug with one-way audio after a transfer

spec/test-utils.js, spec/unit/filter-component.spec.js, src/filter-component.ts
Fixes: https://github.com/vector-im/element-web/issues/20877
Screenshots from purple K POV:
---
* fix relation sender filter ([\#2196](https://github.com/matrix-org/matrix-js-sdk/pull/2196)). Fixes vector-im/element-web#20877. Contributed by @kerryarchibald.
=> fix relation sender filter

src/matrix.ts
Export types from `@types/partials.ts` within the main matrix-js-sdk entrypoint so they can be easily imported by consumers without additional setup, i.e.
```
import { Preset, Visibility } from 'matrix-js-sdk';
```
Signed-off-by: Stanislav Demydiuk <s.demydiuk@gmail.com>
---
=> Export `partials` types

src/client.ts
Fixes https://github.com/vector-im/element-web/issues/21170
---
* Fix bug with the /hierarchy API sending invalid requests ([\#2201](https://github.com/matrix-org/matrix-js-sdk/pull/2201)). Fixes vector-im/element-web#21170.
=> Fix bug with the /hierarchy API sending invalid requests

spec/unit/webrtc/call.spec.ts, src/client.ts, src/webrtc/call.ts, src/webrtc/mediaHandler.ts
Type: enhancement 
Replaces and closes https://github.com/matrix-org/matrix-js-sdk/pull/1977
Blocked on https://github.com/matrix-org/matrix-js-sdk/pull/2157
---
* Support for mid-call devices changes ([\#2154](https://github.com/matrix-org/matrix-js-sdk/pull/2154)). Contributed by @SimonBrandner.
=> Support for mid-call devices changes

spec/unit/room.spec.ts, src/models/room.ts
Fixes https://github.com/vector-im/element-web/issues/21130
Also migrated `room.spec.js` to TypeScript. Important to note that `createMockClient` do not fulfill the `MatrixClient` interface. It was too big of a job to undertake for this fix, hence the `as any` that you can spot here and there.
Better viewed adding `?w=1` to the URL to hide the whitespaces diff, as it looks like our ESLint rules are slightly different for JS and TS files.
---
=> Make createThread more resilient when missing rootEvent

src/client.ts
Incorrect typing for the `versions` entry of the `/versions` endpoint
---
=> Update versions response type

src/browser-index.js, src/client.ts, src/index.ts
This reverts commit 7fa01ffb also as the fix is no longer necessary
---
=> Throw error if both browser-index and (node) index are loaded

src/client.ts
---
* Fix wrong event_id being sent for m.in_reply_to of threads ([\#2213](https://github.com/matrix-org/matrix-js-sdk/pull/2213)).
=> Fix wrong event_id being sent for m.in_reply_to of threads

src/client.ts
As per MSC2675, `eventType` is optional and can be omitted.
https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/2675-aggregations-server.md#querying-relations
Also fixed an issue where the generated URL would be incorrect if someone passed `relationType=null` and a value for `eventType`.
---
=> Make eventType optional for relations

spec/unit/location.spec.ts, src/@types/location.ts, src/content-helpers.ts
---
* add LocationAssetType enum ([\#2214](https://github.com/matrix-org/matrix-js-sdk/pull/2214)). Contributed by @kerryarchibald.
=> add LocationAssetType enum

src/client.ts, src/event-mapper.ts, src/models/room.ts, src/models/thread.ts, src/sync.ts
Related to https://github.com/vector-im/element-web/issues/21113
Related to https://github.com/vector-im/element-web/issues/20914
- Fix threads message ordering without server side support
- Eagerly set thread instance on root event
---
=> Fix message ordering in threads

src/pushprocessor.ts
---
* Fix wrongly asserting that PushRule::conditions is non-null ([\#2217](https://github.com/matrix-org/matrix-js-sdk/pull/2217)).
=> Fix wrongly asserting that PushRule::conditions is non-null

spec/unit/pushprocessor.spec.js
Add tests for https://github.com/matrix-org/matrix-js-sdk/pull/2217
---
=> Add test coverage around push rules with no conditions

src/models/room.ts
One fix for https://github.com/vector-im/element-web/issues/21344 . Does not fix the entire ticket as there's still one part that I can't reproduce
---
=> Disable pending events for thread list when server supports threads

src/client.ts, src/crypto/verification/request/VerificationRequest.ts, src/http-api.ts, tsconfig.json
TypeScript supports checking for "unused locals", which actually includes
locals, private fields, private methods, etc. If a private thing is actually
needed as part of the API surface, you can change it to public to resolve the
error.
This seems like a good check to have, as it highlights unused bits of code that
perhaps got lost while refactoring. This changes our config to reject them and
fixes up a few existing cases.
---
=> Add lint for unused locals

src/client.ts
Related to https://github.com/vector-im/element-web/issues/21073
---
=> fix thread fallback targeting only thread relations

src/models/event.ts, src/models/thread.ts
Fixes incorrect unstable msc variant being used
---
* Fix incorrect usage of unstable variant of `is_falling_back` ([\#2227](https://github.com/matrix-org/matrix-js-sdk/pull/2227)).
=> Fix incorrect usage of unstable variant of `is_falling_back`

spec/unit/filter-component.spec.ts, src/client.ts, src/filter-component.ts, src/models/room.ts, src/timeline-window.ts
A couple of issues were causing this. We can now paginate in a timeline with no initial pagination token,  the JS-SDK implementation would unfortunately not allow for that. And there was a bug of implementation in the local filter
---
=> Fix missing threads in thread list

spec/unit/location.spec.ts, src/@types/location.ts, src/content-helpers.ts
- More types for timestamp, asset and location events
- location event parsing functions
---
=> Location event helper functions

spec/TestClient.js, spec/browserify/sync-browserify.spec.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-event-emitter.spec.js, spec/integ/matrix-client-event-timeline.spec.js, spec/integ/matrix-client-methods.spec.js, spec/integ/matrix-client-opts.spec.js, spec/integ/matrix-client-room-timeline.spec.js, spec/integ/matrix-client-syncing.spec.js, spec/test-utils.js, spec/unit/crypto/cross-signing.spec.js, spec/unit/filter-component.spec.ts, spec/unit/matrix-client.spec.ts, spec/unit/room.spec.ts, src/NamespacedValue.ts, src/client.ts, src/filter-component.ts, src/filter.ts, src/models/event.ts, src/models/thread.ts
Related to https://github.com/vector-im/element-web/issues/21215
- Add check for stable/unstable thread server support
- Use NamespacedValue for threads prefixes
- determine server support before first sync
- remove checks in server support has already been checked
---
=> Switch to using stable values for Threads

src/filter-component.ts
Issue introduced by https://github.com/matrix-org/matrix-js-sdk/pull/2228
---
=> Fix incorrect toJSON for filter-component

spec/integ/megolm-integ.spec.js, spec/unit/crypto/algorithms/megolm.spec.js, src/crypto/algorithms/megolm.ts, src/crypto/index.ts
Since MSC2399 is finished FCP and it's in the spec, we can use the stable name now.
---
=> Send and handle stable name for withheld codes

spec/test-utils/emitter.ts, spec/unit/models/beacon.spec.ts, spec/unit/room-state.spec.js, src/matrix.ts, src/models/beacon.ts, src/models/room-state.ts
https://github.com/matrix-org/matrix-spec-proposals/pull/3489
Done: 
In this PR:
In next PRs:
---
* emit aggregate room beacon liveness ([\#2241](https://github.com/matrix-org/matrix-js-sdk/pull/2241)). Contributed by @kerryarchibald.
=> emit aggregate room beacon liveness

src/client.ts, src/models/beacon.ts
Add missed event emitter type exports
---
=> fix missed types for event emitter

CONTRIBUTING.md
As discussed internally and in #element-dev
---
=> Formalise guidelines around writing tests

spec/unit/content-helpers.spec.ts, spec/unit/matrix-client.spec.ts, spec/unit/models/beacon.spec.ts, src/client.ts, src/content-helpers.ts, src/models/beacon.ts
- Adds a function to allow updating beacon_info events using suffixed m.beacon_info.* event types.
- expose event type on beacon model
- allow setting timestamp on beacon info content helper
=> add upsert function for updating beacon events

src/models/room.ts
Fixes https://github.com/vector-im/element-web/issues/21414
---
=> Apply redaction logic to threaded events

src/models/room.ts, src/models/thread.ts
Related to https://github.com/vector-im/element-web/issues/21439
Related to https://github.com/vector-im/element-web/issues/21442
Some of the ordering was incorrect because some listeners were only active when viewing the thread list. This PR moves the logic to the JS-SDK so that those timelines always listen to incoming events and populate the timeline sets accordingly.
There's no logic change, only moving the code at a place that will be able to listen at all time
This could also make some improvements with the room counter issues, but I have not had a chance to confirm it with a 100% certainty
---
Add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is …
=> Create threads event timeline set in the room model

src/@types/event.ts, src/models/room.ts
See https://github.com/matrix-org/matrix-react-sdk/pull/8084 for the full details.
Notes: Support call room type from MSC3417
---
=> Voice rooms prototype

spec/unit/crypto.spec.js, src/crypto/index.ts
Some of the code in `createSSSS()` assumed that keyInfo was not undefined, so default it to `{}`.
---
* Prevent exception 'Unable to set up secret storage' ([\#2260](https://github.com/matrix-org/matrix-js-sdk/pull/2260)). Contributed by @andybalaam.
=> Prevent exception 'Unable to set up secret storage'

spec/integ/matrix-client-event-timeline.spec.js, spec/integ/matrix-client-methods.spec.js, src/client.ts, src/models/event-context.ts, src/models/room.ts, src/models/search-result.ts, src/models/thread.ts, src/timeline-window.ts
Fixes https://github.com/vector-im/element-web/issues/21543
---
* Fix issues with /search and /context API handling for threads ([\#2261](https://github.com/matrix-org/matrix-js-sdk/pull/2261)). Fixes vector-im/element-web#21543.
=> Fix issues with /search and /context API handling for threads

src/crypto/store/localStorage-crypto-store.ts
Signed-off-by: Adam Van Ymeren <adam@vany.ca>
---
=> Fix getSessionsNeedingBackup() limit support

spec/unit/models/beacon.spec.ts, spec/unit/room-state.spec.js, src/models/beacon.ts, src/models/room-state.ts, src/sync.ts
---
* Live location sharing - handle redacted beacons ([\#2269](https://github.com/matrix-org/matrix-js-sdk/pull/2269)). Contributed by @kerryarchibald.
=> Live location sharing - handle redacted beacons

spec/integ/matrix-client-methods.spec.js, spec/test-utils/test-utils.ts, spec/unit/matrix-client.spec.ts, spec/unit/room.spec.ts, src/client.ts, src/event-mapper.ts, src/models/event-timeline-set.ts, src/models/event.ts, src/models/relations.ts, src/models/room.ts, src/models/thread.ts, src/sync.ts
Fixes https://github.com/vector-im/element-web/issues/21633
---
=> Fix handling of threaded messages around edits & echoes

spec/test-utils/beacon.ts, spec/unit/content-helpers.spec.ts, spec/unit/matrix-client.spec.ts, spec/unit/models/beacon.spec.ts, spec/unit/room-state.spec.js, src/@types/beacon.ts, src/client.ts, src/content-helpers.ts, src/models/beacon.ts, src/models/room-state.ts
https://github.com/matrix-org/matrix-spec-proposals/pull/3672
- changes unstable event prefixes to use `msc3672`
- changes beacon identifier logic. Previously beacons used unique event types to enable multiple state events per user per room so event type could be used as an identifier. According to msc3672 plain event types and state_key are used for beacons, identifier is now `<roomId>_<state_key>`. 
- add extra logic about beacon update
---
=> Live location sharing - update beacon_info implementation to latest MSC

src/client.ts
Applies the same fix as https://github.com/matrix-org/matrix-js-sdk/pull/2283 to the release branch
---
=> Port #2283 to release

spec/unit/matrix-client.spec.ts, spec/unit/models/beacon.spec.ts, spec/unit/room-state.spec.js, spec/unit/utils.spec.ts, src/client.ts, src/content-helpers.ts, src/models/beacon.ts, src/models/room-state.ts, src/sync.ts, src/utils.ts
Process `m.beacon` events, adding them to Beacon state and emitting on change.
---
* Live location sharing - Aggregate beacon locations on beacons ([\#2268](https://github.com/matrix-org/matrix-js-sdk/pull/2268)). Contributed by @kerryarchibald.
=> Live location sharing - Aggregate beacon locations on beacons

src/interactive-auth.ts
Token authenticated registration was added to the Matrix specification in v1.2:
https://spec.matrix.org/v1.2/client-server-api/#token-authenticated-registration
Signed-off-by: Callum Brown <callum@calcuode.com>
---
* Stabilise token authenticated registration support ([\#2181](https://github.com/matrix-org/matrix-js-sdk/pull/2181)). Contributed by @govynnus.
=> Stabilise token authenticated registration support

.git-blame-ignore-revs
Ignore `eslint --fix` formatting changes in git blame
Docs: https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view
```
git log --all --grep='eslint'
```
---
=> Ignore `eslint --fix` formatting changes in git blame

spec/unit/matrix-client.spec.ts, src/client.ts
---
* Support for MSC2457 logout_devices param for setPassword() ([\#2285](https://github.com/matrix-org/matrix-js-sdk/pull/2285)). Contributed by @hughns.
=> Support for MSC2457 logout_devices param for setPassword()

spec/test-utils/test-utils.ts, spec/unit/room.spec.ts, src/event-mapper.ts, src/models/room.ts, src/models/thread.ts
Fixes https://github.com/vector-im/element-web/issues/21716
Fixes https://github.com/vector-im/element-web/issues/21662
Fixes https://github.com/vector-im/element-web/issues/21711
---
=> Fix issues around echo & redaction handling in threads

src/client.ts
In accordance with changes to https://github.com/matrix-org/matrix-spec-proposals/pull/2666, renaming from "shared" to "mutual".
This updates https://github.com/matrix-org/matrix-js-sdk/pull/1417
This blocks https://github.com/matrix-org/matrix-react-sdk/pull/4897
Notes: Change `_unstable_getSharedRooms` to `_unstable_getMutualRooms` and update unstable URL.
Type: task
`Signed-off-by: Jonathan de Jong <jonathan@automatia.nl>`
---
=> Change `_unstable_getSharedRooms` to `_unstable_getMutualRooms`

.github/workflows/test_coverage.yml
The checkout action correctly gets the pull request's HEAD, but then the Codecov uploader still thought that the coverage output was for the HEAD+develop merge commit, rather than HEAD.
Type: task
---
=> Fix coverage diffs for PRs that aren't up to date, take 3

spec/integ/matrix-client-event-timeline.spec.js, src/client.ts, src/models/room.ts
=> Stop tracking threads if threads support is disabled

spec/unit/room-state.spec.js, src/models/room-state.ts
- exposes `liveBeaconIds` on room state
- updates liveBeaconIds on beacon destroy
- emits `RoomStateEvent.BeaconLiveness` whenever liveBeaconIds changes (not just when overall liveness of a room changes)
---
* Live location sharing - expose room liveBeaconIds ([\#2296](https://github.com/matrix-org/matrix-js-sdk/pull/2296)). Contributed by @kerryarchibald.
=> Live location sharing - expose room liveBeaconIds

examples/node/app.js, src/content-repo.ts, src/crypto/store/localStorage-crypto-store.ts, src/crypto/store/memory-crypto-store.ts, src/filter-component.ts, src/store/session/webstorage.js, src/utils.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) or [String.prototype.substring()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) which work similarily but aren't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
---
A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: …
=> Replace deprecated String.prototype.substr()

src/client.ts
---
* Add MatrixClient.doesServerSupportLogoutDevices() for MSC2457 ([\#2297](https://github.com/matrix-org/matrix-js-sdk/pull/2297)). Contributed by @hughns.
=> Add MatrixClient.doesServerSupportLogoutDevices() for MSC2457

spec/unit/crypto/cross-signing.spec.js, src/client.ts, src/crypto/index.ts
This is something I'm now doing multiple different places in matrix-react-sdk, so I figured it was worth adding as a method on MatrixClient.
Notes: Add `MatrixClient.checkIfOwnDeviceCrossSigned` method, for checking if another of our devices is cross-signed regardless of whether this device trusts the MSK.
---
=> Add method for checking whether our other devices are cross-signed, even when this device isn't

spec/integ/matrix-client-methods.spec.js, spec/unit/room.spec.ts, src/models/room.ts
Verified matches Element Android behaviour
Fixes https://github.com/vector-im/element-web/issues/19678
---
* Update threads handling for replies-to-thread-responses as per MSC update ([\#2305](https://github.com/matrix-org/matrix-js-sdk/pull/2305)). Fixes vector-im/element-web#19678.
=> Update threads handling for replies-to-thread-responses as per MSC update

.editorconfig, .github/workflows/notify-downstream.yaml, .github/workflows/pr_static_analysis.yml, .github/workflows/preview_changelog.yaml, .github/workflows/test_coverage.yml
=> Move more stuff from BK to GHA

src/models/room.ts
---
* Prevent attempt to create thread with id "undefined" ([\#2308](https://github.com/matrix-org/matrix-js-sdk/pull/2308)).
=> Prevent attempt to create thread with id "undefined"

src/client.ts, src/webrtc/groupCall.ts, src/webrtc/groupCallEventHandler.ts
No other parts of PTT calls implemented yet
For https://github.com/vector-im/element-call/issues/294
---
* Add PTT call mode & mute by default in PTT calls ([\#2311](https://github.com/matrix-org/matrix-js-sdk/pull/2311)).
=> Add PTT call mode & mute by default in PTT calls

spec/unit/webrtc/call.spec.ts
https://github.com/matrix-org/matrix-js-sdk/commit/3280394bf93622c096e3e260296f7f089b97846b
made call use a bunch of methods that weren't mocked in the tests.
---
=> Make the tests pass again

src/webrtc/groupCall.ts
on sender side by muting mic after the max transmit time has elapsed.
For https://github.com/vector-im/element-call/issues/297
---
* Add maximum trasmit time for PTT ([\#2312](https://github.com/matrix-org/matrix-js-sdk/pull/2312)).
=> Add maximum trasmit time for PTT

src/webrtc/groupCall.ts
Based on https://github.com/matrix-org/matrix-js-sdk/pull/2312
For https://github.com/vector-im/element-call/issues/298
---
* Don't allow user to unmute if another user is speaking  ([\#2313](https://github.com/matrix-org/matrix-js-sdk/pull/2313)).
=> Don't allow user to unmute if another user is speaking 

spec/unit/relations.spec.ts, src/models/event.ts
Fixes https://github.com/vector-im/element-web/issues/21851
---
* Ignore m.replace relations on state events, they're invalid ([\#2306](https://github.com/matrix-org/matrix-js-sdk/pull/2306)). Fixes vector-im/element-web#21851.
=> Ignore m.replace relations on state events, they're invalid

src/client.ts
Comma instead of a colon...
---
* Fix createGroupCall arguments ([\#2325](https://github.com/matrix-org/matrix-js-sdk/pull/2325)).
=> Fix createGroupCall arguments

spec/unit/matrix-client.spec.ts, spec/unit/room-state.spec.js, src/client.ts, src/models/event-timeline-set.ts, src/models/room-state.ts
---
* Live location sharing: handle encrypted messages in processBeaconEvents ([\#2327](https://github.com/matrix-org/matrix-js-sdk/pull/2327)). Contributed by @kerryarchibald.
=> Live location sharing: handle encrypted messages in processBeaconEvents

README.md, package.json
We use `Promise::allSettled` which was added in Node 12.9.0
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled
Node 12 is still in Maintenance status
---
=> Correctly specify minimum Node version

src/models/room.ts
Workaround for https://github.com/vector-im/element-web/issues/20166 https://github.com/vector-im/element-web/issues/11820
Signed-off-by: Aaron Raimist <aaron@raim.ist>
---
=> Mark room versions 7, 8, and 9 as safe

spec/unit/models/event.spec.ts, src/models/event.ts
Fixes https://github.com/vector-im/element-web/issues/21929
---
* Prune both clear & wire content on redaction ([\#2346](https://github.com/matrix-org/matrix-js-sdk/pull/2346)). Fixes vector-im/element-web#21929.
=> Prune both clear & wire content on redaction

src/client.ts, src/models/user.ts, src/sync.ts
This is unstable, so should be more than safe to just outright remove without notice.
For https://github.com/matrix-org/matrix-react-sdk/pull/8521
---
* Remove hacky custom status feature ([\#2350](https://github.com/matrix-org/matrix-js-sdk/pull/2350)).
=> Remove hacky custom status feature

spec/unit/interactive-auth.spec.js, src/interactive-auth.ts
Type: Enhancement
Related: https://github.com/vector-im/element-web/issues/21984
Related: https://github.com/matrix-org/matrix-react-sdk/pull/8554
---
* registration: add function to re-request email token ([\#2357](https://github.com/matrix-org/matrix-js-sdk/pull/2357)). Contributed by @justjanne.
=> registration: add function to re-request email token

src/client.ts
---
* Add stopClient parameter to MatrixClient::logout ([\#2367](https://github.com/matrix-org/matrix-js-sdk/pull/2367)).
=> Add stopClient parameter to MatrixClient::logout

spec/integ/matrix-client-methods.spec.js, spec/unit/webrtc/call.spec.ts, src/@types/requests.ts, src/client.ts, src/crypto/backup.ts, src/http-api.ts, src/store/memory.ts, src/webrtc/call.ts
=> More sonar tweaks and typing improvements

spec/unit/room.spec.ts, src/models/room.ts, src/models/thread.ts
Fixes https://github.com/vector-im/element-web/issues/22162
Fixes https://github.com/vector-im/element-web/issues/22180
---
* Tweak thread creation & event adding to fix bugs around relations ([\#2369](https://github.com/matrix-org/matrix-js-sdk/pull/2369)). Fixes vector-im/element-web#22162 and vector-im/element-web#22180.
=> Tweak thread creation & event adding to fix bugs around relations

src/pushprocessor.ts
Folks have had since Matrix 1.0 (June 2019) to upgrade to a compatible server
Fixes https://github.com/vector-im/element-web/issues/15439
**Note**: there's almost certainly a bug with the UI handling for these default rules, however since the other two aren't exposed in the UI I am less concerned after this fix.
---
* Remove default push rule override for MSC1930 ([\#2376](https://github.com/matrix-org/matrix-js-sdk/pull/2376)). Fixes vector-im/element-web#15439.
=> Remove default push rule override for MSC1930

spec/unit/models/thread.spec.ts, src/models/thread.ts
This is an attempt to narrow down https://github.com/vector-im/element-web/issues/22141
----
Notes: none
---
=> Add a catastrophic throw to thread constructor

spec/integ/matrix-client-syncing.spec.js, src/sync.ts
Fixes https://github.com/vector-im/element-web/issues/22106
**Reviewer**: This has two commits: a failing test and the fix. This is to demonstrate that the test actually works, because I don't exactly have confidence in it myself.
---
* Ensure rooms are recalculated on re-invites ([\#2374](https://github.com/matrix-org/matrix-js-sdk/pull/2374)). Fixes vector-im/element-web#22106.
=> Ensure rooms are recalculated on re-invites

src/crypto/index.ts, src/webrtc/call.ts
This PR encrypts to-device events used in GroupCall signalling.
---
* Add support for sending encrypted to-device events with OLM ([\#2322](https://github.com/matrix-org/matrix-js-sdk/pull/2322)). Contributed by @robertlong.
=> Add support for sending encrypted to-device events with OLM

src/store/indexeddb.ts
Signed-off-by: Lars Richard <lars.richard@iserv.de>
Fixes #2384
---
* Fixes #2384 ([\#2385](https://github.com/matrix-org/matrix-js-sdk/pull/2385)). Fixes undefined/matrix-js-sdk#2384. Contributed by @schmop.
=> Catch promise errors in degradable (fixes #2384)

src/webrtc/call.ts, src/webrtc/groupCall.ts
Fetch the device info once at the start of the cal and cache it
rather than fetching every time, and throw if we're supposed to be
using e2e but the other end has no e2e keys.
Fixes https://github.com/vector-im/element-call/issues/338
---
* Handle other members having no e2e keys ([\#2383](https://github.com/matrix-org/matrix-js-sdk/pull/2383)). Fixes vector-im/element-call#338.
=> Handle other members having no e2e keys

spec/unit/relations.spec.ts, src/models/event.ts, src/models/relations.ts
Fixes https://github.com/vector-im/element-web/issues/22280
---
* Fix behaviour of isRelation with relation m.replace for state events ([\#2389](https://github.com/matrix-org/matrix-js-sdk/pull/2389)). Fixes vector-im/element-web#22280.
=> Fix behaviour of isRelation with relation m.replace for state events

src/client.ts, src/interactive-auth.ts
Type: Task
Related: https://github.com/matrix-org/matrix-react-sdk/pull/8654
---
=> improve types for registration calls

src/store/indexeddb-local-backend.ts
Adds a flag to stop the sync worker trying to persist to indexeddb if there is already a persist in flight.  This means that if indexeddb is being very slow (e.g. due to the browser running for a few seconds every ~10 mins while a macbook is asleep), you won't end up with overlapping write operations to indexeddb which could consume heap and cause an OOM.  It's okay to do this in the sync worker rather than the main thread, as it turns out that all the accumulation happens inside the worker, so we never pass large accumulated sync responses over postmessage to the worker.
If the persist is skipped, we accumulate user presence updates in RAM to stop them being lost (given the sync accumulator doesn't handle them itself for some reason).
Hopefully fixes …
=> Prevent overlapping sync accumulator persists

spec/unit/stores/indexeddb.spec.ts, src/store/indexeddb-local-backend.ts, src/store/indexeddb.ts
Fixes https://github.com/matrix-org/element-web-rageshakes/issues/13170
---
* Fix degraded mode for the IDBStore and test it ([\#2400](https://github.com/matrix-org/matrix-js-sdk/pull/2400)). Fixes matrix-org/element-web-rageshakes#13170.
=> Fix degraded mode for the IDBStore and test it

.eslintrc.js, spec/unit/matrix-client.spec.ts, src/client.ts, src/http-api.ts
This should be fine to do as non-breaking given the function was previously unstable.
---
* Convert `getLocalAliases` to a stable API call ([\#2402](https://github.com/matrix-org/matrix-js-sdk/pull/2402)).
=> Convert `getLocalAliases` to a stable API call

src/webrtc/call.ts, src/webrtc/groupCall.ts
This waits until the mute metadata update is sent to all the calls
before telling the user they're unmuted, when in PTT mode (and only
when starting to talk, ie. unmuting). This should help avoid situations
where the signalling connection is slow enough that the unmute event
takes long enough to reach the other side that you hear someone speak
before they've apparently unmuted.
Involves splitting out the method to send the metadata update.
Small delay looks like this (with network clamped to 50kbps & 100ms latency):
https://user-images.githubusercontent.com/986903/170251775-c6a9c022-23cc-4c0e-8145-2fc69fa8a1a3.mov
---
* Wait for mute event to send in PTT mode ([\#2401](https://github.com/matrix-org/matrix-js-sdk/pull/2401)).
=> Wait for mute event to send in PTT mode

src/crypto/recoverykey.ts, src/index.ts, src/utils.ts
Reverts matrix-org/matrix-js-sdk#2414
import compat is just the worst https://github.com/matrix-org/matrix-react-sdk/runs/6656911557?check_suite_focus=true
=> Revert "Fix request, crypto, and bs58 imports"

src/webrtc/call.ts, src/webrtc/groupCall.ts
When we lose ICE connection to peers, set the status of their feeds
to muted so to end their talking session.
For https://github.com/vector-im/element-call/issues/331
---
* Mute disconnected peers in PTT mode ([\#2421](https://github.com/matrix-org/matrix-js-sdk/pull/2421)).
=> Mute disconnected peers in PTT mode

spec/unit/matrix-client.spec.ts, src/client.ts, src/content-helpers.ts
Fixes https://github.com/vector-im/element-web/issues/22433
---
* Add tests for sendEvent threadId handling ([\#2435](https://github.com/matrix-org/matrix-js-sdk/pull/2435)). Fixes vector-im/element-web#22433.
=> Add tests for sendEvent threadId handling

src/webrtc/groupCall.ts
And not always to true. This was causing audio & video to start muted
sometimes on normal calls because the ICE connection state would change
to 'checking', causing the feeds to be muted.
Fixes https://github.com/vector-im/element-call/issues/382
---
* Set PTT mode on call correctly ([\#2445](https://github.com/matrix-org/matrix-js-sdk/pull/2445)). Fixes vector-im/element-call#382.
=> Set PTT mode on call correctly

src/webrtc/call.ts, src/webrtc/callEventHandler.ts, src/webrtc/groupCall.ts
There are a number of different cases here: there were some before
when dealing with versions that didn't send deviceId. This catches
all of them and makes all these cases emit the same error.
---
* Emit unknown device errors for group call participants without e2e ([\#2447](https://github.com/matrix-org/matrix-js-sdk/pull/2447)).
=> Emit unknown device errors for group call participants without e2e

src/webrtc/groupCall.ts
Only enable the stream cloning behaviour on Safari: it was causing
the audio renderer on Chrome (both desktop and Android) to hang,
causing audio to fail sometimes in Element Call and other Chrome
tabs (eg. YouTube) to fail to play audio.
Fixes https://github.com/vector-im/element-call/issues/267
---
* Only clone streams on Safari ([\#2450](https://github.com/matrix-org/matrix-js-sdk/pull/2450)). Fixes vector-im/element-call#267.
=> Only clone streams on Safari

src/models/thread.ts
See https://github.com/matrix-org/matrix-react-sdk/pull/8845
We can already return null/undefined implicitly, so declare it.
---
* Clearly indicate that `lastReply` on a Thread can return falsy ([\#2462](https://github.com/matrix-org/matrix-js-sdk/pull/2462)).
=> Clearly indicate that `lastReply` on a Thread can return falsy

src/crypto/index.ts, src/store/indexeddb-store-worker.ts
---
* Log real errors and not just their messages, traces are useful ([\#2464](https://github.com/matrix-org/matrix-js-sdk/pull/2464)).
=> Log real errors and not just their messages, traces are useful

spec/test-utils/beacon.ts, spec/unit/models/beacon.spec.ts, src/models/beacon.ts
Adds leniency so start timestamps that are slightly in the future are still considered live.
---
* Live location share - add start time leniency ([\#2465](https://github.com/matrix-org/matrix-js-sdk/pull/2465)). Contributed by @kerryarchibald.
=> Live location share - add start time leniency (PSF-1081)

src/webrtc/groupCall.ts
Depends on https://github.com/matrix-org/matrix-spec-proposals/pull/3831
---
* Expire call member state events after 1 hour ([\#2446](https://github.com/matrix-org/matrix-js-sdk/pull/2446)).
=> Expire call member state events after 1 hour

src/webrtc/groupCall.ts
to match recent updates to MSC3401
---
=> Don't ignore call member events with a distant future expiration date

src/webrtc/groupCall.ts
This was one thing that could allow you to keep transmitting past 20 seconds in PTT mode on Firefox.
---
* Don't block muting on determining whether the device exists ([\#2461](https://github.com/matrix-org/matrix-js-sdk/pull/2461)).
=> Don't block muting on determining whether the device exists

spec/unit/models/beacon.spec.ts, src/models/beacon.ts
Exposes the MatrixEvent as well as parsed location info for use in forwarding.
---
* expose latestLocationEvent on beacon model ([\#2467](https://github.com/matrix-org/matrix-js-sdk/pull/2467)). Contributed by @kerryarchibald.
=> expose latestLocationEvent on beacon model (PSF-1044) 

src/@types/requests.ts
Implement [MSC3827: Filtering of `/publicRooms` by room type](https://github.com/matrix-org/matrix-spec-proposals/pull/3827)
Towards https://github.com/vector-im/element-meta/issues/338
For https://github.com/matrix-org/matrix-react-sdk/pull/8866
---
* Implement MSC3827: Filtering of `/publicRooms` by room type ([\#2469](https://github.com/matrix-org/matrix-js-sdk/pull/2469)).
=> Implement MSC3827: Filtering of `/publicRooms` by room type

src/webrtc/call.ts
Fixes https://github.com/vector-im/element-web/issues/22629
---
* Send call version `1` as a string ([\#2471](https://github.com/matrix-org/matrix-js-sdk/pull/2471)). Fixes vector-im/element-web#22629.
=> Send call version `1` as a string

src/webrtc/call.ts
Regressed by https://github.com/matrix-org/matrix-js-sdk/pull/2352
(you can just use RTCStatsReport as an iterator directly (which
was was what that code was doing before) which uses entries(
which gives you key/value pairs, but using forEach gives you just
the value.
---
* Fix call.collectCallStats() ([\#2480](https://github.com/matrix-org/matrix-js-sdk/pull/2480)).
=> Fix call.collectCallStats()

src/webrtc/call.ts
Older typescript library doesn't know about .values() on the stats
object, so it was failing in react sdk which had an older typescript.
https://github.com/matrix-org/matrix-react-sdk/pull/8935 was an
attempt to upgrade it but did not seem to be helping on CI, despite
being fine locally.
---
=> Go back to forEach in collectcallstats

src/webrtc/call.ts
At the moment it looks like its more valuable to get the audio from
people even if they're not actually shown as speaking. We can always
re-introduce it later.
---
=> Remove the feature to disable audio from muted members

package.json, src/webrtc/call.ts, yarn.lock
This greatly reduces the amount of bandwidth used when transmitting silence.
Here's some sample stats where Firefox and Chrome were both transmitting silence to each other:
.|Before|After
-|-|-
Firefox|50 packets/s, 13 Kb/s|5 packets/s, 700 b/s
Chrome|50 packets/s, 1.2 Kb/s|5 packets/s, 80 b/s
We should investigate at some point why Firefox's bandwidth usage for audio is an order of magnitude higher than Chrome's.
---
* Enable DTX on audio tracks in calls ([\#2482](https://github.com/matrix-org/matrix-js-sdk/pull/2482)).
=> Enable DTX on audio tracks in calls

src/models/room.ts
The plan is to use this for the local rooms when creating a DM.
Notes: `room` now exports `KNOWN_SAFE_ROOM_VERSION`
---
* `room` now exports `KNOWN_SAFE_ROOM_VERSION` ([\#2474](https://github.com/matrix-org/matrix-js-sdk/pull/2474)). Contributed by @weeman1337.
=> Export KNOWN_SAFE_ROOM_VERSION

src/webrtc/callEventHandler.ts
This listener looks like it was left over from something as it just
did nothing at all. The todevice event gets put into the call
event buffer which awaits on decryption for each event before
processing, so it should already wait for decryption.
More info: https://github.com/vector-im/element-call/issues/428
---
=> Remove empty decryption listener

src/client.ts
The value can be undefined, but the type was just string
tests: Ran all tests
signed-off-by: austin ellis austin@hntlabs.com
notes: none
---
=> Fix return type on funcs in matrixClient to be optionally null

src/webrtc/call.ts
This clause was causing all PTT calls to mute the remote side immediately upon ICE connection status changing to 'checking'.
Closes https://github.com/vector-im/element-call/issues/425
---
* Don't mute the remote side immediately in PTT calls ([\#2487](https://github.com/matrix-org/matrix-js-sdk/pull/2487)). Fixes vector-im/element-call#425.
=> Don't mute the remote side immediately in PTT calls

.github/workflows/pull_request.yaml
As it is now used as a blocking stage due to validating required labels
---
=> Run the changelog action regardless of trigger phase

src/client.ts, src/webrtc/call.ts
---
* Add config option for e2e group call signalling ([\#2492](https://github.com/matrix-org/matrix-js-sdk/pull/2492)).
=> Add config option for e2e group call signalling

spec/TestClient.ts, spec/test-utils/webrtc.ts, spec/unit/webrtc/call.spec.ts, spec/unit/webrtc/callFeed.spec.ts, src/webrtc/call.ts
=> Improve VoIP integrations testing

src/client.ts
As of writing, the MSC is in FCP for **rejection**: https://github.com/matrix-org/matrix-spec-proposals/pull/3244
We probably should have named `IRoomCapability` something more unstable-looking, or added jsdoc to say it's unstable, so it feels less dangerous to remove, however considering how people use this I'm not overly concerned enough to call this a breaking change myself.
Paired with https://github.com/matrix-org/matrix-react-sdk/pull/9018
---
* Remove MSC3244 support ([\#2504](https://github.com/matrix-org/matrix-js-sdk/pull/2504)).
=> Remove MSC3244 support

spec/integ/matrix-client-methods.spec.js, src/client.ts
Fixes https://github.com/vector-im/element-web/issues/22757
Also add tests for specifically the functionality described in the issue - I'm very surprised we don't have `createRoom` tests, but that's a future PR's problem.
---
* Actually store the identity server in the client when given as an option ([\#2503](https://github.com/matrix-org/matrix-js-sdk/pull/2503)). Fixes vector-im/element-web#22757.
=> Actually store the identity server in the client when given as an option

src/webrtc/call.ts, src/webrtc/callFeed.ts, src/webrtc/groupCall.ts
Audio & video mute status were set in separate calls but share a
mute status changed event, so you'd always get two mute status
changed events emitted. We could suppress events where the mute
status didn't change, but this would still get two events saying
the same thing when they both changed. Instead, merge setAudioMuted
& setVideoMuted into a single call that sets either or both.
---
* Prevent double mute status changed events ([\#2502](https://github.com/matrix-org/matrix-js-sdk/pull/2502)).
=> Prevent double mute status changed events

spec/unit/realtime-callbacks.spec.js, src/realtime-callbacks.ts
Towards https://github.com/vector-im/element-web/issues/21969
---
=> Remove `setNow` from `realtime-callbacks.ts`

src/client.ts
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/2494
---
* Don't crash with undefined room in `processBeaconEvents()` ([\#2500](https://github.com/matrix-org/matrix-js-sdk/pull/2500)). Fixes #2494.
=> Don't crash with undefined room in `processBeaconEvents()`

spec/TestClient.ts, spec/integ/matrix-client-crypto.spec.ts
=> Typescriptify crypto integration tests

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pull_request.yaml, CHANGELOG.md, package.json, spec/TestClient.ts, spec/integ/matrix-client-event-timeline.spec.ts, spec/integ/matrix-client-methods.spec.js, spec/test-utils/test-utils.ts, spec/test-utils/webrtc.ts, spec/unit/crypto/backup.spec.ts, spec/unit/crypto/crypto-utils.ts, spec/unit/realtime-callbacks.spec.js, spec/unit/utils.spec.ts, spec/unit/webrtc/call.spec.ts, spec/unit/webrtc/callFeed.spec.ts, src/client.ts, src/crypto/api.ts, src/crypto/verification/Error.ts, src/models/room.ts, src/models/thread.ts, src/realtime-callbacks.ts, src/utils.ts, src/webrtc/call.ts, yarn.lock
=> Merge develop into group call branch again

src/client.ts
As shown elsewhere in client.ts, `turnServersExpiry` really is in milliseconds rather than seconds. It seems that other libraries like matrix-react-sdk were already expecting it to be in milliseconds anyways, so it's just the documentation that was wrong.
---
* Add super cool feature ([\#2520](https://github.com/matrix-org/matrix-js-sdk/pull/2520)).
=> Correct the units in TURN servers expiry documentation

spec/integ/megolm-integ.spec.js, spec/unit/crypto/algorithms/megolm.spec.js, src/crypto/algorithms/megolm.ts, src/crypto/index.ts
We no longer send or receive the unstable type.
The [MSC](https://github.com/matrix-org/matrix-spec-proposals/pull/2399) was *merged* to the spec about 2 years ago, so we should be more than safe to remove this sort of support. It was formally released in v1.1 of the spec in November of 2021, well beyond the 2 month window the spec requests of implementation for a grace period.
The only implementation I can see which hasn't changed over is Element Android: https://github.com/matrix-org/matrix-android-sdk2/blob/3adfe4d01c8ff5189ada1373015501256e2a2d57/matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/EventType.kt#L90
Given the massive time scale and spec process here, I'm keen to land this without waiting for Android to fix their event type usage. Otherwise, …
=> Remove unstable support for `m.room_key.withheld`

spec/integ/megolm-integ.spec.ts, spec/test-utils/test-utils.ts, src/crypto/index.ts
---
* Re-insert room IDs when decrypting bundled redaction events returned by `/sync` ([\#2531](https://github.com/matrix-org/matrix-js-sdk/pull/2531)). Contributed by @duxovni.
=> Re-insert room IDs when decrypting bundled redaction events returned by `/sync`

src/webrtc/callFeed.ts
For https://github.com/vector-im/element-call/pull/468
---
=> Add local volume control

src/webrtc/groupCall.ts
The `GroupCall` class uses a reemitter to also emit all the `CallEvent`'s from the calls that are part of the group call (in addition to the `GroupCallEvent`'s). This PR adds the missing events that are coming from the reemitter.
---
* Add missing events from reemitter to GroupCall ([\#2527](https://github.com/matrix-org/matrix-js-sdk/pull/2527)). Contributed by @toger5.
=> Add missing events from reemitter to GroupCall

release.sh
=> Require confirmation when doing proper release when intending to make an RC

src/@types/requests.ts
Requires https://github.com/matrix-org/matrix-spec-proposals/pull/3827
Requires https://github.com/matrix-org/synapse/pull/13370
Requires https://github.com/matrix-org/matrix-react-sdk/pull/9092
---
* Use stable prefixes for MSC3827 ([\#2537](https://github.com/matrix-org/matrix-js-sdk/pull/2537)).
=> Use stable prefixes for MSC3827

src/webrtc/call.ts
We were trying to apply modifications to all media types which led
to confusing warning messages saying opus wasn't present (when it
was for the video stream). Make the modifications media-type specific
to avoid this.
---
=> Make SDP munging media type specific

src/models/room.ts
Minor refactor I stumbled upon whilst working on another piece of code
---
=> Use EventType enum values instead of hardcoded strings

spec/unit/crypto.spec.ts, spec/unit/crypto/algorithms/megolm.spec.ts, spec/unit/matrix-client.spec.ts, src/client.ts, src/crypto/algorithms/megolm.ts, src/crypto/index.ts, yarn.lock
This is a port of the same changes from the robertlong/group-call branch.
Depends on https://github.com/matrix-org/matrix-mock-request/pull/18
---
* Add support for sending user-defined encrypted to-device messages ([\#2528](https://github.com/matrix-org/matrix-js-sdk/pull/2528)).
=> Add support for sending user-defined encrypted to-device messages

spec/unit/crypto/algorithms/megolm.spec.ts, src/crypto/algorithms/megolm.ts
---
* Always block sending keys to unverified devices of verified users ([\#2562](https://github.com/matrix-org/matrix-js-sdk/pull/2562)). Contributed by @duxovni.
=> Always block sending keys to unverified devices of verified users

CHANGELOG.md, package.json, spec/unit/crypto.spec.ts, spec/unit/crypto/algorithms/megolm.spec.ts, spec/unit/matrix-client.spec.ts, spec/unit/queueToDevice.spec.ts, spec/unit/webrtc/call.spec.ts, spec/unit/webrtc/callFeed.spec.ts, src/ToDeviceMessageQueue.ts, src/client.ts, src/crypto/algorithms/megolm.ts, src/crypto/index.ts, src/models/ToDeviceMessage.ts, src/models/room.ts, src/scheduler.ts, src/sliding-sync.ts, src/store/index.ts, src/store/indexeddb-backend.ts, src/store/indexeddb-local-backend.ts, src/store/indexeddb-remote-backend.ts, src/store/indexeddb-store-worker.ts, src/store/indexeddb.ts, src/store/memory.ts, src/store/stub.ts, src/webrtc/call.ts, src/webrtc/callFeed.ts, yarn.lock
This merges the latest changes from develop again. This is as simple a merge as possible: I've not introduced any other changes at this stage.
Reintroduces the setNewStream method which was removed
in https://github.com/matrix-org/matrix-js-sdk/pull/2551 (I think it makes
sense as a convenient way to re-use the feed wrapper object but switch out
the feed? Comment updated appropriately.)
---
=> Merge changes from develop

src/store/indexeddb-local-backend.ts
This should hopefully reduce chances of
https://github.com/vector-im/element-web/issues/21541 a bit more,
as we were incorrectly loading the sync accumulator even
if a sync persist was already in flight, thus wasting RAM
and increasing the chance of the renderer process OOMing
---
* Don't load the sync accumulator if there's already a sync persist in flight ([\#2569](https://github.com/matrix-org/matrix-js-sdk/pull/2569)).
=> Don't load the sync accumulator if there's already a sync persist in flight

src/webrtc/call.ts
These had somehow got mixed up so the type check was failing.
Nothing uses the response return type, so just return void.
---
=> Fix return types of event sending functions

spec/test-utils/webrtc.ts, spec/unit/webrtc/groupCall.spec.ts
=> Add basic creation / entering tests for group calls

.github/workflows/jsdoc.yml
Otherwise it won't include releases in the index as the RC is a superstring of the release version
---
=> Make jsdoc generation gha regex more strict

spec/integ/sliding-sync.spec.ts, src/sliding-sync.ts
This allows clients to know when a request has been applied
on the server. This allows us to change `resend(): void` to
`resend(): Promise<string>` which resolves/rejects with the
transaction ID when it has been applied/not.
---
* Add txn_id support to sliding sync ([\#2567](https://github.com/matrix-org/matrix-js-sdk/pull/2567)).
=> Add txn_id support to sliding sync

src/webrtc/groupCall.ts
=> Tidy up imports

spec/integ/sliding-sync-sdk.spec.ts, src/sliding-sync-sdk.ts
Notes: fixed a sliding sync issue where history could be interpreted as live events.
---
* fixed a sliding sync issue where history could be interpreted as live events. ([\#2583](https://github.com/matrix-org/matrix-js-sdk/pull/2583)).
=> sliding sync bugfix: ensure history is treated as history and not live events

spec/unit/room.spec.ts, src/models/room.ts
Fixes https://github.com/vector-im/element-web/issues/23027
Details on what is happening in https://github.com/vector-im/element-web/issues/23027#issuecomment-1211819879
---
* Fix finding event read up to if stable private read receipts is missing ([\#2585](https://github.com/matrix-org/matrix-js-sdk/pull/2585)). Fixes vector-im/element-web#23027.
=> Fix finding event read up to if stable private read receipts is missing

spec/unit/models/beacon.spec.ts, src/content-helpers.ts, src/models/beacon.ts
Fixes https://github.com/vector-im/element-web/issues/23078
with https://github.com/matrix-org/matrix-react-sdk/pull/9186
---
* Add super cool feature ([\#2591](https://github.com/matrix-org/matrix-js-sdk/pull/2591)). Fixes vector-im/element-web#23078. Contributed by @kerryarchibald.
=> Fix: Handle parsing of a beacon info event without asset

spec/unit/webrtc/groupCall.spec.ts
Inspiration wwlecome for the renamed describe group which we're
really abusing for a bunch of things that happen to have the same
dependencies.
Fixes https://github.com/vector-im/element-call/issues/532
---
=> Add tests for incoming calls in group calls

spec/test-utils/webrtc.ts, spec/unit/webrtc/call.spec.ts, src/webrtc/call.ts
Fixes https://github.com/vector-im/element-call/issues/537
---
=> Add unit tests for hangup / reject

spec/unit/room.spec.ts, src/client.ts, src/models/room.ts
---
* Add ability to override built in room name generator for an i18n'able one ([\#2609](https://github.com/matrix-org/matrix-js-sdk/pull/2609)).
=> Add ability to override built in room name generator for an i18n'able one

.eslintrc.js, src/ReEmitter.ts, src/models/room.ts, src/sliding-sync-sdk.ts, src/sync.ts
This also fixes some potential memory leaks and abuse of `removeAllListeners` in sync.ts.
---
* Re-emit room state events on rooms ([\#2607](https://github.com/matrix-org/matrix-js-sdk/pull/2607)).
=> Re-emit room state events on rooms

src/sliding-sync.ts
Notes: Add `tags` and `not_tags` to the list of valid sliding sync filters.
---
=> Add tags and not_tags to the list of valid sliding sync filters

spec/integ/sliding-sync.spec.ts, src/sliding-sync.ts
If you leave a room you can get a lone DELETE op.
If you join a room you can get a lone INSERT op.
Up until now, we've assumed these operations happen at the ends
of the list (e.g [0] or [length-1]) which is not guaranteed as it
depends on the sort order (e.g sort alphabetically and join a room
called 'D'). In this scenario, the indexes would not be tracked
correctly. Fixed with integration tests.
Notes: fixed a sliding sync bug which could cause the `roomIndexToRoomId` map to be incorrect when a new room is added in the middle of the list or when an existing room is deleted from the middle of the list.
---
* fixed a sliding sync bug which could cause the `roomIndexToRoomId` map to be incorrect when a new room is added in the middle of the …
=> sliding sync: handle lone DELETE and INSERT operations

spec/test-utils/webrtc.ts, spec/unit/webrtc/call.spec.ts, src/webrtc/call.ts
Fixes https://github.com/vector-im/element-call/issues/548
---
=> 1:1 screenshare tests

spec/test-utils/webrtc.ts, spec/unit/webrtc/call.spec.ts
Still involves quite a few casts to any unfortunately as it turns
out we access quite a few private methods on the Call class in these
tests.
---
=> Add types to the call unit test suites

src/webrtc/groupCall.ts
Also move the are-we-in-the-call check up to the top so we don't log a bunch of stuff (and do a bunch of work) to then just exit the function because we haven't joined the call yet.
For https://github.com/vector-im/element-call/issues/559
---
=> Add logging to diagnose connection issue

src/webrtc/groupCallEventHandler.ts
As hopefully explained in comment
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/2589
---
* Wait for client to start syncing before making group calls ([\#2632](https://github.com/matrix-org/matrix-js-sdk/pull/2632)). Fixes #2589.
=> Wait for client to start syncing before making group calls

spec/unit/webrtc/groupCall.spec.ts
=> Test call mute status set on call state chnage

spec/unit/event-timeline-set.spec.ts, spec/unit/room.spec.ts, src/models/event-timeline-set.ts, src/models/room.ts
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/2618
---
* Fix handling of remote echoes doubling up ([\#2639](https://github.com/matrix-org/matrix-js-sdk/pull/2639)). Fixes #2618.
=> Fix handling of remote echoes doubling up

src/client.ts, src/webrtc/groupCallEventHandler.ts
See comment, although this still feels like a poor solution to the
problem. Might be better if the js-sdk processed everything internally
before emitting the 'Room' event (or indeed before joinRoom resolved)
so the app knows everything is ready when it gets that event.
Also removes the corresponding event in favour of this method.
---
* Add client.waitUntilRoomReadyForGroupCalls() ([\#2641](https://github.com/matrix-org/matrix-js-sdk/pull/2641)).
=> Add client.waitUntilRoomReadyForGroupCalls()

spec/unit/matrix-client.spec.ts, src/client.ts, src/models/invites-ignorer.ts, src/utils.ts
This is a second take on the matrix-js-sdk-level machinery needed to be able to ignore invites, this time based on MSC3847.
The intention is that decisions on whether/how to display ignored invites is left in the hands of matrix-react-sdk.
---
* Base support for MSC3847: Ignore invites with policy rooms ([\#2626](https://github.com/matrix-org/matrix-js-sdk/pull/2626)). Contributed by @Yoric.
=> Base support for MSC3847: Ignore invites with policy rooms

spec/integ/sliding-sync-sdk.spec.ts, src/sliding-sync-sdk.ts, src/sliding-sync.ts
This is critical for calculating client-side push rules correctly.
Without it, the push processor may think rooms have a different
number of members, resulting typically in annoying failure modes
where rooms constantly make noises because the code thinks they
are 1:1 rooms.
Notes: add invited_count and joined_count to sliding sync room responses.
---
* add invited_count and joined_count to sliding sync room responses. ([\#2628](https://github.com/matrix-org/matrix-js-sdk/pull/2628)).
=> sliding sync: add invited|joined_count

spec/test-utils/webrtc.ts, spec/unit/webrtc/mediaHandler.spec.ts, src/webrtc/mediaHandler.ts
This was originally test for part of the file, but just adding the rest onto this PR rather than making another one off this one.
Also fixes a bug where streams wouldn't be re-used if only a video or audio stream was requested.
For https://github.com/vector-im/element-call/issues/544
---
=> MediaHandler Tests

spec/unit/NamespacedValue.spec.ts, src/NamespacedValue.ts
For convenience
---
* Add a property aggregating all names of a NamespacedValue ([\#2656](https://github.com/matrix-org/matrix-js-sdk/pull/2656)).
=> Add a property aggregating all names of a NamespacedValue

spec/test-utils/webrtc.ts, spec/unit/webrtc/call.spec.ts
=> Add test for removing RTX codec

src/@types/auth.ts, src/client.ts
Partially reverts https://github.com/matrix-org/matrix-js-sdk/pull/2633 due to the required React SDK PR not being ready to land at the same time
---
=> Revert "Add login flow types from matrix-react-sdk (#2633)"

spec/unit/webrtc/groupCall.spec.ts, src/webrtc/groupCall.ts
We ran an async function between checking for an existing call and adding the new one to the map, so it would have been possible to start creating another call while we were placing the first call. This changes the code to add the call to the map as soon as we've created it.
Also adds more logging.
---
* Fix race in creating calls ([\#2662](https://github.com/matrix-org/matrix-js-sdk/pull/2662)).
=> Fix race in creating calls

.github/workflows/release-npm.yml
Without this, dist-tag will fail as it did [here](https://github.com/matrix-org/matrix-js-sdk/actions/runs/3044693309/jobs/4905368087)
---
=> Have setup-node set up the npmrc for NODE_AUTH_TOKEN

spec/test-utils/webrtc.ts, spec/unit/webrtc/call.spec.ts
=> Add tests for call answering / candidate sending

spec/unit/webrtc/call.spec.ts
---
* Add tests for ice candidate sending ([\#2674](https://github.com/matrix-org/matrix-js-sdk/pull/2674)).
=> Add tests for ice candidate sending

spec/unit/embedded.spec.ts, src/embedded.ts
Otherwise, the RoomWidgetClient class can end up accidentally sending and receiving events from rooms it didn't intend to, if it's an always-on-screen widget.
---
* Target widget actions at a specific room ([\#2670](https://github.com/matrix-org/matrix-js-sdk/pull/2670)).
=> Target widget actions at a specific room

spec/unit/webrtc/call.spec.ts
=> Add test for call transfers

spec/integ/matrix-client-methods.spec.js, spec/test-utils/test-utils.ts, spec/unit/pusher.spec.ts, src/@types/PushRules.ts, src/@types/event.ts, src/client.ts
Implements MSC3881, https://github.com/matrix-org/matrix-spec-proposals/pull/3881
Epic https://element-io.atlassian.net/browse/PSG-595
Fixes partially https://element-io.atlassian.net/browse/PSG-707
---
* Support to remotely toggle push notifications ([\#2686](https://github.com/matrix-org/matrix-js-sdk/pull/2686)).
=> Support to remotely toggle push notifications

spec/integ/matrix-client-methods.spec.js, src/@types/auth.ts, src/@types/uia.ts, src/client.ts
As the added functionality is just passing through an HTTP request I don't think unit tests are needed for this.
---
* Implementation of MSC3882 login token request ([\#2687](https://github.com/matrix-org/matrix-js-sdk/pull/2687)). Contributed by @hughns.
=> Implementation of MSC3882 login token request

spec/unit/webrtc/callEventHandler.spec.ts
=> Add `CallEventHandler` tests

src/webrtc/call.ts
We didn't reset the 'seen end of candidates' flag when doign an ICE restart, so we would have ignored all locally gathered candidates on an ICE restart.
---
* Fix ICE restarts ([\#2702](https://github.com/matrix-org/matrix-js-sdk/pull/2702)).
=> Fix ICE restarts

src/crypto/store/indexeddb-crypto-store-backend.ts, src/store/indexeddb-local-backend.ts
=> Calculate IndexedDB versions automatically to reduce repeated information and possibilities for error

spec/integ/matrix-client-crypto.spec.ts, spec/integ/matrix-client-syncing.spec.ts, src/client.ts, src/sync.ts
When the Matrix client is initialized without crypto support it now breaks in the sync as starting from matrix-js-sdk 19.7.0 the additional code was added that directly access the client's crypto feature. 
This PR is aimed to fix the issue by introducing the additional check that crypto is actually available before accessing it
Signed-off-by: Stanislav Demydiuk <s.demydiuk@gmail.com>
---
* Fix issue in sync when crypto is not supported by client ([\#2715](https://github.com/matrix-org/matrix-js-sdk/pull/2715)). Contributed by @stas-demydiuk.
=> Fix issue in sync when crypto is not supported by client

src/crypto/algorithms/megolm.ts
Signed-off-by: maghen.calinghee@beta.gouv.fr
**Scenario 1: Verification of 2 sessions when logging : session A in and session B in**
_Contexte:_
matrix-js-sdk : 20.0.0
matrix-react-sdk : 3.57.0
1. user 1 has already a session opened : session A
2. user 1 is opening a new session by logging : session B
3. on session B, a verification request dialog is opening
4. on session A, a verification dialog is waiting 
5. session B press `Continue`
6. session A displayed the verification process dialog
7. session B displayed the verification process dialog
8. session A press `They match` and waits for session B
9. session B press `They match`, a success dialog is displayed 
10. on session A , a success dialog is displayed 
11. session A press `Got it`
12. session B receive the key and decrypt the …
=> Unexpected ignored self key request when it's not shared history

src/client.ts
=> Device manager - `last_seen_user_agent` device property

src/client.ts, src/crypto/EncryptionSetup.ts
Fixes https://github.com/vector-im/element-web/issues/22839
It's been stable since at least v1.1, and received the `v3` version specifier implying it's even older than that: https://spec.matrix.org/v1.4/client-server-api/#post_matrixclientv3room_keysversion
---
* Use stable calls to `/room_keys` ([\#2729](https://github.com/matrix-org/matrix-js-sdk/pull/2729)). Fixes vector-im/element-web#22839.
=> Use stable calls to `/room_keys`

src/crypto/SecretStorage.ts
fixes https://github.com/vector-im/element-web/issues/23374
Bug was introduced in the recent security release.
The incorrect code is checking the `sender_key` in the encrypted content, which is normally not set.  It should have been checking the `sender_key` in the cleartext content, or `event.getSenderKey()`.
---
* Use the correct sender key when checking shared secret ([\#2730](https://github.com/matrix-org/matrix-js-sdk/pull/2730)). Fixes vector-im/element-web#23374.
=> Use the correct sender key when checking shared secret

package.json, spec/integ/matrix-client-syncing.spec.ts, spec/test-utils/client.ts, spec/unit/filter.spec.ts, spec/unit/notifications.spec.ts, spec/unit/room.spec.ts, spec/unit/sync-accumulator.spec.ts, src/@types/sync.ts, src/client.ts, src/filter.ts, src/models/read-receipt.ts, src/models/room.ts, src/sync-accumulator.ts, src/sync.ts, src/utils.ts, yarn.lock
Implements https://github.com/matrix-org/matrix-spec-proposals/pull/3773
Related to https://github.com/vector-im/element-web/issues/23192
Passes the quality gate but still has optional strict null checks failures
---
* Add support for unread thread notifications ([\#2726](https://github.com/matrix-org/matrix-js-sdk/pull/2726)).
=> Add support for unread thread notifications

src/utils.ts
These characters are hard to type, but can result in empty display name problems - let's force the app to use the user ID in these cases.
---
=> Update hidden characters regex

spec/unit/feature.spec.ts, spec/unit/filter.spec.ts, src/@types/sync.ts, src/client.ts, src/feature.ts, src/filter-component.ts, src/filter.ts, src/store/memory.ts, src/sync.ts
Fixes https://github.com/vector-im/element-web/issues/23435
Creates a solution to detect features available on a given homeserver.
Developers can now document what matrix version will support a feature as well as the unstable prefixes. This code path is then accessible synchronously
---
* Fix sync init when thread unread notif is not supported ([\#2739](https://github.com/matrix-org/matrix-js-sdk/pull/2739)). Fixes vector-im/element-web#23435.
=> Fix sync init when thread unread notif is not supported

package.json, yarn.lock
---
* Upgrade to Olm 3.2.13 which has been repackaged to support Node 18 ([\#2744](https://github.com/matrix-org/matrix-js-sdk/pull/2744)).
=> Upgrade to Olm 3.2.13 which has been repackaged to support Node 18

spec/integ/matrix-client-relations.spec.ts, src/@types/requests.ts, src/client.ts, src/models/thread.ts
The implementation of [MSC3715](https://github.com/matrix-org/matrix-doc/pull/3715) was stabilized in [synapse](https://github.com/matrix-org/synapse/issues/13919) and we might want to use the new parameter. Note that the old name `direction` was always wrong and never worked so I don't think we need the fallback to the prefixed version. This change would also need a PR at the react-sdk but there only seems to be a [single usage](https://github.com/matrix-org/matrix-react-sdk/blob/cf029c51dc466db448c7324d3dda1fa484a9f3ee/src/stores/widgets/StopGapWidgetDriver.ts#L452). If you accept this change I can do a second PR to update it. I assume merging would need to be coordinated to not break the build(?).
An alternative could be to keep the name `direction` in the interface and convert it to …
=> Correct the dir parameter of MSC3715

src/client.ts
**Blocked on https://github.com/matrix-org/matrix-js-sdk/pull/2719**
Follow-on work from https://github.com/matrix-org/matrix-js-sdk/pull/2729
---
* Use even more stable calls to `/room_keys` ([\#2746](https://github.com/matrix-org/matrix-js-sdk/pull/2746)).
=> Use even more stable calls to `/room_keys`

spec/integ/matrix-client-methods.spec.ts, src/http-api/errors.ts, src/http-api/utils.ts
Unfortunately `fetch` also does not maintain stack traces, so errors are super opaque without this
---
=> Improve MatrixError message

src/webrtc/groupCall.ts
(PTT mode will still block on them, as expected. Also this only seems to affect muting/unmuting the microphone, not the camera)
This will hopefully fix https://github.com/vector-im/element-call/issues/592
---
* Don't block muting/unmuting on network requests ([\#2754](https://github.com/matrix-org/matrix-js-sdk/pull/2754)). Fixes vector-im/element-call#592.
=> Don't block muting/unmuting on network requests

spec/unit/http-api/utils.spec.ts, spec/unit/interactive-auth.spec.ts, src/http-api/errors.ts, src/http-api/index.ts, src/http-api/utils.ts
Previously, non-JSON responses would be missing the `httpStatus` property, which was different to how `request()` used to work.
Ensure we always send this property, even for non-JSON responses.
---
* Always send back an httpStatus property if one is known ([\#2753](https://github.com/matrix-org/matrix-js-sdk/pull/2753)).
=> Always send back an httpStatus property if one is known

src/models/event.ts, src/models/room.ts
- Fix the event handler map for Room and MatrixEvent to contain only items for events that can be emitted (based on EmittedEvents type)
- Export emitted events type for Room and MatrixEvent so they can be used in client apps
Signed-off-by: Stanislav Demydiuk [s.demydiuk@gmail.com](mailto:s.demydiuk@gmail.com)
---
* Export types for MatrixEvent and Room emitted events, and make event handler map types stricter ([\#2750](https://github.com/matrix-org/matrix-js-sdk/pull/2750)). Contributed by @stas-demydiuk.
=> Export types for MatrixEvent and Room emitted events, and make event handler map types stricter

spec/unit/room.spec.ts, src/models/room.ts
For https://github.com/vector-im/element-web/issues/23192
---
=> Fix notification type when resetting threads notifications

src/@types/event.ts, src/models/event.ts, src/models/room.ts
Fixes https://github.com/vector-im/element-web/issues/12680
Requires https://github.com/matrix-org/matrix-react-sdk/pull/9431
---
* Remove deprecated `m.room.aliases` references ([\#2759](https://github.com/matrix-org/matrix-js-sdk/pull/2759)). Fixes vector-im/element-web#12680.
=> Remove deprecated `m.room.aliases` references

src/http-api/prefix.ts
Testing the value of an enum is not sensible, a future end-to-end test involving a mock mail server and a sydent instance is planned.
Fixes https://github.com/vector-im/element-web/issues/23505
---
* Fix IdentityPrefix.V2 containing spurious `/api` ([\#2761](https://github.com/matrix-org/matrix-js-sdk/pull/2761)). Fixes vector-im/element-web#23505.
=> Fix IdentityPrefix.V2 containing spurious `/api`

spec/integ/megolm-integ.spec.ts, spec/olm-loader.ts, spec/unit/crypto/secrets.spec.ts, src/crypto/CrossSigning.ts, src/crypto/OlmDevice.ts, src/crypto/aes.ts, src/crypto/backup.ts, src/crypto/crypto.ts, src/crypto/key_passphrase.ts, src/crypto/keybackup.ts, src/crypto/store/base.ts, src/crypto/store/indexeddb-crypto-store-backend.ts, src/crypto/store/indexeddb-crypto-store.ts, src/crypto/store/localStorage-crypto-store.ts, src/crypto/store/memory-crypto-store.ts, src/index.ts, src/utils.ts
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/2760
Requires https://github.com/vector-im/element-web/pull/23506
---
* Remove node-specific crypto bits, use Node 16's WebCrypto ([\#2762](https://github.com/matrix-org/matrix-js-sdk/pull/2762)). Fixes #2760.
=> Remove node-specific crypto bits, use Node 16's WebCrypto

spec/integ/matrix-client-methods.spec.ts, src/client.ts
Due to `any` types this wasn't caught by TSC
Fixes https://github.com/matrix-org/element-web-rageshakes/issues/16206
---
* Fix POST data not being passed for registerWithIdentityServer ([\#2769](https://github.com/matrix-org/matrix-js-sdk/pull/2769)). Fixes matrix-org/element-web-rageshakes#16206.
=> Fix POST data not being passed for registerWithIdentityServer

src/client.ts
A trivial fix I happened to notice: as with most of the crypto functionality, `setCryptoTrustCrossSignedDevices` cannot be called until after `initCrypto`. We don't call this out for any of the other entrypoints so I haven't done so here either.
---
=> Remove incorrect comment

src/webrtc/call.ts
Switches back to addTrack, digging the transceivers out manually to re-use, because the only way to group tracks into streams re-using trasceivers from the offer is to use setStreams which FF doesn't implement.
---
* Fix connectivity regressions ([\#2780](https://github.com/matrix-org/matrix-js-sdk/pull/2780)).
=> Fix connectivity regressions

spec/unit/room.spec.ts, src/models/room.ts, src/sync.ts
Fixes an issue where notifications were completely wiped before being re-added.
This is an issue as sometimes the count is altered client side on event decryption, and the `highlight` count might end up not being accurate if we reset everything
---
=> Fix to keep locally computed thread notifications

src/crypto/DeviceList.ts
Type: Defect
---
* fix build error caused by wrong ts-strict improvements ([\#2783](https://github.com/matrix-org/matrix-js-sdk/pull/2783)). Contributed by @justjanne.
=> fix build error caused by wrong ts-strict improvements

src/webrtc/groupCall.ts, src/webrtc/mediaHandler.ts
For https://github.com/vector-im/element-call/pull/652
---
* Add throwOnFail to groupCall.setScreensharingEnabled ([\#2787](https://github.com/matrix-org/matrix-js-sdk/pull/2787)).
=> Add throwOnFail to groupCall.setScreensharingEnabled

src/sliding-sync.ts
Bringing TS definitions up-to-date with the latest MSC version.
---
=> Sliding sync: add include_old_rooms; remove is_tombstoned

src/sliding-sync.ts
Reverts matrix-org/matrix-js-sdk#2785 due to the react-sdk companion PR not being ready to land at the same time
=> Revert "Sliding sync: add include_old_rooms; remove is_tombstoned"

spec/integ/matrix-client-syncing.spec.ts, src/sliding-sync-sdk.ts, src/sync.ts
Account data events don't have an ID, clobber them on type instead
If multiple account data events came down sync, the previous event of the last event in the list was used for all prevEv's sent
---
* Fix incorrect prevEv being sent in ClientEvent.AccountData events ([\#2794](https://github.com/matrix-org/matrix-js-sdk/pull/2794)).
=> Fix incorrect prevEv being sent in ClientEvent.AccountData events

spec/unit/embedded.spec.ts, src/client.ts, src/embedded.ts
For https://github.com/vector-im/element-call/issues/657
---
* Add event and message capabilities to RoomWidgetClient ([\#2797](https://github.com/matrix-org/matrix-js-sdk/pull/2797)).
=> Add event and message capabilities to RoomWidgetClient

spec/unit/room.spec.ts, src/models/room.ts
Fixes https://github.com/vector-im/element-web/issues/23590
We need a way for people consuming a room to know when the unread notification have been reset
---
* Emit UnreadNotification event on notifications reset ([\#2804](https://github.com/matrix-org/matrix-js-sdk/pull/2804)). Fixes vector-im/element-web#23590.
=> Emit UnreadNotification event on notifications reset

.eslintrc.js
For https://github.com/vector-im/element-web/issues/23600
---
=> Switch ESLint warnings to be errors instead

src/crypto/verification/SAS.ts, src/sliding-sync-sdk.ts, src/sync.ts, src/utils.ts
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/2811
---
* Replace `instanceof Array` with `Array.isArray` ([\#2812](https://github.com/matrix-org/matrix-js-sdk/pull/2812)). Fixes #2811.
=> Replace `instanceof Array` with `Array.isArray`

spec/unit/webrtc/groupCall.spec.ts, src/client.ts, src/http-api/fetch.ts, src/http-api/interface.ts, src/webrtc/groupCall.ts
Yay `fetch`!
Closes https://github.com/vector-im/element-call/issues/639
---
* Let leave requests outlive the window ([\#2815](https://github.com/matrix-org/matrix-js-sdk/pull/2815)). Fixes vector-im/element-call#639.
=> Let leave requests outlive the window

spec/integ/matrix-client-syncing.spec.ts, src/client.ts
Fixes https://github.com/vector-im/element-web/issues/23634
---
* Catch server versions API call exception when starting the client ([\#2828](https://github.com/matrix-org/matrix-js-sdk/pull/2828)). Fixes vector-im/element-web#23634.
=> Catch server versions API call exception when starting the client

spec/unit/webrtc/groupCall.spec.ts, src/webrtc/groupCall.ts
Unfortunately there are still other methods that could race with `leave` and result in broken group call state, such as `enter` and `terminate`. For the future, should consider writing a more careful specification of how the whole group call state machine is meant to work.
---
* Resolve races between `initLocalCallFeed` and `leave` ([\#2826](https://github.com/matrix-org/matrix-js-sdk/pull/2826)).
=> Resolve races between `initLocalCallFeed` and `leave`

spec/unit/room.spec.ts, src/crypto/algorithms/megolm.ts, src/models/room.ts
---
* Fix default behavior of Room.getBlacklistUnverifiedDevices ([\#2830](https://github.com/matrix-org/matrix-js-sdk/pull/2830)). Contributed by @duxovni.
=> Fix default behavior of Room.getBlacklistUnverifiedDevices

spec/integ/matrix-client-syncing.spec.ts, src/client.ts
https://github.com/matrix-org/matrix-js-sdk/pull/2828 to hotfix release
---
* [Backport staging] Catch server versions API call exception when starting the client ([\#2832](https://github.com/matrix-org/matrix-js-sdk/pull/2832)).
=> [Backport staging] Catch server versions API call exception when starting the client

src/webrtc/groupCall.ts
Part of https://github.com/vector-im/element-call/pull/708
---
* Don't remove our own member for a split second when entering a call ([\#2844](https://github.com/matrix-org/matrix-js-sdk/pull/2844)).
=> Don't remove our own member for a split second when entering a call

spec/unit/event-timeline-set.spec.ts, src/models/event-timeline-set.ts, src/models/event.ts, src/models/room.ts
Reverts matrix-org/matrix-js-sdk#2848
Reverting due to it not working for notification timeline sets - causing downstream breakages https://dashboard.cypress.io/projects/ppvnzg/runs/5793/test-results/3be6d26d-bc97-4167-b966-a0c7aa2a6930
=> Revert "Extra insurance that we don't mix events in the wrong timelines"

src/models/event-timeline.ts
This would mean we can't add event listeners to these events
Required by https://github.com/matrix-org/matrix-react-sdk/pull/9540
---
* Do not freeze state in `initialiseState()` ([\#2846](https://github.com/matrix-org/matrix-js-sdk/pull/2846)).
=> Do not freeze state in `initialiseState()`

spec/unit/event-timeline.spec.ts, src/models/event-timeline.ts
Fixes https://github.com/vector-im/element-web/issues/23695
---
* Fix pagination token tracking for mixed room timelines ([\#2855](https://github.com/matrix-org/matrix-js-sdk/pull/2855)). Fixes vector-im/element-web#23695.
=> Fix pagination token tracking for mixed room timelines

src/@types/PushRules.ts, src/client.ts, src/crypto/DeviceList.ts, src/crypto/OlmDevice.ts, src/crypto/algorithms/olm.ts, src/crypto/backup.ts, src/crypto/index.ts, src/crypto/olmlib.ts, src/filter-component.ts, src/interactive-auth.ts, src/models/event-timeline-set.ts, src/models/room.ts, src/models/user.ts, src/pushprocessor.ts, src/realtime-callbacks.ts, src/rendezvous/MSC3906Rendezvous.ts, src/store/indexeddb-local-backend.ts, src/sync-accumulator.ts, src/sync.ts, src/utils.ts, src/webrtc/call.ts, src/webrtc/callEventHandler.ts, src/webrtc/callFeed.ts
Ignoring test coverage gate in favour of improving other Sonar stats
---
=> Make SonarCloud happier

README.md, spec/unit/crypto/algorithms/megolm.spec.js, src/crypto/algorithms/megolm.ts, src/crypto/index.ts
Factor out `encryptAndSendToDevices` from `megolm.ts`'s `encryptAndSendKeysToDevices()` so it can be used for sending other encrypted payloads (e.g. VoIP signalling).
This PR contains cherry picked commits from https://github.com/matrix-org/matrix-js-sdk/pull/1987 and based it off of the develop branch instead.
---
* Introduce an encryptAndSendToDevices method ([\#2002](https://github.com/matrix-org/matrix-js-sdk/pull/2002)). Contributed by @robertlong.
=> Introduce an encryptAndSendToDevices method

package.json
patch-package is used as a postinstall hook, but since it was in `devDependencies`, upstream packages would not install it. Moving it to `dependencies` isn't ideal since it's not needed at runtime, but the patch-package approach is only a temporary workaround for https://github.com/matrix-org/matrix-events-sdk/pull/16#pullrequestreview-1166721652 anyways.
Notes: none
element-web notes: none
---
=> Move patch-package out of dev dependencies

spec/unit/webrtc/mediaHandler.spec.ts, src/webrtc/mediaHandler.ts
autoGainControl, echoCancellation, and noiseSuppression are audio
processing options that are usually enabled by default on WebRTC input
tracks.
This PR adds the possibility to enable/disable them, as they can be
undesirable in some cases (audiophile use cases). For example, one might
want to stream electronic dance music, which is basically noise, so it
should not be suppressed in that specific case.
Note that these are not exact settings, they are set as "ideal" in order
not to break anything on devices where those constraints are not
implemented.
Related to matrix-org/matrix-react-sdk#8759
Type: task
---
* webrtc: add advanced audio settings ([\#2434](https://github.com/matrix-org/matrix-js-sdk/pull/2434)). Contributed by @MrAnno.
=> webrtc: add advanced audio settings

spec/test-utils/test-utils.ts, spec/test-utils/thread.ts, spec/unit/models/thread.spec.ts, src/models/thread.ts
Related to https://github.com/vector-im/element-web/issues/23721 (potential fix)
Related to https://github.com/vector-im/element-web/issues/23683 (potential fix)
---
* Fixes unwanted highlight notifications with encrypted threads ([\#2862](https://github.com/matrix-org/matrix-js-sdk/pull/2862)).
=> Fixes unwanted highlight notifications with encrypted threads

spec/unit/crypto.spec.ts, src/client.ts, src/crypto/OutgoingRoomKeyRequestManager.ts, src/crypto/index.ts
This isn't really needed, and its semantics are poorly defined. (Contrary to the comment, it dos *not* set any background processes running).
---
=> Remove `Crypto.start()`

src/pushprocessor.ts
Fixes https://github.com/vector-im/element-web/issues/23691
---
* Use an underride rule for Element Call notifications ([\#2873](https://github.com/matrix-org/matrix-js-sdk/pull/2873)). Fixes vector-im/element-web#23691.
=> Use an underride rule for Element Call notifications

src/@types/search.ts, src/client.ts
---
* Add way to abort search requests ([\#2877](https://github.com/matrix-org/matrix-js-sdk/pull/2877)).
=> Add way to abort search requests

spec/unit/read-receipt.spec.ts, src/client.ts
Related to https://github.com/vector-im/element-web/issues/23751
---
* Add ability to send unthreaded receipt ([\#2878](https://github.com/matrix-org/matrix-js-sdk/pull/2878)).
=> Add ability to send unthreaded receipt

src/client.ts
This PR will resolve below defect
Step to repro the defect
1-Go to register
2-Add phone number when register
3-enter correct OTP code and submit
4-server will return error because we are sending POST data via url params.
---
* fix registration add phone number not working ([\#2876](https://github.com/matrix-org/matrix-js-sdk/pull/2876)). Contributed by @bagvand.
=> fix registration add phone number not working

src/webrtc/call.ts
This is a change in how the state machine works: technically it's a breaking change, although likely not worth a specific major release given the level of breakage. Calls will now now go back into the connecting state if the media connection is lost (they'll try to re-establish the connection).
---
* Make calls go back to 'connecting' state when media lost ([\#2880](https://github.com/matrix-org/matrix-js-sdk/pull/2880)).
=> Make calls go back to 'connecting' state when media lost

spec/unit/read-receipt.spec.ts, spec/unit/room.spec.ts, spec/unit/sync-accumulator.spec.ts, src/@types/read_receipts.ts, src/client.ts, src/models/read-receipt.ts, src/models/room.ts, src/sync-accumulator.ts
Following MSC3771, read receipts are not unique per room per user id.
It is now possible for a single user id to have multiple read receipts across threads and the main room timeline.
The sync accumulator was not taking this into consideration and was always persisting the last read receipt it had received
---
* Read receipt accumulation for threads ([\#2881](https://github.com/matrix-org/matrix-js-sdk/pull/2881)).
=> Read receipt accumulation for threads

src/crypto/OlmDevice.ts, src/crypto/algorithms/megolm.ts
Attempt to make the way we log megolm session ids more consistent.
---
* Improve logging of e2ee messages ([\#2884](https://github.com/matrix-org/matrix-js-sdk/pull/2884)).
=> Improve logging of e2ee messages

src/crypto/OlmDevice.ts, src/crypto/algorithms/megolm.ts
I strongly suspect we are logging "secure channel corruption" errors when no
such thing happened, bit I can't quite figure it out yet. Add a bit more
logging to try to track them down.
---
* Improve logging on Olm session errors ([\#2885](https://github.com/matrix-org/matrix-js-sdk/pull/2885)).
=> Improve logging on Olm session errors

src/crypto/index.ts
A followup to #2884. In particular, it is not always the case that the
`sender_key` in a `m.room_key_withheld` message is the sender of that message.
---
* Further improvements to e2ee logging ([\#2900](https://github.com/matrix-org/matrix-js-sdk/pull/2900)).
=> Further improvements to e2ee logging

src/models/event.ts, src/scheduler.ts
---
* Deprecate a function containing a typo ([\#2904](https://github.com/matrix-org/matrix-js-sdk/pull/2904)). Contributed by @poljar.
=> Deprecate a function containing a typo

spec/integ/megolm-integ.spec.ts, spec/test-utils/test-utils.ts, src/crypto/index.ts, src/sync.ts
Fixes https://github.com/vector-im/element-web/issues/23819.
---
* Process `m.room.encryption` events before emitting `RoomMember` events ([\#2910](https://github.com/matrix-org/matrix-js-sdk/pull/2910)). Fixes vector-im/element-web#23819.
=> Process `m.room.encryption` events before emitting `RoomMember` events

README.md
**This probably needs a team-wide conversation.**
Part of https://github.com/vector-im/element-web/issues/22346
---
* Define a spec support policy for the js-sdk ([\#2882](https://github.com/matrix-org/matrix-js-sdk/pull/2882)).
=> Define a spec support policy for the js-sdk

spec/integ/megolm-integ.spec.ts, spec/test-utils/test-utils.ts, src/crypto/index.ts, src/sync.ts
Reverts matrix-org/matrix-js-sdk#2910 to unbreak element-web develop: https://github.com/matrix-org/matrix-react-sdk/actions/runs/3548472721
---
=> Revert "Process `m.room.encryption` events before emitting `RoomMember` events"

spec/test-utils/webrtc.ts, spec/unit/webrtc/call.spec.ts, spec/unit/webrtc/groupCall.spec.ts, spec/unit/webrtc/groupCallEventHandler.spec.ts, src/client.ts, src/utils.ts, src/webrtc/call.ts, src/webrtc/callEventHandler.ts, src/webrtc/callFeed.ts, src/webrtc/groupCall.ts, src/webrtc/groupCallEventHandler.ts
This refactoring brings a number of improvements to `GroupCall`, which I've unfortunately had to combine into a single commit due to coupling:
- Moves the expiration timestamp field on call membership state to be per-device
- Makes the participants of a group call visible without having to enter the call yourself
- Enables users to join group calls from multiple devices
- Identifies active speakers by their call feed, rather than just their user ID
- Plays nicely with clients that can be in multiple calls in a room at once
- Fixes a memory leak caused by the call retry loop never stopping
- Changes `GroupCall` to update its state synchronously, and write back to room state asynchronously
- This was already sort of halfway being done, but now we'd be committing to it
- Generally improves …
=> Refactor GroupCall participant management

spec/integ/matrix-client-methods.spec.ts, src/client.ts
This PR is required by https://github.com/matrix-org/matrix-react-sdk/pull/9596.
Notes: Enable multiple users' power levels to be set at once
Signed-off-by: Marco Bartelt marco.bartelt.ext@bwi.de
---
* Enable multiple users' power levels to be set at once ([\#2892](https://github.com/matrix-org/matrix-js-sdk/pull/2892)). Contributed by @GoodGuyMarco.
=> add-privileged-users-in-room

spec/unit/notifications.spec.ts, spec/unit/read-receipt.spec.ts, src/client.ts, src/models/read-receipt.ts, src/models/room.ts, src/models/thread.ts
Fixes https://github.com/vector-im/element-web/issues/23827
Fixes https://github.com/vector-im/element-web/issues/23754
Fixes https://github.com/vector-im/element-web/issues/23847
This is still missing a couple of tests to ensure synthetic receipts are added when paginating through a thread timeline set. But otherwise should be ready for review
---
* Fix synthesizeReceipt ([\#2916](https://github.com/matrix-org/matrix-js-sdk/pull/2916)). Fixes vector-im/element-web#23827 vector-im/element-web#23754 and vector-im/element-web#23847.
=> Fix synthesizeReceipt

spec/integ/matrix-client-crypto.spec.ts, src/client.ts
---
* Add method to get outgoing room key requests for a given event ([\#2930](https://github.com/matrix-org/matrix-js-sdk/pull/2930)). Contributed by @duxovni.
=> Add method to get outgoing room key requests for a given event

spec/test-utils/webrtc.ts, spec/unit/webrtc/groupCall.spec.ts, src/webrtc/groupCall.ts
If the client uses a widget to join group calls, like Element Web does, then the local device could be joined to the call without GroupCall knowing. This adds a field to GroupCall that allows the client to tell GroupCall when it's using another session to join the call.
---
* Make GroupCall work better with widgets ([\#2935](https://github.com/matrix-org/matrix-js-sdk/pull/2935)).
=> Make GroupCall work better with widgets

spec/test-utils/webrtc.ts, spec/unit/webrtc/groupCall.spec.ts, src/webrtc/groupCall.ts
This backports https://github.com/matrix-org/matrix-js-sdk/pull/2935 to staging as it is a dependency of https://github.com/matrix-org/matrix-react-sdk/pull/9692 which needs fixing in the RC.
---
* Backport "Make GroupCall work better with widgets" to staging ([\#2936](https://github.com/matrix-org/matrix-js-sdk/pull/2936)).
=> Backport "Make GroupCall work better with widgets" to staging

spec/unit/models/thread.spec.ts, src/models/room.ts, src/models/thread.ts
Type: Enhancement
Fixes: https://github.com/vector-im/element-web/issues/23642
---
* Include pending events in thread summary and count again ([\#2922](https://github.com/matrix-org/matrix-js-sdk/pull/2922)). Fixes vector-im/element-web#23642. Contributed by @justjanne.
=> Include pending events in thread summary and count again

spec/unit/notifications.spec.ts, src/client.ts, src/models/room.ts, src/models/thread.ts
Fixes https://github.com/vector-im/element-web/issues/23885
This was originally as an attempt to be more defensive and prevent highlight notification to appear for already read events! 
The synthetic read receipts should help
This clears the release blocker and will monitor the tracker
It also fixes an issue where `public get timeline(): MatrixEvent[]` would always return `undefined` because the `public abstract timeline: MatrixEvent[]` declaration in the parent was overriding it.
It created a lot of inconsistencies when trying to determine whether a message has been previously read or not!
---
* Fix highlight notifications increasing when total notification is zero ([\#2937](https://github.com/matrix-org/matrix-js-sdk/pull/2937)). Fixes …
=> Fix highlight notifications increasing when total notification is zero

spec/integ/matrix-client-event-timeline.spec.ts, src/models/room.ts
Type: Defect
Fixes: https://github.com/vector-im/element-web/issues/23876
---
* Move updated threads to the end of the thread list ([\#2923](https://github.com/matrix-org/matrix-js-sdk/pull/2923)). Fixes vector-im/element-web#23876. Contributed by @justjanne.
=> Move updated threads to the end of the thread list

spec/unit/crypto/verification/setDeviceVerification.spec.ts, src/crypto/index.ts
If you don't set up key backup and verify one of your other devices, you won't receive keys for the messages of already viewed rooms. This PR triggers key requests after verifying an own device.
See the linked issue for a detailed description on how to reproduce it.
Fixes https://github.com/vector-im/element-web/issues/23333
Before
https://user-images.githubusercontent.com/6216686/204786166-4bce51c9-81a8-4b22-8d8a-a0417d002abe.mp4
After
https://user-images.githubusercontent.com/6216686/204786195-32c7692a-6562-446b-b6e5-fc2a9ab50b8b.mp4
---
* Redo key sharing after own device verification ([\#2921](https://github.com/matrix-org/matrix-js-sdk/pull/2921)). Fixes vector-im/element-web#23333.
=> Redo key sharing after own device verification

spec/integ/sliding-sync-sdk.spec.ts, src/sliding-sync-sdk.ts, src/sliding-sync.ts
Flag timeline events as `fromCache` when `initial: true` rooms are received. This stops notifications appearing inappropriately when you scroll the room list or spider the room list, as it causes `liveEvent=false`.
---
* bugfix: sliding sync initial room timelines shouldn't notify ([\#2933](https://github.com/matrix-org/matrix-js-sdk/pull/2933)).
=> bugfix: sliding sync initial room timelines shouldn't notify

spec/test-utils/webrtc.ts, spec/unit/webrtc/call.spec.ts, spec/unit/webrtc/callFeed.spec.ts, spec/unit/webrtc/groupCall.spec.ts, src/webrtc/call.ts, src/webrtc/callFeed.ts, src/webrtc/groupCall.ts
=> Don't expose `calls` on `GroupCall`

package.json, spec/unit/crypto.spec.ts, spec/unit/crypto/algorithms/megolm.spec.ts, src/@types/event.ts, src/ToDeviceMessageQueue.ts, src/crypto/OutgoingRoomKeyRequestManager.ts, src/crypto/SecretStorage.ts, src/crypto/algorithms/megolm.ts, src/crypto/index.ts, src/webrtc/call.ts, yarn.lock
To make it easier to track down where to-device messages are getting lost,
add a custom property to each one, and log its value. Synapse will also log
this property.
We will emit log lines such as:
```
Enqueuing batch of to-device messages. type=m.room.encrypted txnid=m1670257675639.2 [ "@alice:localhost:8482/QSEDQLTFJA (msgid d0bd05e5-1fa3-410c-b1b5-c541ec99aa1b)",  "@bob:localhost:8482/SJGHSKJDH (msgid 0852cdaa-1546-4af7-87fb-07f3350be64f)" ]
```
and
```
received to-device m.room.encrypted from: @testuser82:localhost:8482 id: e354f925-a583-4b71-94d8-7864589ded29
```
part of https://github.com/vector-im/element-meta/issues/558
See also https://github.com/matrix-org/synapse/pull/14598 for the server side bits.
---
* Add a message ID on each …
=> Add a message ID on each to-device message

spec/integ/matrix-client-syncing.spec.ts, src/models/room.ts
Hopefully helps with https://github.com/vector-im/element-web/issues/23921
All read receipts are sent down during initial sync, however the code would previously throw the read receipts to unknown threads down the drain
This pull requests changes that and caches all those receipts, upon a thread discovery, the cache is checked and those receipts are applied
This should alleviate highlight notifications appearing for threads you've already read
> **Warning**
> My gut feeling tells me we might need to force an initial sync so that all read receipts are downloaded once again as we've already thrown quite a few away unfortunately
---
* Cache read receipts for unknown threads ([\#2953](https://github.com/matrix-org/matrix-js-sdk/pull/2953)).
=> Cache read receipts for unknown threads

examples/browser/README.md, examples/browser/browserTest.js
This seems to have been broken for ages
---
=> Fix `examples/browser`

spec/unit/notifications.spec.ts, src/client.ts
Hugely helps with https://github.com/vector-im/element-web/issues/23921
This should fully go away with things like MSC3874.
Threaded events are sent down `/sync` and are considered threaded events by the code that fixes notifications for encrypted rooms. However, if the thread root has not been discovered then the thread model does not exist yet and the optional chaining operator would make the `hasUserReadEvent` variable `undefined` who then got casted to a falsy value... 
---
* Do not calculate highlight notifs for threads unknown to the room ([\#2957](https://github.com/matrix-org/matrix-js-sdk/pull/2957)).
=> Do not calculate highlight notifs for threads unknown to the room

src/client.ts
=> Apply prettier to the client.ts file

spec/unit/crypto/algorithms/megolm.spec.ts, src/crypto/algorithms/megolm.ts
This is another go at trying to get https://github.com/matrix-org/matrix-js-sdk/pull/2908 merged. The original PR has been now split out since it contained two semi-related changes.
---
* Make sure that MegolmEncryption.setupPromise always resolves  ([\#2960](https://github.com/matrix-org/matrix-js-sdk/pull/2960)). Contributed by @poljar.
=> Make sure that MegolmEncryption.setupPromise always resolves 

src/crypto/algorithms/megolm.ts
The second part of #2908. 
This closes: https://github.com/vector-im/element-web/issues/23792.
---
* Don't swallow errors coming from the shareSession call ([\#2962](https://github.com/matrix-org/matrix-js-sdk/pull/2962)). Fixes vector-im/element-web#23792. Contributed by @poljar.
=> Don't swallow errors coming from the shareSession call

src/models/room.ts, src/models/thread.ts
Fixes https://github.com/vector-im/element-web/issues/23951
---
* Fix infinite loop when restoring cached read receipts ([\#2963](https://github.com/matrix-org/matrix-js-sdk/pull/2963)). Fixes vector-im/element-web#23951.
=> Fix infinite loop when restoring cached read receipts

.prettierignore
The example directories include symlinks to the generated matrix.js, which we
should not prettify.
---
=> Exclude generated files from prettier

src/models/thread.ts
Type: Defect
Fixes: https://github.com/vector-im/element-web/issues/23919
---
* Fix #23919: Root message for new thread loaded from network ([\#2965](https://github.com/matrix-org/matrix-js-sdk/pull/2965)). Fixes vector-im/element-web#23919. Contributed by @justjanne.
=> Fix #23919: Root message for new thread loaded from network

src/@types/event.ts, src/client.ts, src/webrtc/call.ts, src/webrtc/callEventTypes.ts, src/webrtc/groupCall.ts
Requires https://github.com/matrix-org/waterfall/pull/70
---
=> Change event shape to match MSC3898

spec/integ/matrix-client-event-timeline.spec.ts, spec/test-utils/thread.ts, spec/unit/room.spec.ts, src/models/room.ts, src/models/thread.ts
Type: Defect
Fixes: https://github.com/vector-im/element-web/issues/23916
Fixes: https://github.com/vector-im/element-web/issues/23942
Requires: https://github.com/matrix-org/matrix-js-sdk/pull/2965
Prevent confusion between synthesized lastEvent and the same event in the actual timeline
---
* Fix #23916: Prevent edits of the last message in a thread getting lost ([\#2951](https://github.com/matrix-org/matrix-js-sdk/pull/2951)). Fixes vector-im/element-web#23916 and vector-im/element-web#23942. Contributed by @justjanne.
=> Fix #23916: Prevent edits of the last message in a thread getting lost

spec/integ/megolm-integ.spec.ts, spec/unit/crypto/cross-signing.spec.ts, spec/unit/room.spec.ts, src/@types/crypto.ts, src/client.ts, src/common-crypto/CryptoBackend.ts, src/common-crypto/README.md, src/crypto/algorithms/megolm.ts, src/crypto/algorithms/olm.ts, src/crypto/index.ts, src/models/event.ts
Part of https://github.com/vector-im/element-web/issues/21972. Eventually I want to replace the whole of the current `Crypto` implementation with an alternative implementation, but in order to get from here to there, I'm factoring out a common interface which will be implemented by both implementations.
I'm also determined to fix the problem where the innards of the crypto implementation are exposed to applications via the `MatrixClient.crypto` property.
It's not (yet) entirely clear what shape this interface should be, so I'm going with a minimal approach and adding things as we know we need them. This means that we need to keep the old `client.crypto` property around as well as a new `client.cryptoBackend` property. Eventually `client.crypto` will go away, but that will be a breaking …
=> Begin factoring out a CryptoBackend interface

spec/unit/matrix-client.spec.ts, spec/unit/stores/memory.spec.ts, src/client.ts, src/feature.ts, src/store/memory.ts
MSC: https://github.com/ShadowJonathan/matrix-doc/blob/account-data-delete/proposals/3391-account-data-delete.md
---
* Support MSC3391: Account data deletion ([\#2967](https://github.com/matrix-org/matrix-js-sdk/pull/2967)). Contributed by @kerryarchibald.
=> Support MSC3391: Account data deletion

package.json, spec/integ/rust-crypto.spec.ts, src/client.ts, src/rust-crypto/constants.ts, src/rust-crypto/index.ts, src/rust-crypto/rust-crypto.ts, yarn.lock
This PR introduces `MatrixClient.initRustCrypto`, which is similar to `initCrypto`, except that it will use the Rust crypto SDK instead of the old libolm-based implementation.
This is very much *not* something you want to use in production code right now, because the integration with the rust sdk is extremely skeletal and almost everything crypto-related will raise an exception rather than doing anything useful.
It is, however, enough to demonstrate the loading of the wasmified rust sdk in element web, and a react sdk with light modifications can successfully log in and out.
Element-web notes: none
---
* Introduce a mechanism for using the rust-crypto-sdk …
=> Introduce a mechanism for using the rust-crypto-sdk

spec/unit/ToDeviceMessageQueue.spec.ts, src/ToDeviceMessageQueue.ts
Fixes https://github.com/matrix-org/element-web-rageshakes/issues/17170 and https://github.com/matrix-org/element-web-rageshakes/issues/17169
If there is any server connectivity issue whilst to-device message queue is processing batches of messages, the queue will be stopped and only resumed once further to-device messages are enqueued. This can lead to UISIs if the sender does not send any new keys immediately after connection is restored.
The solution is to observe client sync status and automatically resume the queue via `sendQueue` when we first recieve a `SyncState.Syncing`. If the queue is already empty, `sendQueue` will exit gracefully.
---
* Resume to-device message queue after resumed sync …
=> Resume to-device message queue after resumed sync

src/webrtc/call.ts
We didn't close streams in group calls (presumably from back when we used the same stream for all calls rather than cloning?) but this left stray screenshare streams in the mediahandler when a participant left whilst we were screensharing.
Fixes https://github.com/vector-im/element-call/issues/742
---
* Close all streams when a call ends ([\#2992](https://github.com/matrix-org/matrix-js-sdk/pull/2992)). Fixes vector-im/element-call#742.
=> Close all streams when a call ends

spec/test-utils/webrtc.ts, spec/unit/webrtc/groupCall.spec.ts, src/webrtc/groupCall.ts
This avoids us having to do ugly things when using an SFU
---
=> Don't use `RoomMember` as a `calls` a key on `GroupCall`

spec/unit/matrix-client.spec.ts, src/@types/event.ts, src/@types/requests.ts, src/client.ts, src/feature.ts
SDK support for [MSC3912](https://github.com/matrix-org/matrix-spec-proposals/pull/3912)
Should be reviewed commitwise, because it contains a heavy refactoring of the client spec.
---
* Implement MSC3912: Relation-based redactions ([\#2954](https://github.com/matrix-org/matrix-js-sdk/pull/2954)).
=> Implement MSC3912: Relation-based redactions

spec/unit/rust-crypto.spec.ts, src/@types/crypto.ts, src/client.ts, src/common-crypto/CryptoBackend.ts, src/crypto/OlmDevice.ts, src/crypto/algorithms/base.ts, src/crypto/algorithms/megolm.ts, src/crypto/backup.ts, src/crypto/index.ts, src/rust-crypto/rust-crypto.ts
Element-web calls `exportRoomKeys` on logout, so we need a stub implementation to get it EW working with the rust crypto sdk.
---
=> Add `exportRoomKeys` to `CryptoBackend`

spec/integ/sliding-sync.spec.ts, src/sliding-sync.ts
Should fix an issue where no `unsubscribe_rooms` are sent when switching rooms. 
This happens because we're deleting the room from the `confirmedRoomSubscription` list when switching between unencrypted rooms and the `unsubscribe_rooms` list can't be calculated correctly, resulting in an ever growing subscriptions list on the server side.
---
* sliding sync: Fix issue where no unsubs are sent when switching rooms ([\#2991](https://github.com/matrix-org/matrix-js-sdk/pull/2991)). Contributed by @S7evinK.
=> sliding sync: Fix issue where no unsubs are sent when switching rooms

src/client.ts
https://spec.matrix.org/v1.5/client-server-api/#get_matrixclientv3accountwhoami
---
* Add `device_id` to `/account/whoami` types ([\#3005](https://github.com/matrix-org/matrix-js-sdk/pull/3005)).
=> Add `device_id` to `/account/whoami` types

spec/TestClient.ts, spec/integ/megolm-integ.spec.ts, src/crypto/index.ts, src/models/room-state.ts, src/models/room.ts
`Room` and `Crypto` currently have some tight coupling in the form of a call to `trackRoomDevices` when out-of-band members are loaded. We can improve this by instead having Crypto listen out for a `RoomSateEvent.Update` notification.
---
=> Break coupling between `Room` and `Crypto.trackRoomDevices`

src/@types/event.ts
=> Update comment for `m.key.verification.ready` event type definition

spec/unit/autodiscovery.spec.ts, src/autodiscovery.ts, src/http-api/prefix.ts
It's been deprecated for over a year at this point - everyone should be able to support v2.
**Requires https://github.com/matrix-org/matrix-react-sdk/pull/9818**
Required by https://github.com/vector-im/element-web/pull/24086
---
* Remove usage of v1 Identity Server API ([\#3003](https://github.com/matrix-org/matrix-js-sdk/pull/3003)).
=> Remove usage of v1 Identity Server API

.github/workflows/release.yml
This is completely untested, but follows the example in https://github.com/vector-im/element-call/blob/main/.github/workflows/netlify-pr.yaml#L49-L51
Related to https://github.com/matrix-org/internal-config/issues/1388
---
* In release.yml use an env section to get ref_name ([\#3017](https://github.com/matrix-org/matrix-js-sdk/pull/3017)). Contributed by @andybalaam.
=> In release.yml use an env section to get ref_name

spec/integ/matrix-client-methods.spec.ts, spec/integ/sliding-sync-sdk.spec.ts, src/client.ts, src/embedded.ts, src/sliding-sync-sdk.ts, src/sync.ts
There are a couple of callback interfaces which are currently stuffed into `IStoredClientOpts` to make it easier to pass them into the `SyncApi` constructor. This isn't really a sensible place for them, because they aren't application options in the same way as the rest of `IStoredClientOpts` are, nor are they 'stored' in indexedDB as the other options are.
I want to add `cryptoBackend` to the things passed into `SyncApi`, so rather than perpetuating the mess, define a new interface `SyncApiOptions` to be passed in separately.
(sorry, this isn't quite passing the code coverage gate. But it almost does, and it's super-annoying to add the tests to make it do so.)
---
=> Factor `SyncApi` options out of `IStoredClientOptions`

spec/unit/crypto.spec.ts, src/crypto/index.ts
Currently, when processing a redacted event, it tries to decrypt the `redacted_because`  (https://github.com/matrix-org/matrix-js-sdk/pull/1589).  However, since this often is not encrypted, the decryption will fail, and this failure will bubble up to the parent event.  This patch simply uses the plain `redacted_because` if it is unable to decrypt it.
fixes https://github.com/vector-im/element-web/issues/24084 and https://github.com/matrix-org/matrix-js-sdk/issues/1648
---
* Avoid triggering decryption errors when decrypting redacted events ([\#3004](https://github.com/matrix-org/matrix-js-sdk/pull/3004)). Fixes vector-im/element-web#24084.
=> Avoid triggering decryption errors when decrypting redacted events

spec/unit/rust-crypto.spec.ts, src/client.ts, src/rust-crypto/index.ts, src/rust-crypto/rust-crypto.ts
The rust matrix-sdk-crypto has an `outgoingRequests()` method which we need to poll, and make the requested requests.
---
=> Handle outgoing requests from rust crypto SDK

src/rust-crypto/rust-crypto.ts
Apparently `??=` was only added to javascript in ES12, and our eleweb build
doesn't support it.
Fixes breakage introduced in https://github.com/matrix-org/matrix-js-sdk/pull/3019.
---
=> Avoid logical assignment operator

src/models/room.ts
... to reduce the number of things referring to the now deprecated `client.crypto`.
---
=> Indirect event decryption attempts via Client

spec/unit/rust-crypto.spec.ts, src/common-crypto/CryptoBackend.ts, src/crypto/index.ts, src/event-mapper.ts, src/rust-crypto/rust-crypto.ts, src/sliding-sync-sdk.ts, src/sync.ts
This introduces a new method in `SyncCryptoCallbacks`. We can't just piggyback onto `ClientEvent.ToDeviceEvent`, because that is only emitted for successfully decrypted to-device events.
We also don't really want to hook into the EventMapper mechanism (as the current `Crypto` implementation does), because the rust crypto api expects the raw to-device events, rather than those that have been mangled into MatrixEvents.
---
=> Pass to-device messages into rust crypto-sdk

spec/unit/rust-crypto.spec.ts, src/rust-crypto/index.ts, src/rust-crypto/rust-crypto.ts
Fixes to #3019
It turns out that MatrixClient uses a `FetchHttpApi` instance with `opts.onlyData = true`, so it was returning the json-parsed response rather than the raw response. Change the way we call `authedRequest` so that we get the raw body back.
---
=> Fix outgoing messages for rust-crypto

spec/unit/models/event.spec.ts, src/models/event.ts
Not everything is a `DecryptionError`, and there's no real reason that we should only do retries for `DecryptionError`s.
---
=> Make error handling in decryptionLoop more generic

spec/integ/matrix-client-syncing.spec.ts, src/@types/read_receipts.ts, src/models/room.ts, src/models/thread.ts
First step for https://github.com/vector-im/element-web/issues/24164
---
* Fix threaded cache receipt when event holds multiple receipts ([\#3026](https://github.com/matrix-org/matrix-js-sdk/pull/3026)).
=> Fix threaded cache receipt when event holds multiple receipts

src/@types/event.ts
For: https://github.com/matrix-org/matrix-react-sdk/pull/9870
---
* Make poll start event type available (PSG-962) ([\#3034](https://github.com/matrix-org/matrix-js-sdk/pull/3034)).
=> Make poll start event type available (PSG-962)

spec/unit/webrtc/groupCall.spec.ts, spec/unit/webrtc/mediaHandler.spec.ts, src/webrtc/call.ts, src/webrtc/groupCall.ts, src/webrtc/mediaHandler.ts
Fixes https://github.com/vector-im/element-call/issues/209
---
* Remove video track when muting video ([\#3028](https://github.com/matrix-org/matrix-js-sdk/pull/3028)). Fixes vector-im/element-call#209.
=> Remove video track when muting video

package.json, yarn.lock
'qs' ([package](https://www.npmjs.com/package/qs), [source](https://github.com/ljharb/qs)) appears to be unused since 34c5598 (PR #2719), and can be safely removed.
It's worth noting that 'qs' has the deepest dependency graph of all (non-development) dependencies.
```
$ npm ls --depth=32 --omit=dev
...
├─┬ qs@6.11.0
│ └─┬ side-channel@1.0.4
│   ├─┬ call-bind@1.0.2
│   │ ├── function-bind@1.1.1
│   │ └── get-intrinsic@1.1.3 deduped
│   ├─┬ get-intrinsic@1.1.3
│   │ ├── function-bind@1.1.1 deduped
│   │ ├── has-symbols@1.0.3
│   │ └─┬ has@1.0.3
│   │   └── function-bind@1.1.1 deduped
│   └── object-inspect@1.12.2
...
```
No other dependencies have more than one level of nesting.
#244 is relevant here (maybe?), though this doesn't go particularly far. A full dev install still weighs 372M on …
=> Remove 'qs' dependency

spec/unit/matrix-client.spec.ts
This is prep for an implementation of [MSC3946](https://github.com/matrix-org/matrix-spec-proposals/pull/3946)
---
=> Tests for getVisibleRooms

spec/unit/room.spec.ts, src/client.ts, src/models/room.ts
This is prep for an implementation of [MSC3946](https://github.com/matrix-org/matrix-spec-proposals/pull/3946)
---
=> Factor out a (public) function to find a room's predecessor

spec/integ/matrix-client-methods.spec.ts, src/client.ts
With extensible events v2, affected events are now gated by a room version, so we don't need this code anymore. 
The proposal has generally moved away from mixing m.room.message with extensible fields as well.
---
* Remove extensible events v1 field population on legacy events ([\#3040](https://github.com/matrix-org/matrix-js-sdk/pull/3040)).
=> Remove extensible events v1 field population on legacy events

package.json
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/3030
---
=> Avoid use of mkdirp

src/event-mapper.ts
MSC3925 suggests that the server should no longer replace the body of edited events, so let's get ready for that. https://github.com/matrix-org/synapse/pull/14811 has already laid the groundwork, by bundling the whole of the edited event.
See also https://github.com/matrix-org/matrix-react-sdk/pull/9886 for some tests.
---
* Handle edits which are bundled with an event, per MSC3925 ([\#3045](https://github.com/matrix-org/matrix-js-sdk/pull/3045)).
=> Handle edits which are bundled with an event, per MSC3925

spec/unit/crypto/algorithms/megolm.spec.ts, src/crypto/algorithms/megolm.ts
This is a series of changes to try to improve the quality of the logging within the crypto subsystem; we try to reduce the noise, but in its stead add a little more logging to try and understand what is going on with https://github.com/vector-im/element-web/issues/23269.
Suggest reviewing commit-by-commit.
---
=> Improve logging in legacy megolm code

src/client.ts
Fixes https://github.com/vector-im/element-web/issues/24216
This is a quick fix so we can unblock the release. I'd like to investigate whether we can (a) report errors in this code, rather than swallowing them; (b) test that app load and login work with an indexeddb impl that behaves this way.
---
* Fix failure to start in firefox private browser ([\#3058](https://github.com/matrix-org/matrix-js-sdk/pull/3058)). Fixes vector-im/element-web#24216.
=> Fix failure to start in firefox private browser

spec/integ/megolm-integ.spec.ts
The megolm tests were making a few assumptions which they really shouldn't; in particular:
* They were creating mock events with event_ids not starting `$`, and lacking `sender`, `origin_server_ts` and `unsigned` properties
* They were not including the (now) required `keys.ed25519` property inside the ciphertext of an olm message.
These work ok currently, but they aren't really correct, and they cause problems when testing the new rust implementation.
---
=> Improvements to megolm integration tests

spec/integ/megolm-integ.spec.ts, src/crypto/algorithms/megolm.ts
Fixes https://github.com/vector-im/element-web/issues/23803
Do not store `m.room_key.withheld` events with a code of `m.unavailable` in the crypto store: doing so causes a spurious "key withheld" message, and may overwrite more useful messages.
This also includes a change to ensure we update the error message when we receive an `m.room_key.withheld` - mostly driven by the need to test the change, but seems like an improvement anyway.
---
* Fix spurious "Decryption key withheld" messages ([\#3061](https://github.com/matrix-org/matrix-js-sdk/pull/3061)). Fixes vector-im/element-web#23803.
=> Fix spurious "Decryption key withheld" messages

spec/unit/content-helpers.spec.ts, spec/unit/extensible_events_v1/ExtensibleEvent.spec.ts, spec/unit/extensible_events_v1/MessageEvent.spec.ts, spec/unit/extensible_events_v1/PollEndEvent.spec.ts, spec/unit/extensible_events_v1/PollResponseEvent.spec.ts, spec/unit/extensible_events_v1/PollStartEvent.spec.ts, spec/unit/extensible_events_v1/utilities.spec.ts, spec/unit/location.spec.ts, spec/unit/models/beacon.spec.ts, spec/unit/relations.spec.ts, src/@types/beacon.ts, src/@types/extensible_events.ts, src/@types/location.ts, src/@types/polls.ts, src/@types/topic.ts, src/content-helpers.ts, src/extensible_events_v1/ExtensibleEvent.ts, src/extensible_events_v1/InvalidEventError.ts, src/extensible_events_v1/MessageEvent.ts, src/extensible_events_v1/PollEndEvent.ts, src/extensible_events_v1/PollResponseEvent.ts, src/extensible_events_v1/PollStartEvent.ts, src/extensible_events_v1/utilities.ts
These types are disappearing, so rescue them in the name of the react-sdk's feature set.
**Reviewer**: Please be aware that these are copy/pasted into the project, with alterations made to appease our linters.
---
=> Extract v1 extensible events polls types out of the events-sdk

spec/unit/crypto.spec.ts, src/client.ts, src/crypto/OlmDevice.ts, src/crypto/index.ts
Adds a log line whenever we save a session and also adds an event that's fired whenever we get a to-device event we can't decrypt (hopefully the comment explains all).
---
=> Add some debugging & a debug event for decryption

spec/unit/models/thread.spec.ts, src/models/room.ts, src/models/thread.ts
Type: Defect
Fixes: https://github.com/vector-im/element-web/issues/23952
---
* Correctly handle limited sync responses by resetting the thread timeline ([\#3056](https://github.com/matrix-org/matrix-js-sdk/pull/3056)). Fixes vector-im/element-web#23952. Contributed by @justjanne.
=> Correctly handle limited sync responses by resetting the thread timeline

spec/unit/rust-crypto.spec.ts, src/client.ts, src/common-crypto/CryptoBackend.ts, src/rust-crypto/rust-crypto.ts
These are all called by the react-sdk when showing an encrypted event:
* `getEventEncryptionInfo`
* `checkUserTrust`
* `checkDeviceTrust`
I don't particularly want to keep this API, but as a rapid means to an end while we figure out the shape of the Rust SDK's api (https://github.com/matrix-org/matrix-rust-sdk/issues/1366), let's stub them for now.
---
=> Element-R: stub implementations of some methods
