src/@types/partials.ts
src/models/room-state.ts
src/models/room.ts

Improve typing around join rules

---

src/models/event.ts

Fix replyInThread getter to match event m.in_reply_to structure

---

src/client.ts
src/models/event.ts
src/sync.ts

Fixes https://github.com/vector-im/element-web/issues/15393
Closes https://github.com/matrix-org/matrix-react-sdk/pull/6267
element-web notes: Don't notify for hidden events sent during calls
<hr>
For the reviewer: This is a change that has a big potential to break things - please review carefully
---
* Count notifications in encrypted rooms client-side ([\#1872](https://github.com/matrix-org/matrix-js-sdk/pull/1872)). Fixes vector-im/element-web#15393 and vector-im/element-web#15393. Contributed by [SimonBrandner](https://github.com/SimonBrandner).

Count notifications in encrypted rooms client-side

---

src/client.ts
src/models/event.ts
src/sync.ts

Reverts matrix-org/matrix-js-sdk#1872

Revert "Count notifications in encrypted rooms client-side"

---

src/crypto/index.ts

https://github.com/matrix-org/matrix-js-sdk/pull/1897 to release
---
* [Release] Exclude opt-in Element performance metrics from encryption ([\#1901](https://github.com/matrix-org/matrix-js-sdk/pull/1901)).

[Release] Exclude opt-in Element performance metrics from encryption

---

src/crypto/verification/SAS.ts

Type: enhancement 
For https://github.com/matrix-org/matrix-react-sdk/pull/6743
---
* Add `ISasEvent` ([\#1908](https://github.com/matrix-org/matrix-js-sdk/pull/1908)). Contributed by [SimonBrandner](https://github.com/SimonBrandner).

Add `ISasEvent`

---

src/models/room-member.ts

Types adjustment for TS migration

---

src/crypto/verification/Base.ts

For https://github.com/matrix-org/matrix-react-sdk/pull/6743
---
* Add `hasBeenCancelled` to `VerificationBase` ([\#1915](https://github.com/matrix-org/matrix-js-sdk/pull/1915)). Contributed by [SimonBrandner](https://github.com/SimonBrandner).

Add `hasBeenCancelled` to `VerificationBase`

---

spec/unit/crypto/algorithms/megolm.spec.js

https://github.com/matrix-org/matrix-js-sdk/pull/1916 to release branch
---

Tests for key sharing security fix

---

spec/unit/models/MSC3089Branch.spec.ts
spec/unit/models/MSC3089TreeSpace.spec.ts

Fixes https://github.com/vector-im/element-web/issues/18461
---

Add missing tests for MSC3089 implementation

---

spec/unit/models/MSC3089Branch.spec.ts
src/models/MSC3089Branch.ts

This isn't hooked up to versioning, yet, but will be eventually.
---
* Add file locking to MSC3089 branches ([\#1909](https://github.com/matrix-org/matrix-js-sdk/pull/1909)).

Add file locking to MSC3089 branches

---

src/autodiscovery.ts
src/client.ts
src/errors.ts
src/realtime-callbacks.ts

- Migrate realtime-callbacks to TypeScript
- Migrate errors to TypeScript
- Migrate AutoDiscovery to TypeScript
---

TypeScript migration for js-sdk

---

src/crypto/verification/QRCode.ts

For https://github.com/matrix-org/matrix-react-sdk/pull/6815
---
* Add `getBuffer()` to `QRCodeData` ([\#1927](https://github.com/matrix-org/matrix-js-sdk/pull/1927)). Contributed by [SimonBrandner](https://github.com/SimonBrandner).

Add `getBuffer()` to `QRCodeData`

---

src/models/event.ts
src/models/room.ts
src/models/thread.ts

Accidentally merged https://github.com/matrix-org/matrix-js-sdk/pull/1930 before fixing all the comments.
---

Fix improperly named enum

---

src/webrtc/mediaHandler.ts

Type: defect
Notes: none
<hr>
CC @robertlong 
---

Fix `getUserMediaStream()` not being able to handle streams of different track combinations

---

src/webrtc/mediaHandler.ts

Type: defect
Fixes https://github.com/vector-im/element-web/issues/19094
Notes: none
<hr>
We weren't correctly deleting streams which lead to a bunch of issues
---

Fix stream stopping and improve logging

---

src/models/room-state.ts
src/models/room.ts

---
* Add `getHistoryVisibility()` and `getGuestAccess()` ([\#1940](https://github.com/matrix-org/matrix-js-sdk/pull/1940)). Contributed by [SimonBrandner](https://github.com/SimonBrandner).

Add `getHistoryVisibility()` and `getGuestAccess()`

---

src/@types/threepids.ts

For https://github.com/matrix-org/matrix-react-sdk/pull/6843
---
* Add `bound` to `IThreepid` ([\#1941](https://github.com/matrix-org/matrix-js-sdk/pull/1941)). Contributed by [SimonBrandner](https://github.com/SimonBrandner).

Add `bound` to `IThreepid`

---

src/client.ts

Fixes https://github.com/vector-im/element-web/issues/19018
---

Switch to /kick API

---

src/client.ts
src/webrtc/groupCall.ts
src/webrtc/groupCallEventHandler.ts

GroupCall improvements

---

CONTRIBUTING.md

Fixes https://github.com/vector-im/element-web/issues/19136
---

Add tests requirements to CONTRIBUTING

---

src/models/thread.ts

For vector-im/element-web#18720
---

Add thread serialisation helper

---

src/webrtc/call.ts

Fix not returning new mic mute state 

---

src/webrtc/call.ts

---
* Allow answering calls without audio/video ([\#1950](https://github.com/matrix-org/matrix-js-sdk/pull/1950)). Contributed by @SimonBrandner.

Allow answering calls without audio/video

---

src/webrtc/call.ts

Fixes https://github.com/vector-im/element-web/issues/19173
Type: defect
Notes: none
---

Pass correct params to `upgradeCall()` to upgrade audio

---

src/client.ts

Type: task
For https://github.com/matrix-org/matrix-react-sdk/pull/6869
---

Changes for TS migration

---

src/webrtc/call.ts
src/webrtc/groupCallEventHandler.ts

De-duplication for group calls

---

src/models/thread.ts

Fixes vector-im/element-web#19225
---

Prepend events to thread when fetching the reply chain

---

src/room-hierarchy.ts

Tweak Room Hierarchy root visibility and add loading getter

---

src/client.ts
src/models/event.ts
src/models/room.ts

Fixes vector-im/element-web#19638
---

Copy relations to thread root in the thread timeline

---

src/models/thread.ts

For https://github.com/vector-im/element-web/issues/19669
---

Getter for last thread reply

---

src/timeline-window.ts

TimelineWindow fix load function signature

---

src/@types/PushRules.ts
src/client.ts
src/crypto/CrossSigning.ts
src/crypto/api.ts
src/crypto/index.ts

Iterate type definitions

---

src/@types/event.ts

Related to https://github.com/vector-im/element-web/issues/19806
---

Add KeyVerificationRequest msgType

---

src/models/thread.ts

Related to https://github.com/vector-im/element-web/issues/19809
---

Add a flag to track user participation in a thread

---

src/client.ts

Fixes https://github.com/vector-im/element-web/issues/19882
---

Fix backwards compatibility for redactEvent

---

src/models/room.ts

Fixes https://github.com/vector-im/element-web/issues/19876
---

Handle remote echo when creating a thread

---

src/index.ts
yarn.lock

These types are needed to describe function signatures that wrap matrix-sdk methods
---

Exporting missing types

---

src/interactive-auth.ts

Signed-off-by: Callum Brown <callum@calcuode.com>
I think this should complete what I started in #2020 but there might still be something missing....
---

Finish adding registration token UIA type

---

package.json
spec/integ/matrix-client-retrying.spec.ts
spec/unit/models/MSC3089TreeSpace.spec.ts
spec/unit/utils.spec.ts
spec/unit/webrtc/call.spec.ts
src/ReEmitter.ts
src/client.ts
src/content-repo.ts
src/crypto/DeviceList.ts
src/crypto/SecretStorage.ts
src/crypto/algorithms/base.ts
src/crypto/algorithms/megolm.ts
src/crypto/algorithms/olm.ts
src/crypto/index.ts
src/crypto/keybackup.ts
src/crypto/olmlib.ts
src/crypto/verification/request/InRoomChannel.ts
src/http-api.js
src/interactive-auth.ts
src/logger.ts
src/matrix.ts
src/models/event-timeline-set.ts
src/models/event.ts
src/models/room.ts
src/scheduler.ts
src/store/index.ts
src/store/indexeddb-local-backend.ts
src/utils.ts
tsconfig.json

Very small step of the way towards noImplicitAny
---

Improve typing

---

package.json
yarn.lock

Update olm to 3.2.8

---

release.sh

Add git archive learnings to release script comment

---

src/client.ts

Fixes /hierarchy and probably more, regressed by http-api TSification
---

Fix sending `undefined` query args to Synapse

---

src/@types/polls.ts

These constants should be in matrix-js-sdk, so once this is merged I will make a PR removing them from matrix-react-sdk.
---

Copy the polls constants to matrix-js-sdk from matrix-react-sdk

---

src/@types/location.ts
src/@types/polls.ts
src/content-helpers.ts

Provide a makeLocationContent to create a location content event

---

src/@types/polls.ts

Remove now-unused makePollContent from its old location

---

src/models/room.ts
src/models/thread.ts

Fixes https://github.com/vector-im/element-web/issues/19197
---

Make threads events indexed by the index manager

---

src/models/MSC3089Branch.ts

---
* Fix timeline search in MSC3089 getFileEvent() ([\#2085](https://github.com/matrix-org/matrix-js-sdk/pull/2085)). Contributed by @hughns.

Fix timeline search in MSC3089 getFileEvent()

---

src/client.ts

Fixes https://github.com/vector-im/element-web/issues/20687
---

Add default IContent value in makeContentExtensible

---

src/models/room.ts

Fixes https://github.com/vector-im/element-web/issues/20640
---

Fix local echo for reactions in threads

---

src/models/thread.ts

Fixes https://github.com/vector-im/element-web/issues/20644
---

Make threads reply chain filter out local event ID

---

src/models/event-timeline-set.ts

Improve typing for Room.timeline data parameter

---

src/models/event.ts

Type: defect
Requires https://github.com/matrix-org/matrix-react-sdk/pull/7671
---
* Don't decrypt redacted messages ([\#2143](https://github.com/matrix-org/matrix-js-sdk/pull/2143)). Contributed by @SimonBrandner.

Don't decrypt redacted messages

---

src/client.ts

Add thread relation in sendEvent if it's missing

---

src/models/room.ts

Fixes https://github.com/vector-im/element-web/issues/20834
---

Avoid re-doing as much work when processing m.receipt event

---

src/models/room-member.ts

To diagnose https://github.com/vector-im/element-web/issues/20962
---

Log when member event membership is undefined

---

src/models/room.ts

Fixes https://github.com/vector-im/element-web/issues/21130
---

Null-guard for undefined rootEvent when creating a thread

---

src/models/MSC3089Branch.ts

---
* Return send event response from MSC3089Branch.createNewVersion() ([\#2186](https://github.com/matrix-org/matrix-js-sdk/pull/2186)). Contributed by @hughns.

Return send event response from MSC3089Branch.createNewVersion()

---

package.json
yarn.lock

(To improve editing polls by giving answers unique IDs)
---

Bump matrix-events-sdk to 0.0.1-beta.7

---

package.json
src/models/room-member.ts
src/models/user.ts
yarn.lock

Signed-off-by: Kerry Archibald <kerrya@element.io>
https://github.com/vector-im/element-web/security/dependabot/3
---

eslint to 8.9.0

---

package.json

Generate a JSON coverage file when requested to generate coverage

---

src/client.ts
src/models/room-state.ts
src/sync.ts

---
* Add new room state emit RoomStateEvent.Update for lower-frequency hits ([\#2192](https://github.com/matrix-org/matrix-js-sdk/pull/2192)).

Add new room state emit RoomStateEvent.Update for lower-frequency hits

---

src/client.ts

https://github.com/matrix-org/matrix-js-sdk/pull/2201 to release
---
* [Release] Fix bug with the /hierarchy API sending invalid requests ([\#2202](https://github.com/matrix-org/matrix-js-sdk/pull/2202)).

[Release] Fix bug with the /hierarchy API sending invalid requests

---

src/@types/spaces.ts
src/client.ts

Fixes https://github.com/vector-im/element-web/issues/19738
---

Stop using development /spaces API in favour of v1 /hierarchy API

---

codecov.yml

Provide settings to control the comments codecov adds to PRs

---

src/utils.ts

---
* Fix defer not supporting resolving with a Promise<T> ([\#2216](https://github.com/matrix-org/matrix-js-sdk/pull/2216)).

Fix defer not supporting resolving with a Promise<T>

---

src/models/event.ts

Related to https://github.com/vector-im/element-web/issues/21412
---

Use stable value for fallback

---

src/models/thread.ts

Fixes https://github.com/vector-im/element-web/issues/21415
---

Fix threads reply count sometimes off by one

---

spec/unit/room-state.spec.js
src/models/beacon.ts
src/models/room-state.ts
src/sync.ts

reemit beacon events

---

src/models/event.ts

Improve typing for MatrixEvent::getContent generic

---

spec/test-utils/beacon.ts
spec/unit/models/beacon.spec.ts
spec/unit/room-state.spec.js
src/models/beacon.ts
src/models/room-state.ts

Use beacon info event type as beacon identifier

---

src/models/room.ts

That would otherwise create very large amount of filters requests to the homeserver
---

Lazy load thread list timeline set

---

.github/codecov.yml
.github/workflows/test_coverage.yml

Port codecov improvements matrix-react-sdk -> matrix-js-sdk

---

src/models/room.ts

Instantiate Thread objects when running fetchRoomThreads

---

.github/workflows/test_coverage.yml

Fix coverage diffs for PRs that aren't up to date

---

src/client.ts

Fixes https://github.com/vector-im/element-web/issues/21704
---

Fix notification panel not loading

---

src/crypto/verification/SAS.ts
yarn.lock

Upgrade dependencies

---

spec/unit/room.spec.ts
src/client.ts
src/models/room.ts
src/store/index.ts
src/store/indexeddb-backend.ts
src/store/indexeddb-local-backend.ts
src/store/indexeddb-remote-backend.ts
src/store/indexeddb.ts
src/store/memory.ts
src/store/stub.ts

De-duplicate code and fix types

---

.github/workflows/static_analysis.yml
sonar-project.properties

Try SonarCloud

---

src/autodiscovery.ts
src/client.ts
src/crypto/DeviceList.ts
src/crypto/backup.ts
src/crypto/index.ts
src/crypto/verification/request/VerificationRequest.ts
src/http-api.ts
src/store/indexeddb-local-backend.ts
src/utils.ts

Apply corrections identified by SonarQube

---

spec/unit/webrtc/call.spec.ts
src/client.ts
src/webrtc/groupCall.ts
src/webrtc/groupCallEventHandler.ts

This just merges the ptt branch into the group call branch - all the changes here should already have been reviewed.
Also fixes the tests
---
* Support for PTT group call mode ([\#2338](https://github.com/matrix-org/matrix-js-sdk/pull/2338)).

Support for PTT group call mode

---

.github/workflows/upgrade_dependencies.yml

Create manual action for upgrading dependencies after rc cut

---

spec/browserify/sync-browserify.spec.js
src/autodiscovery.ts
src/client.ts
src/crypto/OlmDevice.ts
src/crypto/OutgoingRoomKeyRequestManager.ts
src/crypto/SecretStorage.ts
src/crypto/aes.ts
src/crypto/algorithms/olm.ts
src/crypto/backup.ts
src/crypto/dehydration.ts
src/crypto/index.ts
src/crypto/key_passphrase.ts
src/crypto/verification/SAS.ts
src/crypto/verification/request/InRoomChannel.ts
src/http-api.ts
src/matrix.ts
src/pushprocessor.ts
src/utils.ts
src/webrtc/call.ts

Apply suggestions from SonarQube

---

sonar-project.properties

Tweak sonar-project.properties

---

src/client.ts
src/crypto/DeviceList.ts
src/crypto/verification/SAS.ts
src/matrix.ts
src/models/event-timeline-set.ts
src/models/room-state.ts
src/models/room.ts
src/store/index.ts
src/store/stub.ts

Another SonarQube happiness pass

---

spec/unit/matrix-client.spec.ts
src/client.ts

Citation: https://matrix.to/#/!ewdjhNcPcEmYNKzlWp:t2l.io/$CkPuvKdFZyFL547JCy5J3MfvLaWUo_a1XEdmiop1PKc?via=matrix.org&via=element.io&via=envs.net
---

Remove spec v1.3 check for threads

---

.github/workflows/sonarqube.yml
sonar-project.properties

Pass more args to Sonar

---

.github/workflows/sonarqube.yml

Example run with a forked PR https://github.com/t3chguy/matrix-js-sdk/runs/6384523541?check_suite_focus=true
---

Tweaks for sonar to correctly report on forked PRs

---

spec/integ/matrix-client-event-timeline.spec.js
spec/unit/webrtc/callEventHandler.spec.ts
src/@types/requests.ts
src/client.ts
src/crypto/DeviceList.ts
src/crypto/index.ts
src/models/event.ts
src/sync-accumulator.ts
src/sync.ts
src/webrtc/callEventHandler.ts

Fix up more types & Sonar warnings

---

src/webrtc/groupCall.ts

await on the async operation so the promise we return resolves once
everything's actuall complete
---
* Fix races when muting/unmuting ([\#2370](https://github.com/matrix-org/matrix-js-sdk/pull/2370)).

Fix races when muting/unmuting

---

.github/workflows/notify-downstream.yaml
.github/workflows/pr_details.yml
.github/workflows/pull_request.yaml
.github/workflows/sonarcloud.yml
.github/workflows/sonarqube.yml
.github/workflows/static_analysis.yml
.github/workflows/tests.yml

Attempt to re-structure workflows to be more generic & reusable

---

.github/workflows/notify-downstream.yaml

Fix GHA trigger downstream projects

---

.github/workflows/sonarcloud.yml
.github/workflows/sonarqube.yml

Sonarcloud check out upstream develop not fork develop

---

.github/workflows/sonarcloud.yml
.github/workflows/sonarqube.yml

Reverts matrix-org/matrix-js-sdk#2378

Revert "Sonarcloud check out upstream develop not fork develop"

---

src/store/indexeddb.ts

https://github.com/matrix-org/matrix-js-sdk/pull/2385 to release
---
* [Release] Catch promise errors in degradable ([\#2388](https://github.com/matrix-org/matrix-js-sdk/pull/2388)).

[Release] Catch promise errors in degradable

---

src/pushprocessor.ts

As per https://github.com/matrix-org/matrix-spec-proposals/pull/3786#discussion_r864607531
---

Remove `dont_notify` from the `.m.rule.room.server_acl` rule

---

.github/workflows/pr_details.yml
.github/workflows/sonarqube.yml

Improve PR Details job to use github-script and output labels

---

.github/workflows/jsdoc.yml
release.sh

Test example https://github.com/t3chguy/matrix-js-sdk/commit/8f67b714968f4c8db83a6c2a2c2e497fda0a337b
---

Initial attempt at automating jsdoc

---

.istanbul.yml

Remove unused file

---

.github/workflows/sonarcloud.yml

Attempt number 2 from https://github.com/matrix-org/matrix-js-sdk/pull/2378
---

Fix sonarqube using base branch on fork for detecting new code in pr

---

.github/workflows/pull_request.yaml

Reverts matrix-org/matrix-js-sdk#2418

Revert "Github Actions pull_request synchronize runs on PR open anyway"

---

spec/integ/devicelist-integ.spec.js

Fix test suite regression due to TestClient refactoring

---

spec/unit/pushprocessor.spec.js
src/pushprocessor.ts

MSC: https://github.com/matrix-org/matrix-spec-proposals/pull/3786
---
* Update MSC3786 implementation: Check the `state_key` ([\#2429](https://github.com/matrix-org/matrix-js-sdk/pull/2429)).

Update MSC3786 implementation: Check the `state_key`

---

src/crypto/index.ts

Typing minutiae to accompany https://github.com/matrix-org/matrix-react-sdk/pull/8750.
---

The request callback provided by bootstrapCrossSigning is async

---

CONTRIBUTING.md

Document how to inhibit code coverage requirement

---

.github/workflows/pull_request.yaml

Add CI to improve experience for community

---

.github/workflows/sonarcloud.yml

Update sonarcloud-workflow-action to fix projectVersion not being passed properly

---

src/interactive-auth.ts

Per spec, for example: https://spec.matrix.org/v1.2/client-server-api/#dummy-auth
---
* Add missing `type` property on `IAuthData` ([\#2463](https://github.com/matrix-org/matrix-js-sdk/pull/2463)).

Add missing `type` property on `IAuthData`

---

src/webrtc/groupCall.ts

Reverts https://github.com/matrix-org/matrix-js-sdk/pull/2450
Looks like this wasn't really the problem (although may have made it
happens faster) and the actual problem was multiple audio contexts
and/or leaking peer connections as fixed in https://github.com/matrix-org/matrix-js-sdk/pull/2484
---

Revert hack to only clone streams on safari

---

spec/unit/utils.spec.ts
src/crypto/api.ts
src/crypto/verification/Error.ts
src/utils.ts

Towards https://github.com/vector-im/element-web/issues/21969
---

Remove dead code

---

release.sh

Update release.sh to support a `staging` branch

---

spec/integ/megolm-integ.spec.ts
spec/test-utils/test-utils.ts

Rewrite megolm integration tests with async arrow functions

---

src/webrtc/call.ts
src/webrtc/groupCall.ts
src/webrtc/mediaHandler.ts

Requires https://github.com/matrix-org/matrix-js-sdk/pull/2525
For https://github.com/vector-im/element-call/pull/473
---

Add support for audio sharing

---

spec/unit/crypto/algorithms/megolm.spec.ts

Delint group calls

---

spec/unit/queueToDevice.spec.ts

As per comment
https://github.com/matrix-org/matrix-js-sdk/issues/2561 (fixes the logging after tests but not Travis's flakes)
---

Fix output after test finished

---

spec/unit/queueToDevice.spec.ts

https://github.com/matrix-org/matrix-js-sdk/issues/2561
Hopefully this will avoid the flakiness Travis has been experiencing.
---

Increase timeout to try & avoid flakiness in queueToDevice test

---

src/client.ts
src/crypto/algorithms/megolm.ts
src/crypto/index.ts

It went to quite a lot of effort to gather a bunch of information to
return, but the only thing using it already had all that info anyway.
---

Simplify encryptAndSendToDevices

---

spec/unit/crypto/algorithms/megolm.spec.ts
src/crypto/algorithms/megolm.ts

This will be rolled out again later with more accompanying UI adjustments, including clearer error messages and possibly the option to disable it per-room.
---

Revert "Always block sending keys to unverified devices of verified users (#2562)"

---

.eslintrc.js

Context: https://github.com/matrix-org/matrix-js-sdk/pull/2572#pullrequestreview-1066219981 
Type: task
---

Document where new linting rules go

---

.github/workflows/backport.yml

Set up basic Backporting action

---

.github/workflows/backport.yml

Tweak backport

---

spec/unit/autodiscovery.spec.ts
spec/unit/interactive-auth.spec.ts
src/autodiscovery.ts
src/interactive-auth.ts
src/pushprocessor.ts
src/utils.ts
src/webrtc/call.ts

#2572 but without the actual rule change. Will make the rule pass here once merged and has some additional cleanup and modernization around the changed lines.
Type: task
---

Improve test coverage and modernize style for interactive-auth

---

spec/test-utils/webrtc.ts
spec/unit/webrtc/call.spec.ts
spec/unit/webrtc/groupCall.spec.ts
src/webrtc/groupCall.ts

Fixes https://github.com/vector-im/element-call/issues/522
---

Add group call tests for muting

---

src/webrtc/call.ts

Remove duplicate log of answering a call

---

spec/test-utils/webrtc.ts
spec/unit/webrtc/groupCall.spec.ts

Fixes https://github.com/vector-im/element-call/issues/531
---

Add test for updateLocalUsermediaStream

---

spec/unit/webrtc/groupCall.spec.ts

Fixes https://github.com/vector-im/element-call/issues/523
---

Test muting in PTT mode

---

spec/test-utils/webrtc.ts
spec/unit/webrtc/groupCall.spec.ts
src/webrtc/groupCall.ts

Fixes https://github.com/vector-im/element-call/issues/528
---

Add screensharing tests

---

spec/unit/webrtc/call.spec.ts

Fixes https://github.com/vector-im/element-call/issues/547
---

Test call timeouts

---

.github/workflows/static_analysis.yml

Tweak tsc-strict config

---

spec/unit/crypto/outgoing-room-key-requests.spec.ts
src/crypto/store/indexeddb-crypto-store-backend.ts
src/crypto/store/memory-crypto-store.ts

---
* Use deep equality comparisons when searching for outgoing key requests by target ([\#2623](https://github.com/matrix-org/matrix-js-sdk/pull/2623)). Contributed by @duxovni.

Use deep equality comparisons when searching for outgoing key requests by target

---

src/client.ts
src/webrtc/groupCallEventHandler.ts

Emit an event when the group call event handler has processed all
pending group calls.
---
* Add GroupCallEventHandlerEvent.Room ([\#2631](https://github.com/matrix-org/matrix-js-sdk/pull/2631)).

Add GroupCallEventHandlerEvent.Room

---

spec/test-utils/webrtc.ts
spec/unit/webrtc/groupCall.spec.ts

Test disabling screenshare in group calls

---

spec/unit/webrtc/groupCall.spec.ts

Add some types & use mock-typed versions directly - it's clearer which
client we're making assertions about.
---

Refactor the group call placing calls test

---

spec/test-utils/flushPromises.ts
spec/test-utils/webrtc.ts
spec/unit/queueToDevice.spec.ts
spec/unit/webrtc/groupCall.spec.ts

Test that calls in a group call are retried

---

.github/workflows/release-npm.yml
.github/workflows/release.yml
post-release.sh
release.sh

Simplify releases: move npm publishing to gha, consolidate scripts

---

release.sh

Fix release script for layers without a release_config.yaml file

---

src/webrtc/groupCallEventHandler.ts

as otherwise it recurses and logs the entire client + store
---

Log ID instead of object

---

src/models/invites-ignorer.ts

These were causing circular references in the group call branch
---

Fix import locations

---

spec/test-utils/webrtc.ts
spec/unit/webrtc/groupCall.spec.ts
spec/unit/webrtc/groupCallEventHandler.spec.ts
src/webrtc/groupCallEventHandler.ts

Fixes https://github.com/vector-im/element-call/issues/545
---

GroupCallEventhandler Tests

---

spec/unit/webrtc/groupCall.spec.ts

Fixes https://github.com/vector-im/element-call/issues/527
---

Test active speaker events

---

spec/test-utils/webrtc.ts
spec/unit/webrtc/call.spec.ts

Test fallback screensharing

---

src/webrtc/groupCall.ts

Fixes https://github.com/vector-im/element-call/issues/578
---
* Prevent exception when muting ([\#2667](https://github.com/matrix-org/matrix-js-sdk/pull/2667)). Fixes vector-im/element-call#578.

Prevent exception when muting

---

release.sh

Like for in element-desktop
---

Fix reset_dependency for if the dep is indirect

---

.github/workflows/sonarcloud.yml

Add commit status for the sonarcloud workflow run

---

spec/test-utils/webrtc.ts
spec/unit/webrtc/groupCall.spec.ts

Add a few new `GroupCall` tests

---

spec/integ/matrix-client-event-timeline.spec.ts
src/client.ts

Fixes https://github.com/vector-im/element-web/issues/22784
---
* Fix backpagination at end logic being spec non-conforming ([\#2680](https://github.com/matrix-org/matrix-js-sdk/pull/2680)). Fixes vector-im/element-web#22784.

Fix backpagination at end logic being spec non-conforming

---

src/@types/event.ts

Add unstable device_id field for MSC3881

---

spec/test-utils/webrtc.ts
spec/unit/webrtc/groupCallEventHandler.spec.ts

Add a few group call event handler tests

---

src/@types/auth.ts

Refer to explicit Matrix spec versions instead of Latest

---

spec/unit/matrix-client.spec.ts
spec/unit/webrtc/groupCall.spec.ts

Add `MatrixClient` group call tests

---

src/@types/auth.ts

Typings for MSC3824

---

release.sh

Remove redundant rel_branch logic

---

spec/test-utils/webrtc.ts
spec/unit/webrtc/call.spec.ts

Add more `MatrixCall` tests

---

src/client.ts
src/store/index.ts

Account data can return undefined

---

src/@types/event.ts

Fix incorrect MSC3890 unstable prefix

---

spec/unit/crypto/secrets.spec.ts
spec/unit/crypto/verification/sas.spec.ts
spec/unit/models/beacon.spec.ts
src/crypto/store/indexeddb-crypto-store-backend.ts

---
* Bump IDB crypto store version ([\#2705](https://github.com/matrix-org/matrix-js-sdk/pull/2705)). Contributed by @duxovni.

Bump IDB crypto store version

---

spec/integ/matrix-client-syncing.spec.ts
src/crypto/store/indexeddb-crypto-store-backend.ts

---
* Fix missing return when receiving an invitation without shared history ([\#2710](https://github.com/matrix-org/matrix-js-sdk/pull/2710)). Contributed by @duxovni.

Fix missing return when receiving an invitation without shared history

---

.github/workflows/release-npm.yml

Fix release-npm.yml dist-tag npm token passing mechanism

---

spec/unit/stores/indexeddb.spec.ts
src/store/indexeddb-local-backend.ts

Regressed by https://github.com/matrix-org/matrix-js-sdk/pull/2713
Fixes https://github.com/vector-im/element-web/issues/23377
---
* Fix IDB initial migration handling causing spurious lazy loading upgrade loops ([\#2718](https://github.com/matrix-org/matrix-js-sdk/pull/2718)). Fixes vector-im/element-web#23377.

Fix IDB initial migration handling causing spurious lazy loading upgrade loops

---

src/crypto/algorithms/megolm.ts
src/models/event.ts

Rename redecryption-related function arguments for clarity

---

src/client.ts

Check for the spec version when determining private read receipt support

---

.eslintrc.js

Took me too long to figure out what was going on
---

Add custom error message for restricted import

---

src/@types/requests.ts

For https://github.com/matrix-org/matrix-react-sdk/pull/9347
---
* Fix `power_level_content_override` type ([\#2741](https://github.com/matrix-org/matrix-js-sdk/pull/2741)).

Fix `power_level_content_override` type

---

src/webrtc/groupCallEventHandler.ts

More debugging for multiple group calls

---

README.md

SimpleHTTPServer was python 2.
---

README.md: fix jsdoc viewer incantation

---

src/ToDeviceMessageQueue.ts

An attempt to debug https://github.com/vector-im/element-web/issues/23548: let's see if we can figure out where the to-device messages are getting lost.
My first non-trivial js-sdk PR for many years, so very interested in feedback on this.
---

Add debugging for unsent to-device messages

---

src/client.ts

Add `room_type` field to /publicRooms response

---

src/crypto/crypto.ts

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/2788
---

Improve crypto init code and allow easier shimming

---

src/crypto/crypto.ts

Backport 3a6561af364ff652f0910002a22b3b8b7408f33a from #2791.
---

[Backport] Improve crypto init code and allow easier shimming (#2791)

---

spec/unit/webrtc/callEventHandler.spec.ts
spec/unit/webrtc/groupCall.spec.ts
src/webrtc/audioContext.ts
src/webrtc/call.ts
src/webrtc/callEventHandler.ts
src/webrtc/callFeed.ts
src/webrtc/groupCall.ts
src/webrtc/groupCallEventHandler.ts
src/webrtc/mediaHandler.ts

TS strict mode compliance in the call / groupcall code

---

spec/unit/webrtc/groupCall.spec.ts

When these tests failed, this left handles open causing the test process to never die.
---

Clean up group call tests

---

spec/test-utils/webrtc.ts
spec/unit/webrtc/call.spec.ts
spec/unit/webrtc/callEventHandler.spec.ts
spec/unit/webrtc/groupCall.spec.ts
spec/unit/webrtc/groupCallEventHandler.spec.ts
src/webrtc/call.ts
src/webrtc/callEventHandler.ts
src/webrtc/groupCall.ts
src/webrtc/mediaHandler.ts
tsconfig.json

More TS strict mode fixes

---

src/client.ts
src/embedded.ts

A few more strict mode fixes

---

spec/unit/http-api/fetch.spec.ts
src/client.ts
src/http-api/fetch.ts

Fixes https://github.com/vector-im/element-web/issues/23655
---
* Fix authedRequest including `Authorization: Bearer undefined` for password resets ([\#2822](https://github.com/matrix-org/matrix-js-sdk/pull/2822)). Fixes vector-im/element-web#23655.

Fix authedRequest including `Authorization: Bearer undefined` for password resets

---

package.json
tsconfig.json
yarn.lock

Requires https://github.com/matrix-org/eslint-plugin-matrix-org/pull/32
---

Add eslint rule unicorn/no-instanceof-array

---

spec/unit/queueToDevice.spec.ts

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/2561
---

Fix queueToDevice.spec.ts test flakiness

---

src/webrtc/call.ts

Add logging saying why we hung up calls

---

src/webrtc/groupCall.ts

Log the call ID when receiving a call

---

.github/workflows/docs-pr-netlify.yaml
.github/workflows/static_analysis.yml

Upload docs artifact for PRs

---

src/crypto/olmlib.ts
src/models/event.ts

Some attempts to make debugging UISIs a bit easier
---

Improve logs for decrypting events

---

.github/workflows/static_analysis.yml

Add CI check with tsc --noImplicitAny

---

.github/workflows/tests.yml
spec/slowReporter.js

FYI: jest doesn't seems to support TS file for custom reporter, so I have to stick with a js file.
---

Add jest metrics

---

spec/integ/matrix-client-methods.spec.ts
src/client.ts

Fixes https://github.com/vector-im/element-web/issues/23823
---
* Fix 3pid invite acceptance not working due to mxid being sent in body ([\#2907](https://github.com/matrix-org/matrix-js-sdk/pull/2907)). Fixes vector-im/element-web#23823.

Fix 3pid invite acceptance not working due to mxid being sent in body

---

spec/integ/sliding-sync-sdk.spec.ts
src/sliding-sync-sdk.ts

---
* sliding sync: add receipts extension ([\#2912](https://github.com/matrix-org/matrix-js-sdk/pull/2912)).

sliding sync: add receipts extension

---

src/client.ts
src/webrtc/call.ts
src/webrtc/groupCall.ts

Fixes https://github.com/matrix-org/waterfall/issues/37
---
* Implement a very basic focus selection algorithm ([\#2875](https://github.com/matrix-org/matrix-js-sdk/pull/2875)). Fixes matrix-org/waterfall#37.

Implement a very basic focus selection algorithm

---

spec/integ/matrix-client-event-timeline.spec.ts
spec/integ/matrix-client-relations.spec.ts
src/@types/requests.ts
src/client.ts

Type: Task
Fixes: https://github.com/matrix-org/matrix-js-sdk/issues/2725
---

Switch to stable /relations endpoint, stop using unspecced original_event field

---

src/models/thread.ts

Improve perceived performance for threads

---

package.json

Move @types deps into devDeps

---

README.md

Update test runner instructions

---

spec/unit/crypto/cross-signing.spec.ts
src/client.ts
src/crypto/index.ts

... to save clients digging into the guts of `crypto`
---

Expose a new 'userHasCrossSigningKeys' method

---

spec/test-utils/webrtc.ts
spec/unit/webrtc/call.spec.ts
src/webrtc/call.ts
src/webrtc/groupCall.ts
src/webrtc/groupCallEventHandler.ts

Minor VoIP stack improvements

---

spec/unit/room.spec.ts
src/models/room.ts

Avoid creating duplicate threads

---

.git-blame-ignore-revs

commit https://github.com/matrix-org/matrix-js-sdk/commit/349c2c2587c2885bb69eda4aa078b5383724cf5e
---

Add prettier formatting to .git-blame-ignore-revs

---

spec/integ/matrix-client-event-timeline.spec.ts
src/client.ts

Type: Defect
Fixes: https://github.com/vector-im/element-web/issues/24036
---
* Threads are missing from the timeline ([\#2996](https://github.com/matrix-org/matrix-js-sdk/pull/2996)). Fixes vector-im/element-web#24036. Contributed by @justjanne.

Threads are missing from the timeline

---

release.sh

Fix release scripts to not fight with prettier

---

src/sliding-sync-sdk.ts

---
* bugfix: upload OTKs in sliding sync mode ([\#3008](https://github.com/matrix-org/matrix-js-sdk/pull/3008)).

bugfix: upload OTKs in sliding sync mode

---

README.md

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/3048
---

Fix dated example

---

package.json

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/3013
---
* Fix browser entrypoint ([\#3051](https://github.com/matrix-org/matrix-js-sdk/pull/3051)). Fixes #3013.

Fix browser entrypoint

---

package.json

https://github.com/matrix-org/matrix-js-sdk/pull/3051 to release
---
* [Release] Fix browser entrypoint ([\#3052](https://github.com/matrix-org/matrix-js-sdk/pull/3052)).

[Release] Fix browser entrypoint

---

spec/unit/webrtc/call.spec.ts
spec/unit/webrtc/groupCall.spec.ts
src/webrtc/call.ts
src/webrtc/callFeed.ts
src/webrtc/groupCall.ts

Requires https://github.com/vector-im/element-call/pull/837
---
* Add proper (un)subscribe logic ([\#3047](https://github.com/matrix-org/matrix-js-sdk/pull/3047)).

Add proper (un)subscribe logic

---

spec/unit/webrtc/call.spec.ts
src/webrtc/call.ts
src/webrtc/callFeed.ts
src/webrtc/groupCall.ts

Fix typos in `src/webrtc/`

---

spec/unit/webrtc/callFeed.spec.ts
src/webrtc/call.ts
src/webrtc/callFeed.ts

Improve (un)subscription logic

---

src/webrtc/call.ts

---
* Always subscribe to audio tracks ([\#3087](https://github.com/matrix-org/matrix-js-sdk/pull/3087)).

Always subscribe to audio tracks

---

spec/unit/matrix-client.spec.ts

Preparation for [MSC3946](https://github.com/matrix-org/matrix-spec-proposals/pull/3946) 
---

Tests for getRoomUpgradeHistory

---

src/webrtc/call.ts

---
* Don't forget about simulcast in `updateLocalUsermediaStream()` ([\#3093](https://github.com/matrix-org/matrix-js-sdk/pull/3093)).

Don't forget about simulcast in `updateLocalUsermediaStream()`

---

src/webrtc/callFeed.ts

Fixes https://github.com/vector-im/element-call/issues/874
---
* Fix volume indicators and speaker detection not working in SFU mode ([\#3094](https://github.com/matrix-org/matrix-js-sdk/pull/3094)). Fixes vector-im/element-call#874.

Fix volume indicators and speaker detection not working in SFU mode

---

src/webrtc/call.ts

Fixes https://github.com/vector-im/element-call/issues/878
Fixes https://github.com/vector-im/element-call/issues/877
---

Clean-up simulcast code

---

src/webrtc/call.ts

---
* Fix simulcast on chrome ([\#3109](https://github.com/matrix-org/matrix-js-sdk/pull/3109)).

Fix simulcast on chrome

---

spec/unit/webrtc/mediaHandler.spec.ts
src/@types/global.d.ts
src/webrtc/call.ts
src/webrtc/mediaHandler.ts

Add simulcast screensharing encodings

---

spec/integ/matrix-client-event-timeline.spec.ts
spec/integ/matrix-client-methods.spec.ts
spec/test-utils/webrtc.ts
spec/unit/event-timeline-set.spec.ts
spec/unit/matrix-client.spec.ts
spec/unit/models/thread.spec.ts
spec/unit/notifications.spec.ts
spec/unit/room.spec.ts
src/client.ts
src/models/event.ts
src/models/room.ts
src/models/thread.ts
src/sync.ts

Stop labelling threads as experimental

---

src/webrtc/mediaHandler.ts

Don't use ideal/exact in case of screen-sharing

---

.eslintrc.js
package.json
src/crypto/algorithms/megolm.ts
src/crypto/index.ts
yarn.lock

Add @typescript-eslint/no-base-to-string

---

spec/unit/webrtc/groupCall.spec.ts
src/webrtc/call.ts
src/webrtc/callEventHandler.ts
src/webrtc/callFeed.ts
src/webrtc/groupCall.ts
src/webrtc/groupCallEventHandler.ts
src/webrtc/mediaHandler.ts

This should hopefully make debugging calls at least a bit easier 
---

Improve WebRTC logging

---

src/client.ts
src/crypto/index.ts

Iterate types

---

spec/integ/matrix-client-methods.spec.ts
src/@types/IIdentityServerProvider.ts
src/client.ts
src/http-api/fetch.ts

Improve types

---

spec/unit/webrtc/call.spec.ts
spec/unit/webrtc/callFeed.spec.ts
src/webrtc/call.ts
src/webrtc/callFeed.ts
src/webrtc/callTrack.ts
src/webrtc/groupCall.ts
src/webrtc/localCallFeed.ts
src/webrtc/localCallTrack.ts
src/webrtc/remoteCallFeed.ts
src/webrtc/remoteCallTrack.ts

Move mute state into `CallTrack`s

---

.eslintrc.js
spec/integ/matrix-client-opts.spec.ts
spec/integ/sliding-sync-sdk.spec.ts
spec/unit/NamespacedValue.spec.ts
spec/unit/crypto/CrossSigningInfo.spec.ts
spec/unit/crypto/backup.spec.ts
spec/unit/matrix-client.spec.ts
spec/unit/models/MSC3089Branch.spec.ts
spec/unit/models/MSC3089TreeSpace.spec.ts
spec/unit/pushprocessor.spec.ts
spec/unit/room.spec.ts
spec/unit/scheduler.spec.ts

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/2978
---

Fix jest/no-conditional-expect lint and enable it

---

src/webrtc/call.ts

Fix CallOpts types

---

src/webrtc/call.ts

Add a type to the structure used by the SendVoipEvent event

---

package.json
spec/integ/crypto.spec.ts
yarn.lock

~~Requires fixes in the rust-sdk including https://github.com/matrix-org/matrix-rust-sdk/pull/1633, so leaving this as a draft for now.~~
---

Add a new test for event encryption, which works with rust

---

src/webrtc/groupCall.ts

Run prettier on groupCall.ts

---

CHANGELOG.md

Update changelog for v24.0.0 now the security issue is public

---

spec/test-utils/webrtc.ts
spec/unit/webrtc/call.spec.ts
spec/unit/webrtc/callFeed.spec.ts
spec/unit/webrtc/groupCall.spec.ts
src/webrtc/call.ts
src/webrtc/groupCall.ts

Re-applies https://github.com/matrix-org/matrix-js-sdk/pull/3229
Merge https://github.com/matrix-org/matrix-react-sdk/pull/10477 immediately afterwards
---

Re-apply "Add the call object to Call events"

---

.github/workflows/tests.yml

Tidy up merge queue automation

---

.github/workflows/pull_request.yaml

Handle concurrency in merge_queues better

---

src/client.ts
src/http-api/fetch.ts
src/pushprocessor.ts

Update types to match reality

---

.github/workflows/static_analysis.yml
src/client.ts
src/crypto/index.ts
src/crypto/store/base.ts
src/interactive-auth.ts
src/matrix.ts
src/models/room.ts

There aren't that many of these, so I've gone through and fixed them, and
configured the GHA workflow to complain if any creep back in.
---

Fix typedoc warnings

---

src/secret-storage.ts

(and improve some doc-comments)
Seems like I missed a couple of methods when I created this interface in #3267.
---

Add missing methods to `ServerSideSecretStorgage`

---

spec/unit/webrtc/stats/statsReportBuilder.spec.ts
spec/unit/webrtc/stats/trackStatsReporter.spec.ts
src/webrtc/stats/media/mediaTrackStats.ts
src/webrtc/stats/statsReport.ts
src/webrtc/stats/statsReportBuilder.ts
src/webrtc/stats/statsReportGatherer.ts
src/webrtc/stats/trackStatsReporter.ts

Add Jitter to exported webrtc stats
---

Add Jitter to exported webrtc stats

---

src/models/room.ts

Add Room.threadsTimelineSets doc

---

package.json
yarn.lock

---
* Add typedoc-plugin-mdn-links ([\#3292](https://github.com/matrix-org/matrix-js-sdk/pull/3292)).

Add typedoc-plugin-mdn-links

---

spec/unit/webrtc/stats/statsReportGatherer.spec.ts
spec/unit/webrtc/stats/summaryStatsReporter.spec.ts
spec/unit/webrtc/stats/trackStatsReporter.spec.ts
src/webrtc/stats/statsReport.ts
src/webrtc/stats/statsReportGatherer.ts
src/webrtc/stats/summaryStats.ts
src/webrtc/stats/summaryStatsReporter.ts
src/webrtc/stats/trackStatsReporter.ts

Adding the maximum Jitter and Package Loss for every stats Report per poll interval!
---

Add max jitter and max packet loss

---

.github/workflows/release.yml
.github/workflows/static_analysis.yml
package.json
typedoc.json
yarn.lock

Use typedoc-plugin-versions

---

src/models/room.ts

Add proper deprecation doc to room fields

---

src/scheduler.ts

Type: Task
Related: https://github.com/vector-im/element-web/issues/22885
---

Increase log level for scheduler

---

package.json
yarn.lock

Update `@matrix-org/matrix-sdk-crypto-js` to `0.1.0-alpha.7`
Needed for https://github.com/matrix-org/matrix-js-sdk/pull/3272
---

Update `@matrix-org/matrix-sdk-crypto-js` to `0.1.0-alpha.7`

---

src/crypto/algorithms/olm.ts

Add some comments to `OlmDecryption.decryptEvent`

---

src/utils.ts

Use safeSet in recursivelyAssign

---

package.json
yarn.lock

Update `@matrix-org/matrix-sdk-crypto-js` to `^0.1.0-alpha.8`

---

src/client.ts

Update types to match spec

---

src/ReEmitter.ts

Use WeakMap in ReEmitter to help enable garbage collection

---

package.json
spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
src/rust-crypto/OutgoingRequestProcessor.ts
yarn.lock

Element-R: support for SigningKeysUploadRequest

---

spec/integ/cross-signing.spec.ts
spec/unit/rust-crypto/CrossSigningIdentity.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/CrossSigningIdentity.ts
src/rust-crypto/rust-crypto.ts

Fixes https://github.com/vector-im/element-web/issues/25314
---

Element-R: initial implementation of `bootstrapCrossSigning`

---

spec/unit/webrtc/stats/groupCallStats.spec.ts
spec/unit/webrtc/stats/statsReportGatherer.spec.ts
spec/unit/webrtc/stats/summaryStatsReporter.spec.ts
src/webrtc/stats/statsReportGatherer.ts
src/webrtc/stats/summaryStats.ts
src/webrtc/stats/summaryStatsReporter.ts

Filter all summary stats which collect the first time webrtc metrics.

---

.github/workflows/sonarqube.yml

Fixes https://github.com/vector-im/element-web/issues/25334
---

Don't try run sonarcloud if tests got cancelled/failed

---

spec/integ/crypto.spec.ts
spec/olm-loader.ts
spec/unit/crypto.spec.ts
spec/unit/crypto/secrets.spec.ts
spec/unit/crypto/verification/sas.spec.ts
spec/unit/room.spec.ts
spec/unit/webrtc/call.spec.ts
spec/unit/webrtc/groupCall.spec.ts
src/autodiscovery.ts
src/client.ts
src/crypto/CrossSigning.ts
src/crypto/DeviceList.ts
src/crypto/store/memory-crypto-store.ts
src/crypto/verification/request/InRoomChannel.ts
src/embedded.ts

Make sonar happier about our code & tests

---

src/models/event-timeline.ts
src/models/thread.ts

The [original change](https://github.com/matrix-org/matrix-js-sdk/pull/3384) was done in a hurry, so here are some small fixes.
Part of https://github.com/vector-im/element-web/issues/10954
---

Minor improvements to the code inserting events into timelines

---

spec/unit/event-timeline-set.spec.ts

I came across this while doing something unrelated. This test modifies a global variable and leaves it modified.
This change makes sure it is set back to what it was before after the test.
Suggested view to review this: https://github.com/matrix-org/matrix-js-sdk/pull/3390/files?diff=split&w=1
---

Isolate changes to Thread global into a single describe block

---

src/webrtc/call.ts

Export FALLBACK_ICE_SERVER

---

spec/integ/sliding-sync-sdk.spec.ts
src/models/typed-event-emitter.ts
src/sliding-sync-sdk.ts
src/sliding-sync.ts

---
* Make sliding sync linearize processing of sync requests ([\#3442](https://github.com/matrix-org/matrix-js-sdk/pull/3442)).

Make sliding sync linearize processing of sync requests

---

package.json
yarn.lock

Update `@matrix-org/matrix-sdk-crypto-js` to `0.1.0-alpha.10`

---

.github/workflows/cypress.yml

Followup to #3412, and part of a fix to https://github.com/vector-im/element-web/issues/25542
---

Pass Kiwi secrets to react-sdk Cypress build

---

.github/workflows/cypress.yml
.github/workflows/downstream-artifacts.yml

Specify git tags for cypress workflow so updating tests is gated by renovate PRs

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/rust-crypto.ts

Element-R: implement `userHasCrossSigningKeys`

---

src/logger.ts
src/models/room.ts

Requires https://github.com/matrix-org/matrix-react-sdk/pull/11118
To debug https://github.com/vector-im/element-web/issues/25596
To debug https://github.com/vector-im/element-web/issues/25630
To debug https://github.com/vector-im/element-web/issues/25633
---

Add debug logging to figure out missing reactions in main timeline

---

spec/integ/crypto/crypto.spec.ts

For some reason, some tests seem to be timing out in GHA. Let's try bumping up
the timeout.
---

Increase crypto test timeout

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/rust-crypto/rust-crypto.ts

Part of https://github.com/vector-im/element-web/issues/25320
---

Rust crypto: emit `VerificationRequestReceived` events

---

src/models/event.ts

... to help with debugging.
---
* Log the message ID of any undecryptable to-device messages ([\#3543](https://github.com/matrix-org/matrix-js-sdk/pull/3543)).

Log the message ID of any undecryptable to-device messages

---

package.json
yarn.lock

Upgrade `@matrix-org/matrix-sdk-crypto-js` to `^0.1.1`

---

src/models/event.ts

---
* Update IUnsigned type to be extensible ([\#3547](https://github.com/matrix-org/matrix-js-sdk/pull/3547)).

Update IUnsigned type to be extensible

---

src/webrtc/groupCallEventHandler.ts

Add comment on updating the livekit service URL

---

src/sync.ts

Fixes https://github.com/vector-im/element-web/issues/18679
---
* Throw saner error when peeking has its room pulled out from under it ([\#3577](https://github.com/matrix-org/matrix-js-sdk/pull/3577)). Fixes vector-im/element-web#18679.

Throw saner error when peeking has its room pulled out from under it

---

spec/integ/matrix-client-methods.spec.ts
src/client.ts

… for backward compatibility
---

Use `cryptoBackend` in `client.ts` for new rust-crypto implementation

---

package.json
yarn.lock

... to pick up recent bugfixes, and support for `Qr.state`.
---

Bump matrix-crypto-sdk-js

---

.eslintrc.js
spec/integ/matrix-client-event-timeline.spec.ts
spec/integ/sliding-sync.spec.ts
spec/unit/login.spec.ts
spec/unit/oidc/register.spec.ts
spec/unit/rendezvous/ecdhv2.spec.ts
spec/unit/rendezvous/rendezvous.spec.ts
spec/unit/rendezvous/simpleHttpTransport.spec.ts
spec/unit/stores/indexeddb.spec.ts
spec/unit/utils.spec.ts
spec/unit/webrtc/call.spec.ts

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/2976
---

Fix jest/valid-expects lints

---

spec/integ/crypto/verification.spec.ts
src/crypto-api/verification.ts
src/rust-crypto/verification.ts

Closes https://github.com/vector-im/crypto-internal/issues/124
---
* Element-R: support for displaying QR codes during verification ([\#3588](https://github.com/matrix-org/matrix-js-sdk/pull/3588)). Fixes vector-im/crypto-internal#124.

Element-R: support for displaying QR codes during verification

---

spec/unit/room-hierarchy.spec.ts

Add tests for room-hierarchy

---

.github/workflows/downstream-artifacts.yml

Avoid running cypress tests outside of merge queue

---

spec/unit/read-receipt.spec.ts
spec/unit/room.spec.ts
src/models/read-receipt.ts

or vice versa
Fixes https://github.com/vector-im/element-web/issues/25806
---
* Ensure we do not clobber a newer RR with an older unthreaded one ([\#3617](https://github.com/matrix-org/matrix-js-sdk/pull/3617)). Fixes vector-im/element-web#25806.

Ensure we do not clobber a newer RR with an older unthreaded one

---

spec/integ/crypto/cross-signing.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/crypto-api.ts
src/rust-crypto/rust-crypto.ts

---
* ElementR: Add `CryptoApi.getCrossSigningKeyId` ([\#3619](https://github.com/matrix-org/matrix-js-sdk/pull/3619)). Contributed by @florianduros.

ElementR: Add `CryptoApi.getCrossSigningKeyId`

---

package.json
spec/integ/crypto/megolm-backup.spec.ts
src/client.ts
src/crypto-api.ts
src/crypto-api/keybackup.ts
src/crypto/backup.ts
src/crypto/deviceinfo.ts
src/crypto/index.ts
src/rust-crypto/backup.ts
src/rust-crypto/rust-crypto.ts
yarn.lock

Fixes https://github.com/vector-im/crypto-internal/issues/110
---

Implement `CryptoApi.isKeyBackupTrusted`

---

src/matrix.ts

Including:
+ SearchResult
+ EventStatus
+ CallEvent
+ SyncState
+ SyncStateData
+ SetPresence
+ Relations
+ RelationsEvent
+ TypedEventEmitter
+ SSOAction
+ SSOFlow
+ LoginFlow
+ LocationAssetType
and more
---
* Export more into the public interface ([\#3614](https://github.com/matrix-org/matrix-js-sdk/pull/3614)).

Export more into the public interface

---

src/matrix.ts

Re-export localStorage-crypto-store

---

src/client.ts

Improve/fix `client.restoreKeyBackupWithPassword` docs

---

spec/unit/embedded.spec.ts
src/embedded.ts

Support `getOpenIdToken()` in embedded mode

---

src/embedded.ts

Call `sendContentLoaded()`

---

spec/integ/crypto/crypto.spec.ts

Refactor crypto test, separate 4S and backup mgmt test.
No Change in behavior.
Just split a describe in a wrapping describe with two describes, and moved around common functions.
---

Cleanup, separate backup bootstrap and mgmt

---

spec/integ/crypto/crypto.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
spec/unit/rust-crypto/secret-storage.spec.ts
src/crypto/backup.ts
src/rust-crypto/rust-crypto.ts
src/rust-crypto/secret-storage.ts

Fixes https://github.com/vector-im/crypto-internal/issues/152
Udpated the integration test to be able to test it propery:
- Complete mocking to correctly update account data end-points and sync account data back
- Make test work on both rust/legacy when possible.
---

Implement isSecretStorageReady in rust

---

spec/unit/rust-crypto/CrossSigningIdentity.spec.ts
src/rust-crypto/CrossSigningIdentity.ts

Fixes https://github.com/vector-im/crypto-internal/issues/153
Fixes https://github.com/vector-im/element-web/issues/25781
`exportCrossSigningKeysToStorage` was not implemented
---

Implement exportCrossSigningKeysToStorage

---

yarn.lock

... thus picking up a bunch of recent fixes
Fixes https://github.com/vector-im/element-web/issues/26194
Fixes https://github.com/vector-im/element-web/issues/25706
---

Bump matrix-sdk-crypto-wasm to 1.3.0

---

src/autodiscovery.ts

---
* Export AutoDiscoveryError and fix type of ALL_ERRORS ([\#3768](https://github.com/matrix-org/matrix-js-sdk/pull/3768)).

Export AutoDiscoveryError and fix type of ALL_ERRORS

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/rust-crypto.ts

Fixes https://github.com/vector-im/element-web/issues/26244
Cypress tests https://github.com/matrix-org/matrix-react-sdk/pull/11686
---
* ElementR: Check key backup when user identity changes ([\#3760](https://github.com/matrix-org/matrix-js-sdk/pull/3760)). Fixes vector-im/element-web#26244. Contributed by @florianduros.

ElementR: Check key backup when user identity changes

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/RoomEncryptor.ts
src/rust-crypto/backup.ts
src/rust-crypto/rust-crypto.ts

Nothing major here; see individual commits
---

Grab bag of Element-R cleanups

---

README.md

- Corrected a minor typographical error in the README.md file at root dir, under Contributing -> Building.
- Changed "To build a browser version from scratch when developing::" to "To build a browser version from scratch when developing:"
This change is trivial and should have no functional impact on the project.
Signed-off-by: dharshan <dharshan2457@gmail.com>
---

Fix small typo in README.md in root dir

---

spec/unit/oidc/authorize.spec.ts
src/oidc/authorize.ts

For https://github.com/vector-im/element-web/issues/25393
With https://github.com/matrix-org/matrix-react-sdk/pull/11727
---
* OIDC: add `prompt` param to auth url creation ([\#3794](https://github.com/matrix-org/matrix-js-sdk/pull/3794)). Contributed by @kerryarchibald.

OIDC: add `prompt` param to auth url creation

---

package.json
spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
src/rust-crypto/OutgoingRequestProcessor.ts
yarn.lock

Fixes https://github.com/vector-im/element-web/issues/26382
---

 Bump wasm bindings version to 2.1.0

---

package.json
yarn.lock

... for recent changes including a fix to a panic
---

Bump matrix-sdk-crypto-wasm to 2.1.1

---

spec/integ/crypto/crypto.spec.ts
src/rust-crypto/rust-crypto.ts

Fixes the second half of vector-im/element-web#26272
---
* Element-R: silence log errors when viewing a pending event ([\#3824](https://github.com/matrix-org/matrix-js-sdk/pull/3824)).

Element-R: silence log errors when viewing a pending event

---

package.json
spec/unit/rust-crypto/rust-crypto.spec.ts
src/crypto-api.ts
src/rust-crypto/rust-crypto.ts
yarn.lock

---
* Element-R: Add the git sha of the binding crate to `CryptoApi#getVersion` ([\#3838](https://github.com/matrix-org/matrix-js-sdk/pull/3838)). Contributed by @florianduros.

Element-R: Add the git sha of the binding crate to `CryptoApi#getVersion`

---

.github/workflows/release-action.yml
.github/workflows/release.yml

Make release automation reusable and add dependency upgrade support

---

.github/workflows/release-action.yml
.github/workflows/release-gitflow.yml
post-release.sh
release.sh
scripts/release/post-merge-master.sh
scripts/release/pre-release.sh

Split out from https://github.com/matrix-org/matrix-js-sdk/pull/3852 to aid review
---

Tidy release automation

---

.github/workflows/docs-pr-netlify.yaml

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/3891
---

Specify the correct environment for the docs builder workflow

---

.github/workflows/cypress.yml

Requires https://github.com/matrix-org/matrix-react-sdk/pull/11973
---

Fix broken downstream cypress tests

---

src/rust-crypto/backup.ts

fix uncaught exceptions in Backup Loop for rust sdk

---

.github/workflows/cypress.yml
.github/workflows/sonarcloud.yml
.github/workflows/tests.yml

Update Sibz/github-status-action to use node16 to silence warning

---

package.json
src/rust-crypto/rust-crypto.ts
yarn.lock

Fixes https://github.com/vector-im/element-web/issues/26488
---

Bump `matrix-rust-sdk-crypto-wasm` to v3.2.0

---

.github/workflows/cypress.yml

Requires https://github.com/matrix-org/matrix-react-sdk/pull/11959
---

Run matrix-react-sdk playwright tests downstream

---

package.json
yarn.lock

Bump matrix-sdk-crypto-wasm to 3.4.0

---

src/http-api/index.ts

Fixes #3917
---
* Fix upload with empty Content-Type ([\#3918](https://github.com/matrix-org/matrix-js-sdk/pull/3918)). Fixes undefined/matrix-js-sdk#3917. Contributed by @JakubOnderka.

Fix upload with empty Content-Type

---

src/client.ts

...for when we ignore events that don't appear in the room timeline
---

Include event & room ID in log line

---

src/rust-crypto/index.ts

Fixes https://github.com/vector-im/element-web/issues/26524
---
* Element-R: disable sending room key requests ([\#3939](https://github.com/matrix-org/matrix-js-sdk/pull/3939)). Fixes vector-im/element-web#26524.

Element-R: disable sending room key requests

---

package.json
yarn.lock

Should provide the fix for https://github.com/element-hq/element-web/issues/26488
---

Bump matrix-sdk-crypto-wasm to 3.5.0

---

src/rust-crypto/OutgoingRequestProcessor.ts
src/rust-crypto/OutgoingRequestsManager.ts
src/rust-crypto/RoomEncryptor.ts
src/rust-crypto/backup.ts
src/rust-crypto/rust-crypto.ts
src/utils.ts

Add some logs to display the duration of key operations of the rust-sdk
---

Add some perfomance logs

---

spec/integ/crypto/crypto.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/rust-crypto/backup.ts
src/rust-crypto/index.ts
src/rust-crypto/rust-crypto.ts

A series of non-functional (or minor logging changes) in preparation for https://github.com/matrix-org/matrix-js-sdk/issues/3964
---

Groundwork for supporting migration from libolm to rust crypto.

---

package.json
yarn.lock

Fixes https://github.com/element-hq/element-web/issues/26782. among other things.
---

Bump matrix-sdk-crypto-wasm to 3.6.0

---

package.json
yarn.lock

To pick up fix to https://github.com/dumbmatter/fakeIndexedDB/issues/94
---

bump fake-indexeddb

---

.github/CODEOWNERS

Add CODEOWNERS entries for crypto stuff

---

.github/workflows/docs-pr-netlify.yaml
.github/workflows/sonarcloud.yml
.github/workflows/static_analysis.yml
.github/workflows/tests.yml

Use Github Artifacts v4

---

package.json
yarn.lock

I have some other changes in the pipeline which will need this bump.
---

Update `matrix-rust-sdk-crypto-wasm` to 4.1.0

---

spec/unit/matrix-client.spec.ts
spec/unit/queueToDevice.spec.ts
src/client.ts
src/models/event.ts

A series of commits to try and bring this code into the 21st century. Suggest review commit-by-commit.
~~Based on https://github.com/matrix-org/matrix-js-sdk/pull/4030.~~
---

Refactor `MatrixClient.encryptAndSendEvent`

---

spec/integ/crypto/rust-crypto.spec.ts
src/crypto/store/base.ts
src/rust-crypto/index.ts
src/rust-crypto/libolm_migration.ts

Fixes: https://github.com/element-hq/element-web/issues/26820, https://github.com/element-hq/element-web/issues/26678
---
* Element-R: support for migration of the room list from legacy crypto ([\#4036](https://github.com/matrix-org/matrix-js-sdk/pull/4036)). Fixes element-hq/element-web#26820.

Element-R: support for migration of the room list from legacy crypto

---

package.json
yarn.lock

Fixes https://github.com/element-hq/element-web/issues/26930
---
* Dependencies: Bump wasm bindings version to 4.3.0 ([\#4042](https://github.com/matrix-org/matrix-js-sdk/pull/4042)). Fixes element-hq/element-web#26930.

Dependencies: Bump wasm bindings version to 4.3.0

---

src/rust-crypto/libolm_migration.ts

Fixes https://github.com/element-hq/element-web/issues/26935
---
* WebR: migrate the megolm session imported flag ([\#4037](https://github.com/matrix-org/matrix-js-sdk/pull/4037)). Fixes element-hq/element-web#26935.

WebR: migrate the megolm session imported flag

---

spec/unit/oidc/register.spec.ts
src/@types/common.ts
src/matrix.ts
src/oidc/register.ts

---
* Allow specifying more OIDC client metadata for dynamic registration ([\#4070](https://github.com/matrix-org/matrix-js-sdk/pull/4070)).

Allow specifying more OIDC client metadata for dynamic registration

---

src/models/thread.ts

And remove line that set it for it to just get overwritten

Update stale comment

---

spec/unit/pushprocessor.spec.ts
src/pushprocessor.ts

Fix merging of default push rules
(cherry picked from commit 78a225795bb99d44f7ae04f408a9c0213d7c2c47)

Fix merging of default push rules (backport)

---

package.json
yarn.lock

I have some other changes in the pipeline which need this bump.

Update matrix-rust-sdk-crypto-wasm to 4.9.0

---

.github/workflows/downstream-end-to-end-tests.yml

and apply the least privilege principle

Simplify Playwright CI

---

src/client.ts

Fixes https://github.com/element-hq/element-web/issues/27379

Fix sendEventHttpRequest for `m.room.redaction` events without `redacts`

---

src/interactive-auth.ts

Fixes https://github.com/element-hq/element-web/issues/26627
Regressed by https://github.com/matrix-org/matrix-js-sdk/pull/1791

Only pass id_server if we had one to begin with

---

src/rust-crypto/rust-crypto.ts

There is some logic to the ordering of this file, and it had got out of sync recently.
No code changes here, just reordering.

RustCrypto: fix ordering of methods

---

.eslintrc.js
spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/utils.ts

https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate#browser_compatibility

Replace usages of setImmediate with setTimeout for wider compatibility

---

src/client.ts
src/embedded.ts
src/matrixrtc/MatrixRTCSession.ts

This is used to load the focus from the well known in elment-call.

Add fetching the well known in embedded mode.

---

src/rust-crypto/rust-crypto.ts

We had both an `onIncomingKeyVerificationRequest` and an `onKeyVerificationRequest` which did different, but related, things.
Improve the documentation and reduce the duplication.

Rust crypto: Clean up handling of verification events

---

yarn.lock

Bump matrix-rust-sdk to 6.2.1
Fixes https://github.com/element-hq/element-web/issues/27666

Fix "Unable to restore session" error

---

spec/unit/oidc/authorize.spec.ts
src/crypto/aes.ts
src/crypto/backup.ts
src/crypto/crypto.ts
src/crypto/key_passphrase.ts
src/crypto/verification/QRCode.ts
src/oidc/authorize.ts
src/randomstring.ts
src/rendezvous/channels/MSC3903ECDHv2RendezvousChannel.ts
src/rust-crypto/DehydratedDeviceManager.ts
src/rust-crypto/rust-crypto.ts

These aren't needed these days.
Reviewable commit-by-commit.

Remove `crypto` shims

---

package.json
src/rust-crypto/RoomEncryptor.ts
yarn.lock

Fixes: https://github.com/matrix-org/matrix-js-sdk/issues/4312

Bump rust sdk wasm version to 7.0.0

---

src/matrixrtc/MatrixRTCSession.ts
src/matrixrtc/MatrixRTCSessionManager.ts

Use prefixed loggers for MatrixRTC

---

.github/workflows/downstream-end-to-end-tests.yml
.github/workflows/notify-downstream.yaml
.github/workflows/release.yml
.github/workflows/tests.yml

Replace `matrix.org/matrix-react-sdk` with `element-hq/matrix-react-sdk` in CI

---

.github/workflows/sonarcloud.yml

Update sonarcloud action to use v3.3 `matrix-org/sonarcloud-workflow-action`

---

src/matrix.ts

Deprecate top level crypto events re-export

Deprecate top level crypto events re-export

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts

None of the tests themselves should have changed

Organise MatrixRTCSession tests

---

.github/workflows/release-gitflow.yml

of not needing to reset package to `#develop`

Fix gitflow workflow not handling edge case

---

spec/unit/embedded.spec.ts
src/embedded.ts

Add RoomWidgetClient.sendToDeviceViaWidgetApi()

---

src/models/room.ts

Reduce cognitive complexity of Room.addLiveEvents()

---

.github/workflows/release-make.yml

Fixes https://github.com/element-hq/wat-internal/issues/18

Prevent releases when release blockers exist

---

spec/unit/oidc/validate.spec.ts
src/oidc/validate.ts

Renaming source branch closed the PR. See the discussion at: #4582

Handle when aud OIDC claim is an Array

---

package.json
yarn.lock

It appears to "just work"... but I might be missing something

Update matrix-sdk-crypto-wasm to 12.0.0

---

package.json
yarn.lock

... to fix https://github.com/matrix-org/matrix-rust-sdk/issues/4424
Notes: Fix a bug which could prevent loading stored crypto state from storage.

Upgrade matrix-sdk-crypto-wasm to 1.11.0

---

package.json
yarn.lock

... to fix https://github.com/matrix-org/matrix-rust-sdk/issues/4424

Upgrade matrix-sdk-crypto-wasm to 12.1.0

---

spec/integ/matrix-client-syncing.spec.ts

Use rust crypto instead of legacy crypto in sync tests

Use rust crypto instead of legacy crypto in sync tests

---

src/@types/matrix-sdk-crypto-wasm.d.ts
src/rust-crypto/CrossSigningIdentity.ts

check that `importCrossSigningKeys` has actually worked

Add an extra consistency check in `bootstrapCrossSigning`

---

.eslintrc.cjs
spec/test-utils/webrtc.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/@types/common.ts
src/@types/event.ts
src/@types/extensible_events.ts
src/@types/global.d.ts
src/@types/polls.ts
src/client.ts
src/crypto-api/CryptoEventHandlerMap.ts
src/crypto/EncryptionSetup.ts
src/crypto/OutgoingRoomKeyRequestManager.ts
src/embedded.ts
src/http-api/fetch.ts
src/interactive-auth.ts
src/matrixrtc/MembershipManager.ts
src/models/MSC3089TreeSpace.ts
src/models/event.ts
src/secret-storage.ts
src/sliding-sync.ts

To avoid the footgun that is https://www.totaltypescript.com/the-empty-object-type-in-typescript

Apply lint rule @typescript-eslint/no-empty-object-type

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/crypto-api/index.ts
src/rust-crypto/backup.ts
src/rust-crypto/rust-crypto.ts

Fixes #4703
Signed-off-by: Ajay Bura [ajbura@gmail.com](mailto:ajbura@gmail.com)

Report backup key import progress on start and improve types

---

.eslintrc.cjs
src/matrixrtc/EncryptionManager.ts
src/matrixrtc/MatrixRTCSession.ts
src/matrixrtc/MatrixRTCSessionManager.ts
src/matrixrtc/MembershipManager.ts

MatrixRTC: enforce Promise handling using eslint rules

---

package.json

Fix package.json repository.url

---

spec/unit/oidc/register.spec.ts
src/oidc/register.ts

As per discussion and amendment to https://github.com/matrix-org/matrix-spec-proposals/pull/2966

Allow port differing in OIDC dynamic registration URIs

---

src/client.ts
src/pushprocessor.ts

Element Web has a duplicate of this method without caching

Export push processor & method for converting matrix glob to regexp

---

src/rust-crypto/rust-crypto.ts

Duplicate added in https://github.com/matrix-org/matrix-js-sdk/pull/4772

Remove duplicate `deleteSecretStorage` in `RustCrypto.resetEncryption`

---

src/crypto/store/indexeddb-crypto-store.ts

Fixes https://github.com/element-hq/element-web/issues/12555

Fix fallback to MemoryCryptoStore when LocalStorage unavailable

---

spec/unit/http-api/fetch.spec.ts
src/http-api/fetch.ts

Fixes https://github.com/element-hq/element-web/issues/29588

Fix token refresh racing with other requests and not using new token

---

.github/workflows/release-make.yml

Reverts matrix-org/matrix-js-sdk#4784
This failed on https://github.com/element-hq/packages.element.io/actions

Revert "Load gpg key without external action"

---

spec/unit/rust-crypto/verification.spec.ts
src/rust-crypto/rust-crypto.ts
src/rust-crypto/verification.ts

... in an attempt to figure out what might have caused a spurious cancellation today

Write a log line when cancelling verification

---

package.json
spec/integ/crypto/verification.spec.ts
src/matrixrtc/EncryptionManager.ts
src/matrixrtc/MatrixRTCSession.ts
tsconfig.json

Switch typescript lib to es2024 and make necessary type changes
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/4796

Update to Node 22 LTS

---

src/autodiscovery.ts

Fixes https://github.com/element-hq/element-web/issues/11136
https://spec.matrix.org/v1.14/client-server-api/#server-discovery

Fix autodiscovery handling of 2xx (non-200) codes

---

src/NamespacedValue.ts

Fixes #4924
```
Signed-off-by: Alex Tori <toriningen.me@gmail.com>
```

Fix deep import incompatibility (#4924)

---

spec/integ/crypto/crypto.spec.ts
spec/unit/matrix-client.spec.ts
spec/unit/models/event.spec.ts
src/@types/uia.ts
src/client.ts
src/crypto-api/index.ts
src/crypto-api/verification.ts
src/event-mapper.ts
src/matrixrtc/MatrixRTCSession.ts
src/matrixrtc/MembershipManager.ts
src/models/event.ts
src/models/room.ts
src/utils.ts

Remove deprecated fields, methods, utilities

---

spec/integ/crypto/crypto.spec.ts
spec/unit/http-api/fetch.spec.ts
spec/unit/http-api/index.spec.ts
spec/unit/matrix-client.spec.ts
spec/unit/models/event.spec.ts
src/@types/requests.ts
src/@types/uia.ts
src/client.ts
src/crypto-api/index.ts
src/crypto-api/verification.ts
src/event-mapper.ts
src/http-api/fetch.ts
src/http-api/index.ts
src/http-api/interface.ts
src/matrixrtc/MatrixRTCSession.ts
src/matrixrtc/MembershipManager.ts
src/models/event.ts
src/models/room.ts
src/utils.ts

Release tranche of breaking changes

---

knip.ts

Tidy knip config
