matrix-org/matrix-js-sdk

lib/matrix.js
Adds support for new v2 endpoints.
=> add API endpoints for getting & adding 3pids

lib/client.js, lib/http-api.js, lib/models/room-member.js
Also fix some c+p bugs in client
=> Move getAvatarUrl method to client so it can do mxc -> http uri conversion

lib/client.js
This is with reference to the SAML2 work on Synapse
Sign-off: Muthu Subramanian <muthu.subramanian.karunanidhi@ericsson.com>
=> Add SAML2 login method helper

lib/models/room.js
=> Add getMembersWithMembership to get all members with given membership

lib/client.js, lib/webrtc/call.js
Basic screen-sharing support; adds a screensharing stream into the call and adds support for playback of both an audio-only stream (i.e. the voice-over) alongside an AV stream like the screenshare.
=> Screen sharing

lib/client.js
Fixes https://github.com/vector-im/vector-web/issues/276
The diff looks 'orrid, it's literally just an indent block :(
=> Wrap /events response processing in a try/catch

lib/client.js, lib/models/room.js, lib/utils.js
* Inject implicit read receipts into the timeline
* Twiddle local echo a bit to make the implicit receipts match the various different stages of local echo.
=> Implicit read receipts

lib/client.js, lib/http-api.js
Update the CAS login flow to allow the HS to do all the interaction with CAS and use the HS token login
=> SH - CAS / Login token login

lib/client.js, lib/models/room.js, spec/unit/room.spec.js
WIP of room tag support (needs tests)
=> Room tag support

lib/client.js, spec/unit/matrix-client.spec.js
In accordance with http://matrix.org/speculator/spec/head#third-party-invites
=> Invite by 3PID endpoint

lib/client.js, lib/filter.js, lib/matrix.js, lib/store/memory.js, lib/store/stub.js, lib/store/webstorage.js, spec/integ/matrix-client-methods.spec.js, spec/unit/filter.spec.js
With UTs and integration tests. This does not do `/sync` yet.
=> Support v2 filters

lib/client.js, lib/models/event.js, lib/models/room-state.js, lib/models/room.js, lib/store/memory.js, lib/store/stub.js, lib/sync.js
- Added methods to manage push rules
- Fixed sync.js that clobbered client.pushRules
=> Push rules settings

lib/models/user.js, lib/store/memory.js
Regardless of presence events.
=> Make getUsers() return users for *EEEEEVERYOOOOONE*

lib/client.js, lib/models/room.js
Fixes https://github.com/vector-im/vector-web/issues/623
=> Add local echo for read receipts.

lib/matrix.js, lib/timeline-window.js, spec/unit/timeline-window.spec.js
A handy thing for tracking a window into a room timeline, for use with non-contiguous timelines (#63).
Could really do with some unit tests... sorry.
=> TimelineWindow object

lib/client.js, lib/sync.js
Also add a stop method to stop syncing.
Should be functionally identical outside of client and sync.
=> Change the sync state tracking slightly to gut-wrench client a bit less

lib/models/room.js
Store real receipts separately to make this work.
=> Add a param to getEventReadUpTo to have it ignore implicit read receipts

lib/client.js, lib/http-api.js
(add an option to joinRoom for specifying the signing url)
Also @illicitonion
=> Add support for new keypair style 3pid invites

lib/models/room.js, spec/unit/room.spec.js
Also rename slightly confusingly named member list variables.
=> Use our inviter's member event to get their display name if it exists.

spec/integ/matrix-client-syncing.spec.js
We don't have *any* tests for syncLeftRooms right now, so start one.
=> Add a unit test for syncLeftRooms

lib/sync.js
https://github.com/vector-im/vector-web/issues/780
=> make presence work when peeking.

lib/models/event.js, lib/models/room-member.js, lib/models/room-state.js
Reverts matrix-org/matrix-js-sdk#106
=> Revert "make sure we show display names & avatars on parts, and use the right…"

lib/pushprocessor.js
Fixes https://github.com/vector-im/vector-web/issues/1067
=> Only count joined members for the member count in notifications.

lib/sync.js, lib/utils.js, spec/unit/utils.spec.js
Fix the object comparison used for client filters (JSON.stringify is
non-deterministic)
=> Fix a bug where we recreated sync filters

lib/client.js
Requires https://github.com/matrix-org/synapse/pull/716 for the methods to work
Get pusher API added in https://github.com/matrix-org/matrix-doc/pull/308/files
=> Add methods to get (and set) pushers

lib/OlmDevice.js, lib/client.js, spec/MockStorageApi.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-methods.spec.js, spec/unit/webstorage.spec.js
A bunch of work to try and clean up some of the crypto code in MatrixClient.
Best reviewed commit by commit.
=> Various matrix-client refactorings and fixes

CHANGELOG.md, lib/client.js
As per https://github.com/matrix-org/matrix-doc/pull/346/files
=> Add API calls for other requestToken endpoints

lib/client.js
This would cause the request to 400 in the new vector that opens after you clicked the link in the email, as per the comment.
=> Fix email registration

lib/base-apis.js
You missed my deliberate mistake! This was needed for
https://github.com/matrix-org/matrix-react-sdk/pull/370
=> Wrappers for devices API

lib/base-apis.js, lib/client.js, lib/crypto.js, spec/integ/matrix-client-methods.spec.js
Introduce a new Crypto class which encapsulates all of the the crypto-related gubbins, replacing it with thin wrappers in MatrixClient.
I don't know if this is in any way reviewable :/
=> Factor crypto stuff out of MatrixClient

lib/OlmDevice.js, lib/crypto.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-methods.spec.js
Check the signature on downloaded e2e keys, and ignore those that don't match.
=> Verify e2e keys on download

lib/models/room-member.js, spec/unit/room-member.spec.js
So testing truthiness will lead to incorrect behaviour.
https://github.com/vector-im/vector-web/issues/1620
=> Zero is a valid power level

lib/sync.js
I think this was only a problem in the edgiest of edge conditions, but it
certainly didn't look right.
=> Make sure we actually stop the sync loop on logout

lib/pushprocessor.js, lib/sync.js
Also expose a useful function from pushprocessor.
Fixes https://github.com/vector-im/vector-web/issues/1495
=> Update our push rules when they come down stream

lib/client.js, lib/crypto-algorithms/base.js, lib/crypto-algorithms/megolm.js, lib/crypto-algorithms/olm.js, lib/crypto.js, lib/models/event.js, lib/models/room.js, spec/integ/matrix-client-retrying.spec.js
We're going to need to send out a load of messages to distribute the megolm
keys; as a first step, deal with the asynchronicity this will require.
=> Make encryption asynchronous

lib/crypto-deviceinfo.js, lib/crypto.js
mostly because I'm fed up with hacking around the fact that DeviceVerification is hard to get at.
=> Move DeviceInfo and DeviceVerification to separate module

lib/crypto-algorithms/base.js, lib/crypto-algorithms/megolm.js, lib/crypto-algorithms/olm.js, lib/crypto.js
For now, pending the arrival of SPEC-138, this happens via inline messages in the room.
(Requires https://github.com/matrix-org/matrix-js-sdk/pull/178)
=> Send out megolm keys when we start a megolm session

lib/client.js, lib/crypto-algorithms/base.js, lib/crypto-algorithms/megolm.js, lib/crypto.js, lib/models/event.js
This is incredibly hacky at the moment, pending the arrival of ephemeral
events, but it kinda works.
=> support for unpacking megolm keys

lib/crypto-algorithms/megolm.js
Avoid hitting the rate-limiter by putting all of the megolm keys in a single
event.
=> Put all of the megolm keys in one room message

README.md
We are no longer adding callback arguments as a matter of course.
=> README: callbacks deprecated

lib/client.js, lib/crypto.js
Move the event-handler registration from client.js into crypto.js
=> Refactor event handling in Crypto

lib/crypto/OlmDevice.js, lib/crypto/algorithms/base.js, lib/crypto/algorithms/index.js, lib/crypto/algorithms/megolm.js, lib/crypto/algorithms/olm.js, lib/crypto/deviceinfo.js, lib/crypto/index.js, lib/crypto/olmlib.js
It was getting a bit sprawly; this should help keep things together.
=> Move crypto bits into a subdirectory

lib/client.js
This should fix vector-im/vector-web#2204
=> Check if we need to upload new one-time keys every 10 minutes

lib/crypto/index.js, lib/models/event.js
Should fix vector-im/vector-web#2232
=> Include keysProved and keysClaimed in the local echo for events we send.

lib/client.js, lib/crypto/index.js
a function to get information about the device which sent an event, for the benefit of the EncryptionDialog thing
=> Add MatrixClient.getEventSenderDeviceInfo()

lib/base-apis.js, spec/integ/matrix-client-methods.spec.js
Allow app to pass in an auth dict on delete device
=> Support User-Interactive auth for delete device

lib/client.js
As per: http://matrix.org/docs/spec/client_server/r0.2.0.html#get-matrix-client-r0-user-userid-rooms-roomid-tags
=> Add getRoomTags method to client

lib/crypto/index.js
This might help diagnose Erik/Matthew's comms breakdown.
=> Log to the console on unknown session

lib/client.js, lib/crypto/index.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/megolm.spec.js, spec/test-utils.js
Fixes https://github.com/vector-im/vector-web/issues/2275, though more usefully it lays some groundwork for other changes
=> distinguish unknown users from deviceless users

lib/crypto/algorithms/olm.js
Now that the mobile clients have been updated to send the right fields, enforce
their correctness on the recipient side.
=> Apply unknown-keyshare mitigations

lib/client.js, lib/crypto/algorithms/megolm.js, lib/crypto/index.js
Attempt to make the decryption errors less obscure
=> Improve decryption error messages

lib/crypto/index.js, spec/integ/megolm.spec.js
When we send a megolm message, wait for any existing key download to complete.
=> e2e: Wait for pending device lists

lib/crypto/index.js
This is no longer used; remove it.
=> Remove dead _sendPingToDevice function

lib/crypto/OlmDevice.js
... to give better error messages.
=> Sanity check payload length before encrypting

lib/base-apis.js
Uses https://github.com/matrix-org/synapse/pull/1714
=> Add API to delete threepid

lib/client.js
There are users presence subscription methods in matrix specs, I've added methods that allows us to get user presence list, add users there and drop them from there.
=> User presence list feature

package.json, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-event-timeline.spec.js, spec/integ/matrix-client-methods.spec.js, spec/integ/matrix-client-opts.spec.js, spec/integ/matrix-client-retrying.spec.js, spec/integ/matrix-client-room-timeline.spec.js, spec/integ/matrix-client-syncing.spec.js, spec/integ/megolm.spec.js, spec/mock-request.js, spec/unit/realtime-callbacks.spec.js, spec/unit/scheduler.spec.js, spec/unit/timeline-window.spec.js, spec/unit/utils.spec.js
=> Fix linting on all tests

package.json, spec/integ/megolm.spec.js, spec/test-utils.js, src/client.js, src/crypto/OlmDevice.js, src/crypto/algorithms/base.js, src/crypto/algorithms/megolm.js, src/crypto/index.js, src/store/session/webstorage.js
Add a couple of functions to MatrixClient to import and export the megolm data.
Requires a development libolm.
=> Support for importing and exporting megolm sessions

spec/integ/matrix-client-methods.spec.js, src/crypto/DeviceList.js, src/crypto/index.js
Only permit one query per user at a time.
Builds on top of https://github.com/matrix-org/matrix-js-sdk/pull/346.
=> Rewrite the device key query logic

spec/integ/megolm.spec.js, src/crypto/algorithms/megolm.js
Re-fixes https://github.com/vector-im/riot-web/issues/2273.
And test it this time.
=> Fix decryption of events whose key arrives later

src/models/event.js
to say that sender won't always be set
=> Add docs to event

jenkins.sh, package.json
* don't try to run npm under istanbul
* use _mocha instead of mocha because https://github.com/gotwarlost/istanbul/issues/44#issuecomment-16093330
Also:
* write a text report for better travis
* On jenkins, clear out old coverage reports so that we don't pick up last time's.
=> Make test coverage work again

src/interactive-auth.js
As commented, this isn't really the best way to do this, it just happens to be the only way it can fail right now, and doing it properly is a reasonable chunk of work that it doesn't necessarily make sense to be doing right now. Reckon this is OK for now?
=> Give a better error message if the HS doesn't support msisdn registeration

CONTRIBUTING.rst
=> Add a CONTRIBUTING for js-sdk

src/store/indexeddb-local-backend.js, src/store/indexeddb.js
Now the backend drives the sync accumulator as well. Also moves
the backend out to a separate file.
=> Move more functionality to the indexeddb backend

package.json
for matrix-org/matrix-appservice-irc#359
=> Update istanbul to remove minimatch DoS Warning

src/matrix.js, src/webrtc/call.js
=> ability to specify webrtc audio/video inputs for the lib to request

src/client.js
... I'm amazed we got this far without it.
=> MatrixClient: add getUserId()

package.json, src/models/room.js, src/reemit.js, src/sync.js
and rewrite it to use modern JS while we're at it
=> Factor out reEmit to a common module

src/crypto/store/indexeddb-crypto-store.js
Add an `onversionchange` listener to close the db, so that we can delete it
without blocking.
=> indexeddb-crypto-store: fix db deletion

src/crypto/OutgoingRoomKeyRequestManager.js, src/crypto/algorithms/megolm.js, src/crypto/index.js
When we receive a room key, cancel any pending requests we have open for that
key.
=> Send a cancellation for room key requests

src/client.js, src/crypto/DeviceList.js, src/crypto/algorithms/megolm.js, src/models/room.js
In an attempt to diagnose https://github.com/vector-im/riot-web/issues/4278,
add some debug to make the rageshakes more useful.
=> Add a bunch of logging around sending messages

src/store/indexeddb-local-backend.js, src/store/indexeddb.js
- to help understand when it gets stuck in tests
=> Improve error reporting from indexeddbstore.clearDatabase

spec/integ/matrix-client-event-timeline.spec.js
startClient was written in such a way that it would leave a flush() running,
which could sometimes interfere with the rest of the test (or even subsequent
tests), causing sporadic test failures. Make sure that the flush completes
before we move on.
Fix a test which turned out to be relying on that behaviour (there was a flush
which ended up being a no-op, thus effectively inserting a pause allowing the
sync promise to complete.
Fix a beforeEach handler which was relying on startClient resolving to
undefined.
=> Fix a race in a test

browser-index.js
If we don't have indexeddb at all, don't try to make an indexeddb crypto store.
=> Fix failure on Tor browser

src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js
If we get an error when connecting to th indexeddb, fall back to a
MemoryCryptoStore.
This takes a bit of reorganising, because we don't get the error until we try
to connect to the database.
=> Fall back to MemoryCryptoStore if indexeddb fails

src/base-apis.js
Includes https://github.com/matrix-org/matrix-js-sdk/pull/476
=> Implement 'joined_groups' API

package.json
... to run the tests in a loop.
=> Add test:watch script

spec/integ/megolm-integ.spec.js
switch a bunch of `flush()`es to `flushAllExpected()`s
=> Fix some more flakey tests

src/base-apis.js
Set profile for https://github.com/matrix-org/matrix-react-sdk/pull/1229 and also get users because I'll need it soon
=> Add more group APIs

src/store/indexeddb-local-backend.js, src/store/indexeddb.js
In an attempt to see why our tests sometimes time out, add a load of logging to
confirm exactly where it is happening.
(I'll probably revert this once I see the effects)
=> Verbose logging to see what's up with indexeddb

spec/integ/matrix-client-crypto.spec.js, spec/unit/crypto/algorithms/megolm.spec.js, src/client.js, src/crypto/algorithms/base.js, src/crypto/algorithms/megolm.js, src/crypto/algorithms/olm.js, src/crypto/index.js, src/models/event.js
Once everything moves to indexeddb, it's going to require callbacks and the like, so let's make the decrypt API asynchronous in preparation.
(There are two commits here; they should make sense independently)
=> Let event decryption be asynchronous

spec/TestClient.js, src/client.js, src/crypto/index.js
There are 6 commits here, each making a different method asynchronous, and updating its callsites.
It depends on https://github.com/matrix-org/matrix-js-sdk/pull/508 to build.
=> Make a load of methods in the 'Crypto' module asynchronous

src/crypto/DeviceList.js
* DeviceList._updateStoredDeviceKeysForUser
* DeviceList._processQueryResponseForUser
* DeviceList._storeDeviceKeys
=> Make some of DeviceList asynchronous

spec/unit/crypto/algorithms/megolm.spec.js, src/crypto/DeviceList.js, src/crypto/algorithms/megolm.js, src/crypto/algorithms/olm.js, src/crypto/olmlib.js
(This won't build until #520 lands)
=> Make bits of `olmlib` asynchronous

package.json
Because of https://github.com/jsdoc3/jsdoc/issues/1438
=> Upgrade to jsdoc 3.5.5

src/base-apis.js
For https://github.com/matrix-org/matrix-react-sdk/pull/1406
=> Implement wrapper APIs for adding rooms to group summary

src/crypto/DeviceList.js
(... and hence stuck outgoing e2e messages)
Fixes https://github.com/vector-im/riot-web/issues/4278
=> Fix typo which resulted in stuck key download requests

src/crypto/index.js
set the decrypted data to an empty message
Signed-off-by: Hubert Chathi <hubert@uhoreg.ca>
=> don't try to decrypt a redacted message (fixes vector-im/riot-web#3744)

src/models/room-state.js, src/pushprocessor.js
And make pushprocessor use this function
=> Function for working out notif trigger permission

src/pushprocessor.js
This exposes a function to get rules by their ID and
ruleMatchesEvent to test whether a rule matches a given event.
=> Expose more functionality of pushprocessor

src/sync.js
As hopefully explained in the comment
=> Ignore pushrules in our cached sync response

src/crypto/OlmDevice.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js
Don't migrate sessions from localstorage if we already have some
in indexeddb
=> Check for sessions in indexeddb before migrating

src/pushprocessor.js
by not [re]creating RegExps unnecessarily.
=> Optimise pushprocessor

src/crypto/store/indexeddb-crypto-store-backend.js
instead of onsuccess for the txn to add an outgoing room key request.
=> Fix bug in crypto-store-backend; use oncomplete

src/client.js
Because it does some nice caching stuff but that's no good if we
re-create a new one each time.
=> Keep a push processor and re-use it.

spec/unit/matrix-client.spec.js, src/store/indexeddb-local-backend.js, src/store/indexeddb-remote-backend.js, src/store/indexeddb-store-worker.js, src/store/indexeddb.js, src/store/memory.js, src/store/stub.js, src/sync-accumulator.js, src/sync.js
So it can run while we process our sync data.
=> Start first incremental sync request early

src/crypto/index.js, src/crypto/store/indexeddb-crypto-store.js
=> Disable crypto if indexeddb version too new

src/client.js
and replace it with a nice comment
=> Remove not very useful but veryv spammy log line

src/base-apis.js
Needed for new "joinable" groups.
=> Add wrapper for group join API

src/crypto/store/indexeddb-crypto-store-backend.js
As we appear to be getting this error after an e2e upgrade and I want to try & track it down
=> Log IDB errors

src/client.js
=> fix some documentation typos

src/models/room.js
Signed-off-by: Michael Telatynski 7t3chguy@gmail.com
See https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/models/event-timeline.js#L165-L167
=> arguments true and false are actually invalid

src/matrix.js
=> export the Group model class

src/models/room-state.js
as the room state code changed considerably, back-port #673
=> back-port infinite spinner fix for lazy loading

src/sync.js
We do this in other places, but not here
For https://github.com/matrix-org/matrix-react-sdk/pull/2108
=> Send sync error to listener

src/client.js, src/sync.js
To get additional information about the sync state (ie. the error
object).
=> Add getSyncStateData()

src/client.js
=> Lazy loading: lazy load members when request context around an event

src/client.js
as per https://github.com/matrix-org/synapse/commit/e235005be68ee52680110c5bf0a1e20d17f52fb0
=> Lazy loading: check with server for feature support

src/base-apis.js, src/client.js
Use case for this is so bridges can pull out events from replies without all the guff around timelines and contexts.
=> Api to fetch events via /room/.../event/..

src/client.js
To hide rooms that have been replaced
For https://github.com/vector-im/riot-web/issues/7164
=> Add getVisibleRooms()

src/models/room.js
Ready for first review, but need to test and fix lints and stuff first, so don't merge yet.
=> Fix DM avatar

src/client.js, src/crypto/algorithms/megolm.js, src/crypto/index.js
To make debugging crypto slightly faster
=> Pass through function to discard megolm session

src/models/room.js
Merge https://github.com/matrix-org/matrix-js-sdk/pull/708 into release
=> Fix for "otherMember.getAvatarUrl is not a function"

src/client.js
Needed for https://github.com/matrix-org/matrix-react-sdk/pull/2139
=> Add method to query LL state in client

src/models/room-state.js, src/models/room.js, src/store/indexeddb-local-backend.js, src/store/indexeddb-remote-backend.js, src/store/indexeddb-store-worker.js, src/store/indexeddb.js, src/store/stub.js, src/sync.js
Fixes https://github.com/vector-im/riot-web/issues/7226, but needs more testing so don't merge yet.
=> Remove lazy loaded members when leaving room

spec/unit/room.spec.js, src/models/room.js
Required by https://github.com/matrix-org/matrix-react-sdk/pull/2146
=> Fixes for room.guessDMUserId

src/models/room.js
this can easily add up to 100ms / 1000 of members
=> dont wait for LL members to be stored to resolve the members

spec/unit/room.spec.js, src/models/room.js
Fixes https://github.com/vector-im/riot-web/issues/7323
=> room name should only take canonical alias into account

src/client.js
Reverts matrix-org/matrix-js-sdk#644
accidentally went to master
=> Revert "Add getMediaLimits to client"

spec/unit/room-member.spec.js, spec/unit/room-state.spec.js, src/models/room-member.js, src/models/room-state.js
Fixes https://github.com/vector-im/riot-web/issues/7450
=> never replace /sync'ed memberships with OOB ones

package.json, src/crypto/DeviceList.js, src/crypto/OlmDevice.js, src/crypto/OutgoingRoomKeyRequestManager.js, src/crypto/algorithms/megolm.js, src/crypto/algorithms/olm.js, src/crypto/index.js, src/crypto/olmlib.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js, src/logger.js
I am not sure, what the guidelines regarding merges are here. Should I squash my changes?
There are more places where `console` is used. I can take another round if this gets accepted. Or open another ticket.
Since megolm isn't installed, I am not :100:% sure, this does not break. However, I used `loglevel` in the past and pretty sure, this should work :crossed_fingers: (hoping your CI will catch it if not).
The tests were broken before I even started, though :disappointed:
=> Logging lib. Fixes #332

src/sync.js
this will avoid all members for all crypto rooms being downloaded on initial sync.
=> Fix: correctly check for crypto being present

spec/unit/crypto/algorithms/olm.spec.js
Megolm has plenty but none for just the olm layer by itself. I
was playing with getting session re-establishment to work and a
unit test came out.
=> A unit test for olm

spec/integ/megolm-integ.spec.js, src/client.js, src/models/room.js
Fixes https://github.com/vector-im/riot-web/issues/5408
=> Prevent messages from being sent if other messages have failed to send

src/base-apis.js, src/client.js, src/models/room.js
=> Support for jump-to-time within a thread

spec/unit/crypto/backup.spec.js
This somehow managed to evade three reviewers. :-/
=> fix some assertions in e2e backup unit test

src/models/room.js
It should fire `Room.localEchoUpdated` event and returns the oldEventId
#645 
Signed-off-by: Leon leon390422914@gmail.com
=> emit oldEventId on "updatePendingEvent"

src/client.js, src/crypto/index.js
Needed for https://github.com/vector-im/riot-web/issues/7815.
Based on work from @dbkr with a few extra tweaks.
=> Emit for key backup failures

CONTRIBUTING.rst
Signed-off-by: Stephen Solka <stephen0q@gmail.com>
=> Contributing: Note that rebase lets you mass signoff commits

CONTRIBUTING.rst, package-lock.json, package.json, spec/unit/room-member.spec.js, src/base-apis.js, src/client.js, src/crypto/index.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js, src/models/room-member.js, src/models/room-state.js, src/models/room.js, src/models/user.js, src/sync.js, src/utils.js
This is a clean merge with no additional changes.
=> Merge develop into experimental

src/crypto/index.js
Add a 'deviceId' property and leave 'device' undefined for unknown
devices.
https://github.com/vector-im/riot-web/issues/8142
=> Include signature info for unknown devices

src/models/room.js
for https://github.com/matrix-org/matrix-react-sdk/pull/2557
=> add method to room to check for unverified devices

spec/unit/crypto/backup.spec.js, src/client.js, src/crypto/index.js, src/store/session/webstorage.js
Trust backups that we've restored by saving the matching pubkey
locally.
NB. Contains technically breaking API changes to the backup restore
(takes backupInfo rather than version).
=> Trust on decrypt

src/client.js, src/crypto/index.js
Also detect when the key backup version changes and do the right
thing
https://github.com/vector-im/riot-web/issues/8524
=> Add method to force re-check of key backup

release.sh
This appears to handle case of versioned and modified a bit better.
=> Try again to commit package-lock.json

src/crypto/verification/SAS.js
fixes https://github.com/vector-im/riot-web/issues/8703
=> speling is hard

src/crypto/DeviceList.js
fixes https://github.com/vector-im/riot-web/issues/8863
=> only set the dirty flag if something was actually changed

spec/unit/crypto.spec.js, src/crypto/OlmDevice.js, src/crypto/algorithms/megolm.js
- don't cancel key requests if we can't decrypt everything in the session
- overwrite the session key if we get a better version
fixes https://github.com/vector-im/riot-web/issues/8793
=> handle partially-shared sessions better

src/crypto/store/indexeddb-crypto-store-backend.js
Masking the original error here:
https://github.com/vector-im/riot-web/issues/7769
Related:
https://github.com/matrix-org/matrix-js-sdk/pull/847
=> Don't swallow txn errors in crypto store

spec/unit/crypto.spec.js, src/crypto/OutgoingRoomKeyRequestManager.js
fixed a typo, and make sure that we use a separate transaction ID
=> More key request fixes

.buildkite/pipeline.yaml, .travis.yml, travis.sh
TODO: Better pipelines (see https://github.com/vector-im/riot-web/issues/9019)
Part of fixing https://github.com/vector-im/riot-web/issues/9164
**Partnered with**:
* https://github.com/matrix-org/matrix-react-sdk/pull/2788
* https://github.com/vector-im/riot-web/pull/9165
=> Use Buildkite for CI

src/crypto/olmlib.js
fixes https://github.com/vector-im/riot-web/issues/9214
=> make sure resolve object is defined before calling it

docs/storage-notes.md
This collects my notes from investigating the state of browser storage as part
of https://github.com/vector-im/riot-web/issues/9109.
=> Add investigation notes for browser storage

src/client.js, src/models/room.js
See https://github.com/vector-im/riot-web/issues/9225
=> Add debugging for spurious room version warnings

src/client.js
Required for https://github.com/vector-im/riot-web/issues/8539
**Please review with https://github.com/matrix-org/matrix-react-sdk/pull/2818**
=> Add functions for getting room upgrade history and leaving those rooms

src/crypto/store/indexeddb-crypto-store.js, src/indexeddb-helpers.js, src/store/indexeddb-local-backend.js, src/store/indexeddb.js
This will be useful for future storage diagnostics as part of vector-im/riot-web#9271.
Used by https://github.com/matrix-org/matrix-react-sdk/pull/2826
=> Add IndexedDB existence checks

src/crypto/store/localStorage-crypto-store.js
This supports additional diagnostics of stores in
https://github.com/vector-im/riot-web/issues/9309.
Used in https://github.com/matrix-org/matrix-react-sdk/pull/2840
=> Add existence check to local storage based crypto store

src/client.js, src/crypto/index.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js
to try & diagnose https://github.com/vector-im/riot-web/issues/7769
=> Add a bunch of logging

src/crypto/index.js
To try & diagnose https://github.com/vector-im/riot-web/issues/9357
=> Key backup logging improvements

src/models/event-timeline-set.js
Should fix the error seen in https://github.com/matrix-org/riot-web-rageshakes/issues/1389 (https://github.com/vector-im/riot-web/issues/8593)
=> Refuse to set forwards pagination token on live timeline

src/sync.js
In https://github.com/vector-im/riot-web/issues/7769, we're seeing sync startup
fail to complete, but the actual error isn't being logged. Hopefully these extra
debug logs will provide more insight into the failing step.
=> Add logging to sync startup path

src/models/room.js
The spec says they are, so we might as well too.
=> Flag v3 rooms as safe

src/autodiscovery.js
Fixes https://github.com/vector-im/riot-web/issues/7925
**Please review with https://github.com/matrix-org/matrix-react-sdk/pull/2916**
=> Expose better autodiscovery error messages

src/base-apis.js
This fixes the issue Calls to /redact are POSTed when they should be PUT according to the spec #881.  Now redact event is a PUT request instead of a POST request. A transaction id is also added.
Signed-off-by: Janith Kasun janithisipathana@gmail.com
----
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/881 (for magic github stuff) ~ TravisR
=> change event redact,  POST request to PUT request

spec/integ/matrix-client-event-emitter.spec.js, spec/unit/autodiscovery.spec.js, src/autodiscovery.js, src/sync.js
=> Fix tests on develop

README.md, package.json, yarn.lock
See https://github.com/vector-im/riot-web/issues/9497
=> Use packages.matrix.org for Olm

src/models/event-timeline-set.js, src/models/event.js, src/models/relations.js, src/models/room.js
This is part of getting encrypted reactions in https://github.com/vector-im/riot-web/issues/9672.
=> Wait until decrypt before aggregating

src/models/event.js
This has been useful while working on encrypted reactions.
=> Add stringify helper to summarise events when debugging

src/crypto/index.js
Still no luck diagnosing https://github.com/vector-im/riot-web/issues/9357
so adding more logging.
=> More logging when signature verification fails

src/models/event.js
to support getting the date for https://github.com/matrix-org/matrix-react-sdk/pull/2990
=> Add method to retrieve replacing event

src/autodiscovery.js
Reverts matrix-org/matrix-js-sdk#927
=> Revert "Add a bunch of debugging to .well-known IS validation"

spec/unit/login.spec.js, src/base-apis.js
Merge https://github.com/matrix-org/matrix-js-sdk/pull/930 to release branch since it's a breaking change.
=> Saves access_token and user_id after login for all login types

src/crypto/verification/Base.js
This is needed for compatibility with cross-signing, because with cross-signing, the client will be asked to verify the cross-signing key, but current clients don't know how to do that, so they should just ignore it rather than failing.
=> verification: don't error if we don't know about some keys

spec/unit/autodiscovery.spec.js, src/autodiscovery.js
See https://github.com/matrix-org/matrix-react-sdk/pull/3067
=> Provide the discovered URLs when a liveliness error occurs

src/interactive-auth.js
On slow networks/servers we were ending up with lots of requests in
flight.
=> Don't poll UI auth again until current poll finishes

src/models/room.js
To make all the variable names to be consistent
=> Use cameCase instead of underscore

src/models/event-timeline-set.js
See https://github.com/matrix-org/matrix-js-sdk/pull/877#discussion_r271704218
=> Remove irrelevant debug line from timeline handling

src/models/event.js
Part of https://github.com/vector-im/riot-web/issues/10189
React-SDK PR: https://github.com/matrix-org/matrix-react-sdk/pull/3170
=> Handle associated event send failures

src/models/event.js
Fixes https://github.com/vector-im/riot-web/issues/10221
=> Add redacts field to event.toJSON

src/models/event.js
For https://github.com/vector-im/riot-web/issues/9834
=> Get edit date transparently from server aggregations or local echo

src/client.js
For https://github.com/vector-im/riot-web/issues/10200
Tested to work
=> Expose original_event for /relations

src/base-apis.js, src/pushprocessor.js, src/sync.js
https://github.com/matrix-org/matrix-js-sdk/pull/1006 to release
=> [release] Support rewriting push rules when our internal defaults change

src/base-apis.js
Part of https://github.com/vector-im/riot-web/issues/10452
=> Add API for checking IS account info

src/base-apis.js
=> Add matrix base API to report an event

src/base-apis.js, src/http-api.js
Fixes https://github.com/vector-im/riot-web/issues/10540
=> Throw an exception if trying to do an ID server request with no ID server

src/base-apis.js
Fixes https://github.com/vector-im/riot-web/issues/10754
=> Do 3pid lookups in lowercase

src/base-apis.js
https://github.com/matrix-org/matrix-js-sdk/pull/1011 to release
=> [To Release] Add matrix base API to report an event

src/client.js
https://github.com/matrix-org/matrix-js-sdk/pull/1027 to release
This probably won't merge cleanly to develop again
=> Synapse admin functions to release

src/models/event-timeline-set.js
Required by https://github.com/matrix-org/matrix-react-sdk/pull/3508
=> Add method to get access to all timelines

src/crypto/verification/Base.js, src/models/event-timeline-set.js, src/models/relations.js
Part of https://github.com/vector-im/riot-web/issues/11251
https://github.com/matrix-org/matrix-react-sdk/pull/3601 needed some further changes in the js-sdk, see commits.
=> Support for verification requests in the timeline

src/models/room.js
Needed for https://github.com/matrix-org/matrix-react-sdk/pull/3620
=> Add method to get last active timestamp in room

spec/unit/crypto/secrets.spec.js, src/client.js, src/crypto/CrossSigning.js, src/crypto/SecretStorage.js, src/crypto/Secrets.js, src/crypto/index.js
This is includes a variety of naming improvements and other tweaks that have helped me navigate the code.
Part of https://github.com/vector-im/riot-web/issues/11212
=> Cross-signing / secret storage tweaks

src/crypto/index.js, src/crypto/verification/Base.js, src/crypto/verification/SAS.js
Fixes https://github.com/vector-im/riot-web/issues/11383
=> Fix SAS verification in encrypted DMs

src/client.js
We have a heap of logic to do the right thing when a call event
arrives, eg. wait until the client is ready so we can see if there's
already been a hangup event before saying there's an incoming call.
Unfortunately it only waited until the client was prepared, not
until it was syncing, so any events that arrived from the server
in the catchup sync bypassed this logic altogether.
This was probably broken back when we introduced the sync accumulator,
since before then, "PREPARED" meant, "done initialsync" rather than
"loaded fake initialsync from storage".
Fixes https://github.com/vector-im/riot-web/issues/3572
=> Fix ringing chirp on loading

src/client.js, src/crypto/OlmDevice.js, src/crypto/algorithms/megolm.js, src/crypto/index.js, src/crypto/olmlib.js, src/crypto/store/indexeddb-crypto-store.js
to try to diagnose https://github.com/vector-im/riot-web/issues/11502 and https://github.com/vector-im/riot-web/issues/11504 and others
=> expand e2ee logging to better debug UISIs

spec/unit/crypto/verification/sas.spec.js
See commits.
Part of https://github.com/vector-im/riot-web/issues/11520
=> Fix a couple SAS tests

spec/unit/room.spec.js, src/models/room.js
Fixes https://github.com/vector-im/riot-web/issues/11551
=> Update alias handling

package.json
=> Restore watching mode for `start:watch`

spec/integ/megolm-integ.spec.js, spec/unit/crypto/algorithms/megolm.spec.js, spec/unit/crypto/backup.spec.js, src/client.js, src/crypto/OlmDevice.js, src/crypto/SecretStorage.js, src/crypto/algorithms/megolm.js, src/crypto/index.js, src/crypto/olmlib.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js, src/models/room-member.js, src/scheduler.js, src/utils.js
RIP notifications, and the diff.
**Real diff (from intentional conflict chunks merge) starts at https://github.com/matrix-org/matrix-js-sdk/pull/1143/commits/cea3831c2045356bb780fa4849e1cea9715a9f7d**
The conflict chunks were left unresolved in the merge commit to hopefully highlight the changes for review. Because they're a bit weird, I'm asking for a review to make sure that the new import method makes sense still (even after all the other PRs regarding imports have been merged).
This is against the feature branch until the feature branches from the other layers can safely go to develop.
=> Sourcemaps: develop -> feature branch

src/crypto/verification/SAS.js
*Paired with https://github.com/matrix-org/matrix-react-sdk/pull/3825 - TravisR*
=> Emoji verification: Change name of 🔒 to lock

src/client.js, src/crypto/algorithms/megolm.js, src/crypto/index.js
If this requires any more information than is on the docstring then I need to write better docs :p
Default behaviour remains unchanged.
=> Add an option to ignore unverified devices

src/timeline-window.js
This PR exposes some logic from the TimelineWindow needed by https://github.com/matrix-org/matrix-react-sdk/pull/3858.
=> Refactor and expose some logic publicly for the TimelineWindow class.

spec/unit/crypto/cross-signing.spec.js, src/base-apis.js, src/crypto/index.js
Fixes https://github.com/vector-im/riot-web/issues/11945
=> Remove :deviceId from /keys/upload/:deviceId as not spec-compliant

package.json
https://github.com/matrix-org/matrix-js-sdk/pull/1161 to release branch
=> Add a prepare script

spec/unit/crypto/verification/verification_request.spec.js, src/crypto/verification/request/VerificationRequest.js
due diligence for https://github.com/vector-im/riot-web/issues/11980 even though it has been fixed already.
react-sdk PR: https://github.com/matrix-org/matrix-react-sdk/pull/3912
=> Add unit tests for verifying your own device, remove .event property on verification request

package.json, yarn.lock
https://babeljs.io/docs/en/babel-runtime
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/1168
**Review with https://github.com/matrix-org/matrix-js-sdk/pull/1170 and https://github.com/matrix-org/matrix-react-sdk/pull/3920**
=> Move & upgrade babel runtime into dependencies (like it wants)

src/crypto/verification/request/ToDeviceChannel.js
used to check if a verification came through to_device in the toast
Needed by https://github.com/matrix-org/matrix-react-sdk/pull/3927
=> expose deviceId prop on device channel

src/crypto/index.js
Based on https://github.com/matrix-org/matrix-js-sdk/pull/1173
=> Trust our own cross-signing keys if we verify them with another device

src/crypto/SecretStorage.js
and add code to fix up ones mis-stored by the old code
=> Fix support for passthrough keys

src/matrix.js
=> docs: fix MatrixClient reference

src/client.js
Dendrite apparently doesn't give us a bunch of these fields
=> Add a bunch of null guards to feature checks

spec/unit/crypto/verification/InRoomChannel.spec.js, src/crypto/verification/request/InRoomChannel.js
Fixes https://github.com/vector-im/riot-web/issues/12211
=> Fix: verification request appearing for users that are not the receiver or sender if they are in room

src/crypto/CrossSigning.js, src/crypto/index.js, src/crypto/verification/Base.js
So we have a better idea of what's going on
=> Add a bunch of logging to verification

src/client.js, src/crypto/SecretStorage.js
https://github.com/vector-im/riot-web/issues/12199#issuecomment-582049538
React-SDK PR: https://github.com/matrix-org/matrix-react-sdk/pull/4038
=> pass ssss item name to callback so we can differentiate UI on it

src/crypto/verification/request/VerificationRequest.js
**For https://github.com/matrix-org/matrix-react-sdk/pull/4001**
=> Add function to estimate target device for a VerificationRequest

src/crypto/verification/request/VerificationRequest.js
Fixes https://github.com/vector-im/riot-web/issues/12239
=> dont require .done event from other party

src/crypto/verification/request/VerificationRequest.js
Fixes https://github.com/vector-im/riot-web/issues/12194
=> Log every verification event

src/crypto/verification/QRCode.js, src/crypto/verification/request/ToDeviceChannel.js, src/crypto/verification/request/VerificationRequest.js
Contains fixes to the QR code crypto, and also making the verification request work with .ready events using the ToDeviceChannel, as we need .ready events to support QR codes for self-verification.
=> QR self-verification fixes

src/index.ts
fixes https://github.com/matrix-org/matrix-js-sdk/issues/1191
=> don't do a dynamic import of request

src/crypto/verification/request/VerificationRequest.js
Related to https://github.com/vector-im/riot-web/issues/12116
=> add local echo state for accepting or declining a verif req

src/crypto/verification/QRCode.js
Fixes https://github.com/vector-im/riot-web/issues/12383
=> Fix renaming error that broke QR code verification

src/crypto/verification/request/VerificationRequest.js
Regressed in https://github.com/matrix-org/matrix-js-sdk/commit/5ee6ada97345ac5134ac16181c2eba9abcfde174
=> Fix cancelled historical requests not appearing as cancelled

src/client.js, src/crypto/algorithms/megolm.js, src/crypto/index.js
- add function for getting curve25519 public key (so that it can be included in rageshakes)
- remove obsolete comment (because we now do what it say we should do)
- remove some leftover debug comments from development
- add some more log lines
=> misc rageshake fixes

spec/unit/crypto/algorithms/megolm.spec.js, src/crypto/algorithms/megolm.js, src/crypto/index.js
fixes https://github.com/vector-im/riot-web/issues/12428
=> Try to re-fetch devices before giving up on trying to heal a broken olm

src/crypto/verification/request/VerificationRequest.js
See https://github.com/matrix-org/matrix-react-sdk/pull/4091
=> Reduce secret size for new binary packing

src/models/room.js
See https://github.com/matrix-org/matrix-doc/pull/2432 and https://github.com/matrix-org/matrix-react-sdk/pull/4102
Needed for https://github.com/vector-im/riot-web/issues/12364
=> Add room method for alt_aliases

src/crypto/verification/request/VerificationRequest.js
Adding some more fields to help debug https://github.com/vector-im/riot-web/issues/12479
=> More verification request logging

src/crypto/verification/Base.js
Generally a good thing to log, and might help with https://github.com/vector-im/riot-web/issues/12479
=> Verification: log when switching start event

src/crypto/verification/request/VerificationRequest.js
Fixes https://github.com/vector-im/riot-web/issues/12215
=> Don't cancel as 3rd party in verification request

spec/unit/room.spec.js, src/models/room.js
Part of https://github.com/vector-im/riot-web/issues/12337
=> Use alt_aliases instead of local ones for room names

src/crypto/DeviceList.js, src/crypto/index.js
Port https://github.com/matrix-org/matrix-js-sdk/pull/1259 to release
=> Force `is_verified` for key backups to bool and fix computation

src/client.js
Related to https://github.com/vector-im/riot-web/issues/12677
=> Fix: prevent error being thrown during sync in some cases

src/crypto/algorithms/megolm.js
Release PR of https://github.com/matrix-org/matrix-js-sdk/pull/1264/
=> Fix: ensureOlmSessionsForDevices parameter format 

src/client.js, src/scheduler.js
Fixes vector-im/riot-web#11834
Supersedes https://github.com/matrix-org/matrix-react-sdk/pull/4220
=> Fix editing of unsent messages by waiting for actual event id

src/crypto/verification/request/VerificationRequest.js
by comparing the device id rather than the user id, as defined in [MSC2366](https://github.com/uhoreg/matrix-doc/blob/key_verification_accept/proposals/2366-key-verification-accept.md):
> After the m.key.verification.ready event is sent, either party can send an m.key.verification.start event to begin the verification. If both parties send an m.key.verification.start event, and they both specify the same verification method, then the event sent by the user whose user ID is the smallest is used, and the other m.key.verification.start event is ignored. **In the case of a single user verifying two of their devices, the device ID is compared instead.**
Fixes https://github.com/vector-im/riot-web/issues/12764
=> handle racing .start event during self verification

src/crypto/DeviceList.js
fixes https://github.com/vector-im/riot-web/issues/12761
=> don't kill the whole device download if one device gives an error

src/client.js, src/crypto/algorithms/megolm.js, src/crypto/index.js
needed for https://github.com/matrix-org/matrix-react-sdk/pull/4235
=> expose prepareToEncrypt in the client API

src/crypto/verification/request/VerificationRequest.js
Part to fix https://github.com/vector-im/riot-web/issues/12763
=> Fix: assume the requested method is supported by other party with to_device

spec/unit/crypto/secrets.spec.js, src/client.js, src/crypto/CrossSigning.js, src/crypto/SecretStorage.js, src/crypto/index.js, src/crypto/key_passphrase.js, src/index.ts, src/utils.ts
includes the changes from https://github.com/matrix-org/matrix-js-sdk/pull/1228
=> Migrate SSSS to use symmetric algorithm

spec/unit/crypto/secrets.spec.js, src/crypto/SecretStorage.js, src/crypto/index.js, src/index.ts, src/utils.ts
fixes https://github.com/vector-im/riot-web/issues/12431
Note: I have not yet tested to see what happens when Riot gets run with this.  It may explode.  It probably should not be merged until the Riot bits are adjusted to work properly with this, and we have a migration from old SSSS.
=> Use symmetric encryption for SSSS

src/client.js, src/crypto/index.js
Aggregate function that checks the various things are in place for
cross-signing to work.
=> Add function for checking cross-signing is ready

spec/unit/crypto/verification/secret_request.spec.js, src/crypto/verification/Base.js
Rather than accessing private method to get the secret storage
object (this was a bit confusing when I grepped for 'requestSecret'
and didn't find anything).
=> Use requestSecret on the client to request secrets

src/crypto/verification/request/VerificationRequest.js
Fixes https://github.com/vector-im/riot-web/issues/12849
=> Fix: verification gets cancelled when event gets duplicated

spec/unit/crypto/verification/secret_request.spec.js, src/crypto/index.js, src/crypto/verification/Base.js
After a successful verification with ourselves, request the key
backup key too and restore a key backup if we get it.
Also cache the key backup key when we cache the SSK & USK so we have
it available to share.
Fixes https://github.com/vector-im/riot-web/issues/12704
=> Request the key backup key & restore backup

src/crypto/CrossSigning.js, src/crypto/index.js
https://github.com/matrix-org/matrix-js-sdk/pull/1289 to release branch
=> Fix isVerified returning false

spec/unit/crypto/outgoing-room-key-requests.spec.js, src/crypto/OutgoingRoomKeyRequestManager.js, src/crypto/index.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/memory-crypto-store.js
Part 1 of 2; still needs a `matrix-react-sdk` counterpart.
Relates to https://github.com/vector-im/riot-web/issues/12843
=> Expose function to force-reset outgoing room key requests

src/crypto/CrossSigning.js, src/crypto/index.js
Fixes https://github.com/vector-im/riot-web/issues/13056
=> Clear cross-signing keys when detecting the keys have changed

src/crypto/index.js
Fixes https://github.com/vector-im/riot-web/issues/13117
Regressed in https://github.com/matrix-org/matrix-js-sdk/pull/1312
=> Fix e2ee crash after refreshing after having received a cross-singing key reset

src/client.js
... by allowing to set an option that doesn't re-emit for the event mapper.
React-SDK PR: https://github.com/matrix-org/matrix-react-sdk/pull/4414
=> Fix: prevent spurious notifications from indexer

release.sh
This allows the bulk of the release script to be used for riot-desktop, while
skipping the NPM and develop branch parts that do not apply.
Part of https://github.com/vector-im/riot-web/issues/13176
Used by https://github.com/vector-im/riot-desktop/pull/69
=> Adapt release script for riot-desktop

src/crypto/verification/QRCode.js
=> Implement QR code reciprocate for self-verification with untrusted MSK

src/client.js
Fixes https://github.com/vector-im/riot-web/issues/13201
=> Fix: crash when backup key needs fixing from corruption issue

src/crypto/index.js
https://github.com/matrix-org/matrix-js-sdk/pull/1322 to release branch
=> Fix cross-signing/SSSS reset

spec/unit/filter-component.spec.js, src/filter-component.js
Hey Matrix devs!!
I started working with the SDK a few days ago, and I found that I wasn't able to filter timeline events by type. I don't have much experience with JS so I could be wrong, but I looked at the code, and I don't think the condition could ever be `true`.
I made a change, and added a test based on some of the other tests on the repo.
If you would like me to make some changes, don't hesitate to let me know, and I'll make them. And if I got something wrong and the current behaviour is correct, please let me know and I'll close the PR 😄 
Signed-off-by: Nicolas Chamo <nicolas@chamo.com.ar>
=> Fix FilterComponent allowed_values check

src/crypto/OlmDevice.js, src/crypto/algorithms/olm.js
https://github.com/matrix-org/matrix-js-sdk/pull/1326 to release branch
=> Serialise Olm prekey decryptions

spec/unit/interactive-auth.spec.js, src/interactive-auth.js
https://github.com/matrix-org/matrix-js-sdk/pull/1329 to release branch
=> Reject attemptAuth promise if no auth flow found

src/filter.js, src/sync.js
Release PR for https://github.com/matrix-org/matrix-js-sdk/pull/1332
=> Fix: don't do extra /filter request when enabling lazy loading of members

src/client.js
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/905
Signed-off-by: Michael Kohler <me@michaelkohler.info>
=> Document setRoomEncryption not modifying room state

src/crypto/SecretStorage.js
https://github.com/matrix-org/matrix-js-sdk/pull/1336 to release branch
=> Fix setDefaultKeyId to fail if the request fails

src/client.js
https://github.com/matrix-org/matrix-js-sdk/pull/1338 to release branch
=> Make getAccountDataFromServer return null if not found

src/crypto/algorithms/megolm.js
Fixes https://github.com/vector-im/riot-web/issues/13322
=> Prune to_device messages to avoid sending empty messages

src/crypto/OlmDevice.js, src/crypto/algorithms/megolm.js
Move the logging lower to a point where we know the first index.
=> Log first known index with megolm session updates

spec/integ/matrix-client-opts.spec.js, src/client.js, src/http-api.js, src/utils.ts
Related to https://github.com/vector-im/riot-web/issues/13216
This doesn't fix the issue completely, in that if the request fails more than 5 times, the problem will still occur. But should already be an improvement.
I've tested somewhat that this works.
=> Retry account data upload requests

spec/integ/matrix-client-opts.spec.js, src/client.js, src/http-api.js, src/utils.ts
Release PR for https://github.com/matrix-org/matrix-js-sdk/pull/1345
=>  Retry account data upload requests

src/crypto/index.js
Port https://github.com/matrix-org/matrix-js-sdk/pull/1353 to release
=> Remove redundant key backup setup path

CHANGELOG.md, src/client.js, src/crypto/DeviceList.js, src/crypto/SecretStorage.js, src/crypto/index.js, src/crypto/verification/Base.js, src/crypto/verification/QRCode.js, src/models/room.js
https://github.com/matrix-org/matrix-js-sdk/pull/1354 to release branch
=> Add crypto.willUpdateDevices event and make getStoredDevices/getStoredDevicesForUser synchronous

src/crypto/verification/Base.js, src/crypto/verification/request/VerificationRequest.js
=> Handle race between sending and await next event from other party

src/crypto/index.js
Release PR for https://github.com/matrix-org/matrix-js-sdk/pull/1359
=> Fix race between sending .request and receiving .ready over to_device

src/client.js, src/crypto/DeviceList.js
This indicates whether the device database is being populated initially
=> Add initialFetch param to willUpdateDevices / devicesUpdated

src/client.js, src/crypto/index.js
Relates to: https://github.com/vector-im/riot-web/issues/13167
If we're handed a `progressCallback`, call it during the key loading process.
=> Added a progressCallback for backup key loading

src/crypto/OlmDevice.js
Fixes: https://github.com/vector-im/riot-web/issues/12252
=> Customize error payload for oversized messages

src/crypto/index.js
https://github.com/matrix-org/matrix-js-sdk/pull/1364 to release branch
=> Emit event when a trusted self-key is stored

src/crypto/algorithms/megolm.js, src/models/event.js
For https://github.com/vector-im/riot-web/issues/13473
=> Add logging on decryption retries

src/client.js, src/crypto/index.js
Ports https://github.com/matrix-org/matrix-js-sdk/pull/1351 for release
Relates to https://github.com/matrix-org/matrix-react-sdk/pull/4545
land me first
=> Add progress callback for key backups

src/models/room.js
=> Fix getVersion warning saying undefined room

package.json
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/1383
=> Add dist to package.json files so CDNs can serve it

spec/olm-loader.js, spec/unit/crypto/CrossSigningInfo.spec.js, spec/unit/crypto/backup.spec.js, src/client.js, src/crypto/CrossSigning.js, src/crypto/index.js, src/crypto/store/localStorage-crypto-store.js
and also allow specifying the pickle key
Needed for keytar support.
=> encrypt cached keys with pickle key

src/interactive-auth.js
Followon from https://github.com/matrix-org/matrix-react-sdk/pull/4667
=> Send the wrong auth params with the right auth params

spec/unit/crypto/secrets.spec.js, src/client.js, src/crypto/index.js
Release PR of https://github.com/matrix-org/matrix-js-sdk/pull/1398/
=> Bring back backup key format migration

src/pushprocessor.js
Part of https://github.com/matrix-org/matrix-doc/issues/2616
Fixes https://github.com/vector-im/riot-web/issues/14000
Specifically line 328 was to blame for 14000.
=> Remove support for unspecced device-specific push rules

src/interactive-auth.js
Port https://github.com/matrix-org/matrix-js-sdk/pull/1403 to release
=> Use existing session id for fetching flows as to not get a new session

src/client.js, src/crypto/index.js, src/crypto/verification/request/ToDeviceChannel.js
Hopefully the jsdoc explains all.
=> Add method to get current in-flight to-device requests

spec/unit/crypto.spec.js, spec/unit/crypto/backup.spec.js, src/client.js, src/crypto/OlmDevice.js, src/crypto/algorithms/megolm.js, src/crypto/index.js, src/models/event.js
also, if we received a key from backup, don't automatically re-upload it to the backup
=> Don't trust keys megolm received from backup for verifying the sender

src/crypto/index.js
Although see comment and other bug created
Fixes https://github.com/vector-im/riot-web/issues/14828
=> Upload all keys when we start using a new key backup version

release.sh, spec/integ/devicelist-integ-spec.js, spec/integ/megolm-integ.spec.js, src/base-apis.js, src/client.js, src/crypto/DeviceList.js, src/crypto/algorithms/megolm.js, src/crypto/index.js, src/crypto/verification/Base.js, src/models/event.js
This only covers the simple cases of references to issues and repos. More
complex areas, such as deployment scripts, will be handled separately.
Part of https://github.com/vector-im/element-web/issues/14864
=> Replace Riot with Element in docs and comments

src/models/user.js, src/utils.ts
Release PR of https://github.com/matrix-org/matrix-js-sdk/pull/1433
=> Filter out non-string display names

spec/unit/crypto/CrossSigningInfo.spec.js, spec/unit/crypto/verification/secret_request.spec.js, src/crypto/CrossSigning.js, src/crypto/EncryptionSetup.js, src/crypto/SecretStorage.js, src/crypto/index.js, src/crypto/verification/Base.js
This enables storing and requesting master cross-signing private key when verifying other devices or using your security key.
**Reviewer:** I suggest reviewing commit by commit.
Part of https://github.com/vector-im/element-web/issues/13896
Used by https://github.com/matrix-org/matrix-react-sdk/pull/5092
=> Store and request master cross-signing key

src/webrtc/call.js
=> Log the constraints we pass to getUserMedia

.eslintrc.js
For https://github.com/vector-im/element-web/issues/15036
=> Fix eslint ts override tsx matching

src/crypto/index.js
Fixes https://github.com/vector-im/element-web/issues/15087
=> Ensure ready functions return boolean values

src/@types/global.d.ts, src/client.js, src/matrix.ts
tell TypeScript about olm, add all the options for clients, and make options in docs camelCase
=> some TypeScript and doc fixes

README.md
Yarn install guide link was broken, so I just fixed.
=> Fixed Yarn broken link

src/client.js
See https://github.com/matrix-org/matrix-react-sdk/pull/5231
=> Add a function for checking the /versions flag for forced e2ee

src/client.js
Fixes https://github.com/vector-im/element-web/issues/15204
=> Prevent parallel getVersions calls

src/crypto/index.js
May help with https://github.com/vector-im/element-web/issues/15230
=> Add diagnostics to security bootstrap paths

src/webrtc/call.js
Ignore ICE candidates with no m-line index or mid
=> Ignore invalid candidates

spec/browserify/sync-browserify.spec.js, src/models/event-timeline-set.js, src/models/room.js
Fixes https://github.com/vector-im/element-web/issues/10545
Not sure if it covers all the various states but works with a simulated slow connection in both plaintext and e2ee rooms
=> Fix editing local echoes not updating them in real time

src/@types/event.ts
Fixes https://github.com/vector-im/element-web/issues/14804
=> Create a giant event type enum

src/client.js, src/webrtc/call.ts, src/webrtc/callEventHandler.ts
Remove the old hack of inspecting the SDP which no longer seems to
be necessary.
Based on https://github.com/matrix-org/matrix-js-sdk/pull/1499
=> Set the type of the call based on the tracks

src/webrtc/callEventHandler.ts
Wrong kind of event emitter...
=> Fix call event handler listener removing

src/webrtc/call.ts
https://github.com/matrix-org/matrix-js-sdk/pull/1525 to release branch
=> Fix logger typo

src/webrtc/call.ts, src/webrtc/callEventHandler.ts
Hopefully send fewer ICE candidate events by obeying the batching
guidelines in MSC2476.
=> Improve ICE candidate batching

src/crypto/index.js
Port https://github.com/matrix-org/matrix-js-sdk/pull/1529 to release
=> [Release] Await key cache check to avoid prompts

src/crypto/index.js
Another cached promise that wasn't cleared on failure
=> Fix stuck never-sending messages

src/client.js
Synthesise profile updates for ourselves to work around issues when you are in 0 rooms.
=> Client set profile methods update own user

src/@types/event.ts, src/webrtc/call.ts, src/webrtc/callEventHandler.ts
Using m.call.negotiate
VoIP protocol version remains at zero so this won't be enabled unless talking to an element-web from the future (it will still mute, it just won't signal to the other side).
=> Implement call holding functionality

src/client.js
Port https://github.com/matrix-org/matrix-js-sdk/pull/1544 to release
=> [Release] Fix dehydration method name

src/webrtc/call.ts
=> Export CallError

src/webrtc/call.ts
Fixes a bug where the call would ring again when you refreshed,
even though you'd previously rejected it.
=> Honour a call reject event from another of our own devices

spec/unit/webrtc/call.spec.ts, src/@types/event.ts, src/client.js, src/matrix.ts, src/webrtc/call.ts
Based on https://github.com/matrix-org/matrix-js-sdk/pull/1558
Diff: https://github.com/matrix-org/matrix-js-sdk/compare/pull/1558/head...pull/1559/head
=> Ignore party ID if opponent is v0

src/@types/event.ts, src/client.js, src/matrix.ts, src/webrtc/call.ts
Sends an m.call.replaces event and flag for whether to advertise
support.
MSC2747 (https://github.com/matrix-org/matrix-doc/pull/2747)
=> Basic call transfer initiation support

spec/unit/webrtc/call.spec.ts, src/@types/event.ts, src/client.js, src/matrix.ts, src/webrtc/call.ts
Reverts matrix-org/matrix-js-sdk#1559
Forgot this one was based on another PR
=> Revert "Ignore party ID if opponent is v0"

spec/integ/megolm-integ.spec.js, src/crypto/OlmDevice.js
Should fix https://github.com/vector-im/element-web/issues/16025
Signed-Off-By: Sorunome <mail@sorunome.de>
=> Store keys with same index but better trust level

src/models/room.js
MSC2788 (https://github.com/matrix-org/matrix-doc/pull/2788) etc
https://github.com/vector-im/element-web/issues/16068 (short-term 'fix')
=> Room version 6 is now a thing

src/webrtc/call.ts
https://www.youtube.com/watch?v=FAsIx3oPY-8
=> Add DTMF sending support

src/webrtc/call.ts
Port https://github.com/matrix-org/matrix-js-sdk/pull/1583 to release
=> [Release] Fix compatibility with v0 calls

src/sync.js
but two Room instances are created and things get duplicated
=> Fix edge cases with peeking where a room is re-peeked

src/sync.js
https://github.com/matrix-org/matrix-js-sdk/pull/1587 to Release
but two Room instances are created and things get duplicated
=> [Release] Fix edge cases with peeking where a room is re-peeked

src/@types/global.d.ts, src/webrtc/call.ts
More info [here](https://github.com/matrix-org/matrix-react-sdk/pull/5525).
Requires: [`element-desktop` 161](https://github.com/vector-im/element-desktop/pull/161) and [`matrix-react-sdk` 5525](https://github.com/matrix-org/matrix-react-sdk/pull/5525)
=> Fix desktop Matrix screen sharing

README.md
Signed-off-by: Rüdiger Herrmann <ruediger.herrmann@gmx.de>
=> Fix typo in main readme

src/client.js, src/matrix.ts, src/webrtc/call.ts
So we have the option to start gathering sooner
=> Add option to set ice candidate pool size

src/crypto/algorithms/megolm.js, src/crypto/olmlib.js, src/logger.ts
This continues adding more logs to work out the root cause of
https://github.com/vector-im/element-web/issues/16194.
Somehow, we're getting stuck while sharing keys with new sessions.
=> Add debug logs to encryption prep, take 3

src/logger.ts
Tweak the prefixed logger to only do the setup work the first time.
=> Optimise prefixed logger

src/crypto/OlmDevice.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js
We churn through a huge number of crypto store transactions during startup, which may be the cause of the symptoms in https://github.com/vector-im/element-web/issues/16194.
=> Add logging to crypto store transactions

src/webrtc/call.ts
Don't leave candidate messages in the queue, abort if we fail to
send the invite, abort call if we can't send candidates after retries.
Also convert some promise code to async/await
=> Better handling of send failures on VoIP events

src/crypto/OlmDevice.js, src/crypto/algorithms/megolm.js, src/crypto/olmlib.js, src/crypto/store/indexeddb-crypto-store.js, src/logger.ts
It seems like this might be where https://github.com/vector-im/element-web/issues/16194 is deadlocking.
=> Add logging to in progress Olm sessions

src/store/indexeddb.js
This seems like a simple oversight. However, I have no idea whether this is really correct, please verify this.
Signed-off-by: Florian Jacob <florian ÄT wolkenplanet <POINT> de>
=> Fix IndexedDB store creation example

src/models/room.js
This matches the RoomMember function of the same name.
=> Add a function to get a room's MXC URI

src/base-apis.js, src/client.js, src/crypto/verification/request/ToDeviceChannel.js, src/http-api.js
...and fix a daft bug where we'd cancel ourselves when selecting a self-verification partner during cross-signed verification.
=> Expose APIs needed for reworked cross-signing login flow

src/webrtc/call.ts, src/webrtc/callEventTypes.ts
Add ability to transfer a call to another ongoing call, rather than to a person (ie. telling one of the parties to replace an existing call we already have with them).
=> Attended transfer

src/webrtc/call.ts
Fixes [#16800](https://github.com/vector-im/element-web/issues/16800)
=> Properly terminate screen-share calls if NoUserMedia

src/client.js
should fix https://github.com/vector-im/element-web/issues/16810
=> Add missing await

src/models/room.js
Signed-off-by: Hanno Gödecke <hgoedecke@cuvent.com>
=> Add room.getMembers method

src/client.js
Also see https://github.com/vector-im/element-web/issues/15484
=> Fix `/search` with no results field work again

src/client.js, src/logger.ts, src/models/room.js
Reverts matrix-org/matrix-js-sdk#1678
This logging has not proven valuable.
=> Revert "Raise logging dramatically to chase pending event errors"

examples/voip/browserTest.js, examples/voip/index.html
Build atop of [#1660](https://github.com/matrix-org/matrix-js-sdk/pull/1660)
Requires [#1660](https://github.com/matrix-org/matrix-js-sdk/pull/1660)
This updates the VoIP example so that it works with the changes introduced in [#1660](https://github.com/matrix-org/matrix-js-sdk/pull/1660)
=> Update the VoIP example to work with the new changes

src/@types/event.ts
~~Blocked on FCP https://github.com/matrix-org/matrix-doc/pull/1772~~
This will render incompatibility for existing spaces
=> Switch from MSC1772 unstable prefixes to stable

src/models/room-member.js
Proof of working: https://github.com/matrix-org/matrix-react-sdk/pull/6036
=> Null-guard power level object usage

src/webrtc/call.ts
This should fix [#17250](https://github.com/vector-im/element-web/issues/17250).
=> Fix regressed glare

src/webrtc/call.ts
Port https://github.com/matrix-org/matrix-js-sdk/pull/1690 to release
=> [Release] Fix regressed glare

src/client.js, src/webrtc/callEventHandler.ts
Port https://github.com/matrix-org/matrix-js-sdk/pull/1698 to release
=> [Release] Change call event handlers to adapt to undecrypted events

package.json, spec/olm-loader.js, src/@types/global.d.ts, yarn.lock
Port https://github.com/matrix-org/matrix-js-sdk/pull/1705 to release
=> [Release] Bump libolm version and update package name

src/webrtc/callEventHandler.ts
Fixes vector-im/element-web#17393
This issue has been spotted when transfering calls which uses asserted identity.
=> Make consistent call event type checks

src/base-apis.js
Part of https://github.com/vector-im/element-web/issues/17521
=> Switch to stable endpoint/fields for MSC2858

src/webrtc/call.ts
Instead of inactive. Remove the logic for trying to remember who
had who on hold, which is now unnecesasary. Appears to work fine
with element android & ios too.
=> Use sendonly for call hold

spec/unit/matrix-client.spec.js, src/@types/partials.ts, src/@types/requests.ts, src/client.ts
Paired with https://github.com/matrix-org/matrix-react-sdk/pull/6183
=> Move various types from the react-sdk to the js-sdk

src/client.ts, src/crypto/backup.ts, src/crypto/index.ts, src/crypto/key_passphrase.ts, src/models/event.ts, src/webrtc/call.ts, yarn.lock
Just `eslint --fix` with rule from
https://github.com/matrix-org/eslint-plugin-matrix-org/pull/9 in place
=> Comply with new member-delimiter-style rule

src/client.ts, src/crypto/EncryptionSetup.ts, src/crypto/SecretStorage.ts, src/crypto/api.ts, src/crypto/dehydration.ts, src/crypto/index.ts, src/matrix.ts
This found a few bugs, most notably the fact that we don't do anything at all with secret request cancellations, I've commented out the code in question.
=> Convert SecretStorage to TypeScript

src/crypto/index.ts
as Element Web devtools uses it for debugging
=> Make `Crypto::inRoomVerificationRequests` public

CONTRIBUTING.md
=> Convert CONTRIBUTING to markdown

.github/PULL_REQUEST_TEMPLATE.md
=> Fix link to CONTRIBUTING.md

src/store/indexeddb-remote-backend.ts
=> Actually print IndexedDB command error if there is one

package.json, src/client.ts, src/models/user.ts, src/sync.ts, src/utils.ts, yarn.lock
Requires https://github.com/matrix-org/eslint-plugin-matrix-org/pull/10
=> Conform to new typescript eslint rules

src/webrtc/call.ts, src/webrtc/callEventTypes.ts
For https://github.com/matrix-org/matrix-react-sdk/pull/6472
=> Handle DTMF support

package.json, release.sh, yarn.lock
This can just be a package.json dep now, so removing the checks for the tool existing (both of them...)
=> Switch to new changelog generator

src/webrtc/call.ts
Fixes https://github.com/vector-im/element-web/issues/18219
=> Send `user_hangup` reason if the opponent supports it

src/models/MSC3089Branch.ts
because it makes sense, and we kinda need it.
=> Expose a getFileEvent() function off a MSC3089Branch

src/webrtc/call.ts
Fixes https://github.com/vector-im/element-web/issues/18449
Regressed by https://github.com/matrix-org/matrix-js-sdk/pull/1821
=> Fix error on turning off screensharing

src/models/MSC3089TreeSpace.ts
This was originally thought to be able to be performed in another way, but unfortunately isn't as easy as originally predicted.
=> Add support for reading permissions from tree spaces

src/models/event-timeline.ts
This definitely needs explanation, but hopefully the comment is sufficient.
Type: defect
Fixes https://github.com/vector-im/element-web/issues/18321
Regressed in https://github.com/matrix-org/matrix-js-sdk/pull/1765
=> Fix blank profile in join events

src/webrtc/call.ts, src/webrtc/callEventHandler.ts
Type: defect
Port https://github.com/matrix-org/matrix-js-sdk/pull/1851 to release
Requires https://github.com/matrix-org/matrix-react-sdk/pull/6622
---
* [Release] Fix glare related regressions ([\#1854](https://github.com/matrix-org/matrix-js-sdk/pull/1854)). Contributed by [SimonBrandner](https://github.com/SimonBrandner).
=> [Release] Fix glare related regressions

src/webrtc/call.ts, src/webrtc/callEventHandler.ts
Reverts matrix-org/matrix-js-sdk#1851
This seems to have broken quite a lot of functionality: https://github.com/vector-im/element-web/issues/18578
---
* Revert "Fix glare related regressions" ([\#1857](https://github.com/matrix-org/matrix-js-sdk/pull/1857)).
=> Revert "Fix glare related regressions"

src/webrtc/call.ts, src/webrtc/callEventHandler.ts
Fixes https://github.com/vector-im/element-web/issues/18578
Fixes https://github.com/vector-im/element-web/issues/18538
Type: defect
---
* Fix broken voice calls, no ringing and broken call notifications ([\#1858](https://github.com/matrix-org/matrix-js-sdk/pull/1858)). Fixes vector-im/element-web#18578 vector-im/element-web#18538 and vector-im/element-web#18578. Contributed by [SimonBrandner](https://github.com/SimonBrandner).
=> Fix broken voice calls, no ringing and broken call notifications

src/webrtc/callEventHandler.ts
https://github.com/matrix-org/matrix-js-sdk/pull/1858 to release branch
---
* Fix multiple VoIP regressions ([\#1860](https://github.com/matrix-org/matrix-js-sdk/pull/1860)).
=> Fix multiple VoIP regressions

release.sh
https://github.com/matrix-org/matrix-js-sdk/pull/1856 to release branch
---
=> Fix release script to handle no signing ID

src/client.ts
Required for matrix-org/matrix-react-sdk#6619
---
=> Expose IMyDevice interface

src/webrtc/callEventHandler.ts
Type: task
Requires https://github.com/matrix-org/matrix-react-sdk/pull/6627
---
=> Revert quick VoIP fix

src/client.ts
Related: https://github.com/matrix-org/matrix-react-sdk/pull/6635
---
=> Add necessary changes for PasswordReset migration

src/webrtc/call.ts, src/webrtc/callEventHandler.ts, src/webrtc/callEventTypes.ts
=> Improve TypeScript in `MatrixCall` 
