spec/TestClient.ts
spec/integ/megolm-integ.spec.ts
spec/test-utils/test-utils.ts
src/rust-crypto/rust-crypto.ts

A bunch of changes to tests, and wire up decryption.
---
* Implement decryption via the rust sdk ([\#3074](https://github.com/matrix-org/matrix-js-sdk/pull/3074)).

Implement decryption via the rust sdk

---

src/webrtc/groupCall.ts
src/webrtc/mediaHandler.ts

This happens in dev mode with React 18 and caused extra user media stream to end up floating around.
Fixes https://github.com/vector-im/element-call/issues/847
---
* Handle group call getting initialised twice in quick succession ([\#3078](https://github.com/matrix-org/matrix-js-sdk/pull/3078)). Fixes vector-im/element-call#847.

Handle group call getting initialised twice in quick succession

---

src/models/thread.ts

Follow up of https://github.com/matrix-org/matrix-react-sdk/pull/9933
Notes: Fix backwards compability for environment not support Array.prototype.at
---
* Fix backwards compability for environment not support Array.prototype.at ([\#3080](https://github.com/matrix-org/matrix-js-sdk/pull/3080)).

replace .at(-1) with array.length-1

---

src/webrtc/groupCall.ts

As per comment
---
* Add null check for our own member event ([\#3082](https://github.com/matrix-org/matrix-js-sdk/pull/3082)).

Add null check for our own member event

---

spec/integ/sliding-sync-sdk.spec.ts
spec/integ/sliding-sync.spec.ts
src/sliding-sync.ts

Update the request/response API shape to match the latest MSC3575 version, which converts `lists` from being an array of list objects to being a map of list objects.
---

refactor: sliding sync: swap to lists-as-keys

---

spec/unit/matrix-client.spec.ts
src/client.ts

Fixes a bug I found in `getRoomUpgradeHistory` while I was testing it for MSC3946.
When we were verifying links, we were looking for the wrong room ID in a tombstone event, so we never successfully verified correct links between rooms.
I note that two places (SpaceStore and SpaceHierarchy) in matrix-react-sdk do supply the `verifyLinks` flag, so this may possibly fix some bugs in spaces.
---
* Fix "verifyLinks" functionality of getRoomUpgradeHistory ([\#3089](https://github.com/matrix-org/matrix-js-sdk/pull/3089)). Contributed by @andybalaam.

Fix "verifyLinks" functionality of getRoomUpgradeHistory

---

spec/unit/crypto/algorithms/megolm.spec.ts
spec/unit/utils.spec.ts
src/crypto/algorithms/megolm.ts
src/utils.ts

This was originally intended to help with vector-im/element-web#21612, but ended up addressing #1255 as well.
The input delay was addressed by adding a `setTimeout` to the cpu-bound portion of the code. That should allow rendering code and event handlers to preempt key preparation periodically. Should help somewhat, but probably not a full solution. Ideally, `setImmediate` should be used or approximated, but it's basically not supported in any browser, so 0ms timeouts it is.
That allowed for cancellation to be addressed. There are multiple ways this could have been achieved, and I wasn't able to find a clear precedent. I opted for passing around stateful closures. It had the most minimal impact on the API that I could come up with.
I've tried my best to follow the contribution guidelines …

Reduce Megolm blocking and add cancellation

---

src/client.ts

Refactor getRoomUpgradeHistory to use Room.findPredecessorRoomId

---

spec/unit/crypto/algorithms/megolm.spec.ts

cc @andybalaam 
I introduced a flaky test in #3035 to confirm that `MegolmEncryption#prepareToEncrypt` didn't block the main thread too much, but it turns out that, when run in varying environments, it tends to fail.
The same behavior is guaranteed by [the following cancellation test](https://github.com/matrix-org/matrix-js-sdk/blob/66ae985af592cdc5e9a9f92bb8a91cc8a4069327/spec/unit/crypto/algorithms/megolm.spec.ts#L591-L600) – if the thread is blocked, it can't be cancelled.
Refs:
* https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$seEu9__-mwtnsjmrBheOMhpvow0qzldCnSqMtntINog
* https://github.com/matrix-org/matrix-js-sdk/actions/runs/3998796658/jobs/6861889997
* https://github.com/matrix-org/matrix-js-sdk/actions/runs/4006364721/jobs/6877800626
-   [x] Tests written for new code (and …

Remove flaky megolm test

---

spec/unit/webrtc/call.spec.ts
src/webrtc/call.ts

Builds on https://github.com/matrix-org/matrix-js-sdk/pull/3028 but without removing the sender and causing a renegotiation.
---
* Remove video tracks on video mute without renegotiating ([\#3091](https://github.com/matrix-org/matrix-js-sdk/pull/3091)).

Remove video tracks on video mute without renegotiating

---

spec/unit/matrix-client.spec.ts
spec/unit/room.spec.ts
src/@types/event.ts
src/client.ts
src/models/room.ts

See [MSC3946](https://github.com/matrix-org/matrix-spec-proposals/pull/3946). Support looking up room predecessors using this MSC if the caller explicitly opts in.
Adds an optional boolean argument to `getVisibleRooms`, `getRoomUpgradeHistory` and `getPredecessorRoomId` that specifies whether to use the new logic.
---
* MSC3946 Dynamic room predecessors ([\#3042](https://github.com/matrix-org/matrix-js-sdk/pull/3042)). Contributed by @andybalaam.

MSC3946 Dynamic room predecessors

---

spec/unit/room.spec.ts
src/client.ts
src/models/room.ts

Inside matrix-react-sdk we need a room's predecessor event id (the id of the last known event in the room) as well as the predecessor room id, so provide both.
This changes a public function, but it was only added yesterday so I don't see it as a breaking change.
---
* Provide eventId as well as roomId from Room.findPredecessor ([\#3095](https://github.com/matrix-org/matrix-js-sdk/pull/3095)). Contributed by @andybalaam.

Provide eventId as well as roomId from Room.findPredecessor

---

src/webrtc/call.ts

---
* Don't throw with no `opponentDeviceInfo` ([\#3107](https://github.com/matrix-org/matrix-js-sdk/pull/3107)).

Don't throw with no `opponentDeviceInfo`

---

spec/unit/crypto/verification/sas.spec.ts
src/crypto/verification/SAS.ts

[MSC3783](https://github.com/matrix-org/matrix-spec-proposals/pull/3783) has finished FCP, so we can use the stable identifiers for the MAC with fixed base64 encoding now.
Related spec PR: https://github.com/matrix-org/matrix-spec/pull/1412
Polyjuice Client Test (test.uhoreg.ca) has also been [updated](https://gitlab.com/polyjuice/polyjuice_client_test/-/commit/12694cc99316a03a5d0efad7f418e919448c7b09).  With current app.element.io, it will show:
But with this patch, it shows
---
* Add support for stable …

Add support for stable identifier for fixed MAC in SAS verification

---

package.json
spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/OutgoingRequestProcessor.ts
src/rust-crypto/rust-crypto.ts
yarn.lock

This is a follow-up to https://github.com/matrix-org/matrix-js-sdk/pull/3019: it implements the remaining two types of message types, now that rust SDK has sensibly-shaped types for them.
It turns out that I need to pull this stuff out to a separate class, so this PR also includes that.
Part of vector-im/element-web#21972.
---

Element-R: implement remaining OutgoingMessage request types

---

src/webrtc/call.ts

Since we don't speak e2e to them anyway
---
* Don't require e2e keys for foci ([\#3118](https://github.com/matrix-org/matrix-js-sdk/pull/3118)).

Don't require e2e keys for foci

---

spec/unit/read-receipt.spec.ts
src/client.ts
src/models/room.ts

A lot of logic regarding servers that do not support thread notifications (pre MSC3773) exists. This PR removes some of it. 
Comes with its react-sdk counterpart too.
---

Cleanup pre MSC3773 thread unread notif logic

---

src/models/room-state.ts
src/models/room.ts

Part of https://github.com/vector-im/element-web/issues/24323
---

Move the logic of roomPredecessor into the RoomState class

---

spec/unit/room.spec.ts
src/models/room-state.ts

Part of [MSC3946](https://github.com/matrix-org/matrix-spec-proposals/pull/3946)
---
* Handle optional last_known_event_id property in m.predecessor ([\#3119](https://github.com/matrix-org/matrix-js-sdk/pull/3119)). Contributed by @andybalaam.

Handle optional last_known_event_id property in m.predecessor

---

src/rust-crypto/rust-crypto.ts

Previously, if we failed to decrypt a to-device event, we would raise an "expected a string" error when we later tried to decrypt it as a room event. This at least makes the error clearer.
---

Element R: Fix obscure errors when we fail to decrypt to-device events

---

src/webrtc/call.ts

Works around https://github.com/matrix-org/waterfall/issues/98
See comment and that issue for full explanation.
---
* Work around pion bug to fix screen sharing ([\#3120](https://github.com/matrix-org/matrix-js-sdk/pull/3120)).

Work around pion bug to fix screen sharing

---

src/sync.ts

Currently, whenever we receive an invite on element R, it crashes the sync loop. A quick fix to make it not do that.
---
* Element-R: Fix invite processing ([\#3121](https://github.com/matrix-org/matrix-js-sdk/pull/3121)).

Element-R: Fix invite processing

---

package.json
spec/integ/crypto.spec.ts
spec/unit/matrix-client.spec.ts
spec/unit/rust-crypto/KeyClaimManager.spec.ts
src/client.ts
src/common-crypto/CryptoBackend.ts
src/crypto/index.ts
src/rust-crypto/KeyClaimManager.ts
src/rust-crypto/RoomEncryptor.ts
src/rust-crypto/index.ts
src/rust-crypto/rust-crypto.ts
src/sliding-sync-sdk.ts
src/sync.ts
yarn.lock

This PR wires up the Rust-SDK into the event encryption path. I'm sorry it's a bit meaty - I've tried to break it down into bite-size commits and I recommend reviewing them in turn.
I'm also sorry that it's not as well tested as I would like, and in particular there are no integration tests. I've had trouble getting the tests to work for reasons including, but not limited to, https://github.com/matrix-org/matrix-rust-sdk/issues/1443. However, empirically it works in a browser, and I'm keen to see this shipped. I'll return to the tests soon.
---
* Element-R: implement encryption of outgoing events ([\#3122](https://github.com/matrix-org/matrix-js-sdk/pull/3122)).

Element-R: implement encryption of outgoing events

---

yarn.lock

Upgrade matrix-sdk-crypto-js, to pick up https://github.com/matrix-org/matrix-rust-sdk/pull/1429
---
* Element-R: fix a bug which prevented encryption working after a reload ([\#3126](https://github.com/matrix-org/matrix-js-sdk/pull/3126)).

Element-R: fix a bug which prevented encryption working after a reload

---

src/rust-crypto/OutgoingRequestProcessor.ts

otherwise it's rather hard to see them, at least in Firefox.
---

Element-R: log outgoing HTTP requests

---

spec/unit/scheduler.spec.ts
src/models/room.ts
src/scheduler.ts

Type: Defect
Fixes: https://github.com/vector-im/element-web/issues/22885
Fixes: https://github.com/vector-im/element-web/issues/18942
---
* Messages sent out of order after one message fails ([\#3131](https://github.com/matrix-org/matrix-js-sdk/pull/3131)). Fixes vector-im/element-web#22885 and vector-im/element-web#18942. Contributed by @justjanne.

Messages sent out of order after one message fails

---

src/webrtc/call.ts

As per comment.
This is again somewhat of a temporary hack workaround until we work out a way to manage our transceivers sensibly.
---
* Re-use transceivers for user media ([\#3144](https://github.com/matrix-org/matrix-js-sdk/pull/3144)).

Re-use transceivers for user media

---

src/webrtc/call.ts

It just wasn't getting stopped, so if the call ended while ICE was disconnected, we'd get confusing error messages after the call ended.
---
* Stop the ICE disconnected timer on call terminate ([\#3147](https://github.com/matrix-org/matrix-js-sdk/pull/3147)).

Stop the ICE disconnected timer on call terminate

---

post-release.sh
release.sh

Include 'browser' in list of adjusted properties in release.sh

---

spec/unit/models/poll.spec.ts
src/models/poll.ts

`matrixClient.relations` only decrypts events when there is an `eventType` filter set
Explicitly decrypt poll relation events before processing.
---

Poll history: decrypt poll relations before processing

---

spec/unit/room.spec.ts
src/models/room-state.ts
src/models/room.ts

Fix predecessor types, nowhere does the spec say it can be `null`

---

spec/test-utils/webrtc.ts
spec/unit/webrtc/call.spec.ts
spec/unit/webrtc/callFeed.spec.ts
spec/unit/webrtc/groupCall.spec.ts
src/webrtc/call.ts
src/webrtc/callEventTypes.ts
src/webrtc/callFeed.ts
src/webrtc/callTrack.ts
src/webrtc/groupCall.ts
src/webrtc/localCallFeed.ts
src/webrtc/localCallTrack.ts
src/webrtc/remoteCallFeed.ts
src/webrtc/remoteCallTrack.ts

Todos:
Follow up work
- Move mute handling into `CallTrack`s
- Possibly abstract publishing into a  class
- Possibly abstract subscribing into a class
- Possibly abstract different `CallFeed` purposes into separate classes
---

Refactor `CallFeed`s

---

spec/unit/models/poll.spec.ts
src/models/poll.ts

Keep track of undecryptable poll relations to communicate to users that their vote count may be inaccurate:
---
* Polls: count undecryptable poll relations ([\#3163](https://github.com/matrix-org/matrix-js-sdk/pull/3163)). Contributed by @kerryarchibald.

Polls: count undecryptable poll relations

---

src/content-helpers.ts

Fixes https://github.com/matrix-org/element-web-rageshakes/issues/20177
Fixes https://github.com/matrix-org/element-web-rageshakes/issues/20178
---
* Better type guard parseTopicContent ([\#3165](https://github.com/matrix-org/matrix-js-sdk/pull/3165)). Fixes matrix-org/element-web-rageshakes#20177 and matrix-org/element-web-rageshakes#20178.

Better type guard parseTopicContent

---

spec/unit/models/poll.spec.ts
src/models/poll.ts

---
* Polls: expose end event id on poll model ([\#3160](https://github.com/matrix-org/matrix-js-sdk/pull/3160)). Contributed by @kerryarchibald.

Polls: expose end event id on poll model

---

spec/integ/matrix-client-unread-notifications.spec.ts
src/models/room.ts

Type: Defect
Fixes: https://github.com/vector-im/element-web/issues/24000
---
* Fix reactions in threads sometimes causing stuck notifications ([\#3146](https://github.com/matrix-org/matrix-js-sdk/pull/3146)). Fixes vector-im/element-web#24000. Contributed by @justjanne.

Fix reactions in threads sometimes causing stuck notifications

---

spec/unit/models/event.spec.ts
src/models/event.ts

Requires https://github.com/matrix-org/matrix-react-sdk/pull/10248
---
* Fix spec compliance issue around encrypted `m.relates_to` ([\#3178](https://github.com/matrix-org/matrix-js-sdk/pull/3178)).

Fix spec compliance issue around encrypted `m.relates_to`

---

spec/unit/pushprocessor.spec.ts
src/@types/PushRules.ts
src/pushprocessor.ts

- adds polls push rule ids from [MSC3930](https://github.com/matrix-org/matrix-spec-proposals/blob/travis/msc/polls-notifs/proposals/3930-polls-notifications.md)
- adds function to retrieve a user's rule and kind by id `getPushRuleAndKindById` - used [here](https://github.com/matrix-org/matrix-react-sdk/pull/10263)
---

Polls push rules

---

spec/unit/webrtc/groupCall.spec.ts
src/client.ts
src/webrtc/groupCall.ts
src/webrtc/groupCallEventHandler.ts

- ensure group call backwards-compatibility and move `allowCallWithoutVideoAndAudio`to the end of the `CroupCall` constructor
- The changes in PR https://github.com/matrix-org/matrix-js-sdk/pull/3162#event-8651860750 brakes with the `matrix-react-sdk` because of using GroupCall there: https://github.com/matrix-org/matrix-react-sdk/blob/2d2b40ddac5fa1adb12b34eea436e0b70e8a9857/src/models/Call.ts#L723
- The changes in PR `3162` leads to breaking dependencies: https://github.com/matrix-org/matrix-react-sdk/actions/runs/4316690112/jobs/7532790787
This PR is a fix for it.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRI …

Fix: braking changes with GroupCall and ensure backwards-compatibility

---

package.json
src/rust-crypto/browserify-index.ts
yarn.lock

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/3182.
Even this took me an annoyingly long time to figure out. We *really* need to figure out if browserify is important to us.
---

Stub out the rust crypto implementation for browserify

---

CHANGELOG.md

Remove items incorrectly included in changelog for 23.4.0

---

spec/unit/pushprocessor.spec.ts
src/@types/PushRules.ts
src/pushprocessor.ts

This implements the **stable** version of [MSC3758](https://github.com/matrix-org/matrix-spec-proposals/pull/3758) -- a new push rule condition to match an event property exactly (instead of globbing).
MSC3758 is in the final comment period, but not yet merged. We must wait until it finishes FCP before merging.
~~This is currently based on #3134, I'll rebase once that is merged.~~
-   [x] ~~Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md))~~
---
* Implement MSC3758: a push rule condition to match event properties exactly …

Implement MSC3758: a push rule condition to match event properties exactly

---

spec/unit/webrtc/call.spec.ts
spec/unit/webrtc/groupCall.spec.ts
src/webrtc/call.ts
src/webrtc/callFeed.ts
src/webrtc/callTrack.ts
src/webrtc/feedPublication.ts
src/webrtc/localCallFeed.ts
src/webrtc/localCallTrack.ts
src/webrtc/remoteCallFeed.ts
src/webrtc/remoteCallTrack.ts
src/webrtc/trackPublication.ts

I am not 100% happy with the abstraction - let me know if you have any thoughts
---

Abstract publishing

---

spec/unit/pushprocessor.spec.ts
src/@types/PushRules.ts
src/pushprocessor.ts

Implements the **stable** version of [MSC3966](https://github.com/matrix-org/matrix-spec-proposals/pull/3966) which adds a push rule condition to check for a value in an array.
MSC3966 is in the final comment period, but not yet merged. We must wait until it finishes FCP before merging.
~~This is currently based on matrix-org/matrix-js-sdk#3179, I'll rebase once that is merged.~~
-   [x] ~~Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md))~~
---
* Implement MSC3966: a push rule condition to check if an array contains a value …

Implement MSC3966: a push rule condition to check if an array contains a value

---

src/models/beacon.ts

To aid in `strictNullChecks` [work in react-sdk](https://github.com/vector-im/element-web/issues/24756), remove unnecessary optional operator on `_beaconInfo`
https://github.com/vector-im/element-web/issues/24756
---

adjust beacon model to make beaconInfo definitely assigned in constructor

---

src/rust-crypto/KeyClaimManager.ts
src/rust-crypto/RoomEncryptor.ts
src/rust-crypto/rust-crypto.ts

A couple of fixes for things that I messed up in #3122.
---
* Fixes to event encryption in the Rust Crypto implementation ([\#3202](https://github.com/matrix-org/matrix-js-sdk/pull/3202)).

Fixes to event encryption in the Rust Crypto implementation

---

.github/workflows/backport.yml
.github/workflows/docs-pr-netlify.yaml
.github/workflows/notify-downstream.yaml
.github/workflows/pull_request.yaml
.github/workflows/release-npm.yml
.github/workflows/release.yml
.github/workflows/sonarcloud.yml
.github/workflows/sonarqube.yml
.github/workflows/tests.yml
.github/workflows/upgrade_dependencies.yml

Type: Task
Related: https://github.com/matrix-org/matrix-js-sdk/pull/3208
Related: https://github.com/matrix-org/matrix-react-sdk/pull/10351
Related: https://github.com/vector-im/element-web/pull/24786
Previously, we used tags to version third-party actions. t3chguy suggested we should pin them to specific commit hashes by default.
---

Pin versions of third-party github actions

---

src/client.ts

Export `TimestampToEventResponse` to use in `matrix-react-sdk` tests
Part of https://github.com/matrix-org/matrix-react-sdk/pull/10405
-   [ ] ~~Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md))~~
---

Export `TimestampToEventResponse` to use in `matrix-react-sdk` tests

---

spec/unit/webrtc/stats/statsCollector.spec.ts
spec/unit/webrtc/stats/statsReportEmitter.spec.ts
src/webrtc/call.ts
src/webrtc/groupCall.ts
src/webrtc/stats/statsCollector.ts
src/webrtc/stats/statsReport.ts
src/webrtc/stats/statsReportEmitter.ts

Export WebRTC stats metrics as GroupCall Event.
This is a cleanup for: https://github.com/matrix-org/matrix-js-sdk/pull/3220
---

Exporting live WebRTC metric as GroupCall Event from SDK #3220

---

spec/integ/crypto.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/common-crypto/CryptoBackend.ts
src/crypto/index.ts
src/rust-crypto/rust-crypto.ts
src/sync.ts

Fix https://github.com/vector-im/element-web/issues/24795#event-8732738550
---
* Send one time key count and unused fallback keys for rust-crypto ([\#3215](https://github.com/matrix-org/matrix-js-sdk/pull/3215)). Fixes vector-im/element-web#24795. Contributed by @florianduros.

Send one time key count and unused fallback keys for rust-crypto

---

spec/unit/pushprocessor.spec.ts
src/@types/PushRules.ts
src/client.ts
src/models/event.ts
src/pushprocessor.ts

-   [x] ~~Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md))~~
See matrix-org/matrix-react-sdk#9983 & matrix-org/matrix-spec-proposals#3952.
Fixes vector-im/element-web#24376
---
* Implement MSC3952: intentional mentions ([\#3092](https://github.com/matrix-org/matrix-js-sdk/pull/3092)). Fixes vector-im/element-web#24376.

Implement MSC3952: intentional mentions

---

src/models/room.ts

In certain rooms (e.g. with many state changes hidden via user preferences), the events array presented to `eventShouldLiveIn` may contain 100s of events. As part of its various checks, `eventShouldLiveIn` would get an event's associated ID (reply / relation / redaction parent). It would then use `events.find` to search the entire (possibly large) `events` array to look for the parent. (This by itself seems sub-optimal and should probably change to use a map.)
For many events in a room, there is no associated ID. Unfortunately, `eventShouldLiveIn` did not check whether the associated ID actually exists before running off to search all of `events`, resulting in O(n^2) work.
This changes `eventShouldLiveIn` to first check that there is an associated ID before proceeding with its (slow) …

Stop doing O(n^2) work to find event's home

---

spec/integ/crypto.spec.ts

This Just Works, so I don't know why I didn't enable the test sooner.
---

Enable the `prepareToEncrypt` test for Element-R

---

spec/test-utils/webrtc.ts
spec/unit/webrtc/groupCallEventHandler.spec.ts
src/webrtc/groupCallEventHandler.ts

Redacted group call events should be interpreted as terminated calls.
Closes https://github.com/vector-im/voip-internal/issues/128
---
* Handle group call redaction ([\#3231](https://github.com/matrix-org/matrix-js-sdk/pull/3231)). Fixes vector-im/voip-internal#128.

Handle group call redaction

---

spec/test-utils/webrtc.ts
spec/unit/webrtc/call.spec.ts
spec/unit/webrtc/callFeed.spec.ts
spec/unit/webrtc/groupCall.spec.ts
src/webrtc/call.ts
src/webrtc/groupCall.ts

As explained in the comment. I've added it to the end so this should be completely backwards compatible (although it would be much nicer if it were the first arg, probably).
---

Add the call object to Call events

---

spec/integ/crypto.spec.ts
src/client.ts
src/crypto-api.ts
src/crypto/index.ts
src/rust-crypto/RoomEncryptor.ts
src/rust-crypto/rust-crypto.ts

Fixes https://github.com/vector-im/element-web/issues/24431
~~Based on https://github.com/matrix-org/matrix-js-sdk/pull/3203~~
---

Element-R: Add support for `/discardsession`

---

spec/test-utils/webrtc.ts
spec/unit/webrtc/groupCall.spec.ts
src/webrtc/groupCall.ts

We previously used disposeCall to terminate the call which meant that sometimes a call would never get a hangup event. This changes it so that we always end a call by calling hangup, then do the cleanup when the hangup event arrives, so the cleanup is the same whether we hang up or the other side does.
This means we have somewhere we can reliably end OpenTelemetry spans (we were seeing them sometimes close but other times not).
---

Refactor the way group calls hang up

---

package.json
spec/unit/stores/indexeddb-store-worker.spec.ts
spec/unit/stores/indexeddb.spec.ts
src/store/index.ts
src/store/indexeddb-backend.ts
src/store/indexeddb-local-backend.ts
src/store/indexeddb-remote-backend.ts
src/store/indexeddb-store-worker.ts
src/store/indexeddb.ts

https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase/close_event
For https://github.com/vector-im/element-web/issues/24831
---
* Fire `closed` event when IndexedDB closes unexpectedly ([\#3218](https://github.com/matrix-org/matrix-js-sdk/pull/3218)).

Fire `closed` event when IndexedDB closes unexpectedly

---

spec/unit/room.spec.ts
src/models/room-state.ts
src/models/room.ts

---
* Allow via_servers property in findPredecessor (update to MSC3946) ([\#3240](https://github.com/matrix-org/matrix-js-sdk/pull/3240)). Contributed by @andybalaam.

Allow via_servers property in findPredecessor (update to MSC3946)

---

tsconfig.json

For "reasons", `index.ts` exports everything twice: both directly, and as a "default" object. So, pointing `typedoc` at it means we get a rather redundant "default" module which is just re-exports of everything (see http://matrix-org.github.io/matrix-js-sdk/24.0.0/modules/default.html).
If we point it instead directly at `matrix.ts`, we get rid of the "default" module and everything else continues to work.
---
Some background on those "reasons". It seems to be so that you can do either:
```javascript
// import a specific identifier
import {createClient} from "matrix-js-sdk";  // ES module
var {createClient} = require("matrix-js-sdk"); // CommonJS equivalent
var client = createClient({/* ... */});
```
or:
```javascript
// import default object as 'sdk'
import sdk from "matrix-js-sdk";  // …
```

Remove redundant "default" module in generated typedoc.

---

spec/unit/crypto/secrets.spec.ts
src/client.ts
src/crypto/CrossSigning.ts
src/crypto/EncryptionSetup.ts
src/crypto/SecretStorage.ts
src/crypto/api.ts
src/crypto/dehydration.ts
src/crypto/index.ts
src/matrix.ts
src/secret-storage.ts

This interface currently:
* is in the wrong place (it is tied to the Crypto api, which is unnecessary)
* assumes that we will be using an AES key, which is not necessarily the case
* Has a bad name starting with `I`
This PR attempts to solve all three problems, by splitting the class up, renaming it, and moving it.
The old name is still exported for backwards compatibility.
This is the first step part of a larger piece of work in refactoring the SecretStorage interface (https://github.com/vector-im/element-web/issues/24982)
---

Split up, rename, and move `ISecretStorageKeyInfo`

---

.github/workflows/sonarqube.yml
.github/workflows/tests.yml

They're already checked on the PR
Fixes issue with merge queue always failing if new code coverage on develop < 80%
---

Skip sonarcloud & coverage in merge_queue

---

src/webrtc/call.ts

For apps that need acces to the per connection as soon as it's created for debugging etc.
---

Add an event emitted when a Call creates a PeerConnection

---

package.json
spec/integ/crypto.spec.ts
spec/test-utils/test-utils.ts
src/rust-crypto/index.ts
src/rust-crypto/rust-crypto.ts
yarn.lock

Currently, any event which is received before the decryption keys will not be decrypted. We can fix this by retrying decryption after keys are received.
Fixes https://github.com/vector-im/element-web/issues/24489
~~Requires https://github.com/matrix-org/matrix-rust-sdk/pull/1704~~
---
* Element-R: handle events which arrive before their keys ([\#3230](https://github.com/matrix-org/matrix-js-sdk/pull/3230)). Fixes vector-im/element-web#24489.

Element-R: handle events which arrive before their keys

---

spec/unit/crypto/secrets.spec.ts
src/client.ts
src/crypto/EncryptionSetup.ts
src/crypto/SecretStorage.ts
src/crypto/api.ts
src/crypto/index.ts
src/secret-storage.ts

We have a number of interfaces related to SecretStorage defined either in `crypto/api` or `crypto/SecretStorage`. This isn't entirely appropriate, because the SecretStorage implementation is orthogonal to the E2EE implementation.
This PR moves those interfaces out to `secret-storage.ts`, which was started in #3242. It is part of a larger piece of work in refactoring the SecretStorage interface (vector-im/element-web#24982).
Suggest reviewing commit-by-commit
---

Move `SecretStorage`-related interfaces out to new module

---

spec/integ/sliding-sync-sdk.spec.ts
src/crypto/index.ts
src/sliding-sync-sdk.ts

Following comment about sliding sync in https://github.com/matrix-org/matrix-js-sdk/pull/3215#discussion_r1144640847
The purpose is to use the `processKeyCounts` method of the `CryptoBackend` interface  to process one time key counts and unused fall back keys after a `/sync` instead of using a duplicated behaviour
The sliding sync tests about it are eased because the `processKeyCounts` behaviour is already tested in https://github.com/matrix-org/matrix-js-sdk/blob/develop/spec/integ/crypto.spec.ts#L1966
Also
- `processKeyCounts` is implemented by old and …

Use `processKeyCounts` in sliding sync

---

spec/integ/matrix-client-methods.spec.ts
spec/unit/rendezvous/rendezvous.spec.ts
src/@types/auth.ts
src/client.ts
src/feature.ts
src/rendezvous/MSC3906Rendezvous.ts

---
* Support for MSC3882 revision 1 ([\#3228](https://github.com/matrix-org/matrix-js-sdk/pull/3228)). Contributed by @hughns.

Support for MSC3882 revision 1

---

src/crypto/SecretStorage.ts

Another case where we were importing types as normal imports which confuses bundlers.
---

Fix another export type

---

.github/workflows/pull_request.yaml
src/client.ts

Renamed because it clashes with ICapabilities from embedded. I would happily take alternative naming suggestions.
---

Export type for return of getCapabilities()

---

src/store/index.ts
src/store/memory.ts
src/store/stub.ts
src/sync.ts

The only implementation of this is an async function, but I can’t await it because the interface hides the return type.
signed-off-by austin ellis <austin@hntlabs.com>
Type: defect
---
* Change `Store.save()` to return a `Promise` ([\#3221](https://github.com/matrix-org/matrix-js-sdk/pull/3221)). Contributed by @texuf.

Change `Store.save()` to return a `Promise`

---

.github/workflows/tests.yml
jest.config.ts
package.json
yarn.lock

Two functional changes here:
* Set `silent: false` for the [GitHub Actions Reporter](https://jestjs.io/docs/configuration#github-actions-reporter), which stops it swallowing failure reasons (otherwise it only puts it in an annotation)sends it to annotations)
* Enable the `summary` reporter, which makes it easier to see why a test run as a whole failed.
Setting `silent: false` requires us to use a config file, and using a config file overrides the config from `package.json`. So in the end it's easier just to have one config file with some intelligence for whether we are in GHA or not.
---
Add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is plus `X-Breaking-Change` if it's a …

Improve output in github actions for jest tests

---

src/rust-crypto/rust-crypto.ts

The rust crypto-sdk expects `UserId`s, not raw strings.
Follow-up to #3254
---

Element-R: fix to device list change notifications

---

spec/unit/secret-storage.spec.ts
src/crypto/EncryptionSetup.ts
src/secret-storage.ts

Obviously, `getAccountDataFromServer` can return null.
---

Typescript fix to `AccountDataClient`

---

src/matrix.ts

Followup to #3275
Fixes a warning from webpack:
[element-js] WARNING in ../matrix-js-sdk/src/matrix.ts 46:0-61
[element-js] "export 'OutgoingRoomKeyRequest' was not found in './crypto/store/base'
---

OutgoingRoomKeyRequest is only a type

---

src/models/typed-event-emitter.ts

I'm not 100% sure that this is the right thing to do, but...
Currently, `TypedEventEmitter<Events>` overrides `eventNames()` to say that it can only return events of type `Events`. This is problematic, because of the following situation:
Suppose you have a method which wants to register a listener for `FooEvent`s. To do so, it needs an event emitter which is a known source of `FooEvent`s. In other words, it takes an `eventEmitter` parameter of type `TypedEventEmitter<FooEvent>`.
But now suppose we have a class which can emit all sorts of different events, *including*, but not limited to, `FooEvent`. This class extends `TypedEventEmitter<FooEvent|BarEvent|BazEvent>`, which is great as far as the `emit` and `addListener` methods go, and should be fine for our method's needs. However, we …

Remove `eventNames` from `TypedEventEmitter`

---

spec/unit/crypto.spec.ts
spec/unit/matrix-client.spec.ts
src/client.ts
src/crypto/index.ts
src/secret-storage.ts

There is no reason to indirect secret storage via the Crypto layer, and exposing it directly means it will work for Element-R.
Fixes: https://github.com/vector-im/element-web/issues/24982
---

Expose ServerSideSecretStorage independently of Crypto

---

src/webrtc/call.ts

`getCapabilities` exists now(?), but `setCodecPreferences` doesn't, which means it would throw an error and fail the call.
---
* Fix screen sharing on Firefox 113 ([\#3282](https://github.com/matrix-org/matrix-js-sdk/pull/3282)). Contributed by @tulir.

Fix screen sharing on Firefox 113

---

spec/unit/matrix-client.spec.ts

https://github.com/vector-im/element-web/issues/24927
Unit test `paginateEventTimeline` with notifications timeline before changing it
---

unit test paginating /notifications

---

spec/integ/matrix-client-methods.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/crypto-api.ts
src/crypto/index.ts
src/rust-crypto/rust-crypto.ts

A precursor to https://github.com/vector-im/element-web/issues/25092
---

Element-R: implement `{get,set}TrustCrossSignedDevices`

---

spec/integ/matrix-client-methods.spec.ts
spec/unit/crypto/verification/sas.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/common-crypto/CryptoBackend.ts
src/crypto-api.ts
src/crypto/CrossSigning.ts
src/crypto/index.ts
src/matrix.ts
src/rust-crypto/rust-crypto.ts

Define a new endpoint to replace the existing `checkDeviceTrust` which is awkward to implement in rust.
Review commit-by-commit.
Based on https://github.com/matrix-org/matrix-js-sdk/pull/3281.
Part of https://github.com/vector-im/element-web/issues/25092.
---

New `CryptoApi.getDeviceVerificationStatus` api

---

src/timeline-window.ts

Fixes https://github.com/vector-im/element-web/issues/25104
---
* Fix TimelineWindow getEvents exploding if no neigbouring timeline ([\#3285](https://github.com/matrix-org/matrix-js-sdk/pull/3285)). Fixes vector-im/element-web#25104.

Fix TimelineWindow getEvents exploding if no neigbouring timeline

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/crypto-api.ts
src/crypto/CrossSigning.ts
src/rust-crypto/rust-crypto.ts

... which turns out to be useful
---

`DeviceVerificationStatus`: add new `signedByOwner` property

---

src/client.ts

---
* Deprecate MatrixClient::resolveRoomAlias ([\#3316](https://github.com/matrix-org/matrix-js-sdk/pull/3316)).

Deprecate MatrixClient::resolveRoomAlias

---

spec/unit/webrtc/groupCall.spec.ts
src/webrtc/groupCall.ts

This fixes broken media when someone reconnects to the call after a forced disconnect (when their old call gets replaced immediately by a new call). We listen for changes in the call feeds and the tearing down of the feeds for the old call caused us to remove the feed for the new call.
Also adds the call to the calls map before it'as initialised, such that it's the active call for the user/device when the feedsChanged event arrives, otherwise we'll ignore the event.
---
* Fix lack of media when a user …

Fix lack of media when a user reconnects

---

src/webrtc/call.ts

Note that an answer operation pending process is not treated as an unstable negotiation state and an offer will not rejected from impolite peer. The PR fixes the issue  adding an answer is not in race with renegotiation.'
We not using `await this.peerConn!.setLocalDescription(offer);` parameter less. We would also like to adjust this. Unfortunately, we munging the local SDP before adding it. That needs to be adjust first.
---

Adjust negotiation process for pending answer process

---

spec/unit/sync-accumulator.spec.ts
src/receipt-accumulator.ts
src/sync-accumulator.ts

Part of https://github.com/vector-im/element-web/issues/24629
In order to allow us to write simple unit tests, factor out the part of the sync accumulator that does receipt handling. Later changes may well make this more self-contained. This change is intended to be simple enough that we can convince ourselves by examining it that it has the same behaviour as before.
This code is performance-critical, so I added a couple of tests. When I increased the `testSize` in those tests to 10 million and 1 million, I got these results:
With the old code:
✓ can handle large numbers of identical receipts (8760 ms)
✓ can handle large numbers of receipts for different users and events (12123 ms)
With the new code:
✓ can handle large numbers of identical receipts (9035 ms)
✓ can handle large numbers of …

Factor out ReceiptAccumulator

---

src/@types/uia.ts
src/client.ts
src/interactive-auth.ts

`IAuthData` is the response, not the request. The request is an `IAuthDict`
(I feel like this is very much the sort of confusion that could have been resolved if the type had been documented in the first place.)
---

Fix various APIs which incorrectly use an `IAuthData`

---

spec/unit/webrtc/groupCall.spec.ts
spec/unit/webrtc/stats/groupCallStats.spec.ts
src/webrtc/groupCall.ts
src/webrtc/stats/groupCallStats.ts

Build a group call property to enable stats collecting
---

Make webrtc stats collection optional

---

src/receipt-accumulator.ts
src/sync-accumulator.ts

Part of https://github.com/vector-im/element-web/issues/24629
Move all the logic for processing receipts into the ReceiptAccumulator, so we can create simpler tests, and so it's easier to deal with when we start fixing bugs in it.
It's probably worth looking at this commit-by-commit.
---

Move receipt-specific logic into ReceiptAccumulator

---

src/sync.ts

Closes https://github.com/vector-im/element-web/issues/25214
Notes: Fix racing between one-time-keys processing and sync
---
* Fix racing between one-time-keys processing and sync ([\#3327](https://github.com/matrix-org/matrix-js-sdk/pull/3327)). Fixes vector-im/element-web#25214. Contributed by @florianduros.

Fix racing between one-time-keys processing and sync

---

spec/unit/room.spec.ts
src/models/room.ts

Part of https://github.com/vector-im/element-web/issues/25207
Notes: Added `Room.getLastLiveEvent` and `Room.getLastThread`. Deprecated `Room.lastThread` in favour of `Room.getLastThread`.
---
* Added `Room.getLastLiveEvent` and `Room.getLastThread`. Deprecated `Room.lastThread` in favour of `Room.getLastThread`. ([\#3321](https://github.com/matrix-org/matrix-js-sdk/pull/3321)).

Add `Room.getLastLiveEvent` and `Room.getLastThread`

---

spec/integ/matrix-client-event-timeline.spec.ts
spec/unit/event-timeline-set.spec.ts
src/@types/requests.ts
src/client.ts
src/feature.ts
src/models/thread.ts
src/utils.ts

Type: Enhancement
Fixes: https://github.com/vector-im/element-web/issues/25021
Related: https://github.com/matrix-org/matrix-spec-proposals/pull/3981
---
* Implement MSC 3981 ([\#3248](https://github.com/matrix-org/matrix-js-sdk/pull/3248)). Fixes vector-im/element-web#25021. Contributed by @justjanne.

Implement MSC 3981

---

spec/unit/receipt-accumulator.spec.ts

Part of https://github.com/vector-im/element-web/issues/24629
Set up some basic unit tests before we fix the actual bug and write tests that validate that.
---

Tests for the ReceiptAccumulator

---

spec/unit/matrix-client.spec.ts
src/@types/PushRules.ts
src/client.ts

Removing a pusher [is a bit opaque](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/settings/Notifications.tsx#L444) and violates types
Adds a nice method to MatrixClient to remove a pusher.
Used https://github.com/matrix-org/matrix-react-sdk/pull/10724
For https://github.com/vector-im/element-web/issues/25217
---
* add client method to remove pusher ([\#3324](https://github.com/matrix-org/matrix-js-sdk/pull/3324)). Contributed by @kerryarchibald.

add client method to remove pusher

---

src/interactive-auth.ts

Correct interactive-auth types

---

spec/unit/receipt-accumulator.spec.ts
src/receipt-accumulator.ts

Fixes https://github.com/vector-im/element-web/issues/24629
---
* Accumulate receipts for the main thread and unthreaded separately ([\#3339](https://github.com/matrix-org/matrix-js-sdk/pull/3339)). Fixes vector-im/element-web#24629. Contributed by @andybalaam.

Accumulate receipts for the main thread and unthreaded separately

---

.github/workflows/release-npm.yml

Attempting to fix failure to publish to NPM due to an "invalid token" error https://github.com/matrix-org/matrix-js-sdk/actions/runs/4926808655/jobs/8819822367 .
This reverts commit ca9263fa647e4cfc581a137c389ea646bcf71ce6.
---

Revert "Update JS-DevTools/npm-publish action to v2 (#3336)"

---

spec/unit/crypto/cross-signing.spec.ts
src/client.ts
src/crypto-api.ts
src/crypto/EncryptionSetup.ts
src/crypto/index.ts
src/interactive-auth.ts

Move out of the legacy `crypto` module, give it a rename, pull out a seperate `UIAuthCallback` interface
review commit-by-commit
---

Rename and move `crypto.IBootstrapCrossSigningOpts`

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/rust-crypto/index.ts
src/rust-crypto/rust-crypto.ts

Our new crypto impl is going to need access to the secret storage, to store the cross signing keys, and do key backup
---

Pass SecretStorage into RustCrypto

---

src/webrtc/callFeed.ts

Closes https://github.com/vector-im/element-call/issues/1051
---
* Keep measuring a call feed's volume after a stream replacement ([\#3361](https://github.com/matrix-org/matrix-js-sdk/pull/3361)). Fixes vector-im/element-call#1051.

Keep measuring a call feed's volume after a stream replacement

---

src/content-repo.ts
src/crypto/store/indexeddb-crypto-store-backend.ts
src/crypto/store/memory-crypto-store.ts
src/http-api/fetch.ts
src/http-api/index.ts
src/models/read-receipt.ts
src/models/room-member.ts
src/models/room-state.ts
src/models/room.ts
src/scheduler.ts
src/sliding-sync-sdk.ts
src/store/indexeddb-local-backend.ts
src/sync.ts
src/webrtc/call.ts

Fixes https://github.com/vector-im/element-web/issues/12261
Before
After 
---

Enable better tree shaking

---

.github/workflows/release.yml
package.json
yarn.lock

Will let us avoid gh-pages limits e.g. https://github.com/matrix-org/matrix-js-sdk/actions/runs/4959850423/jobs/8874801036
The current action mangled symlinks (using `cp -L`) which caused later runs of typedoc to get upset, whilst fixing that I also ended up hitting a >10G limit on github-pages so added a prune task
Manually pruned `gh-pages` and re-applied symlinks
---

Fix typedoc release documentation deployment

---

src/client.ts

https://github.com/matrix-org/matrix-js-sdk/pull/3272 added new methods to CryptoApi for accessing user device lists. Mark the old ones as deprecated.
---
* Deprecate device methods in MatrixClient ([\#3357](https://github.com/matrix-org/matrix-js-sdk/pull/3357)).

Deprecate device methods in MatrixClient

---

spec/unit/webrtc/call.spec.ts
spec/unit/webrtc/groupCall.spec.ts
src/webrtc/callFeed.ts
src/webrtc/groupCall.ts

Sometimes when audio and video are muted in an awkward order then the local media stream will be duplicated. 
Then there is a ghost reference to the old stream that is not cleaned up.
Bug Fix for:
https://github.com/vector-im/element-call/issues/1044
---

Check permission on mute mic, only if no audio track exists.

---

spec/unit/sync-accumulator.spec.ts
src/sync-accumulator.ts

if a sync summary for (say) invited_member_count goes from 1 to 0, it should be accumluated as 0, rather than 1.
Fixes https://github.com/vector-im/element-web/issues/23345
---
* correctly accumulate sync summaries. ([\#3366](https://github.com/matrix-org/matrix-js-sdk/pull/3366)). Fixes vector-im/element-web#23345.

correctly accumulate sync summaries.

---

spec/unit/sync-accumulator.spec.ts
src/sync-accumulator.ts

fix accumulated sync summaries - andy review

---

spec/unit/sync-accumulator.spec.ts

Caused by https://github.com/matrix-org/matrix-js-sdk/pull/3367
---

Fix CI failure on develop due to force merged PR and prettier failure

---

spec/unit/stores/indexeddb.spec.ts
src/store/index.ts
src/store/indexeddb-backend.ts
src/store/indexeddb-local-backend.ts
src/store/indexeddb-remote-backend.ts
src/store/indexeddb.ts
src/store/memory.ts
src/store/stub.ts

---
* Add methods to terminate idb worker ([\#3362](https://github.com/matrix-org/matrix-js-sdk/pull/3362)).

Add methods to terminate idb worker

---

src/matrix.ts
src/models/typed-event-emitter.ts

I had cause to figure out wtf these classes were doing, and rather than keep the knowledge to myself I thought I would share it with others...
---

Comments for typed-event-emitter classes

---

src/crypto/verification/request/InRoomChannel.ts

There exists a bug (in the legacy `Crypto` implementation), in which in-room verifications-via-emoji will fail for applications which use the default `pendingEventOrdering` setting.
The basis of the problem is that the verifier sees a local echo of our own outgoing `m.key.verification.mac`. It tries to verify the MAC in that message, which of course fails.
The solution is to treat such local echoes in the same way as remote echoes.
---
* Fix verification bug with `pendingEventOrdering: "chronological"` ([\#3382](https://github.com/matrix-org/matrix-js-sdk/pull/3382)).

Fix verification bug with `pendingEventOrdering: "chronological"`

---

package.json
typedoc.json
yarn.lock

Lets us monitor documentation coverage over time
Example https://pr3379--js-sdk-docs-previews.netlify.app/stable/coverage.svg
---

Add typedoc-plugin-coverage

---

src/models/event-timeline-set.ts
src/models/event-timeline.ts
src/models/thread.ts

Fixes https://github.com/vector-im/element-web/issues/25406
This adds a new way of inserting a related event into a timeline, by adding it after its "parent", and before any event with a later timestamp. Previously a new event like a reaction would appear at the end. This makes it more likely we will guess an ordering close to the correct Sync Order.
We won't need this after MSC3981.
---
* Attempt a potential workaround for stuck notifs ([\#3384](https://github.com/matrix-org/matrix-js-sdk/pull/3384)). Fixes vector-im/element-web#25406. Contributed by @andybalaam.

Attempt a potential workaround for stuck notifs

---

src/crypto-api.ts
src/crypto-api/verification.ts
src/crypto/verification/Base.ts
src/crypto/verification/QRCode.ts
src/crypto/verification/SAS.ts

I need to pull out an interface which is implemented by the `VerificationBase` implementations, but the magic around the event types that are emitted is getting in my way.
Everything is much easier if we declare a single enum that contains all the possible emitted events, rather than having separate enums for each implementation and the base class.
So, here we combine the three enums into one, and, for backwards compatibility, make the old enums be aliases to the new one (which should be safe as they are now supersets of the old ones).
Review commit-by-commit.
Notes: Deprecate `QrCodeEvent`, `SasEvent` and `VerificationEvent`: they are now replaced by a combined `VerifierEvent`.
---
* Deprecate `QrCodeEvent`, `SasEvent` and …

Combine `QrCodeEvent`, `SasEvent` and `VerificationEvent`

---

spec/test-utils/thread.ts
spec/unit/room.spec.ts
src/models/room.ts

fixes https://github.com/vector-im/element-web/issues/25411
PSF-2018
---

Fix mark as unread button

---

spec/test-utils/test-utils.ts
spec/unit/models/thread.spec.ts
spec/unit/room.spec.ts

This is at least a basic test for the code we added in a rush in https://github.com/matrix-org/matrix-js-sdk/pull/3384
---

Test for inserting events into the timeline in timestamp order

---

src/receipt-accumulator.ts

Add more context for why threaded vs unthreaded read receipts
See https://github.com/matrix-org/matrix-js-sdk/pull/3339#discussion_r1195364120
-   [ ] ~~Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md))~~
---

Add more context for why threaded vs unthreaded read receipts

---

src/crypto-api.ts

Followups to #3287 and #3360: minor clarifications to the doc-comments
---

Minor fixes to CryptoApi doc comments

---

spec/unit/event-timeline-set.spec.ts

While attempting to test a new change, I discovered that the test "should allow edits to be added to thread timeline" did not actually fail if its assertions failed. Further, those assertions were incorrect.
So this change fixes the test to create the thread, wait for it to be initialised, and then add events to it. This simplifies the flow and ensures the test fails if something unexpected happens.
Part of https://github.com/vector-im/element-web/issues/10954
---

Fix an existing test for editing messages in threads

---

spec/unit/models/thread.spec.ts
src/models/thread.ts

I suggest reviewing commit by commit.
This fixes a part that was missing from [Attempt a potential workaround for stuck notifs](https://github.com/matrix-org/matrix-js-sdk/pull/3384) - that PR inserted events that have arrived in the wrong order into (approx) the correct place in the timeline.
This change refuses to make a local echo receipt for a late-arriving event. We always consider synthesised receipts as the most important, so by making one for an old event, we were fooling ourselves into thinking newer stuff hadn't been read.
(This only applies when we don't have server support for recursive relations. When we do, we will simply trust the order of events from the server, so we won't consider timestamps - we'll just know the most recent event from the server is the most recent …

Only add a local receipt if it's after an existing receipt

---

src/models/thread.ts

The tests already cover this logic - just refactoring it to be clearer.
Slight change: before this did all events that were either in thread or not a relation. In fact, we only do this for thread events, so we explicitly check for messages that are either in the thread or thread roots. This should have the same effect.
Part of https://github.com/vector-im/element-web/issues/10954
---

Adjust fetchEditsWhereNeeded to use a clearer filter and async function

---

spec/unit/pushprocessor.spec.ts
spec/unit/utils.spec.ts
src/models/invites-ignorer.ts
src/utils.ts

Fixes https://github.com/vector-im/element-web/issues/25474
https://spec.matrix.org/v1.7/appendices/#glob-style-matching has no mention of the extended format, Synapse lost support for it in 2021, the extra replacements were meant to be added if extended=true, extended used to default to true, this method was subject to many fat fingers.
---
* Remove spec non-compliant extended glob format ([\#3423](https://github.com/matrix-org/matrix-js-sdk/pull/3423)). Fixes vector-im/element-web#25474.

Remove spec non-compliant extended glob format

---

src/models/room.ts

As should have been done a year ago.
See https://github.com/vector-im/element-web/issues/16068
---
* Mark room version 10 as safe ([\#3425](https://github.com/matrix-org/matrix-js-sdk/pull/3425)).

Mark room version 10 as safe

---

README.md

It seems to work fine, and I have a demo bot with it https://github.com/sigmaSd/deno-matrix-bot
---
* mention deno support in the README ([\#3417](https://github.com/matrix-org/matrix-js-sdk/pull/3417)). Contributed by @sigmaSd.

mention deno support in the README

---

spec/integ/matrix-client-event-timeline.spec.ts
spec/integ/matrix-client-syncing.spec.ts
spec/integ/matrix-client-unread-notifications.spec.ts
spec/integ/sliding-sync-sdk.spec.ts
spec/unit/models/thread.spec.ts
spec/unit/room.spec.ts
src/@types/event.ts
src/client.ts
src/models/event.ts
src/models/room.ts
src/sliding-sync-sdk.ts
src/sync.ts

Fixes https://github.com/vector-im/element-web/issues/25450
Fixes https://github.com/vector-im/element-web/issues/25494
Uses https://github.com/matrix-org/matrix-spec-proposals/pull/4023
If MSC4023 unsigned data is not included it'll use the `/event/` API to fetch the parent event to determine what thread to associate the relation with, it'll then store that unsigned in the sync accumulator to prevent needing to do that work again.
---
* Ensure we do not add relations to the wrong timeline ([\#3427](https://github.com/matrix-org/matrix-js-sdk/pull/3427)). Fixes vector-im/element-web#25450 and vector-im/element-web#25494.

Ensure we do not add relations to the wrong timeline

---

jest.config.ts

... because it is otherwise impossible to see what failed.
This ensures that Jest prints out a list of the failed tests at the end of a test run; by default it will only do so if more than 20 test suites were run.
---

Always show a summary after Jest tests

---

spec/unit/room-member.spec.ts
src/client.ts

This updates the Mutual Rooms ([MSC2666](https://github.com/matrix-org/matrix-spec-proposals/pull/2666)) implementation to match the [latest version](https://github.com/matrix-org/matrix-spec-proposals/pull/2666#issuecomment-1412236010).
This also cleans and clears up the support for older versions of the MSC. The new version paginates, and so that support has been added too.
Type: Task
`Signed-off-by: Jonathan de Jong <jo@jo.wtf>`
---

Update Mutual Rooms (MSC2666) support

---

.github/workflows/cypress.yml
.github/workflows/downstream-artifacts.yml

Part of vector-im/element-web#25313.
Fires off a Cypress test run against a rust-crypto-enabled Element Web R after each js-sdk PR.
Requires https://github.com/matrix-org/matrix-react-sdk/pull/10969.
---

GHA: build and cypress-test a copy of element-web after each push

---

.github/workflows/cypress.yml
.github/workflows/downstream-artifacts.yml

Fixes:
> ```
> error parsing called workflow ".github/workflows/downstream-artifacts.yml" -> "matrix-org/matrix-react-sdk/.github/workflows/element-web.yaml@HEAD" : failed to fetch workflow: reference to workflow should be either a valid branch, tag, or commit
> ```
Fixes to #3412 
---

Fix downstream-artifacts build

---

.github/workflows/downstream-artifacts.yml

(The cypress tests are currently failing and clobbering the results for the react-sdk in Cypress Cloud)
---

Disable downstream artifacts build for develop branch

---

src/matrix.ts
src/models/event.ts
src/models/room.ts
src/models/thread.ts

Export types related to threads from SDK so consumers who also use typescript can easily consume them
Signed-off-by: Stanislav Demydiuk [s.demydiuk@gmail.com](mailto:s.demydiuk@gmail.com)
---
* Export thread-related types from SDK ([\#3447](https://github.com/matrix-org/matrix-js-sdk/pull/3447)). Contributed by @stas-demydiuk.

Export thread-related types from SDK

---

spec/integ/crypto/verification.spec.ts
spec/test-utils/test-data/generate-test-data.py
spec/test-utils/test-data/index.ts

Followup to https://github.com/matrix-org/matrix-js-sdk/pull/3436: another integration test, this time using the QR code flow
---

Integration test for QR code verification

---

src/client.ts
src/feature.ts

Fixes: https://github.com/vector-im/element-web/issues/25497
`supportsIntentionalMentions` was being set using a client option set on client start. react-sdk set this value using a setting with an unstable version controller. react-sdk's `ServerSupportUnstableFeatureController` uses the matrix client to determine support, and is only initialised **after** the client is started. So, intentional mention support in matrix-js-sdk was always falsy.
`supportsIntentionalMentions` is used in react-sdk during client-side notification creation.
Now, intentional mention support uses the client's `canSupport` map. 
This means the user's lab setting does not affect `supportsIntentionalMentions`. Intentional mentions is moving out of labs soon after these bugs are fixed so the impact will be minimal. …

use cli.canSupport to determine intentional mentions support

---

spec/unit/matrix-client.spec.ts
src/@types/event.ts
src/@types/requests.ts
src/client.ts

Adapts the implementation to the latest version of [MSC3912](https://github.com/matrix-org/matrix-spec-proposals/pull/3912#issuecomment-1567173949)
- `with_relations` → `with_rel_types`
- `with_rel_types` is now always a list of strings incl. `*`
- I decided to keep `with_relations` and mark it as deprecated. It should be removed once the MSC becomes stable.
Part of https://github.com/vector-im/element-web/issues/25471
---
* Update MSC3912 implementation to use `with_rel_type` instead of `with_relations` …

Update MSC3912 implementation to use `with_rel_type` instead of `with_relations`

---

spec/integ/crypto/verification.spec.ts
src/crypto/verification/request/VerificationRequest.ts

I'm trying to pull out an interface from `VerificationRequest`, so that I can replace it with a Rust implementation without changes to the application (vector-im/crypto-internal#96).
Currently it exposes `channel` and `qrCodeData` which are entire objects of which only one or two fields are used. By adding more specific methods, we can reduce the amount of stuff that has to be implemented considerably.
Based on #3439 
---

Add new methods to VerificationRequest

---

spec/unit/http-api/fetch.spec.ts
src/http-api/fetch.ts

Fixes: https://github.com/vector-im/element-web/issues/25526
---
* Fix: handle `baseUrl` with trailing slash in `fetch.getUrl` ([\#3455](https://github.com/matrix-org/matrix-js-sdk/pull/3455)). Fixes vector-im/element-web#25526. Contributed by @kerryarchibald.

Fix: handle `baseUrl` with trailing slash in `fetch.getUrl`

---

spec/integ/matrix-client-event-timeline.spec.ts
src/models/room.ts

Fixes https://github.com/vector-im/element-web/issues/25522
---
* Fix thread list being ordered based on all updates ([\#3458](https://github.com/matrix-org/matrix-js-sdk/pull/3458)). Fixes vector-im/element-web#25522.

Fix thread list being ordered based on all updates

---

spec/integ/crypto/verification.spec.ts
src/crypto-api/verification.ts
src/crypto/verification/Base.ts
src/crypto/verification/QRCode.ts
src/crypto/verification/SAS.ts

The abstract base class `VerificationBase` (along with its two concrete subclasses `SAS` and `ReciprocateQRCode`) implement the logic for performing a device or user verification once a specific verification method has been agreed between the two parties.
We want to reimplement this in Rust, so as a first step, pull out an interface from the current Javascript implementation, which in future we can implement with a rust-backed implementation - and deprecate direct access to the old classes..
Notes: Introduce a new `Crypto.Verifier` interface, and deprecate direct access to `VerificationBase`, `SAS` and `ReciprocateQRCode`
Part of https://github.com/vector-im/crypto-internal/issues/95.
---
* Introduce a new `Crypto.Verifier` interface, and …

Element-R: Pull out an interface from `VerificationBase`

---

spec/integ/crypto/cross-signing.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/rust-crypto.ts

---
* Add `rust-crypto#isCrossSigningReady` implementation ([\#3462](https://github.com/matrix-org/matrix-js-sdk/pull/3462)). Contributed by @florianduros.

Add `rust-crypto#isCrossSigningReady` implementation

---

spec/integ/crypto/verification.spec.ts
src/crypto-api/verification.ts
src/crypto/verification/request/VerificationRequest.ts

Notes: Introduce a new `Crypto.VerificationRequest` interface, and deprecate direct access to the old `VerificationRequest` class. Also deprecate some related classes that were exported from `src/crypto/verification/request/VerificationRequest`: `VerificationRequestEvent`, `Phase`.
---
* Introduce a new `Crypto.VerificationRequest` interface, and deprecate direct access to the old `VerificationRequest` class. Also deprecate some related classes that were exported from `src/crypto/verification/request/VerificationRequest` ([\#3449](https://github.com/matrix-org/matrix-js-sdk/pull/3449)).

Pull out a new `VerificationRequest` interface

---

.github/workflows/release-npm.yml

Hi! I was checking in on closed issues in JS-DevTools/npm-publish and noticed a link-back in JS-DevTools/npm-publish#15 to #3350.
Since `npm-publish@v1` uses deprecated GitHub Actions APIs that could stop working at any point, I wanted to help y'all get on v2. There seemed to be two breaking changes that affected your repository:
- v1 modifies `.npmrc` by replacing `NODE_AUTH_TOKEN` (added by `actions/setup-node`) with `INPUT_TOKEN`, v2 no longer makes this modification
- v1 calls `npm publish`, v2 calls `npm publish --ignore-scripts`
This PR upgrades the npm-publish package to v2 and modifies the publish workflow accordingly.
- Upgrade JS-DevTools/npm-publish to [v2.2.0](https://github.com/JS-DevTools/npm-publish/releases/tag/v2.2.0)
- Remove workaround for JS-DevTools/npm-publish#15
- …

Upgrade JS-DevTools/npm-publish to v2.2.0

---

spec/setupTests.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/crypto-api.ts
src/crypto/api.ts
src/rust-crypto/rust-crypto.ts

- Related to https://github.com/vector-im/crypto-internal/issues/120
- Already implemented in the old crypto
- Add a new implementation in the new crypto which is not using Olm.
- I'm using `crypto.getRandomValues` from `crypto/crypto.ts` instead of `global.crypto` because:
- `crypto/crypto.ts` is doing all the job to check into the global variable
- We are calling `subtleCrypto` underneath (`keyFromPassphrase` -> `deviveKey`) which is imported from `crypto/crypto.ts`
- In the test, `global.crypto` can't be override directly (TypeError...). I used …

ElementR: Add `rust-crypto#createRecoveryKeyFromPassphrase` implementation

---

spec/integ/crypto/verification.spec.ts
src/client.ts
src/common-crypto/CryptoBackend.ts
src/crypto-api.ts
src/crypto/index.ts
src/rust-crypto/rust-crypto.ts

Part of https://github.com/vector-im/crypto-internal/issues/97 and https://github.com/vector-im/crypto-internal/issues/98.
Based on https://github.com/matrix-org/matrix-js-sdk/pull/3473
Notes: Deprecate `MatrixClient.findVerificationRequestDMInProgress`, `MatrixClient.getVerificationRequestsToDeviceInProgress`, and `MatrixClient.requestVerification`, in favour of methods in `CryptoApi`.
---
* Deprecate `MatrixClient.findVerificationRequestDMInProgress`, `MatrixClient.getVerificationRequestsToDeviceInProgress`, and `MatrixClient.requestVerification`, in favour of methods in `CryptoApi`. ([\#3474](https://github.com/matrix-org/matrix-js-sdk/pull/3474)).

Add new methods for verification to `CryptoApi`

---

spec/unit/room.spec.ts
src/models/room.ts

Fixes https://github.com/vector-im/element-web/issues/25573
---
* Fix: remove polls from room state on redaction ([\#3475](https://github.com/matrix-org/matrix-js-sdk/pull/3475)). Fixes vector-im/element-web#25573. Contributed by @kerryarchibald.

Fix: remove polls from room state on redaction

---

src/crypto-api.ts

* `CryptoApi` should be first
* `export *` should be last
* everything else in the middle
---

Fix order of things in `crypto-api.ts`

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/index.ts

Previously, if you called `CryptoApi.getUserDeviceInfo()` before the first `/sync` request happened, it would return an empty list, which made a bunch of the tests racy. Add a hack to get the OlmMachine to think about its device lists during startup.
---

Element-R: wait for OlmMachine on startup

---

src/webrtc/mediaHandler.ts

---
* Fix bug where switching media caused media in subsequent calls to fail ([\#3489](https://github.com/matrix-org/matrix-js-sdk/pull/3489)).

Fix bug where switching media caused media in subsequent calls to fail

---

src/models/event-timeline-set.ts
src/models/read-receipt.ts
src/models/thread.ts

---
* Add getLastUnthreadedReceiptFor utility to Thread delegating to the underlying Room ([\#3493](https://github.com/matrix-org/matrix-js-sdk/pull/3493)).

Add getLastUnthreadedReceiptFor utility to Thread delegating to the underlying Room

---

spec/unit/autodiscovery.spec.ts
spec/unit/oidc/register.spec.ts
spec/unit/oidc/validate.spec.ts
src/autodiscovery.ts
src/oidc/error.ts
src/oidc/register.ts
src/oidc/validate.ts

For https://github.com/vector-im/element-web/issues/25468
Used in react-sdk https://github.com/matrix-org/matrix-react-sdk/pull/11074
---
* OIDC: add dynamic client registration util function ([\#3481](https://github.com/matrix-org/matrix-js-sdk/pull/3481)). Contributed by @kerryarchibald.

OIDC: add dynamic client registration util function

---

spec/unit/rust-crypto/rust-crypto.spec.ts

A couple of tests were waiting for a request that wasn't happening, so timing out after 1.5 seconds. Let's avoid the extra slowth.
(This was introduced by changes in https://github.com/matrix-org/matrix-js-sdk/pull/3487, but the changes in this PR do no harm anyway)
---

Element-R: speed up slow unit test

---

spec/unit/event-timeline-set.spec.ts
src/models/event-timeline-set.ts
src/models/room.ts

Relations are not timeline specific
Fixes https://github.com/vector-im/element-web/issues/25596
---
* Aggregate relations regardless of whether event fits into the timeline ([\#3496](https://github.com/matrix-org/matrix-js-sdk/pull/3496)). Fixes vector-im/element-web#25596.

Aggregate relations regardless of whether event fits into the timeline

---

package.json
spec/integ/crypto/verification.spec.ts
spec/test-utils/E2EKeyReceiver.ts
spec/test-utils/E2EKeyResponder.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/rust-crypto/rust-crypto.ts
src/rust-crypto/verification.ts
yarn.lock

Fixes https://github.com/vector-im/element-web/issues/25316
~~Based on https://github.com/matrix-org/matrix-js-sdk/pull/3495~~
Notes: Support for interactive device verification in Element-R.
---
* Support for interactive device verification in Element-R. ([\#3490](https://github.com/matrix-org/matrix-js-sdk/pull/3490)). Fixes vector-im/element-web#25316.

Element-R: Basic implementation of SAS verification

---

.github/workflows/cypress.yml

`cypress.yaml` is currently pinned to an old version of the react-sdk, meaning that each attempt to run it is currently failing with an error.
(See https://github.com/matrix-org/matrix-js-sdk/actions/runs/5355422916:
> `The workflow is not valid. .github/workflows/cypress.yml (Line: 27, Col: 28): Invalid secret, TCMS_USERNAME is not defined in the referenced workflow. .github/workflows/cypress.yml (Line: 28, Col: 28): Invalid secret, TCMS_PASSWORD is not defined in the referenced workflow.`
)
(Introduced by https://github.com/matrix-org/matrix-js-sdk/pull/3480)
---

Bump version of the react-sdk cypress workflow file

---

spec/integ/crypto/verification.spec.ts
src/rust-crypto/rust-crypto.ts

Based on #3497
Part of https://github.com/vector-im/element-web/issues/25319.
Notes: Support for interactive device verification in Element-R.
---
* Support for interactive device verification in Element-R. ([\#3503](https://github.com/matrix-org/matrix-js-sdk/pull/3503)).

Element R: Implement `requestOwnUserVerification`

---

spec/integ/crypto/verification.spec.ts
src/rust-crypto/rust-crypto.ts

Refactor these integration tests. A series of commits which should be reviewable individually.
Based on #3508 .
---

Rearrange the verification integration tests, again

---

spec/integ/crypto/verification.spec.ts
src/crypto-api/verification.ts
src/rust-crypto/verification.ts

Based on #3504
The final part of https://github.com/vector-im/element-web/issues/25319
Notes: Support for interactive device verification in Element-R.
---
* Support for interactive device verification in Element-R. ([\#3505](https://github.com/matrix-org/matrix-js-sdk/pull/3505)).

Element-R: implement cancellation of verification requests

---

spec/integ/crypto/verification.spec.ts

We still seem to be suffering test timeouts. Hopefully this will fix the integ tests, where #3509 etc fix the unit tests.
---

Further fixes to test timeouts

---

spec/unit/oidc/authorize.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/oidc/authorize.ts
src/oidc/error.ts

For https://github.com/vector-im/element-web/issues/25574
Used https://github.com/matrix-org/matrix-react-sdk/pull/11096
[3.1.1.  Authorization Code Flow Steps
](https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth
)
**1. Client prepares an Authentication Request containing the desired request parameters.
2. Client sends the request to the Authorization Server.
3. Authorization Server Authenticates the End-User.
4. Authorization Server obtains End-User Consent/Authorization.
5. Authorization Server sends the End-User back to the Client with an Authorization Code.**
6. Client requests a response using the Authorization Code at the Token Endpoint.
7. Client receives a response that contains an ID Token and Access Token in the response body.
8. Client validates the ID token and …

OIDC: navigate to authorization endpoint

---

spec/unit/rust-crypto/rust-crypto.spec.ts

Followup to https://github.com/matrix-org/matrix-js-sdk/pull/3500: increase the timeout for another test which is also timing out.
---

Increase another crypto test timeout

---

spec/integ/crypto/verification.spec.ts
src/client.ts
src/crypto/index.ts

Previous PRs (https://github.com/matrix-org/matrix-js-sdk/pull/3449, etc) have pulled out an interface from the `VerificationRequest` class, but applications registering for the `CryptoEvent.VerificationRequest` event could still be expecting a fully-fledged class rather than the interface.
To handle this without breaking backwards compat, add a new event type that carries the interface, not the class.
based on https://github.com/matrix-org/matrix-js-sdk/pull/3515
Notes: Deprecate `Crypto.VerificationRequest` application event, replacing it with `Crypto.VerificationRequestReceived`.
---
* Deprecate `Crypto.VerificationRequest` application event, replacing it with `Crypto.VerificationRequestReceived`. …

Create a new event type for verification requests

---

src/@types/requests.ts
src/client.ts

Improve types to match reality around old identity servers

---

src/crypto/verification/SAS.ts

Notes: fix a bug which caused the wrong emoji to be shown during SAS device verification.
The [spec](https://spec.matrix.org/v1.7/client-server-api/#sas-method-emoji) mandates U+1F600 ("Grinning Face"), not U+1F642 "Slightly Smiling Face".
---
* fix a bug which caused the wrong emoji to be shown during SAS device verification. ([\#3523](https://github.com/matrix-org/matrix-js-sdk/pull/3523)).

Use the right smiley in emoji verification

---

spec/integ/crypto/verification.spec.ts
src/crypto/verification/QRCode.ts

[`crypto.getRandomValues`](https://nodejs.org/docs/latest-v18.x/api/crypto.html#cryptogetrandomvaluestypedarray) was added to the nodejs library in node 17. However, it was actually available in node 16, hiding under [`crypto.webcrypto`](https://nodejs.org/docs/latest-v16.x/api/webcrypto.html#cryptogetrandomvaluestypedarray). We have some shims that sort this out in `src/crypto/crypto.ts`, so let's use them.
All of this means that we don't need to monkey-patch `crypto` to run the tests on node 16.
---

QRCode: fix breakage on node 16

---

spec/integ/crypto/verification.spec.ts
spec/unit/rust-crypto/verification.spec.ts
src/crypto-api/verification.ts
src/crypto/verification/request/VerificationRequest.ts
src/rust-crypto/verification.ts

Once we have a verification request in flight, we can start a SAS flow by sending an `m.key.verification.start`. This is slightly fiddly because at the moment the js-sdk breaks this into two steps: first do a `.beginKeyVerification` on the `VerificationRequest` to immediately get a `Verifier`, and then call `.verify` on the `Verifier` to send the `start` message.
However, in the Rust world, creating the equivalent to a verifier is asynchronous and sends the `start` message.
So, we create a new method which does both, and implement it in legacy crypto for forward compatibility.
Notes: Deprecate `VerificationRequest.beginKeyVerification()` in favour of `VerificationRequest.startVerification()`.
Part of https://github.com/vector-im/element-web/issues/25320.
---
Here's what your changelog …

Element-R: support for starting a SAS verification

---

.github/workflows/tests.yml
package.json

Node 16 is quite old, and is somewhat slow. We don't appear to have any need to support it.
---
* Drop support for Node 16 ([\#3533](https://github.com/matrix-org/matrix-js-sdk/pull/3533)).

Drop support for Node 16

---

src/crypto/verification/SAS.ts

Currently, the anchor emoji has a ["Variation Selector-16"](https://codepoints.net/U+FE0F) (U+FE0F) character after it.
The unicode specs do define U+2694 U+FE0F as a valid sequence (with suggested rendering ![image](https://github.com/matrix-org/matrix-js-sdk/assets/1389908/c9a328f8-6d49-4d45-9b7a-af42627d3122)), but our spec doesn't include the variation selector, and the difference means that my cypress tests (which attempt a verification between Element-R and unrusty Element Web) fail intermittently. As far as I can tell, it doesn't make any difference to our actual displayed output in Element.
Something of a follow-up to https://github.com/matrix-org/matrix-js-sdk/pull/3523, but hopefully this will be the last, because I have regenerated the whole list from the spec data.
---
Here's …

Use the right anchor emoji for SAS verification

---

spec/integ/crypto/verification.spec.ts
spec/unit/rust-crypto/verification.spec.ts
src/rust-crypto/rust-crypto.ts
src/rust-crypto/verification.ts
yarn.lock

Part of https://github.com/vector-im/element-web/issues/25320
~~Based on https://github.com/matrix-org/matrix-js-sdk/pull/3528~~
---

Element-R: Implement `VerificationRequest.accept`

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/rust-crypto/index.ts

It turns out that, for some usecases (in particular, "bot users" for cypress tests), we don't need persistent storage and an in-memory store will be fine.
(It's worth noting that, for that usecase, we *can't* just use the default indexeddb store, since that interferes with the store for the client under test. We could use a different prefix for the indexeddb, but it seems like we might as well avoid the overhead of indexeddb altogether.)
We can also use a memory store for the unit tests.
Based on #3532.
---
* Rust crypto: allow using a memory store ([\#3536](https://github.com/matrix-org/matrix-js-sdk/pull/3536)).

Rust crypto: allow using a memory store

---

package.json
spec/integ/crypto/verification.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
spec/unit/rust-crypto/verification.spec.ts
src/client.ts
src/rust-crypto/index.ts
src/rust-crypto/verification.ts
yarn.lock

A couple of little methods on `VerificationRequest`
Part of https://github.com/vector-im/element-web/issues/25320
Based on https://github.com/matrix-org/matrix-js-sdk/pull/3526
---

Element-R: Implement `VerificationRequest.{timeout,pending}`

---

package.json
spec/unit/oidc/authorize.spec.ts
spec/unit/oidc/validate.spec.ts
src/oidc/authorize.ts
src/oidc/error.ts
src/oidc/validate.ts
yarn.lock

For https://github.com/vector-im/element-web/issues/25657
[3.1.1.  Authorization Code Flow Steps
](https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth
)
1. Client prepares an Authentication Request containing the desired request parameters.
2. Client sends the request to the Authorization Server.
3. Authorization Server Authenticates the End-User.
4. Authorization Server obtains End-User Consent/Authorization.
5. Authorization Server sends the End-User back to the Client with an Authorization Code.
6. Client requests a response using the Authorization Code at the Token Endpoint.
7. Client receives a response that contains an ID Token and Access Token in the response body.
8. **Client validates the ID token** and retrieves the End-User's Subject Identifier.
-   [ ] Tests …

OIDC: validate id token

---

src/crypto/algorithms/olm.ts

Specifically, when checking the event sender matches who sent us the session keys we skip waiting for pending device list updates if we already know who owns the session key.
This mitigates some of https://github.com/vector-im/element-web/issues/24682.
I've also stuck an try/catch across the `downloadKeys(..)` call, on the assumption that it would make it easier to track this failure mode down. I've completely made up the new `OLM_BAD_SENDER_CHECK_FAILED` error code.
Ideally, I think instead of doing it like this we'd instead specifically track who sent us the session keys (or at least, who we believe session keys should be from), and match against those when we do the decryption. But that's a bigger job and I think this should help a bunch while this gets fixed properly.
---
Here's what …

Fix an instance of failed to decrypt error when an in flight `/keys/query` fails.

---

spec/unit/models/event.spec.ts
src/models/event.ts

---
* Ignore thread relations on state events for consistency with edits ([\#3540](https://github.com/matrix-org/matrix-js-sdk/pull/3540)).

Ignore thread relations on state events for consistency with edits

---

src/client.ts
src/webrtc/callEventTypes.ts
src/webrtc/groupCall.ts
src/webrtc/groupCallEventHandler.ts

Fixes https://github.com/vector-im/voip-internal/issues/168
Requires https://github.com/vector-im/element-call/pull/1159
---

Put LiveKit info into the `m.call` state event

---

src/crypto/backup.ts
src/crypto/index.ts

When the client is stopped the background upload of keys to backup is not shutdown.
Added a new stop() api that is called by crypto (similar to outgoingRoomKeyRequestManager , deviceList ..)
---
* add stop() api to BackupManager for clean shutdown ([\#3553](https://github.com/matrix-org/matrix-js-sdk/pull/3553)).

add stop() api to BackupManager for clean shutdown

---

spec/integ/matrix-client-event-timeline.spec.ts
spec/test-utils/thread.ts
spec/unit/models/thread.spec.ts
spec/unit/room.spec.ts
src/models/thread.ts

Fixes https://github.com/vector-im/element-web/issues/25395
Currently the `fetchRootEvent` method would get called for each emit of `Room.Timeline` which meant if a thread was found with 10 events, we'd call `/event/` 10 times. A lot of our tests seem to expect the `/event/` API being hammered which should have been a red flag much much earlier. This change doesn't fix all the issues with the Thread model (https://github.com/matrix-org/matrix-js-sdk/pull/3542 aims to do that) but helps avoid calling the init code paths multiple times (especially at the same time). The only time the init code path will be re-called is if the last event was redacted just to simplify the change. Perfect is the enemy of freaking hugely better.
---
* Prevent …

Prevent threads code from making identical simultaneous API hits

---

src/crypto/index.ts

Previously, we only marked the time that we re-created an Olm session after the session was created.  So if we try to unwedge while we're in the middle of unwedging, it won't be rate-limited, and we end up creating multiple new sessions.  This patch sets up rate limiting before any `await`s, with a delay of 5 minutes, so it doesn't race any more.
Fixes https://github.com/vector-im/element-web/issues/25716
No tests yet because I'm not sure how to test this.  Suggestions welcome.
---
* Don't allow Olm …

Don't allow Olm unwedging rate-limiting to race

---

package.json
spec/test-utils/oidc.ts
spec/unit/autodiscovery.spec.ts
spec/unit/oidc/authorize.spec.ts
spec/unit/oidc/validate.spec.ts
src/autodiscovery.ts
src/oidc/authorize.ts
src/oidc/discovery.ts
src/oidc/validate.ts
yarn.lock

For https://github.com/vector-im/element-web/issues/25392
- adds `oidc-client-ts` library
- use `oidc-client-ts` for discovery and authorization url creation
- deprecate `autodiscovery.validateDiscoveryAuthenticationConfig` and `generateAuthorizationUrl`
---

OIDC: use `oidc-client-ts`

---

src/embedded.ts

As per comment, so we can start digging ourselves out of the widget API hole we're currently in.
---

Send 'contentLoaded' event

---

spec/integ/crypto/verification.spec.ts
src/crypto-api/verification.ts
src/crypto/verification/request/VerificationRequest.ts
src/rust-crypto/verification.ts

The api to generate a QR code is async in rust, and the easiest way to deal with it is to make a new method.
Notes: Deprecate `VerificationRequest.getQRCodeBytes` and replace it with the asynchronous `generateQRCode`.
---
* Deprecate `VerificationRequest.getQRCodeBytes` and replace it with the asynchronous `generateQRCode`. ([\#3562](https://github.com/matrix-org/matrix-js-sdk/pull/3562)).

Add async method for generating a QR code

---

spec/test-utils/webrtc.ts
spec/unit/embedded.spec.ts
spec/unit/webrtc/groupCallEventHandler.spec.ts

Fixes https://github.com/vector-im/element-call/issues/1224
---

Appease CI on `livekit` branch

---

spec/integ/matrix-client-methods.spec.ts
src/client.ts

While making it more resilient to causing issues like nuking room state
Removes the need to pass the current power level `event` param
Fixes https://github.com/vector-im/element-web/issues/13900
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/1844
---
* Simplify `MatrixClient::setPowerLevel` API ([\#3570](https://github.com/matrix-org/matrix-js-sdk/pull/3570)). Fixes vector-im/element-web#13900 and #1844.

Simplify `MatrixClient::setPowerLevel` API

---

spec/unit/embedded.spec.ts
src/embedded.ts

Fixes: https://github.com/matrix-org/matrix-js-sdk/issues/3538
This adds oidc token support to the embedded backend.
---
* add getOpenIdToken to embedded client backend ([\#3571](https://github.com/matrix-org/matrix-js-sdk/pull/3571)). Fixes #3538. Contributed by @toger5.

add getOpenIdToken to embedded client backend

---

src/common-crypto/CryptoBackend.ts
src/rust-crypto/CrossSigningIdentity.ts
src/rust-crypto/KeyClaimManager.ts
src/rust-crypto/OutgoingRequestProcessor.ts
src/rust-crypto/RoomEncryptor.ts
src/rust-crypto/device-converter.ts
src/rust-crypto/index.ts
src/rust-crypto/rust-crypto.ts
src/rust-crypto/secret-storage.ts
src/rust-crypto/verification.ts

... for the avoidance of doubt such as that discussed at https://github.com/matrix-org/matrix-js-sdk/pull/3565#pullrequestreview-1522185838
Personally I think this is totally unnecessary but if everybody else thinks this is the only way for things to not be considered part of the public API, I guess I have to live with it.
---

Mark all the rust crypto stuff internal

---

spec/integ/crypto/verification.spec.ts
spec/unit/rust-crypto/verification.spec.ts
src/client.ts
src/crypto-api/verification.ts
src/crypto/verification/request/VerificationRequest.ts
src/rust-crypto/rust-crypto.ts
src/rust-crypto/verification.ts

Before I change *displaying* QR codes, I need an end-to-end test for it. And before I can write an end-to-end test for it, I need to be able to *scan* QR codes. So here is support in the js-sdk for scanning QR codes. It will only work with Rust crypto, but that's enough for a Cypress test, and Rust is the future.
---
* Add support for scanning QR codes during verification, with Rust crypto ([\#3565](https://github.com/matrix-org/matrix-js-sdk/pull/3565)).

Add support for scanning QR codes during verification, with Rust crypto

---

spec/unit/http-api/fetch.spec.ts
src/http-api/fetch.ts

Added simple logging for all requests made from the js-sdk to ease rageshakes investigation.
~~Looks like that:~~
```
FetchHttpApi: GET --> http://localhost:8080/_matrix/client/r0/sync?filter=0&timeout=30000&since=s26_3787_3_8_29_1_12_38_0_1
```
udpated as per to remove url params that could contain secrets
```
FetchHttpApi: PUT --> /_matrix/client/v3/sendToDevice/m.room.encrypted/b8f4c87559504be794f3e1496a8970a5
rageshake.ts:77 FetchHttpApi:  <-- 200 8ms /_matrix/client/v3/sendToDevice/m.room.encrypted/b8f4c87559504be794f3e1496a8970a5
rageshake.ts:77 …
```

Improve logging of http requests to aid debugging

---

spec/unit/crypto/DeviceList.spec.ts

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/2977
---

Fix broken DeviceList.spec.ts test

---

src/client.ts
src/webrtc/callEventTypes.ts
src/webrtc/groupCall.ts
src/webrtc/groupCallEventHandler.ts

Expose method to update it instead and generally simplify a bit: change it to a single string rather than an array of structs.
---
* Don't update calls with no livekit URL ([\#3598](https://github.com/matrix-org/matrix-js-sdk/pull/3598)).

Don't update calls with no livekit URL

---

src/client.ts

Should fix issues like
> ```
> POST /_matrix/client/r0/rooms/{room_id}/receipt/m.read/{event_id} 400
>
> M_INVALID_PARAM: MatrixError: [400] event_id $foo is not related to thread $bar
> ```
---
* Fix read receipt sending behaviour around thread roots ([\#3600](https://github.com/matrix-org/matrix-js-sdk/pull/3600)).

Fix read receipt sending behaviour around thread roots

---

package.json
spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/rust-crypto.ts
yarn.lock

Fixes: https://github.com/vector-im/element-web/issues/25773
---
* Element-R: ensure that `userHasCrossSigningKeys` uses up-to-date data ([\#3599](https://github.com/matrix-org/matrix-js-sdk/pull/3599)). Fixes vector-im/element-web#25773.

Element-R: ensure that `userHasCrossSigningKeys` uses up-to-date data

---

src/matrix.ts

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/3506
---
* Export typed event emitter key types ([\#3597](https://github.com/matrix-org/matrix-js-sdk/pull/3597)). Fixes #3506.

Export typed event emitter key types

---

spec/unit/http-api/fetch.spec.ts
src/http-api/fetch.ts

Log query parameters on HTTP requests
Follow-up to https://github.com/matrix-org/matrix-js-sdk/pull/3485
**Before:**
```
FetchHttpApi: --> GET https://server:8448/some/path
FetchHttpApi: <-- GET https://server:8448/some/path [1234ms 200]
```
**After:**
```
FetchHttpApi: --> GET https://server:8448/some/path?query=xxx
FetchHttpApi: <-- GET https://server:8448/some/path?query=xxx [1234ms 200]
```
All query parameters values are sanitized to `xxx` but the existence of the query parameter is helpful to distinguish between requests and a peace of mind sanity check to see that they are on the request. Like initial vs incremental `/sync` with `?since=xxx`. In the future, it would be nice to log more values.
```
yarn jest spec/unit/http-api/fetch.spec.ts
```
-   [x] Tests written for new code …

Log query parameters on HTTP requests

---

package.json
spec/integ/crypto/verification.spec.ts
spec/unit/rust-crypto/CrossSigningIdentity.spec.ts
spec/unit/rust-crypto/KeyClaimManager.spec.ts
spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
spec/unit/rust-crypto/verification.spec.ts
src/rust-crypto/CrossSigningIdentity.ts
src/rust-crypto/KeyClaimManager.ts
src/rust-crypto/OutgoingRequestProcessor.ts
src/rust-crypto/RoomEncryptor.ts
src/rust-crypto/device-converter.ts
src/rust-crypto/index.ts
src/rust-crypto/rust-crypto.ts
src/rust-crypto/verification.ts
yarn.lock

We've renamed matrix-sdk-crypto-js and released a v1.0.
---

matrix-sdk-crypto-js -> matrix-sdk-crypto-wasm

---

src/@types/global.d.ts
src/client.ts
src/http-api/fetch.ts
src/http-api/interface.ts

Fixes https://github.com/vector-im/element-web/issues/7292
---
* Specify /preview_url requests as low priority ([\#3609](https://github.com/matrix-org/matrix-js-sdk/pull/3609)). Fixes vector-im/element-web#7292.

Specify /preview_url requests as low priority

---

spec/integ/matrix-client-event-timeline.spec.ts
spec/integ/matrix-client-methods.spec.ts
spec/test-utils/thread.ts
spec/unit/read-receipt.spec.ts
spec/unit/room.spec.ts
src/client.ts
src/models/room.ts

Which caused stuck notifications
~Requires https://github.com/matrix-org/matrix-react-sdk/pull/11294~
---
* Fix edge cases around non-thread relations to thread roots and read receipts ([\#3607](https://github.com/matrix-org/matrix-js-sdk/pull/3607)).

Fix edge cases around non-thread relations to thread roots and read receipts

---

src/rust-crypto/rust-crypto.ts

Empirically, this seems to fix some problems with leaking references to IndexedDB.
Fixes: https://github.com/vector-im/element-web/issues/25817
Fixes: https://github.com/vector-im/element-web/issues/25779 I *hope*
---

Make sure to drop references to user device lists

---

spec/integ/crypto/verification.spec.ts
src/rust-crypto/rust-crypto.ts

We were using the local `userId` instead of using the one in the function parameter.
---
* ElementR: Fix `userId` parameter usage in `CryptoApi#getVerificationRequestsToDeviceInProgress` ([\#3611](https://github.com/matrix-org/matrix-js-sdk/pull/3611)). Contributed by @florianduros.

ElementR: Fix `userId` parameter usage in `CryptoApi#getVerificationRequestsToDeviceInProgress`

---

spec/unit/read-receipt.spec.ts
src/client.ts

---
* Only send threaded read receipts if threads support is enabled ([\#3612](https://github.com/matrix-org/matrix-js-sdk/pull/3612)).

Only send threaded read receipts if threads support is enabled

---

spec/unit/room.spec.ts
src/models/event-timeline-set.ts
src/models/room.ts

This caused missing messages especially when building permalink timelines (/context API)
Fixes https://github.com/vector-im/element-web/issues/22603
---
* Fix how `Room::eventShouldLiveIn` handles replies to unknown parents ([\#3615](https://github.com/matrix-org/matrix-js-sdk/pull/3615)). Fixes vector-im/element-web#22603.

Fix how `Room::eventShouldLiveIn` handles replies to unknown parents

---

spec/unit/interactive-auth.spec.ts
src/http-api/errors.ts
src/interactive-auth.ts

Regressed by https://github.com/matrix-org/matrix-js-sdk/pull/3537/files#diff-fb40184a19e00dd3879d5e26bbfeb35c56fcaa4b5d6ef403bef82b0b82ea101bL566-L573
---
* Fix registration check your emails stage regression ([\#3616](https://github.com/matrix-org/matrix-js-sdk/pull/3616)).

Fix registration check your emails stage regression

---

spec/integ/matrix-client-event-timeline.spec.ts
spec/unit/models/thread.spec.ts
spec/unit/room.spec.ts
src/models/thread.ts

Fixes https://github.com/vector-im/element-web/issues/24466
Reverts a small part of https://github.com/matrix-org/matrix-js-sdk/pull/3541
---
* Fix threads ending up with chunks of their timelines missing ([\#3618](https://github.com/matrix-org/matrix-js-sdk/pull/3618)). Fixes vector-im/element-web#24466.

Fix threads ending up with chunks of their timelines missing

---

spec/integ/crypto/megolm-backup.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/crypto-api.ts
src/crypto/index.ts
src/rust-crypto/backup.ts
src/rust-crypto/rust-crypto.ts

... which replaces which replaces `BackupManager.getKeyBackupEnabled()` and `BackupManager.version`
Fixes https://github.com/vector-im/crypto-internal/issues/106
~~Based on https://github.com/matrix-org/matrix-js-sdk/pull/3631~~
---

Add `CryptoApi.getActiveSessionBackupVersion()`

---

spec/unit/event-timeline-set.spec.ts
spec/unit/notifications.spec.ts
spec/unit/room-state.spec.ts
spec/unit/room.spec.ts
src/client.ts
src/models/event.ts

By correctly comparing push rules before & after decryption
I suggest reviewing commit-by-commit
Fixes https://github.com/vector-im/element-web/issues/25803
---
* Ensure we don't overinflate the total notification count ([\#3634](https://github.com/matrix-org/matrix-js-sdk/pull/3634)). Fixes vector-im/element-web#25803.

Ensure we don't overinflate the total notification count

---

spec/unit/event-timeline-set.spec.ts
spec/unit/notifications.spec.ts
spec/unit/room-state.spec.ts
spec/unit/room.spec.ts
src/client.ts
src/models/event.ts

Reverts matrix-org/matrix-js-sdk#3634
Fixes https://github.com/vector-im/element-web/issues/25881
Closes https://github.com/matrix-org/matrix-react-sdk/pull/11341
Reopens https://github.com/vector-im/element-web/issues/25803
Caused worse issues than it fixed, this area of code is awful
---

Revert "Ensure we don't overinflate the total notification count"

---

src/timeline-window.ts

For https://github.com/vector-im/element-web/issues/25873
---
* Bump pagination limit to account for threaded events ([\#3638](https://github.com/matrix-org/matrix-js-sdk/pull/3638)).

Bump pagination limit to account for threaded events

---

spec/integ/matrix-client-event-timeline.spec.ts
src/client.ts
src/models/room.ts

For https://github.com/vector-im/element-web/issues/25676#issue-1778333111
> Some rooms don't clear the unread count / dot when entering them
---
* Skip processing thread roots and fetching threads list when support is disabled ([\#3642](https://github.com/matrix-org/matrix-js-sdk/pull/3642)).

Skip processing thread roots and fetching threads list when support is disabled

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/rust-crypto.ts

Needs https://github.com/matrix-org/matrix-react-sdk/pull/11292
---

ElementR: Throw error if missing `userId` in `CryptoApi.findVerificationRequestDMInProgress`

---

src/crypto/OlmDevice.ts
src/webrtc/groupCallEventHandler.ts

Mark more logs as debug to tidy the console

---

spec/unit/rust-crypto/verification.spec.ts
src/rust-crypto/rust-crypto.ts
src/rust-crypto/verification.ts

---
* ElementR: Process all verification events, not just requests ([\#3650](https://github.com/matrix-org/matrix-js-sdk/pull/3650)). Contributed by @florianduros.

ElementR: Process all verification events, not just requests

---

src/client.ts

We @nordeck are currently implementing the knock rooms behind the feature flag `feature_ask_to_join` (introduced in https://github.com/matrix-org/matrix-react-sdk/pull/11182).
This pull request adds the `join_rule` field to `/publicRooms` response ([MSC2403](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/2403-knock.md#changes-regarding-the-public-rooms-directory)).
- https://github.com/matrix-org/matrix-react-sdk/pull/11464
---
* Add `join_rule` field to /publicRooms response …

Add `join_rule` field to /publicRooms response

---

src/embedded.ts

Start MatrixRTC in embedded mode

---

spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
src/rust-crypto/OutgoingRequestProcessor.ts

`OutgoingRequestProcessor`: do not throw errors if shutting down

---

spec/unit/room.spec.ts
src/models/room.ts

Fixes https://github.com/vector-im/element-web/issues/26033
We can not move the `setSummary` before adding the events to the timeline. Therefore we need a way for applications to know when the summary has been updated so they can update their logic
---
* Emit summary update event ([\#3687](https://github.com/matrix-org/matrix-js-sdk/pull/3687)). Fixes vector-im/element-web#26033.

Emit summary update event

---

spec/integ/crypto/crypto.spec.ts
spec/test-utils/mockEndpoints.ts
src/client.ts
src/crypto-api.ts
src/crypto/backup.ts
src/crypto/index.ts
src/rust-crypto/rust-crypto.ts

Deprecates `prepareKeyBackupVersion`/`createKeyBackupVersion` in favor of a new api `resetKeyBackup` that deletes existing backups if needed and then creates a new one.
Rust Implemention is just stub for now.
---
* Deprecate `MatrixClient.{prepare,create}KeyBackupVersion` in favour of new `CryptoApi.resetKeyBackup` API ([\#3689](https://github.com/matrix-org/matrix-js-sdk/pull/3689)).

Deprecate `MatrixClient.{prepare,create}KeyBackupVersion` in favour of new `CryptoApi.resetKeyBackup` API

---

spec/unit/crypto/secrets.spec.ts
src/crypto/EncryptionSetup.ts

Fixes https://github.com/vector-im/element-web/issues/26115.
Ideally we'd have better tests for this, but since:
1. it's a bug in legacy crypto which we hope to kill off soon
2. the only reason I'm fixing it now is because it broke a cypress test I'm trying to write
... I'm afraid I'm not inclined to spend a lot of time on it.
element-web notes: Fix bug which caused "Set up secure backup" flow not to actually enable  backups.
---
* Legacy crypto: re-check key backup after `bootstrapSecretStorage` ([\#3692](https://github.com/matrix-org/matrix-js-sdk/pull/3692)). Fixes vector-im/element-web#26115.

Legacy crypto: re-check key backup after `bootstrapSecretStorage`

---

src/webrtc/call.ts

For https://github.com/vector-im/element-desktop/issues/1197#issuecomment-1706522499
---
* Allow calls without ICE/TURN/STUN servers ([\#3695](https://github.com/matrix-org/matrix-js-sdk/pull/3695)).

Allow calls without ICE/TURN/STUN servers

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/common-crypto/CryptoBackend.ts
src/crypto-api.ts
src/crypto/CrossSigning.ts
src/crypto/index.ts
src/rust-crypto/CrossSigningIdentity.ts
src/rust-crypto/rust-crypto.ts

... in favour of a new `CryptoApi.getUserVerificationStatus` API
They are the same, but the new one is async.
Part of https://github.com/vector-im/element-web/issues/25752
---
* Deprecate `MatrixClient.checkUserTrust` ([\#3691](https://github.com/matrix-org/matrix-js-sdk/pull/3691)).

Deprecate `MatrixClient.checkUserTrust`

---

spec/integ/matrix-client-syncing.spec.ts
spec/integ/matrix-client-unread-notifications.spec.ts
spec/test-utils/test-utils.ts
spec/unit/sync-accumulator.spec.ts
src/models/room.ts
src/sync-accumulator.ts
src/sync.ts

We [@nordeck](https://github.com/nordeck) are currently implementing the knock rooms behind the feature flag `feature_ask_to_join` (introduced in https://github.com/matrix-org/matrix-react-sdk/pull/11182).
This PR reads `knock` information from the `/sync` endpoint.
Epic: [https://github.com/vector-im/element-web/issues/18655](https://github.com/vector-im/element-web/issues/18655)
---
* Sync knock rooms ([\#3703](https://github.com/matrix-org/matrix-js-sdk/pull/3703)). Contributed by …

Sync knock rooms

---

spec/unit/room.spec.ts
src/models/room.ts

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/3684 and there are lots more details about why we chose this solution in that issue.
---
* Don't reset unread count when adding a synthetic receipt ([\#3706](https://github.com/matrix-org/matrix-js-sdk/pull/3706)). Fixes #3684. Contributed by @andybalaam.

Don't reset unread count when adding a synthetic receipt

---

spec/unit/crypto.spec.ts
src/client.ts
src/common-crypto/CryptoBackend.ts
src/crypto-api.ts
src/crypto/index.ts
src/models/event.ts
src/rust-crypto/rust-crypto.ts

Part of https://github.com/vector-im/element-web/issues/25321. This implements a new API which tells the application what sort of "shield" it should display for a given encrypted event.
We have to do it this way because the Rust crypto SDK wants to expose the information in that way (see https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_common/deserialized_responses/struct.EncryptionInfo.html, and [`VerificationState::to_shield_state_lax`](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_common/deserialized_responses/enum.VerificationState.html#method.to_shield_state_lax).
The logic here is lifted from the current code in react-sdk, https://github.com/matrix-org/matrix-react-sdk/blob/v3.79.0/src/components/views/rooms/EventTile.tsx#L589-L637.
---
Here's what your changelog …

Implement `getEncryptionInfoForEvent` and deprecate `getEventEncryptionInfo`

---

src/models/room.ts

Explain why synthetic receipts don't mark the room as read

---

spec/integ/crypto/rust-crypto.spec.ts
src/client.ts

`T-Defect`
In some environments global.indexedDB is undefined. This is checked in other places of the code but was forgotten in client.clearStores(). This leads to an error being thrown: `TypeError: Cannot read property 'deleteDatabase' of undefined`
---
* Dont access indexed db when undefined ([\#3707](https://github.com/matrix-org/matrix-js-sdk/pull/3707)). Contributed by @finsterwalder.

Dont access indexed db when undefined

---

package.json
spec/unit/rust-crypto/CrossSigningIdentity.spec.ts
src/rust-crypto/CrossSigningIdentity.ts
src/rust-crypto/index.ts
src/rust-crypto/rust-crypto.ts
yarn.lock

Fixes https://github.com/vector-im/crypto-internal/issues/148
---

Element-R: Emit `CryptoEvent.UserTrustStatusChanged` when user identity is updated

---

spec/integ/crypto/megolm-backup.spec.ts
spec/test-utils/test-data/generate-test-data.py
spec/test-utils/test-data/index.ts
src/client.ts
src/common-crypto/CryptoBackend.ts
src/crypto/backup.ts
src/crypto/index.ts
src/rust-crypto/rust-crypto.ts

Introduce a new `BackupDecryptor` interface, which we can implement separately for legacy and Rust crypto.
---

Refactor key backup recovery to prepare for rust

---

spec/unit/interactive-auth.spec.ts

Reading the test "should fire stateUpdated callback with error when a request fails" it looks like this would always cause an infinite loop between doRequest and statusUpdated calls. I don't know why this wasn't a problem until we updated Jest to v29.5.4, but after that point it was.
This change should fix the test failures for the Jest upgrade PR: https://github.com/matrix-org/matrix-js-sdk/pull/3670 .
---

Avoid an infinite loop in the interactive-auth test

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/rust-crypto.ts

Implement the API introduced in #3693 in Rust.
~~Based on #3717.~~ Part of https://github.com/vector-im/element-web/issues/25321
---

Rust implementation of `getEncryptionInfoForEvent`

---

spec/integ/crypto/rust-crypto.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/rust-crypto/index.ts

`pickleKey` is a passphrase set by the application for this express purpose.
Fixes https://github.com/vector-im/element-web/issues/24967
---

Element-R: use the pickleKey to encrypt the crypto store

---

spec/integ/matrix-client-syncing-errors.spec.ts
src/client.ts
src/sync.ts

Type: [defect]`T-Defect`
This PR solves issue: https://github.com/matrix-org/matrix-js-sdk/issues/3678
When you start a client, which has connection problems, a keepAlive is started.
But when the connection is actively stopped e.g. via calling stopSync(), the keepAlive is not aborted and keeps retrying possibly indefinitely.
---
* Stop keep alive, when sync was stoped ([\#3720](https://github.com/matrix-org/matrix-js-sdk/pull/3720)). Contributed by @finsterwalder.

Stop keep alive, when sync was stoped

---

spec/unit/crypto.spec.ts
src/crypto/index.ts
src/rust-crypto/rust-crypto.ts

https://github.com/matrix-org/matrix-js-sdk/pull/3693 attempted to port the logic for event shields from react-sdk to js-sdk, but I seem to have messed up this case.
I've double checked all the logic and... it's hopefully right this time.
---
* Fix the warning for messages from unsigned devices ([\#3743](https://github.com/matrix-org/matrix-js-sdk/pull/3743)).

Fix the warning for messages from unsigned devices

---

.github/workflows/cypress-skipped.yml

Hopefully the comments explain this.
---

Add github action to mark cypress tests skipped

---

src/pushprocessor.ts

For https://github.com/vector-im/element-web/issues/26227
Stop overriding intentional mentions rules, so that users can set their preferences
---
* Remove IsUserMention and IsRoomMention from DEFAULT_OVERRIDE_RULES ([\#3752](https://github.com/matrix-org/matrix-js-sdk/pull/3752)). Contributed by @kerryarchibald.

Remove IsUserMention and IsRoomMention from DEFAULT_OVERRIDE_RULES

---

spec/integ/matrix-client-methods.spec.ts
spec/unit/rendezvous/rendezvous.spec.ts
src/@types/auth.ts
src/client.ts
src/rendezvous/MSC3906Rendezvous.ts

---
* Support for stable MSC3882 get_login_token ([\#3416](https://github.com/matrix-org/matrix-js-sdk/pull/3416)). Contributed by @hughns.

Support for stable MSC3882 get_login_token

---

spec/integ/crypto/crypto.spec.ts
spec/integ/crypto/olm-utils.ts
spec/integ/crypto/verification.spec.ts

Move the tests into `verification.spec.ts`, enable for both stacks, and other cleanups.
Each commit should stand alone.
---

Clean up integ tests for incoming user verification

---

spec/olm-loader.ts
src/browser-index.ts
src/crypto/crypto.ts
src/crypto/index.ts

Switches use of `global` to `globalThis`, which is better supported when building with modern build tools like Vite.
Refs #2903
Exiting tests pass, but to actually test this one needs to include the SDK in an app built with Vite. I've tested against our own, private repo and it works, but if we really need a sample repo for an integration test I could do that.
Signed-off-by: Damon Vestervand <damon@beyondwork.ai>
-   [X] Tests written for new code (and old code if feasible)
-   [X] Linter and other CI checks pass
-   [X] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md))
---

Use globalThis instead of global

---

package.json

Manual backport of https://github.com/matrix-org/matrix-js-sdk/pull/3771 to fix the release process.

Remove the dist script since we no longer have a browserify build

---

spec/integ/crypto/verification.spec.ts
src/rust-crypto/rust-crypto.ts

Fixes https://github.com/vector-im/element-web/issues/26245
---
* Element-R: emit `VerificationRequestReceived` on incoming request ([\#3762](https://github.com/matrix-org/matrix-js-sdk/pull/3762)). Fixes vector-im/element-web#26245.

Element-R: emit `VerificationRequestReceived` on incoming request

---

spec/integ/crypto/verification.spec.ts
src/rust-crypto/verification.ts

Fixes https://github.com/vector-im/element-web/issues/26300
Update doc https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/35
Crash when https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/right_panel/VerificationPanel.tsx#L432 is executed when a device doesn't support QR Code.
SDK Bindings https://matrix-org.github.io/matrix-rust-sdk-crypto-wasm/classes/VerificationRequest.html#generateQrCode documentation misses that https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk-crypto/src/verification/r …

Element-R: Avoid errors in `VerificationRequest.generateQRCode` when QR code is unavailable

---

src/rust-crypto/OutgoingRequestProcessor.ts

Since #3485, we log every request anyway, so there's no need to log twice.
---

Element-R: don't log every HTTP request

---

src/models/thread.ts

Added to try and help debug https://github.com/vector-im/element-web/issues/26254
---

Warn when we drop an event trying to add it to a thread

---

src/matrixrtc/MatrixRTCSession.ts

This does not resolve the promise until the event is actually send. No network connection would make awaiting on this blocking.
---

make leaveRoomSession async

---

src/models/thread.ts

This is part of my work on https://github.com/vector-im/element-web/issues/26254
---

Comments attempting to explain the addEvent method

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/rust-crypto.ts

Fixes https://github.com/vector-im/element-web/issues/26316
---
* Element-R: Connect device to key backup when crypto is created ([\#3784](https://github.com/matrix-org/matrix-js-sdk/pull/3784)). Fixes vector-im/element-web#26316. Contributed by @florianduros.

Element-R: Connect device to key backup when crypto is created

---

spec/unit/http-api/fetch.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/http-api/fetch.ts
src/http-api/interface.ts
src/rust-crypto/index.ts
src/rust-crypto/rust-crypto.ts

Allow clients to specify a logger instance when instantiating a matrix client via the `ClientOpts`.
This is is particularly useful for clients that want to support multiple matrix accounts, but I also want to use it in the cypress tests.
It builds on the work done by @clokep in #3484, and replaces that PR.
It's not yet complete - there are still *lots* of places that use the global `logger` - but it puts the framework in place and catches quite a lot of the main culprits.
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/1899.
---
* Allow applications to specify their own logger instance ([\#3792](https://github.com/matrix-org/matrix-js-sdk/pull/3792)). Fixes #1899.

Allow applications to specify their own logger instance

---

spec/integ/crypto/verification.spec.ts
src/crypto-api/verification.ts
src/rust-crypto/verification.ts

The rust crypto sdk doesn't actually finish QR code verification until the `m.key.verification.done` is received, so make sure we don't tell the application it is done before that happens.
Fixes https://github.com/vector-im/element-web/issues/26293
---
* Element-R: Don't mark QR code verification as done until it's done ([\#3791](https://github.com/matrix-org/matrix-js-sdk/pull/3791)). Fixes vector-im/element-web#26293.

Element-R: Don't mark QR code verification as done until it's done

---

spec/unit/matrixrtc/CallMembership.spec.ts
src/matrixrtc/CallMembership.ts
src/matrixrtc/MatrixRTCSession.ts

I fell into another js-sdk trap: this is "only guaranteed to be set for events that appear in a timeline" and not state events. It does not say why. We only ever used it to get the sender user ID anyway, so just use getSender().
---
* Don't use event.sender in CallMembership ([\#3793](https://github.com/matrix-org/matrix-js-sdk/pull/3793)).

Don't use event.sender in CallMembership

---

package.json
yarn.lock

Fixes https://github.com/vector-im/element-web/issues/26301
The new bindings do not use Dashmap anymore, it was causing the panic
---

Bump wasm bindings version to 2.0.0

---

spec/unit/read-receipt.spec.ts
src/client.ts

As part of investigating https://github.com/vector-im/element-web/issues/26366 I found this code hard to understand, so I extracted it, tested it, and commented it.
It should hopefully be reasonably easy to convince yourself the logic is unchanged if you review commit by commit.
I can well believe that there is a much clearer way to express this - I just expanded the existing logic and would welcome further improvements.
---

Clarify code that chooses a thread ID to include in a receipt

---

src/matrixrtc/MatrixRTCSession.ts

https://github.com/matrix-org/matrix-js-sdk/pull/3756 changed the membership update function to await on the next call, but this meant it never returned and therefore never cleared `updateCallMembershipRunning`. We therefore didn't send the updated call member event when leaving, instead sending it whenever the next poll interval arrived.
This changes it to only await if we are retrying, not if we're just scheduling the next poll.
@toger5 review appreciated on this one - does this line up with what you expected your fix to do?
Fixes https://github.com/vector-im/element-call/issues/1763
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/ …

Fix sending call member events on leave

---

spec/unit/models/thread.spec.ts
src/models/thread.ts

Fixes https://github.com/vector-im/element-web/issues/26254
(hopefully)
Reduce the number of cases where we drop events that we are trying to add to a thread.
I have lots of refactorings I would like to do to addEvent but this change isolates the functional change that may address the referenced bug.
I will be holding off on merging this until after the release candidate on 17th October 2023, so that we can try it out for a couple of weeks and evaluate whether it causes more stuck notifications.
---

Add events to the thread even if they appear to be out of order

---

src/models/event.ts

Per https://github.com/vector-im/element-web/issues/26380, this method is too easy to use accidentally, and per the comments, it doesn't even return a meaningful JSON-serialisation of the object.
---
* Deprecate `MatrixEvent.toJSON` ([\#3801](https://github.com/matrix-org/matrix-js-sdk/pull/3801)).

Deprecate `MatrixEvent.toJSON`

---

spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
src/rust-crypto/OutgoingRequestProcessor.ts

The logs will look something like this:
The first line comes from the rust-sdk; I think it's helpful to also log just before we actually send the batch.
---
* Element-R: log when we send to-device messages ([\#3810](https://github.com/matrix-org/matrix-js-sdk/pull/3810)).

Element-R: log when we send to-device messages

---

src/matrixrtc/MatrixRTCSession.ts

This gets logged very frequently - including once for each room at startup - and it's filling the logs.
/cc @dbkr
---

Reduce some log spam from `MatrixRTCSession.callMembershipsForRoom`

---

src/models/event.ts
src/models/room.ts
src/models/thread.ts

Since the redacted event is moving to the main timeline, the redaction belongs there too, since its relationship to the redacted event is the only thing making it part of the thread.
It's possible this will fix some flakiness in our read receipt tests. I found it while investigating them...
Part of https://github.com/vector-im/element-web/issues/24392
---
* Move the redaction event to main at the same time we move redacted ([\#3815](https://github.com/matrix-org/matrix-js-sdk/pull/3815)). Contributed by @andybalaam.

Move the redaction event to main at the same time we move redacted

---

spec/unit/models/event.spec.ts
src/models/event.ts
src/models/room.ts
src/models/thread.ts

My [recent change](https://github.com/matrix-org/matrix-js-sdk/pull/3798) moved threaded messages into the main timeline when they were redacted.
I realised we should not do this to thread roots, as they need to stay "in" both the main timeline and the thread, so we can render a thread UI from them, even though they are redacted.
Part of https://github.com/vector-im/element-web/issues/24392
---
* Don't remove thread info from a thread root when it is redacted ([\#3814](https://github.com/matrix-org/matrix-js-sdk/pull/3814)). Contributed by @andybalaam.

Don't remove thread info from a thread root when it is redacted

---

src/matrix.ts

We use these from react-sdk (from crypto, when they were there, but I just moved them and inadvertantly broke react-sdk).
---

Export base64 utils

---

src/rust-crypto/index.ts
src/rust-crypto/rust-crypto.ts

* turn the log level down to DEBUG
* don't pointlessly log every call to `outgoingRequests`
---

Reduce log spam from rust crypto

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/rust-crypto.ts

Fixes part of https://github.com/vector-im/element-web/issues/26272
---
* Element-R: silence log errors when viewing a decryption failure ([\#3821](https://github.com/matrix-org/matrix-js-sdk/pull/3821)).

Element-R: silence log errors when viewing a decryption failure

---

.github/workflows/tests.yml

This uses the latest cached version rather than fetching the latest released version so we don't reply on (and hammer) node's download servers for the very latest version before the actions runners get updated. We'll still stay current, just not quite so aggressively current.
---

Change latest node ver to '*'

---

src/store/indexeddb-local-backend.ts

Resolve https://github.com/vector-im/element-web/issues/25941
Type: defect
---
* Don't emit a closed event if the indexeddb is closed by Element ([\#3832](https://github.com/matrix-org/matrix-js-sdk/pull/3832)). Fixes vector-im/element-web#25941. Contributed by @dhenneke.

Don't emit a closed event if the indexeddb is closed by Element

---

src/client.ts
src/common-crypto/CryptoBackend.ts
src/rust-crypto/rust-crypto.ts

The current deprecation notice advises you to use a method which does something completely different.
Fixing this "properly" is slightly challenging because we don't want to support setting it to `true` in Rust Crypto; yet I don't really want to change the default for legacy crypto.
Let's just document the behaviour for now.
---

Fix up comments on `globalErrorOnUnknownDevices`

---

spec/integ/matrix-client-event-emitter.spec.ts
spec/unit/event-mapper.spec.ts
spec/unit/matrix-client.spec.ts
spec/unit/stores/indexeddb.spec.ts
src/client.ts
src/models/user.ts
src/store/index.ts
src/store/indexeddb.ts
src/store/memory.ts
src/store/stub.ts
src/sync.ts

Storage classes - `memory.ts` and `indexeddb.ts` both create user objects without setting it up to emit events on matrix client.
This is sometimes preventing the memberlist from updating on incoming presence events because [this listener](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/rooms/MemberList.tsx#L152) never runs.
---
* Fix reemitter not being correctly wired on user objects created in storage classes ([\#3796](https://github.com/matrix-org/matrix-js-sdk/pull/3796)). Contributed by @MidhunSureshR.

Fix reemitter not being correctly wired on user objects created in storage classes

---

spec/integ/matrix-client-methods.spec.ts
src/@types/auth.ts
src/client.ts

To be merged after:
- https://github.com/matrix-org/matrix-js-sdk/pull/3416
- https://github.com/matrix-org/matrix-react-sdk/pull/11001
---

Remove deprecated support for unstable MSC3882

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml
.github/workflows/release-master.yml
.github/workflows/release-npm.yml
.github/workflows/release.yml
docs/SUMMARY.md
docs/release.md

Fixes https://github.com/vector-im/wat-internal/issues/21
Notes:
+ Changes our first RC from `rc.1` to `rc.0`
+ Switches from allchange to release-drafter set up with similar rules
Example:
https://github.com/t3chguy/matrix-js-sdk/pull/21 before RC:
Finalise RC0:
https://github.com/t3chguy/matrix-js-sdk/pull/22 after RC:
Finalise as final:
Workflow:
+ Release captain uses automation to cut branches
+ Release captain waits for draft release to be made and reads the release notes for sanity and makes any changes necessary, including changing version number
+ Release captain uses automation to promote the draft release into an RC 0-N times as appropriate
+ Release captain uses automation to promote the draft release into a final one
---
This change is marked as an *internal change* (Task), …

New release automations

---

spec/unit/matrixrtc/CallMembership.spec.ts
spec/unit/matrixrtc/mocks.ts
src/matrixrtc/CallMembership.ts
src/models/event.ts

Reverts matrix-org/matrix-js-sdk#3839.
This turns out to have caused test failures (https://github.com/vector-im/element-web/issues/26500), and there is debate about what the correct fix is.
Fixes https://github.com/vector-im/element-web/issues/26500
---

Revert "Age fallback using origin_server_ts instead of 0"

---

spec/unit/read-receipt.spec.ts
spec/unit/room.spec.ts
src/models/read-receipt.ts

Helps with some of the flaking redaction tests, and some of the just-plain-failing editing tests.
We were seeing bugs where the latest receipt was not pointing at an event in this thread (or an event we had at all), so the room was considered unread, but we were unable to send a correct receipt because we already had one. This change means we effectively ignore the existing receipt because we can't use it, allowing us to send a correct one.
Part of https://github.com/vector-im/element-web/issues/24392
When I enable lots of disabled tests (in https://github.com/matrix-org/matrix-react-sdk/pull/11781 ) with this change, they pass consistently on my machine.
---
* Ignore receipts pointing at missing or invalid events …

Ignore receipts pointing at missing or invalid events

---

.github/workflows/cypress.yml

For fixing broken cypress tests. 
The current workfile is pinned to an earlier tag that does not contain the changes to disable sorry-cypress
---

Update workfile to pull in changes from react-sdk

---

spec/test-utils/test-utils.ts
spec/unit/timeline-window.spec.ts
src/timeline-window.ts

Fixes https://github.com/vector-im/element-web/issues/26498 even when https://github.com/matrix-org/matrix-js-sdk/pull/3798 is present.
Listen for events being removed in the TimelineWIndow, and shorten the window if the removal makes it longer than the available events.
---
* Shorten TimelineWindow when an event is removed ([\#3862](https://github.com/matrix-org/matrix-js-sdk/pull/3862)). Fixes vector-im/element-web#26498. Contributed by @andybalaam.

Shorten TimelineWindow when an event is removed

---

spec/unit/matrixrtc/CallMembership.spec.ts
spec/unit/matrixrtc/mocks.ts
src/matrixrtc/CallMembership.ts
src/models/event.ts

Reverts matrix-org/matrix-js-sdk#3854.
This causes significant logspam, and seems like it needs more thought for various other reasons which I've tried to set out at https://github.com/matrix-org/matrix-js-sdk/pull/3861#issuecomment-1803863086.
---

Revert "Better fallback for unavailable event age"

---

.github/workflows/tests.yml

Run tests on LTS and Node 21

---

.github/workflows/release-action.yml

Fixes https://github.com/vector-im/wat-internal/issues/15
---

Automate checking there is no published release using the version already

---

src/client.ts

Fixes https://github.com/vector-im/element-web/issues/26520
If you're interested in know why we need a `userCreator` in the first place, see https://github.com/matrix-org/matrix-js-sdk/pull/3796#discussion_r1362060951
This PR merely adds a method that sets the store property while making sure that userCreator is also wired correctly.
---
* Ensure `setUserCreator` is called when a store is assigned ([\#3867](https://github.com/matrix-org/matrix-js-sdk/pull/3867)). Fixes vector-im/element-web#26520. Contributed by @MidhunSureshR.

Ensure `setUserCreator` is called when a store is assigned

---

.github/workflows/triage-labelled.yml

This is the equivalent of https://github.com/vector-im/element-desktop/blob/develop/.github/workflows/triage-labelled.yml.
---

Automatically add tech-debt issues to the right project

---

.github/workflows/release-action.yml

Fixes https://github.com/vector-im/wat-internal/issues/17
---

Add automation to advance release blocker labels during the release

---

spec/unit/models/event.spec.ts
spec/unit/room-state.spec.ts
spec/unit/room.spec.ts
src/models/event.ts
src/models/room.ts
src/models/thread.ts

Re-enable the code that was reverted in https://github.com/matrix-org/matrix-js-sdk/pull/3858 due to https://github.com/vector-im/element-web/issues/26498 .
This is fixed by https://github.com/matrix-org/matrix-js-sdk/pull/3862 , which is proved by https://github.com/matrix-org/matrix-react-sdk/pull/11839 .
We will delay merging this until after the RC on 14th November, since it remains a risky change that we want to validate for as long as possible on develop.element.io before we include it in a release.
---
* Unrevert "Move redacted messages out of any thread, into main thread" ([\#3869](https://github.com/matrix-org/matrix-js-sdk/pull/3869)). Contributed by @andybalaam.

Unrevert "Move redacted messages out of any thread, into main thread"

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/@types/event.ts
src/matrixrtc/MatrixRTCSession.ts
src/matrixrtc/types.ts

This adds the `CallNotify` event type and the corresponding `ICallNotifyContent`
Also this adds a sessionId to matrixRTCSessions. The sessionId is the value of call_id of the first membership. The memberships for a session are filtered by that id. So we can take either membership to calculate the sessionId
---
* Add CallNotifyEvent to support matrixRTC ringing ([\#3878](https://github.com/matrix-org/matrix-js-sdk/pull/3878)). Contributed by @toger5.

Add CallNotifyEvent to support matrixRTC ringing

---

src/matrixrtc/MatrixRTCSession.ts

This could have caused weirdness in non per-user key calling mode.
---
* Don't rotate keys if not managing media keys ([\#3877](https://github.com/matrix-org/matrix-js-sdk/pull/3877)).

Don't rotate keys if not managing media keys

---

.github/workflows/triage-labelled.yml

`inherit` doesn't work across orgs, sadly.
---

Explicitly forward ELEMENT_BOT_TOKEN

---

src/models/MSC3089Branch.ts
src/models/event.ts
src/models/room.ts
src/models/thread.ts

Somebody seems to have decided that `isRetry` needs setting whenever we try to decrypt an event. This is nonsense, and leads to confusing logs.
---

Stop logging decryptions as retries

---

spec/unit/rust-crypto/KeyClaimManager.spec.ts
src/logger.ts
src/rust-crypto/KeyClaimManager.ts
src/rust-crypto/RoomEncryptor.ts
src/rust-crypto/rust-crypto.ts

It's currently rather hard to see what's going on during event encryption in the rust crypto stack. One of the problems is that you can have multiple encryption operations overlapping.
The main idea here is to include an identifier for the event being encrypted on each log line. (We don't yet have an event ID, so instead use the txn ID.) In order to pass this down through the call hierarchy, I've created the idea of a `LogSpan` (drawing inspiration from [OpenTracing](https://opentracing.io/docs/overview/spans/)).
---

Improve logging of event encryption in `RustCrypto`

---

spec/unit/matrixrtc/CallMembership.spec.ts
spec/unit/matrixrtc/MatrixRTCSession.spec.ts
spec/unit/matrixrtc/mocks.ts
src/matrixrtc/CallMembership.ts
src/models/event.ts

State events from a couple of home servers dont return an `age` proptery in their unsigned field. (including element.io).
For an actual exampe, this room: https://matrix.to/#/#thisweekinmatrix:matrix.org can be checked (lots of member events from other homeservers are not featuring a unsigned.age field): 
Call state events are relying on this property to determin if they are expired or not.
Before a non existent age property in the unsigned field resulted in falling back to 0. The `localTimestamp` was then `Date.now()` at the time of loading this event. Which made it always really recent -> never expired.
-   [x] Sign-off given on the changes (see …

Better fallback for the event `localTimestamp` calculation.

---

src/client.ts
src/models/read-receipt.ts
src/models/thread.ts
src/rust-crypto/RoomEncryptor.ts
src/rust-crypto/rust-crypto.ts
src/webrtc/groupCallEventHandler.ts

There's an awful lot going on in our console at the moment, making it hard to find important stuff, and contributing to poor performance and [poor log retention](https://github.com/vector-im/element-web/issues/26532).
A couple of different things in this PR:
* Increase the `MaxListeners` setting on `MatrixClient` and `Thread`, so that we don't get "possible EventEmitter leak" warnings.
* Disable a couple of warning/info lines that are just part of regular operation and are logged in large volumes.
---

Reduce console log spam

---

src/rust-crypto/RoomEncryptor.ts

Quick improvment on send message performance.
Previously we were waiting on all `key/query` to be processed before sharing the room keys (to ensure having the most up to date device list).
It's a bit too aggressive, and in some case was impacting time to send for no benefits.
In this change we will only wait for `key/query` if the list of member (lazy loading) was just resolved in this send cycle. Because in this case several users might be added to the tracked user list and there is a high risk that their list of devices won't be known yet. And as they might be in the room since long it would be bad that they don't get the key.
If the member list is not just resolved, we don't want to wait on all `key/query`, we just trigger a launch in background. Freshly joined users will get the key …

Only await key query after lazy members resolved

---

spec/unit/room.spec.ts
src/models/read-receipt.ts

This log line fires whenever we check for receipt for any user that points too far back in history for us to have the event loaded. It's far too noisy to be useful.
---

Remove 'Ignoring receipt' log line that logs very often'

---

src/client.ts

As per https://spec.matrix.org/latest/client-server-api/#get_matrixclientv1roomsroomidtimestamp_to_event
---
* Fix type for TimestampToEventResponse.origin_server_ts ([\#3906](https://github.com/matrix-org/matrix-js-sdk/pull/3906)). Contributed by @Half-Shot.

Fix type for TimestampToEventResponse.origin_server_ts

---

.github/workflows/release-make.yml
.github/workflows/release.yml
.github/workflows/static_analysis.yml
package.json
yarn.lock

This is the equivalent of https://github.com/vector-im/element-web/pull/26621 applied to this repository
This, unfortunately, required renaming the `release-action` workflow because its name threw off the validator.
For: https://github.com/matrix-org/matrix-react-sdk/pull/11930
For: https://github.com/vector-im/element-web/pull/26641
For: https://github.com/vector-im/element-desktop/pull/1347
---

Set up CI to lint workflows with action-validator

---

package.json
yarn.lock

There are a bunch of improvements in 3.1.0 ([changelog](https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/blob/main/CHANGELOG.md#matrix-sdk-crypto-wasm-v310)), but in particular this should fix [#26375](https://github.com/vector-im/element-web/issues/26375). 
---

Update to matrix-sdk-crypto-wasm 3.1.0

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/CrossSigningIdentity.ts
src/rust-crypto/rust-crypto.ts

Finalization in Javascript is not guaranteed - sometimes the FinalizationRegistry just forgets to call the finalizers on some objects. This is problematic because it means we leak references on the Rust side, which (as well as causing memory leaks) ultimately leads to us holding open the indexeddb, which then means we can't successfully log in/out.
This isn't meant to be a comprehensive fix, but it does add explicit `free` calls in a number of places which seem particularly prone to leaking, and empirically it was enough for me to get a Cypress test which logs out and back in working again.
---

Explicitly free some Rust-side objects

---

spec/test-utils/thread.ts
spec/unit/models/room-receipts.spec.ts
spec/unit/models/thread.spec.ts
spec/unit/read-receipt.spec.ts
spec/unit/room.spec.ts
src/client.ts
src/models/compare-event-ordering.ts
src/models/event-timeline-set.ts
src/models/read-receipt.ts
src/models/room-receipts.ts
src/models/room.ts
src/models/thread.ts

Part of https://github.com/vector-im/element-web/issues/24392
Needed for https://github.com/matrix-org/matrix-react-sdk/pull/11903
Re-write hasUserReadEvent to store all the information at the Room level. Because we must always consider unthreaded receipts globally, it doesn't make sense to answer this question at the Thread level.
We leave the old code for now, because it does other jobs, but soon, we will delete the old storage of receipts.
---
* Rewrite receipt-handling code ([\#3901](https://github.com/matrix-org/matrix-js-sdk/pull/3901)). Contributed by @andybalaam.

Rewrite receipt-handling code

---

spec/integ/crypto/crypto.spec.ts
src/@types/crypto.ts
src/client.ts
src/crypto-api.ts
src/crypto/index.ts
src/rust-crypto/rust-crypto.ts

`MatrixClient` API was exposing two methods that only worked for legacy crypto:
- `getDeviceEd25519Key`
- `getDeviceCurve25519Key`
=> These are used in the react-sdk for some functionality (rageshake, sentry, rendez-vous).
I have deprectaded those calls from `MatrixClient` and created a new API in `CryptoApi` (where it belongs):
`getOwnDeviceKeys(): Promise<OwnDeviceKeys>`
---

move get device key API from client to crypto

---

spec/integ/crypto/verification.spec.ts
src/client.ts
src/crypto/index.ts
src/rust-crypto/backup.ts
src/rust-crypto/rust-crypto.ts

Add a new crypto event to signal when the key backup decryption key is stored in cache.
Needed for new PRs around backup (would allow to start/resume downloading from a backup)
---

Signal key backup in cache

---

spec/integ/crypto/cross-signing.spec.ts
spec/integ/crypto/crypto.spec.ts
spec/test-utils/AccountDataAccumulator.ts
src/rust-crypto/CrossSigningIdentity.ts
src/rust-crypto/rust-crypto.ts

Currently, `bootstrapCrossSigning` raises an exception if it is called a second time before secret storage is set up. It is easily fixed by checking that 4S is set up before trying to export to 4S.
Also a few logging fixes while we're in the area.
Fixes https://github.com/vector-im/element-web/issues/26393
---
* Rust-crypto: fix `bootstrapCrossSigning` on second call ([\#3912](https://github.com/matrix-org/matrix-js-sdk/pull/3912)). Fixes vector-im/element-web#26393.

Rust-crypto: fix `bootstrapCrossSigning` on second call

---

spec/unit/rust-crypto/verification.spec.ts
src/rust-crypto/rust-crypto.ts
src/rust-crypto/verification.ts

If the acceptance of an incoming verification request races with a `/keys/query` for the other user, then subsequent operations can fail (see https://github.com/matrix-org/matrix-rust-sdk/issues/2896).
This is a slightly hacky workaround that means we wait for the devicelist to arrive for the relevant operations.
Required for a fix to https://github.com/vector-im/element-web/issues/26420.
---

Element-R: await `/keys/query` during Verification requests

---

.github/workflows/cypress.yml

This seems to have been broken by https://github.com/matrix-org/matrix-js-sdk/pull/3914, which changed the name of the status check that is updated.
---

Fix "mark_skipped" action for end-to-end tests

---

spec/integ/crypto/crypto.spec.ts
src/client.ts
src/crypto/index.ts

since its equivalent is done automatically in Rust crypto when we call resetKeyBackup.
Part of https://github.com/vector-im/element-web/issues/26323
---

Call scheduleAllGroupSessionsForBackup during resetKeyBackup

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/common-crypto/CryptoBackend.ts
src/crypto-api.ts
src/crypto/algorithms/megolm.ts
src/crypto/index.ts
src/rust-crypto/rust-crypto.ts

Fixes https://github.com/vector-im/element-web/issues/26347
I also threw in a proper enum for the key source, but I can remove that
---
* Don't back up keys that we got from backup ([\#3934](https://github.com/matrix-org/matrix-js-sdk/pull/3934)). Fixes vector-im/element-web#26347.

Don't back up keys that we got from backup

---

spec/unit/crypto.spec.ts
src/client.ts
src/crypto/RoomList.ts
src/crypto/index.ts

Part of https://github.com/vector-im/element-web/issues/26108
---

Move roomList out of MatrixClient, into legacy Crypto

---

spec/integ/matrix-client-event-timeline.spec.ts
spec/unit/thread-utils.spec.ts
src/client.ts
src/models/thread.ts
src/thread-utils.ts

We used MSC3981 to pass the recurse param to the /relations endpoint so that we could get relations to events in a thread, but we kept the rel_type filter on (as m.thread) so no second-order relations would ever have been returned (a nested thread isn't a thing).
This removes the filter and does some filtering on the client side to remove any events that shouldn't live in the threaded timeline (ie. non-thread relations to the thread root event).
This should help fix stuck unreads because it will avoid the event that the receipt refers to going missing (but only on HSes that support MSC3981).
For https://github.com/vector-im/element-web/issues/26718
-   [ ] Sign-off given on the changes …

Remove m.thread filter from relations API call

---

spec/unit/rust-crypto/RoomEncryptor.spec.ts
src/rust-crypto/RoomEncryptor.ts

According to rust sdk documentation there should only be one call in flight to shareRoomKeys, it was not the case.
If `prepareToEncrypt` is called in background (when starting to type a message), and the message is sent before it completes there could be 2 in flight.
---

ElementR: Ensure there is only one call to shareRoomKeys in flight at once

---

spec/integ/crypto/crypto.spec.ts
spec/unit/crypto/crypto-utils.ts
spec/unit/crypto/secrets.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
spec/unit/secret-storage.spec.ts
src/crypto-api.ts
src/crypto/SecretStorage.ts
src/crypto/index.ts
src/rust-crypto/rust-crypto.ts
src/secret-storage.ts

Fixes https://github.com/vector-im/element-web/issues/26721
---
* ElementR: Fix missing key check values in 4S key storage ([\#3950](https://github.com/matrix-org/matrix-js-sdk/pull/3950)). Fixes vector-im/element-web#26721.

ElementR: Fix missing key check values in 4S key storage

---

spec/unit/crypto/store/CryptoStore.spec.ts
src/crypto/store/base.ts
src/crypto/store/indexeddb-crypto-store-backend.ts
src/crypto/store/indexeddb-crypto-store.ts
src/crypto/store/localStorage-crypto-store.ts
src/crypto/store/memory-crypto-store.ts

Some groundwork for https://github.com/element-hq/element-web/issues/26678: add a bunch of methods to Legacy `CryptoStore` to support reading the migration data.
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/3963
---

Add new methods to `CryptoStore` for Rust Crypto migration

---

spec/unit/matrix-client.spec.ts
src/client.ts

Implements [MSC4026](https://github.com/matrix-org/matrix-spec-proposals/pull/4026).
I believe this probably is as simple as this: it will mean that the versions response can obviously change after logging in, but since the client is constructed again with an access token, this should just work (?)
A remaining question is whether this needs to be optional. Opening the PR to prompt the discussion. Apps might not expect it, but it's just the same auth that we're sending to other endpoints on the same server.
---
Here's what your changelog entry will look …

Send authenticated /versions request

---

.github/workflows/sonarcloud.yml
.github/workflows/sonarqube.yml
.github/workflows/tests.yml

To allow reuse in matrix-react-sdk
And fix a small typo which makes little to no difference
---

Move sonarcloud shard support into reusable workflow

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/rust-crypto.ts

Fixes https://github.com/element-hq/element-web/issues/26717
---
* Element-R: fix `bootstrapSecretStorage` not resetting key backup when requested ([\#3976](https://github.com/matrix-org/matrix-js-sdk/pull/3976)). Fixes element-hq/element-web#26717.

Element-R: fix `bootstrapSecretStorage` not resetting key backup when requested

---

README.md

I noticed that when using strings in the event names in the client listeners (`client.on`, `client.once`), the TypeScript types don't work. When using the enums, types work wonderfully.
This PR changes the examples in the readme to use enums (like `RoomEvent.Timeline`) instead of strings (like `"Room.timeline"`).
❌ Types in the argument do NOT work here. `event`, `room`, and `toStartOfTimeline` default to `any`
```typescript
client.on("Room.timeline", function (event, room, toStartOfTimeline) {
...
```
✅ Types work well. `event`, `room`, and `toStartOfTimeline` have proper types.
```typescript
client.on(RoomEvent.Timeline, function (event, room, toStartOfTimeline) {
...
```
----
I understand the simplicity of using strings, but having proper types is important for onboarding new users.
An …

Use enums instead of strings for client event listeners (`client.on`, `client.once` ...) in the README to improve type inference

---

spec/unit/rust-crypto/RoomEncryptor.spec.ts
src/logger.ts
src/rust-crypto/RoomEncryptor.ts
src/utils.ts

Fixes https://github.com/element-hq/element-web/issues/26684
Encryption order was not ensured with the existing code. So in some case editing an inflight message would encrypt the edit first and schedule it first. That will cause an error because it will send an edit of an unknown event.
It can also invert the message order.
There is a sheduler currently but it doesn't handle encryption, it only queues the event for sending.
The scheduler should probably handle the encryption, but for now I modified RoomEncryptor to ensure order.
Notice that there was already a ordering mechanism but only to ensure order of `olmMachine.shareRoomKey` but it was not enough.
Added a test to reproduce the problem if the fix is not present.
-   [ ] …

ElementR: Ensure Encryption order per room

---

README.md
spec/unit/autodiscovery.spec.ts
src/version-support.ts

We only claim to support a year of spec releases, so this should be fine.
Part of: https://github.com/matrix-org/matrix-js-sdk/issues/3915
---
* Bump minimum spec version to v1.5 ([\#3970](https://github.com/matrix-org/matrix-js-sdk/pull/3970)).

Bump minimum spec version to v1.5

---

package.json
yarn.lock

Reverts matrix-org/matrix-js-sdk#3989
Since it appears to cause https://github.com/matrix-org/element-web-rageshakes/issues/23557:
```
2024-01-08T15:59:21.961Z I INFO matrix_sdk_indexeddb::crypto_store::migrations: Fixing inbound group session data keys
row_count=153771
at /home/runner/.cargo/git/checkouts/matrix-rust-sdk-1f4927f82a3d27bb/3e17fc2/crates/matrix-sdk-indexeddb/src/crypto_store/migrations.rs:327
2024-01-08T15:59:21.981Z E Unable to load session Error: invalid type: boolean `false`, expected u8
```
(This is a failure to upgrade the DB when using Element R.)
---
* Revert "Bump matrix-sdk-crypto-wasm to 3.6.0" ([\#3991](https://github.com/matrix-org/matrix-js-sdk/pull/3991)). Contributed by @andybalaam.

Revert "Bump matrix-sdk-crypto-wasm to 3.6.0"

---

package.json
yarn.lock

Reverts matrix-org/matrix-js-sdk#3991, which itself was a revert of https://github.com/matrix-org/matrix-js-sdk/pull/3989, which bumped matrix-sdk-crypto-wasm to 3.6.0 providing (among other things) an indexeddb migration that [fixes](https://github.com/matrix-org/matrix-rust-sdk/pull/2957) a bug in the previous migration.
After investigation, we discovered that the problems I was seeing when migrating were caused by local changes I had made to my indexeddb, so this will not affect any other users.
Fixes https://github.com/element-hq/element-web/issues/26782
---

Bump matrix-sdk-crypto-wasm to 3.6.0 (take 2)

---

.github/workflows/downstream-artifacts.yml
.github/workflows/downstream-end-to-end-tests.yml
.github/workflows/sonarcloud.yml

Stop running react-sdk Cypress tests

---

spec/integ/crypto/rust-crypto.spec.ts
spec/unit/crypto/store/CryptoStore.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/crypto/index.ts
src/crypto/store/base.ts
src/crypto/store/indexeddb-crypto-store-backend.ts
src/crypto/store/indexeddb-crypto-store.ts
src/crypto/store/localStorage-crypto-store.ts
src/crypto/store/memory-crypto-store.ts
src/rust-crypto/index.ts
src/rust-crypto/libolm_migration.ts

... so that we can display progress feedback in the UI.
part of https://github.com/element-hq/element-web/issues/26773
---
* Emit events during migration from libolm ([\#3982](https://github.com/matrix-org/matrix-js-sdk/pull/3982)).

Emit events during migration from libolm

---

README.md
src/autodiscovery.ts
src/version-support.ts

This PR does two things:
* It puts the "minimum supported matrix version" from v1.5 back down to v1.1. In other words, it is a partial revert of https://github.com/matrix-org/matrix-js-sdk/pull/3970. (Partial, because we don't need to update the tests.)
We're doing this largely because https://github.com/matrix-org/matrix-js-sdk/pull/3970 was introduced without a suitable announcement and deprecation policy. We haven't yet decided if the js-sdk's spec support policy needs to change, or if we will re-introduce this change in future in a more graceful manner.
* It increases the "maximum supported matrix version" from v1.5 up to v1.9. Previously, the two concepts were tied together, but as discussed at length in https://github.com/matrix-org/matrix-js-sdk/issues/3915#issuecomment-1865221366, …

Broaden spec version support

---

src/matrixrtc/MatrixRTCSession.ts

drop 'malformed member event' log level, given all TR rooms are malformed like this.

---

src/rust-crypto/backup.ts

Quick improvements on logs for secret gossiping
---

Element-R: improve logging for secret gossiping

---

package.json
spec/unit/rust-crypto/KeyClaimManager.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/KeyClaimManager.ts
src/rust-crypto/RoomEncryptor.ts
src/rust-crypto/index.ts
src/rust-crypto/rust-crypto.ts
yarn.lock

Fixes https://github.com/element-hq/element-web/issues/26900, https://github.com/element-hq/element-web/issues/26714 and https://github.com/element-hq/element-web/issues/26774
Side effects of https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/82
> New thing with Vec<_> support in wasm-bindgen: it drops the items on the JS side as soon as the method is called. Basically, the ownership of the JS values are transferred to Rust.
Impacted Methods
---

Element R: Bump matrix-rust-sdk-crypto-wasm to version 4.0.0

---

spec/unit/rust-crypto/BackupKeyLoop.spec.ts
spec/unit/rust-crypto/backup.spec.ts
src/rust-crypto/backup.ts

Fixes https://github.com/element-hq/element-web/issues/26893
Avoid calling the expensive room count at each backup iteration
---
* ElementR | backup: call expensive `roomKeyCounts` less often ([\#4015](https://github.com/matrix-org/matrix-js-sdk/pull/4015)). Fixes element-hq/element-web#26893.

ElementR | backup: call expensive `roomKeyCounts` less often

---

src/rust-crypto/verification.ts

https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/82/files#diff-cf8f469cee769b4b3555833df9943f95a94dd55a4c6c5c8b8c7419e34fc8b5d8R341 changed the return type of `Sas.decimals()` from  `Array<any> | undefined` to `Uint16Array | undefined`. This can no longer be cast to `[number, number, number]` without causing a type error (for reasons I don't *really* understand, tbh).
---

Fix type error introduced by crypto-wasm 4.0.0

---

package.json
spec/integ/crypto/cross-signing.spec.ts
spec/integ/crypto/crypto.spec.ts
spec/integ/crypto/megolm-backup.spec.ts
spec/integ/crypto/verification.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
yarn.lock

Bump matrix-sdk-crypto-wasm to 4.0.1

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/crypto/OlmDevice.ts
src/rust-crypto/libolm_migration.ts

Fixes https://github.com/element-hq/element-web/issues/26894.
Requires https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/89 (or rather, an update to a version of matrix-rust-sdk-crypto-wasm 4.0.1 which includes it).
element-web notes: Fix potential failure in migration from legacy to Rust cryptography.
---
* Fix crypto migration for megolm sessions with no sender key ([\#4024](https://github.com/matrix-org/matrix-js-sdk/pull/4024)). Fixes element-hq/element-web#26894.

Fix crypto migration for megolm sessions with no sender key

---

spec/unit/matrix-client.spec.ts
src/client.ts
src/models/room.ts
src/sliding-sync-sdk.ts
src/sync.ts

... and replace a lot of calls to `MatrixClient.isRoomEncrypted` with it.
This is a lesser check (since it can be tricked by servers withholding the  state event), but for most cases it is sufficient. At the end of the day, if the server witholds the state, the room is pretty much bricked anyway. The one thing we *mustn't* do is allow users to send *unencrypted* events to the room.
Preparation work for https://github.com/element-hq/element-web/issues/26108.
---

Introduce `Room.hasEncryptionStateEvent`

---

CHANGELOG.md
src/store/indexeddb.ts

Retroactively changes the changelog entry to include since when this change is needed as well, so that other people upgrading the SDK can more easily find what to change.
Fix #3986
Only documentation & error strings have changed so I have not adjusted any tests. A proper integration test would probably be nice, but I didn't have the time to look into how that is setup on this project.
---

fix IndexedDBStore API documentation

---

spec/integ/crypto/crypto.spec.ts
spec/test-utils/mockEndpoints.ts
spec/unit/matrix-client.spec.ts
src/client.ts
src/crypto-api.ts
src/crypto/index.ts
src/rust-crypto/RoomEncryptor.ts
src/rust-crypto/rust-crypto.ts

We want to make sure that servers are not sneakily hiding or changing encryption configuration settings, which we do by persisting the encryption settings to the crypto store.
---
* Element-R: check persistent room list for encryption config ([\#4035](https://github.com/matrix-org/matrix-js-sdk/pull/4035)).

Element-R: check persistent room list for encryption config

---

spec/unit/room.spec.ts
src/models/read-receipt.ts
src/models/room.ts
src/models/thread.ts

When looking for stuck unreads, we saw the sometimes `timeline` and `this.getLiveTimeline().getEvents()` are different.
`timeline` is a copy of the `this.getLiveTimeline().getEvents()` which is manually updated. To avoid missing copy, `timeline` becomes a getter to `this.getLiveTimeline().getEvents()`.
Also make `timeline` deprecated.
After some days of testing it, it seems to get rid of the remaining stuck unreads and make disappear some of the zombie notifications.
Closes https://github.com/element-hq/element-web/issues/26878
Part of …

Make `timeline` a getter

---

spec/unit/rust-crypto/rust-crypto.spec.ts

Tests that https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/72 fixes https://github.com/element-hq/element-web/issues/26566
---

Element R: Add test that requests are encoded properly

---

spec/unit/matrixrtc/CallMembership.spec.ts
spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/CallMembership.ts
src/matrixrtc/MatrixRTCSession.ts

Currenlty we use a combination of two fields in the Call member state events (`created_ts` + `expires`)
We want to move to just use a `expire_ts`.
This needs rethinking the logic behind syncing clients clocks. 
`created_ts` was mirring the `origin_server_timestamp` on update.
But `expire_ts` can only be known when the clock sync is known.
---
* Add expire_ts compatibility to matrixRTC ([\#4032](https://github.com/matrix-org/matrix-js-sdk/pull/4032)). Contributed by @toger5.

Add expire_ts compatibility to matrixRTC

---

package.json
scripts/release/merge-release-notes.js
yarn.lock

Saner Releases - improve changelog merging & allow pre-public testing (pack)

---

.github/workflows/release-make.yml

Add waits for post-release steps for improved visibility

---

spec/unit/crypto/store/IndexedDBCryptoStore.spec.ts
src/crypto/store/base.ts
src/crypto/store/indexeddb-crypto-store-backend.ts
src/crypto/store/indexeddb-crypto-store.ts

Adds a utility method to check for existance of a legacy database not yet migrated.
Will be used by the react sdk StorageManager for the consistency checks see this [PR](https://github.com/matrix-org/matrix-react-sdk/pull/12225)
---

Add utility to check for non migrated legacy db

---

package.json
yarn.lock

Fixes https://github.com/element-hq/element-web/issues/26948
---
* Bump matrix-sdk-crypto-wasm to 4.5.0 ([\#4060](https://github.com/matrix-org/matrix-js-sdk/pull/4060)). Fixes element-hq/element-web#26948. Contributed by @andybalaam.

Bump matrix-sdk-crypto-wasm to 4.5.0

---

spec/integ/crypto/rust-crypto.spec.ts
src/crypto/store/base.ts
src/rust-crypto/index.ts

Fixes https://github.com/element-hq/element-web/issues/26977
During the migration process we will migrate the private device and identity keys to rust stack. 
But until an initial `key/query` is done the sdk don't have access to the public keys and won't be able to establish the current trust.
This could result in several side effects where the app would improperly see trust for a short period.
Some side effects when this race occurs:
- Messages sent by the current device will have a red shield for a few frames before going back to normal
- The react-sdk could show the toaster to upgrade trust.
This PR adds a new migration step that ensures that an initial `keys/query` is done before handing back control to the app. This might slow a bit the startup, but will avoid all the mentionned side …

ElementR | Ensure own user and device trust are updated after migration before giving back control to the app.

---

spec/integ/crypto/crypto.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/crypto-api.ts
src/crypto/index.ts
src/rust-crypto/backup.ts
src/rust-crypto/rust-crypto.ts

Part of https://github.com/element-hq/element-web/issues/26681
When we export keys with Rust encryption, we serialise them into JSON to cross the Rust/JS boundary, then we deserialise them in `RustCrypto` to match the `CryptoApi` interface, then serialise them again in matrix-react-sdk's ExportE2eKeysDialog so that we can encrypt the information and save it to disk.
By providing an `exportRoomKeysAsJson` method, we can provide the keys as a string immediately, avoiding the need to deserialise and re-serialise them, and similarly in the import case.
---
* Add "AsJson" forms of the key import/export methods ([\#4057](https://github.com/matrix-org/matrix-js-sdk/pull/4057)). Contributed by @andybalaam.

Add "AsJson" forms of the key import/export methods

---

spec/unit/matrixrtc/MatrixRTCSessionManager.spec.ts
src/matrixrtc/MatrixRTCSession.ts
src/matrixrtc/MatrixRTCSessionManager.ts

Encrypted Timeline messages need to be awaited before they can be checked for their type.
---
* Await encrypted messages ([\#4063](https://github.com/matrix-org/matrix-js-sdk/pull/4063)). Contributed by @toger5.

Await encrypted messages

---

spec/unit/matrix-client.spec.ts
src/client.ts

Picked out from https://github.com/matrix-org/matrix-js-sdk/pull/4064
---
* Add getAuthIssuer method for MSC2965 ([\#4071](https://github.com/matrix-org/matrix-js-sdk/pull/4071)).

Add getAuthIssuer method for MSC2965

---

spec/unit/oidc/validate.spec.ts
src/oidc/validate.ts

Split out from https://github.com/matrix-org/matrix-js-sdk/pull/4064

Validate `account_management_uri` and `account_management_actions_supported` from OIDC Issuer well-known

---

package.json
yarn.lock

To reduce memory usage during export - see https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/105

Bump matrix-react-sdk-crypto-wasm to v4.6.0

---

spec/unit/embedded.spec.ts
src/embedded.ts
src/matrix.ts

For element call we want to have control over the sendContentLoaded action. As soon as we sent this action the widget will be shown.
However we need to adjust the theme first before we show the widget to not have an awkward flash of the wrong theme during the widget loading procedure.
So this should not be sent by the js-sdk and instead be sent by element call after the theme has been setup.

Make sending ContentLoaded optional for a widgetClient

---

spec/integ/matrix-client-event-timeline.spec.ts
src/client.ts

The root event of a thread used to arrive with the pagination request, but this was unspecced and so got changed to simply fetch the root event. In many (almost all) cases this shouldn't be necessary because the thread should already have its root event: re-use it if it's already there. This is only in pagination, so there's no reason to believe that the root event would have changed and needs to be re-fetched.
This removes a number of duplicate calls to the /event/ endpoint from the tests.

Don't re-fetch thread root if we already have it

---

spec/integ/sliding-sync.spec.ts
src/sliding-sync-sdk.ts
src/sliding-sync.ts

While debugging verification when using sliding sync, I encountered the same events being processed multiple times, causing the VerificationRequest state machine to break (some events are reentrant, but ready -> ready is a cancellable error). 
I noticed that the `onResponse` for `ExtensionToDevice` was declared `void` but overridden as `Promise<void>`, with the `nextBatch` cursor getting updated at the END of the function (after an await). In local testing, it was observed that next `onRequest` would sometimes start before the previous `onResponse` was finished, leading to the same `since` parameter being sent, leading to the same events being processed multiple times.
-   [X] Linter and other CI checks pass
-   [X] Sign-off …

Fix race condition with sliding sync extensions

---

spec/unit/pushprocessor.spec.ts
src/pushprocessor.ts

To handle the client not knowing it due to the server not proactively telling us down incremental syncs

Add `.m.rule.is_room_mention` push rule to DEFAULT_OVERRIDE_RULES

---

spec/integ/matrix-client-syncing.spec.ts
src/client.ts
src/models/room.ts

This is some code to process our own receipts and recalculate our notification counts.
There was no reason for this to be in client. Room is still rather large, but at least it makes somewhat more sense there.
Moving as a refactor before I start work on it.

Move code for processing our own receipts to Room

---

src/client.ts

post [/publicRooms](https://spec.matrix.org/v1.9/client-server-api/#post_matrixclientv3publicrooms) request requires `limit` and `since` params in body.
Signed-off-by: Ajay Bura ajbura@gmail.com

Fix public rooms post request search params and body

---

spec/integ/matrix-client-syncing.spec.ts
spec/unit/room.spec.ts
src/models/room.ts
src/sync.ts

This changes interface of Room, so this is a BREAKING CHANGE.
Correctly mirrors the logic we use for room notifications for thread notifications, ie. set only the total notifications count from the server if it's zero.
I'm not delighted with this since it ends up with function on room whose contract is to do something frankly, deeply weird and unintuitive. However, this is the hack we use for room notifications and it, empirically, works well enough. To do better, we'd need much more complex logic to overlay notification counts for decrypted messages. It could be less weird if we made the function able to zero out either type of count with an option, but since we'd only actually use it with one type, this seems worse, not better.
Fixes …

Fix highlights from threads disappearing on new messages

---

README.md
spec/unit/testing.spec.ts
src/testing.ts
typedoc.json

We'd like a way to generate mock encrypted events in a way that doesn't require access to private classes/methods within the JS-SDK. Accordingly, here's a new entrypoint.
I couldn't bring myself to add stuff to the README without clearing out a little of the crap, so that's included here too.

Add some test utils in a new entrypoint

---

src/errors.ts
src/sync.ts

Fixes https://github.com/element-hq/element-web/issues/27195
Replaces https://github.com/matrix-org/matrix-js-sdk/pull/4112
Accompanies https://github.com/matrix-org/matrix-react-sdk/pull/12358

Remove the logic that throws when the lazy loading options has changed.

---

README.md

This seems easier / more efficient than listening to all membership events and then filtering by user ID.
Signed-off-by: Johannes Marbach <n0-0ne+github@mailbox.org>

Use RoomEvent.MyMembership in auto-join example

---

spec/unit/matrix-client.spec.ts
spec/unit/models/event.spec.ts
src/@types/partials.ts
src/@types/uia.ts
src/client.ts
src/interactive-auth.ts
src/models/event.ts
src/models/room.ts
src/models/thread.ts
src/oidc/validate.ts
src/rust-crypto/OutgoingRequestProcessor.ts

+ Removes deprecated `experimentalThreadSupport` field on the start client options in favour of `threadSupport`
+ Removed deprecated method `supportsExperimentalThreads` on `MatrixClient` in favour of `supportsThreads`
+ Remove deprecated method `resolveRoomAlias` on `MatrixClient` in favour of `getRoomIdForAlias`
+ Remove deprecated method `setPushActions` on `MatrixEvent` in favour of `setPushDetails`
+ Remove deprecated method `hasAssocation` on `MatrixEvent` in favour of `hasAssociation`
+ Remove deprecated overload `makeRedacted` on `MatrixEvent`, `room` param is now required
+ Remove deprecated symbol `IImageInfo` - use `ImageInfo` instead
+ Remove deprecated symbol `IAuthDict` - use `AuthDict` instead
+ Remove deprecated symbol `OidcDiscoveryError` - use `OidcError` instead
+ …

Remove various deprecated methods & re-exports

---

spec/unit/testing.spec.ts
src/testing.ts

Followup to https://github.com/matrix-org/matrix-js-sdk/pull/4127: adds another test helper method. Also a couple of other additions.

Add new `decryptExistingEvent` test helper

---

spec/unit/pushprocessor.spec.ts
src/pushprocessor.ts

Fixes https://github.com/element-hq/element-web/issues/27173
Regressed by https://github.com/matrix-org/matrix-js-sdk/pull/4100

Fix merging of default push rules

---

spec/integ/crypto/cross-signing.spec.ts
spec/integ/crypto/crypto.spec.ts
spec/integ/crypto/megolm-backup.spec.ts
src/rust-crypto/rust-crypto.ts

Some non-functional refactors and test cleanups, in preparation for work on https://github.com/element-hq/element-meta/issues/2313.
Review commit-by-commit

Refactoring and simplification in decryption error handling

---

src/rust-crypto/libolm_migration.ts

Fixes https://github.com/element-hq/element-web/issues/27196

ElementR| Retry query backup until it works during migration to avoid spurious correption error popup

---

spec/test-utils/oidc.ts
spec/unit/oidc/register.spec.ts
src/@types/oidc-client-ts.d.ts
src/oidc/register.ts
src/oidc/validate.ts

Split out from https://github.com/matrix-org/matrix-js-sdk/pull/4134
Review commit-by-commit

OIDC improvements in prep of OIDC-QR reciprocation

---

spec/integ/crypto/crypto.spec.ts
spec/integ/crypto/megolm-backup.spec.ts
spec/unit/rust-crypto/PerSessionKeyBackupDownloader.spec.ts
src/crypto-api.ts
src/rust-crypto/PerSessionKeyBackupDownloader.ts
src/rust-crypto/backup.ts
src/rust-crypto/rust-crypto.ts

If an event was sent before our device was created, and backup is not configured, we have no hope of decrypting it. To reflect this, use a different error code for the decryption failure.
Part of https://github.com/element-hq/element-meta/issues/2313
Suggest review commit-by-commit

Crypto: use a new error code for UTDs from device-relative historical events

---

src/models/room-state.ts

Add comment to make clear that RoomStateEvent.Events does not update related objects in the js-sdk

---

src/crypto/store/memory-crypto-store.ts

This replaces the index-legwork to retrieve the sender key and session ID with `encodeURIComponent` & `decodeURIComponent`. It's possibly a matter of taste but I'm finding this less brittle than hard-coding the indexes.

Use encoded URI components when storing sessions in memory crypto store

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/libolm_migration.ts

Fixes https://github.com/element-hq/element-desktop/issues/1603
Some old session might have stored the ssss cached secret in clear form (raw UInt8Array). The existing migration code will fail on such sessions with 
```
TypeError: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
...
at async getAndDecryptCachedSecretKey (vector://vector/webapp/bundles/1d2e934471ebcb41f3e7/865.js:4549:44)
```
Updated the  migration's `getAndDecryptCachedSecretKey` to support both cases similar to https://github.com/matrix-org/matrix-js-sdk/blob/4fc6ba884e166cccf7c0af18e01e5f8c7056fa6b/src/crypto/CrossSigning.ts#L659
-   [ ] New or updated `public`/`exported` symbols have …

Element-R: Fix rust migration when ssss secret are stored not encryted in cache (old legacy behavior)

---

spec/integ/crypto/crypto.spec.ts
src/@types/event.ts
src/crypto-api.ts
src/models/event.ts
src/rust-crypto/rust-crypto.ts

Depends on a server that implements MSC4115, such as https://github.com/element-hq/synapse/pull/17104.
Part of https://github.com/element-hq/element-meta/issues/2317

Use a different error code for UTDs when user was not in the room

---

README.md
spec/unit/content-repo.spec.ts
spec/unit/matrix-client.spec.ts
src/client.ts
src/content-repo.ts

Add helpers for authenticated media, and associated documentation

---

src/http-api/method.ts

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods
We notably don't include the following:
* `CONNECT` - Matrix doesn't use this, and is unlikely to foreseeably use it.
* `TRACE` - Same as above
We add the following, though:
* `OPTIONS` - Valid thing to use under https://spec.matrix.org/v1.10/client-server-api/#web-browser-clients
* `PATCH` - Plausibly useful while we're here. May be used in the near-ish future.
* `HEAD` - Could be used by https://github.com/matrix-org/matrix-spec-proposals/pull/4120
We add them now instead of later to avoid relatively tiny PRs needing to go through heavyweight process. Instead, other layers can just use these verbs if and as needed.
It was briefly considered to use https://github.com/jrylan/http-method-enum instead, though the supply chain …

Add missing (and common-ish) HTTP method verbs to types

---

src/@types/partials.ts
src/@types/state_events.ts
src/models/room-state.ts

Regressed by https://github.com/matrix-org/matrix-js-sdk/pull/4105

Fix state_events.ts types

---

src/rust-crypto/verification.ts

Fixes https://github.com/element-hq/element-web/issues/27394

Wire up verification cancel & mismatch for rust crypto

---

spec/unit/crypto/cross-signing.spec.ts
spec/unit/crypto/secrets.spec.ts
spec/unit/models/MSC3089Branch.spec.ts
src/@types/auth.ts
src/@types/event.ts
src/@types/registration.ts
src/client.ts
src/crypto/CrossSigning.ts
src/crypto/EncryptionSetup.ts
src/crypto/index.ts
src/crypto/store/base.ts
src/crypto/store/indexeddb-crypto-store-backend.ts
src/crypto/store/indexeddb-crypto-store.ts
src/crypto/store/localStorage-crypto-store.ts
src/crypto/store/memory-crypto-store.ts
src/interactive-auth.ts
src/matrix.ts
src/models/room.ts

Requires https://github.com/matrix-org/matrix-react-sdk/pull/12524
+ Removes `threepidCreds` on `EmailIdentityDict` - should use `threepid_creds`
+ Removes `Room::shouldUpgradeToVersion` - should use `Room::getRecommendedVersion` instead
+ Removes `user` field on UIA calls, uses `identifier` instead
+ Removes `address` field on Login request interface - should use `identifier` instead
+ Removes `IEncryptedFile` - should use `EncryptedFile` on types export instead
+ Removes `ICrossSigningKey` - should use `CrossSigningKeyInfo`
+ Removes `IJoinRuleEventContent` - should use `RoomJoinRulesEventContent`
+ Removes `home_server` field on RegisterResponse - should derive from `user_id` by splitting at the first colon instead

Remove deprecated methods and fields

---

spec/integ/crypto/rust-crypto.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/rust-crypto/index.ts

... instead of using the pickleKey. This allows us to avoid a slow PBKDF operation.
Part of https://github.com/element-hq/element-web/issues/26821.

`initRustCrypto`: allow app to pass in the store key directly

---

package.json
spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/common-crypto/CryptoBackend.ts
src/crypto/index.ts
src/rust-crypto/PerSessionKeyBackupDownloader.ts
src/rust-crypto/backup.ts
src/rust-crypto/rust-crypto.ts
yarn.lock

Slightly more involved than normal because it requires us to pass a backup version into `OlmMachine.importBackedUpRoomKeys`.
On the other hand we can now re-enable the test that was disabled in https://github.com/matrix-org/matrix-js-sdk/pull/4214 due to https://github.com/matrix-org/matrix-rust-sdk/issues/3447
Fixes: https://github.com/element-hq/element-web/issues/27165
element-web notes: Fix a bug in the Rust crypto implementation which caused repeated HTTP requests to `/keys/query` when the session was unverified.

Bump matrix-sdk-crypto-wasm to 5.0.0

---

spec/integ/crypto/megolm-backup.spec.ts
spec/integ/matrix-client-methods.spec.ts
spec/integ/matrix-client-room-timeline.spec.ts
spec/test-utils/test-utils.ts
spec/unit/autodiscovery.spec.ts
spec/unit/event-timeline-set.spec.ts
spec/unit/matrix-client.spec.ts
spec/unit/room.spec.ts
src/@types/registration.ts
src/autodiscovery.ts
src/client.ts
src/crypto-api/keybackup.ts
src/crypto/index.ts
src/matrix.ts
src/models/event-timeline-set.ts
src/models/event-timeline.ts
src/models/event.ts
src/models/room.ts
src/rust-crypto/rust-crypto.ts
src/sync-accumulator.ts
src/utils.ts

Requires https://github.com/matrix-org/matrix-react-sdk/pull/12555
+ Removes legacy overload of `EventTimelineSet::addLiveEvent`
+ Removes legacy overload of `EventTimeline::addEvent`
+ Removes legacy overload of `Room::addLiveEvents`
+ Removes backwards compatible export of `CryptoApi`, use `Crypto.CryptoApi` instead
+ Removes backwards compatible export of `DeviceVerificationStatus`, use `Crypto.DeviceVerificationStatus` instead
+ Removes `Autodiscovery.ERROR_HOMESERVER_TOO_OLD`, use `Autodiscovery.ERROR_UNSUPPORTED_HOMESERVER_SPEC_VERSION` instead
+ Removes registration request body fields `x_show_msisdn`, `bind_msisdn`, `bind_email`. These were unspecced and unsupported for a long time.
+ Removes long deprecated event fields `age`, `prev_content`, these now live in `unsigned`
+ …

Remove more deprecated methods, fields, and exports

---

spec/integ/crypto/rust-crypto.spec.ts
spec/test-utils/test_indexeddb_cryptostore_dump/empty_account/README.md
spec/test-utils/test_indexeddb_cryptostore_dump/empty_account/dump.json
spec/test-utils/test_indexeddb_cryptostore_dump/empty_account/index.ts
spec/test-utils/test_indexeddb_cryptostore_dump/full_account/index.ts
spec/test-utils/test_indexeddb_cryptostore_dump/no_cached_msk_dump/index.ts
spec/test-utils/test_indexeddb_cryptostore_dump/unverified/index.ts
src/rust-crypto/libolm_migration.ts

Fixes https://github.com/element-hq/element-web/issues/27447

Don't run migration for Rust crypto if the legacy store is empty

---

spec/unit/queueToDevice.spec.ts

https://github.com/dumbmatter/fakeIndexedDB/pull/93 causes a bunch of tests to start failing because the fake timers need running in order for fake indexeddb to work. It also seems to cause failures to bleed between tests somehow if fake timers are enabled/disabled. This keeps all the fake timer tests in one suite and all the others in another, which appears to work.
This should allow https://github.com/matrix-org/matrix-js-sdk/pull/4224 to be merged.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.m …

Fix the queueToDevice tests for the new fakeindexeddb

---

src/rendezvous/RendezvousFailureReason.ts

Split out from https://github.com/matrix-org/matrix-js-sdk/pull/4134/
Required as RendezvousFailureReason becomes a union type from which the enum members cannot be accessed, without this the merge queue fails due to a chicken-and-egg problem.

Use LegacyRendezvousFailureReason over RendezvousFailureReason

---

src/@types/search.ts
src/client.ts

Requires https://github.com/matrix-org/matrix-react-sdk/pull/12575

Fix incorrect assumptions about required fields in /search response

---

spec/integ/crypto/crypto.spec.ts
src/@types/event.ts
src/models/event.ts

MSC4115 has been accepted, so enable checking the stable name.
fixes https://github.com/element-hq/element-web/issues/27515

Add support for stable name for MSC4115

---

README.md
spec/unit/content-repo.spec.ts
src/content-repo.ts

The MSC has completed FCP, so stable endpoints can be used.
Seeing as limited servers have shipped with the unstable endpoints, we're not generally concerned with backwards compatibility to `unstable` here - none of the freezing for the unauthenticated endpoints has happened yet.
For the "Matrix 1.11" bits, I am extremely confident that 1.11 will ship with MSC3916 - it's a release blocker. See https://github.com/matrix-org/matrix-spec/issues/1857 for release coordination.

Use stable endpoints for MSC3916

---

src/webrtc/call.ts

Dreadful hack to work around a bug in recent chrome/electron's WebRTC, as explained.
I'm not sure which is the least hideous out of this (ie. repeatedly calling setCodecPreferences and seeing if it crashes each time) or hardcoding the bad codec and skipping it. Opinions welcome. Edit: LiveKit work around this bug by using the receiver codecs (https://github.com/livekit/client-sdk-js/pull/1088) so that's also an option.
This will probably want backporting to the release.
Fixes https://github.com/element-hq/element-desktop/issues/1703
-   [ ] Sign-off given on the changes (see …

Fix screen sharing in recent Chrome

---

src/@types/state_events.ts

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/4244

Work around spec bug for m.room.avatar state event content type

---

spec/unit/matrixrtc/CallMembership.spec.ts
spec/unit/matrixrtc/LivekitFocus.spec.ts
spec/unit/matrixrtc/MatrixRTCSession.spec.ts
spec/unit/matrixrtc/MatrixRTCSessionManager.spec.ts
src/@types/event.ts
src/matrixrtc/CallMembership.ts
src/matrixrtc/LivekitFocus.ts
src/matrixrtc/MatrixRTCSession.ts
src/matrixrtc/MatrixRTCSessionManager.ts
src/matrixrtc/focus.ts

The call.member events are refactored in a backwards compatible way to not only have one array: `foci_active: Focus[]` but instead one array:
`foci_preferred: Focus[]`
and a single:
`focus_active: Focus`
Foci active should just be one field describing what you are currently using. In a fully cascading world this is your own foci. In the livekit scenario this describes how you connect to the correct livekit session. (using the oldest session member should be the default, but if someone is using sth else everyone should connect to the other livekit session as well. Not yet implemented)
`foci_preferred` is what `foci_active` has been. The list of possible foci this user knows about or can use.
fixes https://github.com/element-hq/element-call/issues/1737
Signed-off-by: Timo K …

Make the js-sdk compatible with MSC preferred foci and active focus.

---

spec/integ/matrix-client-methods.spec.ts
src/client.ts
src/feature.ts

This is the client-side implementation for https://github.com/matrix-org/matrix-spec-proposals/pull/4156.

Add via parameter for MSC4156

---

spec/unit/base64.spec.ts
src/base64.ts

`String.replace` only replaces a single instance of the search pattern by default; we need a regex in `g` mode if we want to replace them all.
For https://github.com/element-hq/element-call/issues/2429

Correctly transform base64 with multiple instances of + or /

---

spec/integ/crypto/megolm-backup.spec.ts
spec/integ/matrix-client-methods.spec.ts
spec/integ/matrix-client-syncing-errors.spec.ts
spec/test-utils/client.ts
spec/unit/rendezvous/rendezvous.spec.ts
spec/unit/room.spec.ts
src/client.ts
src/matrix.ts
src/models/room.ts
src/rendezvous/MSC3906Rendezvous.ts
src/serverCapabilities.ts

& keep them up to date.
I've elected to change the interface here and split it into two functions rather than re-use the same one. That way, the cached one doesn't need to return a promise. This does make it a BREAKING CHANGE. I've given both functions different names so it's obvious that they're different. It's a trivial code update so I don't really think its worth having a backwards compat function?
It also splits some code out of client.ts(!)
Any of the tests that use `runAllTimers()` needed replacing with something that would just run the ones they need, since this works by continually setting a timer to keep the capabilities up to date. I don't think `runAllTimers()` is a sensible thing to use unless you're testing a small piece of code where you know all the timers it's setting.
- …

Fetch capabilities in the background

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
spec/unit/matrixrtc/mocks.ts
src/matrixrtc/MatrixRTCSession.ts

Use legacy call membership if anyone else is

---

src/models/room.ts
tsconfig.json

I want to be able to use `WeakRef`, and per https://github.com/element-hq/element-web/issues/24913#issuecomment-2182448007, I believe this should be safe.

Bump ES target version to ES2022

---

src/rust-crypto/verification.ts

Fixes a couple of reference cycles which could cause objects to be leaked, ultimately meaning that we hold open a connection to IndexedDB, exacerbating https://github.com/vector-im/element-web/issues/25779.
Requires #4264 
Should be reviewable commit-by-commit.

Element-R: Fix resource leaks in verification logic

---

src/crypto-api/index.ts

I found it quite confusing having `CryptoApi` be defined so far from the `crypto-api` folder.

Rename `crypto-api.ts` -> `crypto-api/index.ts`

---

spec/integ/crypto/rust-crypto.spec.ts
src/client.ts

This was a temporary hack added in https://github.com/matrix-org/matrix-js-sdk/pull/4210 while clients were updated. This has now happened (https://github.com/matrix-org/matrix-react-sdk/pull/12543), so we can remove the hack and bring the behaviour in line with the documentation.
Notes: `MatrixClient.initRustCrypto` no longer uses the `pickleKey` as a passphrase for the rust crypto store. Populate `storagePassword` or `storageKey` to ensure the indexeddb store is encrypted.

Remove redundant hack for using the old pickle key in rust crypto

---

examples/node/package.json

This example seems to have been broken by the switch to Typescript. We can't just symlink in `../..` because that gives us the typescript version of the source, which, obviously, doesn't work in node.
Instead, make sure we use a prebuilt version of the js-sdk.
It's actually even more broken as of js-sdk 33.0.0, thanks to the switch to ES modules (#4187), but we'll get to that later.

Fix build for example script

---

src/rust-crypto/RoomEncryptor.ts

- it was spammy: https://github.com/element-hq/element-web/issues/27031
- it didn't actually log the duration, because the `block` function didn't `await` the inner promise.
This is impacting our ability to debug UTDs on Element-Web due to the spam cycling out useful logs.
Fixes https://github.com/element-hq/element-web/issues/27031

Remove useless log line

---

src/crypto/aes.ts
src/crypto/crypto.ts
src/crypto/key_passphrase.ts
src/oidc/authorize.ts
src/rendezvous/channels/MSC3903ECDHv2RendezvousChannel.ts

I believe the only reason we had this was that, before Node v11.0, `TextEncoder` wasn't available in the global object. Nowadays it is (see https://nodejs.org/api/util.html#class-utiltextencoder), so let's get rid of it.

Remove redundant `TextEncoder` shim

---

yarn.lock

Bump matrix-rust-sdk to 6.2.0
Fixes https://github.com/element-hq/element-web/issues/27658

Fix error when sending encrypted messages in large rooms

---

spec/integ/matrix-client-syncing.spec.ts
src/client.ts
src/sync.ts

If a user has left a room but wants to see a snapshot of what it looked like when they left, they would peek into the room.
In some use cases, it makes sense to sync many more than the hardcoded 20 timeline events.
Since it seems like something that all users could benefit from, I figured I would submit it as an upstream PR.
- _Extended existing test suite to cover new parameter_
Signed-off-by: Joel Garplind …

Add ability to choose how many timeline events to sync when peeking

---

.github/workflows/release-make.yml
.github/workflows/release-npm.yml
.github/workflows/release.yml
.github/workflows/static_analysis.yml
.github/workflows/tests.yml
package.json

According to https://github.com/matrix-org/matrix-js-sdk?tab=readme-ov-file#supported-platforms, we *only* support the latest LTS release (which is currently 20, per https://github.com/nodejs/release#release-schedule), so this should be safe.

Bump node.js requirement to 20.

---

src/crypto/key_passphrase.ts

Attempts to use the rust crypto stack without having made the legacy libolm stack available could have resulted in incorrect errors.

Fix incorrect "Olm is not available" errors

---

src/crypto-api/index.ts

it doesn't work in rust crypto, and we have no plans to fix it (https://github.com/element-hq/element-web/issues/27455)

Deprecate `CreateSecretStorageOpts.getKeyBackupPassphrase`

---

spec/unit/room.spec.ts
src/models/room.ts
src/utils.ts

and change the one use of it to just intantiate a collator and use it.
This was marked as internal module so this shouldn't be a breaking change. Of course, react-sdk was using it.
Requires: https://github.com/matrix-org/matrix-react-sdk/pull/12782

Remove the compare function from utils

---

src/matrixrtc/index.ts

This is required so we can (finally) remove the react-sdk import eslint exception comments.

Add index.ts for matrixrtc module

---

src/matrixrtc/MatrixRTCSession.ts

This is a solution (I am not sure it can be considered a actual fix. see below for additional thoughts on this) for EW exccessive logging for thirdroom rooms.
We do run checks on m.call.member events to check if the event can be considered a legacy event or a new session type event. This check does not consider that there is also a third content format created by thirdroom.
Hence we need to be more explicit to not consider third room call member events as session type events.
A more proper solution (that also was discussed is to rename the event type `org.matrix.msc3401.call.member`->`org.matrix.msc4143.call.member` comes to mind)
This is a much more breaking change however so we first go with this first reduce the logging step is a better first step.
-   [x] Tests written for new code …

Be specific about what is considered a MSC4143 call member event.

---

src/client.ts

It looks like the default value for this config option was changed, but the comment wasn't updated.  The comment at https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/http-api/interface.ts#L56 was updated, and https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/http-api/fetch.ts#L48 is where the default value gets applied.
And while I'm here, added a note that using the query param is deprecated.

Fix comment for useAuthorizationHeader config.

---

spec/unit/room.spec.ts

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/4331

Remove flaky test

---

spec/unit/matrix-client.spec.ts
spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/@types/requests.ts
src/client.ts
src/embedded.ts
src/matrixrtc/MatrixRTCSession.ts

Support MSC4140: Delayed events (Futures)

---

package.json
spec/integ/rendezvous/MSC4108SignInWithQR.spec.ts
spec/unit/embedded.spec.ts
src/client.ts
src/embedded.ts
yarn.lock

Dependencies:
- https://github.com/matrix-org/matrix-js-sdk/pull/4294
- https://github.com/matrix-org/matrix-widget-api/pull/92

Support Futures via widgets

---

src/matrixrtc/MatrixRTCSession.ts

Do not prefix the non-legacy session membership state keys with an underscore for rooms using MSC3757 (in addtion to MSC3779).

Also check for MSC3757 for session state keys

---

src/@types/global.d.ts
src/crypto/algorithms/base.ts

For https://github.com/element-hq/element-web/issues/24913

Make code tsc es2022 compliant

---

package.json
yarn.lock

This is to get https://github.com/matrix-org/matrix-widget-api/pull/97.

Bump matrix-widget-api

---

src/matrixrtc/MatrixRTCSession.ts

Akin to how legacy call events should be sent in rooms where there is any ongoing legacy call, send non-legacy events in rooms where there are only non-legacy calls; else fall back to the config preference.

Use non-legacy calls if any are found

---

src/matrixrtc/MatrixRTCSession.ts

A argument name change on `private` function for consistency with other parts of the class.

delayBeforeuse => delayBeforeUse for consistency

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/MatrixRTCSession.ts

This fixes https://github.com/element-hq/element-call/issues/2415 by having call participants proactively sending a  new `io.element.call.encryption_keys` room event with the same key if they detect that another participants has updated the `membershipID` or `created_ts` part of their call membership.

Resend MatrixRTC encryption keys if a membership has changed

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/MatrixRTCSession.ts

This change ensures that if an older key is received after a newer one then it isn't allowed to overwrite the newer one. Resolves https://github.com/element-hq/element-call/issues/2549

Handle MatrixRTC encryption keys arriving out of order

---

scripts/release/pre-release.sh

Attempts to fix the issue https://github.com/matrix-org/matrix-js-sdk/issues/4347. Added a line in `scripts/pre-release.sh` that should add `"type" = "module"` to  `package.json`. Analogous to https://github.com/matrix-org/matrix-js-sdk/pull/4285/commits/432aaa46d548728145a3af44245d9cc110ae180e.
Reasoning:
CI order goes [Release Process](https://github.com/matrix-org/matrix-js-sdk/blob/develop/.github/workflows/release.yml) > [Release …

Ensure "type" = "module" ES declaration in pre-release.sh

---

scripts/release/pre-release.sh

Reverts matrix-org/matrix-js-sdk#4350

Revert "Ensure "type" = "module" ES declaration in pre-release.sh"

---

package.json

Currently, we replace the entrypoints in package.json during the release cycle. I think, historically, this was done to make matrix-react-sdk and element-web development easier, but neither of those projects actually use these entrypoints (instead they import from `src`).
Accordingly, I think the switcheroo is unnecessary; furthermore it causes a whole bunch of confusion by making the development environment different from the release environment, and it complicates our CI and release process.
In short, the switcheroo has to die.
This change updates `package.json` to make the switcheroo a no-op, and removes the call to `scripts/switch_package_to_release.js` from the static analysis CI job. Unfortunately we'll need to update the react SDK before we can actually remove that script.
There is …

set entrypoints to use ./lib rather than ./src

---

.github/CODEOWNERS

The scripts in here are used in the release, and from the develop branch too (because it's the main branch and github actions does this) so it's critical for the release process.

Set web team as codeowner for the scripts dir

---

src/crypto-api/index.ts

These things are only used by the legacy crypto stack.

Deprecate unused callback hooks `CryptoCallbacks.onSecretRequested` and `CryptoCallbacks.getDehydrationKey`

---

src/client.ts
src/feature.ts

[MSC4156](https://github.com/matrix-org/matrix-spec-proposals/pull/4156) has been merged so unstable prefixes are no longer required. To my knowledge, the only homeserver that implemented the unstable feature was Synapse. The unstable prefixes in Synapse are being removed with https://github.com/element-hq/synapse/pull/17650.

Stabilise MSC4156

---

src/rust-crypto/CrossSigningIdentity.ts
src/rust-crypto/PerSessionKeyBackupDownloader.ts
src/rust-crypto/rust-crypto.ts

A grab-bag of small logging improvements in the Rust crypto wrapper.

Minor improvements to logging in device verification

---

src/client.ts

Slap a `@deprecated` tag on all the MatrixClient methods which no longer work with rust crypto.
Fixes: https://github.com/element-hq/element-web/issues/26919

Element-R: Mark unsupported MatrixClient methods as deprecated

---

src/matrixrtc/CallMembership.ts

This is in line with the other information we're already exposing, such as the event's sender and timestamp. We want this in order to play around with [adding reactions](https://github.com/element-hq/element-call/pull/2542) to the membership event.

Expose the event ID of a call membership

---

package.json
src/crypto-api/index.ts
src/rust-crypto/RoomEncryptor.ts
src/rust-crypto/rust-crypto.ts
yarn.lock

Bump dependency on rust-sdk-crypto-wasm to v8.0.0

---

examples/node/app.js
examples/node/package.json

Relates to: #4287
Relates to: element-hq/element-web#26922
Signed-off-by: Johannes Marbach <n0-0ne+github@mailbox.org>

Fix build failure in node.js example

---

src/embedded.ts

Fix sending redacts in embedded (widget) mode

---

src/matrix.ts

This came up in https://github.com/matrix-org/matrix-js-sdk/pull/4394#discussion_r1750457708.

Export membership types

---

.eslintrc.cjs
package.json
src/client.ts
yarn.lock

When importing without an extension
```
import { MemoryCryptoStore } from "./crypto/store/memory-crypto-store";
```
this rule throws an error
```
/Users/jm/Code/matrix-js-sdk/src/matrix.ts
19:35  error  require file extension '.ts'  node/file-extension-in-import
```
Sadly, it does _not_ throw an error when the file is imported with a `.js` extension. I'm not sure why but I suppose forgetting the extension entirely is the most common case anyway.
Relates to: https://github.com/matrix-org/matrix-js-sdk/issues/4392
-   [x] Sign-off given on the changes (see …

Add ESLint rule to ensure .ts extensions on imports

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/MatrixRTCSession.ts
src/matrixrtc/types.ts

Instead we only share what is needed.
This PR also records stats for how many keys have been sent/received and age of those received.

Don't share full key history for RTC per-participant encryption

---

package.json
spec/integ/crypto/crypto.spec.ts
src/crypto-api/index.ts
src/crypto/index.ts
src/rust-crypto/rust-crypto.ts
yarn.lock

Adds a global "crypto mode" setting to the crypto API (only works with Rust crypto), and changes the decryption settings based on that.

Add crypto mode setting for invisible crypto, and apply it to decrypting events

---

src/rust-crypto/rust-crypto.ts

https://github.com/element-hq/element-web/issues/27888 shows a slightly mysterious error message, but the problem is `createSecretStorageKey` returning the wrong thing.

Throw clearer error if `createSecretStorageKey` misbehaves

---

spec/integ/crypto/crypto.spec.ts
src/crypto-api/index.ts
src/crypto/index.ts
src/rust-crypto/rust-crypto.ts

crypto: Replace cryptoMode with DeviceIsolationMode concept

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/MatrixRTCSession.ts

Rotate Matrix RTC media encryption key when a new member joins a call for Post Compromise Security

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/MatrixRTCSession.ts

This is an "alternative" to https://github.com/matrix-org/matrix-js-sdk/pull/4423 which cleans up the RTCSession API instead.

RTCSession cleanup: deprecate getKeysForParticipant() and getEncryption(); add emitEncryptionKeys()

---

spec/unit/rust-crypto/RoomEncryptor.spec.ts
src/crypto-api/index.ts
src/rust-crypto/RoomEncryptor.ts
src/rust-crypto/rust-crypto.ts

Fixes https://github.com/element-hq/element-web/issues/28038
based on the work done on https://github.com/matrix-org/matrix-js-sdk/pull/4407

crypto: configure key sharing strategy based on DeviceIsolationMode

---

yarn.lock

Mostly, to pick up https://github.com/matrix-org/matrix-rust-sdk/pull/3985

Bump matrix-rust-sdk to 9.1.0

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/MatrixRTCSession.ts

Fix MatrixRTC sender key wrapping

---

src/crypto-api/index.ts
src/crypto-api/keybackup.ts
src/crypto-api/verification.ts
src/matrix.ts
src/models/typed-event-emitter.ts
src/secret-storage.ts
src/store/indexeddb.ts
typedoc.json

Currently the crypto-api hierarchy is exposed only as a `Crypto` namespace under the "matrix" entrypoint in the documentation.
This isn't really right: it's meant to be a separate entrypoint (in the same way as `types`, `testing` and `utils` are). This PR fixes that problem.
Before:
After:

Expose crypto-api as its own typedoc module

---

src/crypto/index.ts

Deprecate the crypto events which are no longer used by the rust crypto.

Deprecate the crypto events which are not used by the rust-crypto

---

spec/unit/rust-crypto/PerSessionKeyBackupDownloader.spec.ts
spec/unit/rust-crypto/backup.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/client.ts
src/crypto-api/CryptoEvent.ts
src/crypto-api/CryptoEventHandlerMap.ts
src/crypto-api/index.ts
src/crypto/index.ts
src/rust-crypto/PerSessionKeyBackupDownloader.ts
src/rust-crypto/backup.ts
src/rust-crypto/rust-crypto.ts

- Add the crypto events used by the rust-crypto into the crypto api
- Use this new events for the rust-crypto
The old crypto events and the new ones are using the same string in the enums so there is no breaking change when listening for the events on the `MatrixClient`.

Add crypto events to `crypto-api`

---

src/@types/requests.ts

for MSC4140's GET `/delayed_events` (as of [`28970ec`](https://github.com/matrix-org/matrix-spec-proposals/blob/28970ec477f5d0ed051dbd9fa208a741207ae97e/proposals/4140-delayed-events-futures.md#getting-delayed-events))
Note that this does not match the response type of the MSC's new `/delayed_events/scheduled` and `delayed_events/finalized` endpoints; this only fixes a typing error in the original response type.
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop …

Fix DelayedEventInfo type

---

.github/workflows/downstream-end-to-end-tests.yml
.github/workflows/notify-downstream.yaml
.github/workflows/release.yml
.github/workflows/tests.yml

Requires https://github.com/element-hq/element-web/pull/28192

Update workflows referencing matrix-react-sdk to use only element-web

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/MatrixRTCSession.ts

- Try sending call join after preparing delayed leave
- On leave, send delayed leave instead of a new event

Prepare delayed call leave events more reliably

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/MatrixRTCSession.ts

Refactor/simplify Promises in MatrixRTCSession

---

src/rust-crypto/rust-crypto.ts

We used to use the notation `<sender key>|<megolm session id>` fairly widely in log messages, but since the transition to rust crypto, it's unusual and now somewhat confusing. Make the log messages more explicit.

Avoid `<sender>|<session>` notation in log messages

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/MatrixRTCSession.ts

This change reverts https://github.com/matrix-org/matrix-js-sdk/pull/4422.
Instead, the rotation when a new member joins will be reintroduced as part of supporting to-device based MatrixRTC encryption key distribution.

Do not rotate MatrixRTC media encryption key when a new member joins a session

---

src/crypto-api/index.ts

Deprecate `CreateSecretStorageOpts.keyBackupInfo` used in `CryptoApi.bootstrapSecretStorage.`
The parameter is not used in [`RustCrypto.bootstrapSecretStorage`](https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/rust-crypto/rust-crypto.ts#L788)

Deprecate `CreateSecretStorageOpts.keyBackupInfo` used in `CryptoApi.bootstrapSecretStorage.`

---

.github/CODEOWNERS

Obviously, the crypto api is owned by the (web) crypto team!

Update codeowners for `crypto-api`

---

spec/unit/rust-crypto/backup.spec.ts
src/rust-crypto/backup.ts

Getting rid of the legacy types used in `RustCrypto#RustBackupManager`

Replace legacy keyBackup types

---

spec/unit/http-api/errors.spec.ts
spec/unit/http-api/index.spec.ts
spec/unit/http-api/utils.spec.ts
src/http-api/errors.ts
src/http-api/utils.ts
src/matrixrtc/MatrixRTCSession.ts
src/rust-crypto/PerSessionKeyBackupDownloader.ts
src/rust-crypto/backup.ts

Capture HTTP error response headers & handle Retry-After header (MSC4041)

---

spec/integ/crypto/crypto.spec.ts
spec/integ/crypto/megolm-backup.spec.ts
src/rust-crypto/index.ts

Remove remaining legacy crypto imports in new crypto and tests. Except migration crypto stuff.

Remove remaining legacy crypto imports in new crypto and tests

---

src/client.ts

Fixes https://github.com/element-hq/element-web/issues/17510

Refactor MatrixClient::forget to not abuse membershipChange API

---

src/crypto-api/index.ts

I was trying to work out why this was being used in a check. It turns out it only returns the key ID if the private part is stored locally, which seems very much non-obvious.

Make doc clearer on getCrossSigningKeyId

---

src/crypto-api/index.ts

Deprecate unused callbacks in `CryptoCallbacks` in the rust crypto stack.

Deprecate unused callbacks in `CryptoCallbacks`

---

src/client.ts

- The method is using `BackupManager` which is from the old crypto stack.
- The key backup methods should be exposed in the `CryptoApi` and not in `MatrixClient`

Deprecate `MatrixClient.getKeyBackupVersion`

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/MatrixRTCSession.ts

Depends on:
- https://github.com/matrix-org/matrix-js-sdk/pull/4492
- https://github.com/matrix-org/matrix-widget-api/pull/100

MatrixRTCSession: handle rate limit errors

---

src/embedded.ts

as the types can be deduced by the function arguments.

Remove redundant type arguments in function call

---

src/rust-crypto/KeyClaimManager.ts
src/rust-crypto/rust-crypto.ts

Fix tsdoc error in rust-crypto folder

---

src/matrixrtc/MatrixRTCSession.ts

When receiving a state change that says you are no longer a member of a RTC session that you are actually still participating in, send another state event to put yourself back in the session membership.
This can happen when an administrator overwrites your call membership event (which is allowed even with MSC3757's restrictions on state), or if your delayed disconnection event (via MSC4140) timed out before your client could send a heartbeat to delay it further.
-   [x] Sign-off given on the changes (see …

When state says you've left ongoing call, rejoin

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/MatrixRTCSession.ts

Not all of the new config options are being tested, but the code coverage is still reached.
The use of `Math.random()` that is flagged by SonarCloud is acceptable.

Allow configuration of MatrixRTC timers when calling joinRoomSession()

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/MatrixRTCSession.ts

Use a lower delay time if the server rejects a delay as too long.

Handle M_MAX_DELAY_EXCEEDED errors

---

README.md
src/client.ts

Closes https://github.com/matrix-org/matrix-js-sdk/issues/4132
Add examples and documentation to setup e2e encryption with the rust crypto stack.

Update e2e doc in `README.md`

---

spec/integ/crypto/megolm-backup.spec.ts
src/client.ts
src/crypto-api/index.ts
src/crypto-api/keybackup.ts
src/crypto/index.ts
src/rust-crypto/backup.ts
src/rust-crypto/rust-crypto.ts

The goal is to simplify the `restoreKeyBackup` api and move it out of the `MatrixClient` to the `CryptoApi`. 
- Added two methods to `CryptoApi`
- `restoreKeyBackup`
- if a recovery key is provided, we use it otherwise we try to getting form our local cache or from the secret storage.
- In [`RestoreKeyBackupDialog`](https://github.com/element-hq/element-web/blob/develop/src/components/vie …

Add `restoreKeybackup` to `CryptoApi`.

---

src/client.ts

[The legacy crypto `ICryptoCallback` are already an reexport of the crypto api `CryptoCallback`](https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/crypto/index.ts#L120).

Use crypto api import for `CryptoCallbacks` instead of legacy crypto

---

src/client.ts

`MatrixClient.isEventSenderVerified` calls `MatrixClient.getEventSenderDeviceInfo` which is deprecated and not supported by the rust cryptography stack.

Deprecate `MatrixClient.isEventSenderVerified`

---

spec/unit/embedded.spec.ts
src/embedded.ts
src/matrixrtc/MatrixRTCSessionManager.ts

This fixes remote echos not appearing in the widget api. As a consequence, an event listener in a matroska widget will never receive events sent by itself with`isSending() === false`.
This is needed in the raise hand logic for element call. We send a raise hand and need to update the ui as soon as it is sent so that pressing the button again redacts the raise hand.
The issue is caused by the following:
- An event gets a txId assigned by the embedded client (the widget)
- This txId is tracked, so that the event can be matched once the remote echo is received. In that case the js-sdk "ignores" the remote event and instead updates the already existing local event to reflect it is send.
- Using the widget api the event gets a txid twice. once in the widget (but that txid does **not** get …

Fix local echo in embedded mode

---

spec/integ/crypto/megolm-backup.spec.ts
src/rust-crypto/backup.ts

Closes https://github.com/matrix-org/matrix-js-sdk/issues/4534

Fix `RustBackupManager` remaining values after current backup removal

---

.github/workflows/backport.yml
.github/workflows/docs-pr-netlify.yaml
.github/workflows/downstream-end-to-end-tests.yml
.github/workflows/notify-downstream.yaml
.github/workflows/pull_request.yaml
.github/workflows/release-drafter-workflow.yml
.github/workflows/release-drafter.yml
.github/workflows/release-gitflow.yml
.github/workflows/release-make.yml
.github/workflows/release-npm.yml
.github/workflows/release.yml
.github/workflows/sonarcloud.yml
.github/workflows/sonarqube.yml
.github/workflows/static_analysis.yml
.github/workflows/sync-labels.yml
.github/workflows/tests.yml
.github/workflows/triage-incoming.yml
.github/workflows/triage-labelled.yml

For https://github.com/element-hq/element-web/issues/22729

Tighten GITHUB_TOKEN permissions

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/MatrixRTCSession.ts

Re-send MatrixRTC media encryption keys for a new joiner even if a rotation is in progress

---

src/client.ts
src/crypto-api/CryptoEventHandlerMap.ts
src/crypto/index.ts

- Deprecate remaining legacy functions
- Move `CryptoEvent.LegacyCryptoStoreMigrationProgress` handler to be able to remove all the legacy crypto event and handler map.

Deprecate remaining legacy functions and move `CryptoEvent.LegacyCryptoStoreMigrationProgress` handler

---

src/models/relations.ts
src/models/room.ts

Remove deprecated calls of `MatrixClient`

---

src/common-crypto/CryptoBackend.ts
src/rust-crypto/backup.ts
src/rust-crypto/libolm_migration.ts
src/testing.ts

- Replace some legacy crypto imports
- Deprecate `CryptoBackend.getEventEncryptionInfo`

Replace deprecate imports

---

README.md
spec/integ/crypto/crypto.spec.ts
spec/integ/crypto/olm-encryption-spec.ts
spec/integ/devicelist-integ.spec.ts
spec/integ/matrix-client-methods.spec.ts
spec/integ/matrix-client-syncing.spec.ts
spec/integ/sliding-sync-sdk.spec.ts
spec/test-utils/test-utils.ts
spec/unit/crypto.spec.ts
spec/unit/crypto/algorithms/megolm.spec.ts
spec/unit/crypto/backup.spec.ts
spec/unit/crypto/cross-signing.spec.ts
spec/unit/crypto/dehydration.spec.ts
spec/unit/crypto/secrets.spec.ts
spec/unit/crypto/verification/util.ts
src/client.ts

Rename `MatrixClient.initCrypto` into `MatrixClient.initLegacyCrypto` to force people to think about the deprecation.

Rename `MatrixClient.initCrypto` into `MatrixClient.initLegacyCrypto`

---

package.json
spec/integ/crypto/verification.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/rust-crypto.ts
yarn.lock

Update matrix-sdk-crypto-wasm to 11.0.0

---

src/matrixrtc/MatrixRTCSession.ts

n.b. The original scope of this PR has changed (reduced). It is not feasible to test this at the moment. We are planning a refactor of this class to make it easier to test.
With it being set to one the following issue could occur:
```
// If sending state cancels your own delayed state, prepare another delayed state
// TODO: Remove this once MSC4140 is stable & doesn't cancel own delayed state
if (this.disconnectDelayId !== undefined) {
try {
const knownDisconnectDelayId = this.disconnectDelayId;
await resendIfRateLimited(
() =>
this.client._unstable_updateDelayedEvent(
knownDisconnectDelayId,
UpdateDelayedEventAction.Restart,
),
1000,
);
} catch (e) {
logger.warn("Failed to update delayed disconnection event, prepare it again:", e);
this.disconnectDelayId = undefined;
await …
```

Only re-prepare MatrixrRTC delayed disconnection event on 404 

---

src/crypto-api/index.ts
src/rust-crypto/rust-crypto.ts

Attempting to get the backup key out of secret storage can cause the user to be prompted for their key, which is not helpful if this is being done as part of a reset. This check was redundant anyway and we can just overwrite the key with the same value.
Also fix docs and remove check for active backup.

Avoid key prompts when resetting crypto

---

spec/integ/matrix-client-syncing.spec.ts
spec/integ/sliding-sync-sdk.spec.ts
spec/unit/crypto/secrets.spec.ts
spec/unit/matrix-client.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
spec/unit/rust-crypto/secret-storage.spec.ts
spec/unit/secret-storage.spec.ts
src/@types/common.ts
src/@types/event.ts
src/client.ts
src/crypto/CrossSigning.ts
src/crypto/EncryptionSetup.ts
src/crypto/SecretStorage.ts
src/crypto/index.ts
src/models/invites-ignorer-types.ts
src/models/invites-ignorer.ts
src/rust-crypto/rust-crypto.ts
src/rust-crypto/secret-storage.ts
src/secret-storage.ts

Requires https://github.com/element-hq/element-web/pull/28752

Use mapped types for account data content

---

src/http-api/utils.ts

I'm not sure why this was limited to a small set of 4xx responses. Nominally, no 4xx request should be retried (in fact the comment below says this, but then the code didn't quite match it).
This was causing key backup requests to be retried even when the server responded 404 because the backup in question had been deleted, meaning the client would retry uselessly and it would take longer for the client to prompt the user for action.

Don't retry on 4xx responses

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/MatrixRTCSession.ts
src/matrixrtc/MatrixRTCSessionManager.ts
src/matrixrtc/MembershipManager.ts

Can be reviewed commit by commit.
This changes the api between the session and the `MembershipManager`.
It also makes sure that the tests are only using this api and nothing specific to the current `MembershipManager` implementation.
It is planned to do the same thing with the encryption logic of the session.
This allows to exchange the `MembershipManager` with a different implementation.

MatrixRTC: refactor MatrixRTCSession MemberManager API

---

src/matrixrtc/MembershipManager.ts

MatrixRTC: additional TS docs for IMembershipManager interface

---

src/matrixrtc/EncryptionManager.ts
src/matrixrtc/MatrixRTCSession.ts

MatrixRTC: refactor MatrixRTCSession media encryption key logic into EncryptionManager

---

spec/unit/room-member.spec.ts
spec/unit/room.spec.ts
src/models/room-member.ts
src/models/room.ts

Fixes getAvatarUrl in src/models/room.ts and src/models/room-member.ts not working on homeservers that enforce authenticated media
Signed-off-by: Maurizio Abbruzzo [maurizio@abbruzzosantiago.de](mailto:maurizio@abbruzzosantiago.de)

Add authenticated media to getAvatarUrl in room and room-member models

---

spec/unit/embedded.spec.ts
src/embedded.ts
yarn.lock

This change enables room widget clients to take advantage of the more reliable method of communicating room state over the widget API provided by [this update to MSC2762](https://github.com/matrix-org/matrix-spec-proposals/pull/4237).
Depends on https://github.com/matrix-org/matrix-widget-api/pull/116

Distinguish room state and timeline events in embedded clients

---

src/crypto-api/CryptoEvent.ts

`CryptoApi` itself does not emit events (or at least, its public type information does not allow you to listen for events emitted by CryptoApi).

Fix documentation on `CryptoEvent`

---

src/client.ts

`MatrixClient.login` has some very unintuitive behaviour where it
stashes the access token, but not the device id, refresh token, etc etc, which
led people to imagine that they had a functional `MatrixClient` when they
didn't. In practice, you have to create a *new* `MatrixClient` given the `LoginResponse`.
As the first step for sorting this out, this deprecates the broken method and
replaces it with one that has sensible behaviour.
Related to: #4502

Deprecate `MatrixClient.login` and replace with `loginRequest`

---

spec/unit/interactive-auth.spec.ts
spec/unit/matrixrtc/MatrixRTCSession.spec.ts
spec/unit/matrixrtc/mocks.ts
spec/unit/randomstring.spec.ts
spec/unit/secret-storage.spec.ts
spec/unit/thread-utils.spec.ts
src/client.ts
src/crypto/key_passphrase.ts
src/crypto/verification/request/ToDeviceChannel.ts
src/oidc/authorize.ts
src/randomstring.ts
src/rust-crypto/rust-crypto.ts
src/secret-storage.ts
src/webrtc/call.ts

...and renames them, removing the special lowercase and uppercase versions and exporting the underlying function instead.
I don't believe any of these uses are speed-sensitive, so I don't really see much value in maintaining separate, fast, insecure versions. I've just changed everything to use the secure versions.
Any apps that use these will either need to take the speed hit from secure random functions and use the new ones, or write their own insecure versions. Either way, they deliberately have different names so apps will need to make a choice rather then just get moved to the secure versions.
The lowercase and uppercase versions were used exactly once each in element-web and never in js-sdk itself. The underlying function is very simple and exporting just this gives more flexibility …

Change randomString et al to be secure

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/crypto-api/index.ts
src/crypto/index.ts
src/rust-crypto/rust-crypto.ts

Task https://github.com/element-hq/element-web/issues/28977
Require https://github.com/matrix-org/matrix-js-sdk/pull/4615
Add `CryptoApi.resetEncryption`.
The goal of this new api is to give an easy to reset the current encryption state of the user:
- Disable backing up room keys and delete any existing backup.
- Remove the default secret storage key from the account data (ie: the recovery key).
- Reset the cross-signing keys.
- Re-enable backing up room keys if enabled before.

Add `CryptoApi.resetEncryption`

---

spec/integ/rendezvous/MSC4108SignInWithQR.spec.ts
spec/test-utils/oidc.ts
spec/unit/matrix-client.spec.ts
spec/unit/oidc/authorize.spec.ts
spec/unit/oidc/register.spec.ts
spec/unit/oidc/tokenRefresher.spec.ts
spec/unit/oidc/validate.spec.ts
src/client.ts
src/oidc/authorize.ts
src/oidc/discovery.ts
src/oidc/index.ts
src/oidc/register.ts
src/oidc/tokenRefresher.ts
src/oidc/validate.ts
src/rendezvous/MSC4108SignInWithQR.ts
src/testing.ts

Updates to latest variant of https://github.com/sandhose/matrix-spec-proposals/blob/msc/sandhose/oidc-discovery/proposals/2965-auth-metadata.md
Also drastically simplifies the overly-duplicated config/metadata interfaces

Switch OIDC primarily to new `/auth_metadata` API

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/crypto-api/index.ts
src/rust-crypto/rust-crypto.ts

Following discussion in https://github.com/matrix-org/matrix-js-sdk/pull/4614#discussion_r1925377884.
- We decided to always create a new key backup at the end of `resetEncryption`.
- Add logging to help futur RS.

`CryptoApi.resetEncryption` should always create a new key backup

---

src/webrtc/call.ts

Require https://github.com/matrix-org/matrix-js-sdk/pull/4620
`webrtc/call.ts` uses deprecated and unsupported methods by the rust cryptography. I suppose it's somewhat broken since the usage of the rust cryptography.
I removed theses calls for https://github.com/element-hq/element-web/issues/26922
We wait for the js-sdk to drop the support of the legacy crypto (https://github.com/element-hq/element-web/issues/26922) to merge it in order to keep the feature when the legacy crypto is used.

Remove deprecated calls in `webrtc/call.ts`

---

src/client.ts
src/sync.ts

Remove legacy crypto support in `sync` api

---

spec/unit/embedded.spec.ts
src/embedded.ts
yarn.lock

Fixes #4655
This reverts commit bdd4d82cb3587d6d6285d05bb31d07796ca3959e.

Revert "Distinguish room state and timeline events in embedded clients (#4574)"

---

src/webrtc/call.ts

The deprecated `DeviceInfo` was set into `opponentDeviceInfo` however `opponentDeviceInfo` was only used for boolean operations. We can replace it with a boolean attribute.

Remove deprecated `DeviceInfo` in `webrtc/call.ts`

---

src/@types/event.ts

Element X uses this so it knows not to turn backup on again. Add it to js-sdk so we can set it so EX doesn't go turning key backup back on again.

Add unspecced backup disable flag

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/crypto-api/index.ts
src/crypto/index.ts
src/rust-crypto/rust-crypto.ts

Add API to withdraw verification requirement `CryptoAPi.withdrawVerificationRequirement`

Add API to withdraw verification requirement `CryptoAPI.withdrawVerificationRequirement`

---

spec/unit/models/event.spec.ts
src/models/event.ts

Remove usage of legacy crypto in `event.ts`

Remove usage of legacy crypto in `event.ts`

---

spec/integ/crypto/megolm-backup.spec.ts
src/matrix.ts

Remove  deprecated export in `matrix.ts`

Remove legacy crypto export in `matrix.ts`

---

spec/unit/matrix-client.spec.ts
spec/unit/room.spec.ts

Remove legacy crypto in integ tests

Remove usage of legacy crypto in integ tests

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/crypto/store/base.ts
src/crypto/store/indexeddb-crypto-store-backend.ts
src/crypto/store/indexeddb-crypto-store.ts
src/crypto/store/localStorage-crypto-store.ts
src/crypto/store/memory-crypto-store.ts

The migration from the legacy crypto to the rust crypto uses the legacy stores. In order to be able to delete the rest of the legacy crypto, these stores shouldn't rely on the types of the legacy crypto.
This PR does:
- Keep the store methods which are needed in the migration and in the tests
- Extract the types of the legacy crypto in put then in. `src/crypto/store/base.ts`
The legacy crypto tests and linting are in failure due to the removal of the store methods. The legacy crypto will be removed in the next PR.

Clean up legacy stores

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/crypto-api/index.ts
src/crypto/index.ts
src/rust-crypto/DehydratedDeviceManager.ts
src/rust-crypto/rust-crypto.ts

Needed for starting dehydration after restart -- since we only want to do that if we already have a key cached, and we don't need to try to rehydrate a device.
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/4484

Provide more options for starting dehydration

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/common-crypto/CryptoBackend.ts
src/rust-crypto/rust-crypto.ts

Remove deprecated methods of `CryptoBackend` and remove their implementations in `rust-crypto`
The CI is in failure because the root branch (which is a feature branch) has removed deprecated MatrixClient methods used by the legacy crypto. Legacy crypto which will be removed in this feature branch.

Remove deprecated methods of `CryptoBackend`

---

spec/unit/embedded.spec.ts
src/embedded.ts

The interface of `encryptAndSendToDevices` changes because `DeviceInfo` is from the legacy crypto. In fact `encryptAndSendToDevices` only need pairs of `userId` and `deviceId`.
We need to update the interface and we can simplify it.
The CI is in failure because the root branch (which is a feature branch) has removed deprecated `MatrixClient` methods used by the legacy crypto. Legacy crypto which will be removed in this feature branch.

Remove usage of legacy crypto in `embedded.ts`

---

spec/unit/content-helpers.spec.ts
src/@types/state_events.ts
src/@types/topic.ts
src/client.ts
src/content-helpers.ts
src/extensible_events_v1/utilities.ts

Pairs with https://github.com/matrix-org/matrix-spec/pull/2068, and an Element Web PR shortly.
The `topic` key of a topic may be undefined when it is removed, and this PR aims to support that use case. This may be considered a breaking change in that we're changing the Topic event content interfaces, but it's only to match up with reality.
NOTE: I was unsure what kind of `T-` this might be, I've gone with defect as I think it's resolving a problem where the js-sdk didn't match reality, but this could be construed as other things too.

Handle empty m.room.topic

---

src/@types/topic.ts

Leftover from https://github.com/matrix-org/matrix-js-sdk/pull/4673#discussion_r1938973139
I've taken the choice to remove the relatively trivial type we import from `matrix-events-sdk` due to it being abandoned anyway.

Fix topic types

---

.eslintrc.cjs
spec/TestClient.ts
spec/integ/crypto/cross-signing.spec.ts
spec/integ/crypto/crypto.spec.ts
spec/integ/crypto/megolm-backup.spec.ts
spec/integ/crypto/to-device-messages.spec.ts
spec/integ/crypto/verification.spec.ts
spec/integ/matrix-client-syncing.spec.ts
spec/test-utils/test-utils.ts

- Remove `CRYPTO_BACKEND` iteration
- Remove `oldBackendOnly` remaining tests
- Replace `newBackendOnly` by `it` -> we only have the rust crypto stack!
- Clean up some comments and specific code for legacy crypto

Clean up integ test after legacy crypto removal

---

spec/unit/rust-crypto/rust-crypto.spec.ts
spec/unit/secret-storage.spec.ts
src/rust-crypto/rust-crypto.ts
src/secret-storage.ts

Issue https://github.com/matrix-org/internal-config/issues/1602

Fix `resetEncryption` to remove secrets in 4S

---

src/@types/crypto.ts
src/crypto-api/index.ts
src/models/device.ts
src/models/event.ts

In https://github.com/matrix-org/matrix-js-sdk/pull/4672, I removed some broken link to the `CryptoApi`. Thanks to @t3chguy, I was able to fix them.

Restore broken link to `CryptoApi`

---

src/@types/crypto.ts
src/rust-crypto/backup.ts

Task https://github.com/matrix-org/matrix-js-sdk/pull/4653
Remove unused crypto type and missing doc

Remove unused crypto type and missing doc

---

src/models/event.ts

Deprecate parameter and functions using legacy crypto in `models/event.ts`

Deprecate parameter and functions using legacy crypto in `models/event.ts`

---

spec/integ/crypto/cross-signing.spec.ts
spec/integ/crypto/crypto.spec.ts
spec/test-utils/AccountDataAccumulator.ts
spec/test-utils/mockEndpoints.ts
spec/unit/matrix-client.spec.ts
src/client.ts

Wait for the echo to come back from the server before we assume the account data has been successfully set.
We have a bit of a problem in the dehydration setup code in that it calls `bootstrapSecretStorage` and, not unreasonably, expects `isSecretStorageReady` to return true. Currently, it doesn't, because `isSecretStorageReady` checks the in-memory account data cache, which isn't updated until the echo comes back down `/sync`.
So, the thing to do seems to be to wait for the echo to come back before proceeding. But I'm not really sure where this fits best: I considered putting it in `ServerSideSecretStorageImpl` or even `bootstrapSecretStorage`, but it really feels like this is a wider problem than just secret storage.
(A prerequisite for …

`MatrixClient.setAccountData`: await remote echo.

---

spec/unit/rust-crypto/CrossSigningIdentity.spec.ts
spec/unit/rust-crypto/KeyClaimManager.spec.ts
spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
spec/unit/rust-crypto/PerSessionKeyBackupDownloader.spec.ts
spec/unit/rust-crypto/RoomEncryptor.spec.ts
spec/unit/rust-crypto/backup.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/CrossSigningIdentity.ts
src/rust-crypto/backup.ts
src/rust-crypto/rust-crypto.ts

A forthcoming release of matrix-rust-sdk-crypto-wasm tightens up a number of
typescript types. In preparation, we need to get our house in order too.

Clean up typescript types related to rust crypto

---

CONTRIBUTING.md
README.md
code_style.md

Previously `CONTRIBUTING.md` just redirected to the same in `element-web` repo but it's more appropriate to have a separate guide since:
1. the project ownership has changed - `matrix-js-sdk` is owned by `matrix-org` while `element-web` is owned by `element-hq`. 
2. `matrix-js-sdk` uses a sign-off while `element-web` requires CLA.
`code_style.md` is also added separately.

Improve `CONTRIBUTING.md` and add `code_style.md`

---

src/@types/uia.ts
src/client.ts
src/interactive-auth.ts
src/rust-crypto/OutgoingRequestProcessor.ts

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/4702
Requires https://github.com/element-hq/element-web/pull/29255

Improve types around User Interactive Auth

---

README.md

If using the SDK outside the browser with end-to-end encryption, IndexedDB usage needs to be disabled otherwise it will cause the Rust code to panic.
See also:
- https://github.com/matrix-org/matrix-js-sdk/issues/4570
- https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/issues/168
- https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/issues/195#issuecomment-2661510343
Signed-off-by: Adam Spiers <github@adamspiers.org>
```
Notes: none
```

Mention caveat in README about IndexedDB outside browser

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/crypto-api/index.ts
src/rust-crypto/DehydratedDeviceManager.ts
src/rust-crypto/rust-crypto.ts

When we reset encryption (and reset cross-signing keys), delete the dehydrated device since it is (if present) signed with the old cross-signing key.
Fixes https://github.com/element-hq/element-web/issues/29131

Delete the dehydrated device when resetEncryption is called

---

package.json
spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
spec/unit/rust-crypto/OutgoingRequestsManager.spec.ts
spec/unit/rust-crypto/verification.spec.ts
src/@types/matrix-sdk-crypto-wasm.d.ts
src/rust-crypto/OutgoingRequestProcessor.ts
src/rust-crypto/OutgoingRequestsManager.ts
src/rust-crypto/verification.ts
yarn.lock

Relevant changes are:
-   Accept stable identifier `sender_device_keys` for MSC4147 (Including device  keys with Olm-encrypted events). ([#4420](https://github.com/matrix-org/matrix-rust-sdk/pull/4420))
-   Room keys are not shared with unsigned dehydrated devices. ([#4551](https://github.com/matrix-org/matrix-rust-sdk/pull/4551))

Update matrix-rust-sdk-crypto-wasm to v14.0.1.

---

src/event-mapper.ts
src/sliding-sync-sdk.ts
src/sync.ts

We don't need all the complicated stuff when we have a to-device event, so let's simplify.

Simplify code paths for building to-device `MatrixEvent`s

---

src/@types/event.ts

A couple of to-device message types which are in the spec but not in the js-sdk.

Add `EventType.SecretRequest` and `EventType.SecretSend`

---

babel.config.cjs
package.json
spec/unit/http-api/fetch.spec.ts
spec/unit/http-api/index.spec.ts
spec/unit/matrix-client.spec.ts
src/http-api/fetch.ts
src/utils.ts
src/utils/decorators.ts
tsconfig-build.json
tsconfig.json
yarn.lock

Fixes https://github.com/element-hq/element-web/issues/27810

Fix idempotency issue around token refresh

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/crypto-api/index.ts
src/rust-crypto/rust-crypto.ts

As an all-in-one method for deleting all server side key storage on the user's account (as the doc hopefully explains).

Add disableKeyStorage() to crypto API

---

src/matrixrtc/NewMembershipManager.ts
src/matrixrtc/NewMembershipManagerActionScheduler.ts

EC expects isJoined to represent if we should be in joined state or not. It does not correlate to what our actual state of the scheduler is. We used the scheduler running state before but on leave the running state will stay true until we successfully updated the room state.
EC expects isJoined to immediately be false.
This introduces a member variable `activated` that represents if the MemberhsipManager is trying to connect or trying to disconnect independent on the current state.

MatrixRTC: Fix running not representing what we need from `isJoined` in EC

---

spec/unit/matrix-client.spec.ts
src/client.ts

This arrived in Matrix 1.13 https://spec.matrix.org/latest/client-server-api/#post_matrixclientv3roomsroomidreport

Add reportRoom API

---

src/rust-crypto/OutgoingRequestProcessor.ts

In an attempt to guard against the request loop getting stuck, put a timeout on outgoing HTTP requests.
Fixes: https://github.com/element-hq/element-web/issues/29534

Rust crypto: set a timeout on outgoing HTTP requests

---

spec/integ/matrix-client-methods.spec.ts
src/client.ts

Adds parameter to getMediaConfig (client.ts) to use authenticated media call for media config.
Signed-off-by: Maurizio Abbruzzo [maurizio@abbruzzosantiago.de](mailto:maurizio@abbruzzosantiago.de)

Add authenticated media parameter to getMediaConfig

---

spec/unit/pushprocessor.spec.ts
src/pushprocessor.ts

Fix cache key not taking non-pattern parameters into account
Use lookarounds to ensure the word boundary isn't treated as part of the match

Improve PushProcessor::getPushRuleGlobRegex

---

spec/unit/matrixrtc/MembershipManager.spec.ts
src/matrixrtc/LegacyMembershipManager.ts
src/matrixrtc/MatrixRTCSession.ts
src/matrixrtc/NewMembershipManager.ts
src/matrixrtc/NewMembershipManagerActionScheduler.ts
src/matrixrtc/index.ts
src/matrixrtc/types.ts

We do already have the state `hasMemberEvent` that allows to distinguish the two cases. No need to create two dedicated actions.
This also moves code from `NewMemberhsipManager.ts` -> `types.ts`.
And we expose status through an event emitter for the membership manager.

MatrixRTC MembershipManger: remove redundant sendDelayedEventAction and expose status

---

spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/rust-crypto.ts

Regression due to https://github.com/matrix-org/matrix-js-sdk/pull/4742
When [`RustCrypto.resetEncryption`](https://github.com/matrix-org/matrix-js-sdk/blob/3657eb61d85e4848c2f849c06c3628776e29f929/src/rust-crypto/rust-crypto.ts#L1458) is called, [`CrossSigningIdentity.resetCrossSigning`](https://github.com/matrix-org/matrix-js-sdk/blob/3657eb61d85e4848c2f849c06c3628776e29f929/src/rust-crypto/CrossSigningIdentity.ts#L174) raises this error:
```
Uncaught (in promise) Error: No keys specified and no default key present
store secret-storage.ts:525
exportCrossSigningKeysToStorage CrossSigningIdentity.ts:184
resetCrossSigning CrossSigningIdentity.ts:154
bootstrapCrossSigning CrossSigningIdentity.ts:46
resetEncryption rust-crypto.ts:1473
onClick ResetIdentityPanel.tsx:92
React 23 …
```

Fix `RustCrypto.resetEncryption` failure

---

yarn.lock

As they aren't passing the tests upgraded individually
Replaces:
* https://github.com/matrix-org/matrix-js-sdk/pull/4782
* https://github.com/matrix-org/matrix-js-sdk/pull/4781
* https://github.com/matrix-org/matrix-js-sdk/pull/4780
* https://github.com/matrix-org/matrix-js-sdk/pull/4779

Upgrade eslint, babel & related deps

---

spec/unit/embedded.spec.ts
spec/unit/matrixrtc/MatrixRTCSession.spec.ts
spec/unit/matrixrtc/RoomKeyTransport.spec.ts
spec/unit/matrixrtc/ToDeviceKeyTransport.spec.ts
spec/unit/matrixrtc/mocks.ts
src/client.ts
src/embedded.ts
src/matrixrtc/EncryptionManager.ts
src/matrixrtc/IKeyTransport.ts
src/matrixrtc/MatrixRTCSession.ts
src/matrixrtc/RoomKeyTransport.ts
src/matrixrtc/ToDeviceKeyTransport.ts
src/matrixrtc/types.ts
src/webrtc/call.ts

Require changes on StopGapWidget to properly pass to device events without stripping things

MatrixRTC: ToDevice distribution for media stream keys

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
spec/unit/matrixrtc/MembershipManager.spec.ts
spec/unit/matrixrtc/RoomKeyTransport.spec.ts
spec/unit/matrixrtc/ToDeviceKeyTransport.spec.ts
spec/unit/matrixrtc/memberManagerTestEnvironment.ts
src/matrixrtc/EncryptionManager.ts
src/matrixrtc/MatrixRTCSession.ts
src/matrixrtc/MatrixRTCSessionManager.ts
src/matrixrtc/NewMembershipManager.ts
src/matrixrtc/NewMembershipManagerActionScheduler.ts
src/matrixrtc/RoomKeyTransport.ts
src/matrixrtc/ToDeviceKeyTransport.ts

This will make the logs look like this:

Make logging consistent for matrixRTC

---

.github/workflows/release-make.yml

Based on https://github.com/element-hq/packages.element.io/pull/11

Load gpg key without external action

---

package.json
src/logger.ts
src/matrixrtc/MatrixRTCSessionManager.ts
yarn.lock

This fixes an issue where a log extension (a modification to the `methodFactory`) applied to a parent logger would ONLY be executed when logging with the parent but not on any of the children created with `getChild()`.
This PR changes `getChild` to also inherit the `methodFactory` from the parent.

Inherit `methodFactory` extensions from the parent to the child loggers.

---

spec/unit/content-helpers.spec.ts
src/@types/topic.ts
src/content-helpers.ts

https://github.com/matrix-org/matrix-spec-proposals/pull/3765 was merged which means we can switch to stable identifiers and the final state of the proposal.

Stabilise MSC3765

---

spec/unit/http-api/fetch.spec.ts
src/http-api/refresh.ts

The condition was inverted here, but the tests were passing because they didn't add enough expiry time for the token expiry to be over the threshold.
Fix the condition and tests, add another test and generally add a bunch of comments so hopefully this is less confusing for the next person.
Fixes https://github.com/element-hq/element-web/issues/29858

Fix token refresh behaviour for non-expired tokens

---

spec/unit/embedded.spec.ts
src/embedded.ts

This reverts commit fd9a44e701532aaa969dff131bd85707dd5bdda3.
We are ready to reintroduce support for the [`update_state` widget action](https://github.com/matrix-org/matrix-spec-proposals/pull/4237) now that matrix-rust-sdk is [about to gain support for it](https://github.com/matrix-org/matrix-rust-sdk/pull/4947/) as well.
For https://github.com/element-hq/voip-internal/issues/289
Closes https://github.com/matrix-org/matrix-js-sdk/issues/4665

Reapply "Distinguish room state and timeline events in embedded clients"

---

package.json
yarn.lock

For better logging when a backed up key fails to deserialise.
https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/releases/tag/v14.2.0

Bump matrix-sdk-crypto-wasm to 14.2.0

---

spec/unit/embedded.spec.ts
src/embedded.ts

I've revived the changes from https://github.com/matrix-org/matrix-js-sdk/pull/4662 that allow RoomWidgetClient to function even if the client into which it is embedded does not support the `update_state` action.
This seems useful for easing the transition outlined at https://github.com/element-hq/voip-internal/issues/289 with our upcoming Element Call release (for which we want to test some unrelated mobile changes, where mobile currently does not support `update_state`), so I propose we add this compatibility layer.

Allow the embedded client to work without update_state support

---

package.json

Olm is needed at build time to run the tests, but is no longer needed at runtime.
Reverts https://github.com/matrix-org/matrix-js-sdk/commit/5568dfdd41f6e7fbb3e5d1d04c42016ed3c678a0

Remove `@matrix-org/olm` from dependency list

---

spec/integ/crypto/rust-crypto.spec.ts
src/client.ts

Related to #3974
I'm not 100% sure this makes sense, but I think it'll do what I want. (Which is having completely separate databases, but under the same principal/domain in IndexedDB.)

Allow customizing the IndexedDB database prefix used by Rust crypto.

---

package.json
src/rust-crypto/rust-crypto.ts
yarn.lock

For js-sdk users, this includes the following:
-   Send stable identifier `sender_device_keys` for MSC4147 (Including device keys with Olm-encrypted events).
([#4964](https://github.com/matrix-org/matrix-rust-sdk/pull/4964))
-   Check the `sender_device_keys` field on _all_ incoming Olm-encrypted to-device messages and ignore any to-device messages which include the field but whose data is invalid (as per [MSC4147](https://github.com/matrix-org/matrix-spec-proposals/pull/4147)).
([#4922](https://github.com/matrix-org/matrix-rust-sdk/pull/4922))
-   Fix bug which caused room keys to be unnecessarily rotated on every send in the presence of blacklisted/withheld devices in the room.
([#4954](https://github.com/matrix-org/matrix-rust-sdk/pull/4954))
-   Fix …

Update matrix-sdk-crypto-wasm to `15.0.0`

---

tsconfig.json

This prevents tsc from picking up random types from parent directories such as in situations like an element-web layered build, and generally seems like good hygiene as we don't want to pick up random types from whatever directory we happen to be checked out into.

Specify typeroot

---

src/client.ts
src/matrixrtc/MatrixRTCSessionManager.ts

There is a `Logger` instance associated with each `MatrixClient`, which we should be using in preference to the global logger, to make it easier to debug systems where multiple clients are running, or where the application wants to use a Logger implementation other than `console.log`.
This PR is one of a series that fixes up parts of the code to use the right logger. This one affects VoIP code -- specifically `MatrixRTCSessionManager`.

Use client logger in `MatrixRTCSessionManager`

---

spec/unit/rust-crypto/CrossSigningIdentity.spec.ts
spec/unit/rust-crypto/KeyClaimManager.spec.ts
spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
spec/unit/rust-crypto/RoomEncryptor.spec.ts
spec/unit/rust-crypto/backup.spec.ts
src/rust-crypto/CrossSigningIdentity.ts
src/rust-crypto/OutgoingRequestProcessor.ts
src/rust-crypto/RoomEncryptor.ts
src/rust-crypto/backup.ts
src/rust-crypto/rust-crypto.ts

There is a `Logger` instance associated with each `MatrixClient`, which we should be using in preference to the global logger, to make it easier to debug systems where multiple clients are running, or where the application wants to use a Logger implementation other than `console.log`.
This PR is one of a series that fixes up parts of the code to use the right logger. This one affects crypto code.

Use client logger in more places (crypto code)

---

src/client.ts
src/rust-crypto/rust-crypto.ts

A couple of places where we were still using the legacy logger
Followup to https://github.com/matrix-org/matrix-js-sdk/pull/4899 / https://github.com/matrix-org/matrix-js-sdk/pull/4900

Fix more incorrect logger use

---

src/@types/requests.ts
src/client.ts

I don't know when this last did something, but it's been a while.

Deprecate non-functional `IJoinRoomOpts.syncRoom`

---

src/@types/requests.ts

This option is non-functional, and was deprecated in https://github.com/matrix-org/matrix-js-sdk/pull/4913. Remove it altogether.
This PR targets the `vNext` branch, for inclusion in the next major release.

Remove deprecated `IJoinRoomOpts.syncRoom` option

---

spec/integ/matrix-client-methods.spec.ts
src/@types/requests.ts
src/client.ts

Preparation for supporting MSC4268 (history sharing on invite)

Give `MatrixClient.invite` an options param

---

src/matrixrtc/MatrixRTCSession.ts
src/matrixrtc/MembershipManager.ts

This adds a `race` so that restart delayed events can be timed out before the js-sdk local timeout happens.
This has to be done this way because the local timeout cannot be passed to the widget driver via the widget api for a specific request.

Custom abort timeout logic for restarting delayed events that is compatible with the widget api

---

src/http-api/fetch.ts

Currently, this is looking for a `json` property on `IHttpOpts`. There is no such property, so that part of the declaration is completely redundant, and we may as well remove it.
I looked into making it check `IRequestOpts`, which *does* have a `json` property, but couldn't make it work.
Also add some docs, while we're there.

Simplify declaration of `ResponseType`

---

spec/unit/http-api/fetch.spec.ts
src/http-api/fetch.ts
src/http-api/interface.ts

I need to make an authenticated request to the media repo, and expect to get a binary file back. AFAICT there is no easy way to do that right now.

fetch api: add support for downloading raw response

---

package.json
spec/test-utils/test-utils.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/crypto-api/index.ts
src/rust-crypto/rust-crypto.ts
yarn.lock

matrix-sdk-crypto-wasm 15.1.0 adds a new `DecryptionErrorCode`, which we need to support.

Update to matrix-sdk-crypto-wasm 15.1.0, and add new `ShieldStateCode.MismatchedSender`

---

spec/unit/http-api/fetch.spec.ts
spec/unit/http-api/index.spec.ts
src/client.ts
src/http-api/fetch.ts
src/http-api/index.ts
src/http-api/interface.ts

`FetchHttpApi` is never used without `onlyData: true`, and there is a bunch of type and code boilerplate to support it. Let's remove support for running without `onlyData: true`, as part of a longer-term mission to remove it altogehter.
This PR targets the `vNext` branch, with the intention that it be part of the next major release of the js sdk.

Remove support for `FetchHttpApi` without `onlyData: true`

---

spec/unit/matrixrtc/MembershipManager.spec.ts
src/matrixrtc/MembershipManager.ts

Fixes: https://github.com/element-hq/element-call/issues/3424
This PR adds a test for a edgecase where the membership manager can reach an unknown state.
The edge case is as following:
- restarting the delayed leave event gives a 404 (not found, the delayed event got sent by the HS)
- We have NOT yet received that our state is missing from the sync
- We are scheduling a new SendDelayedEvent action so we can setup a new delayed state event
- Just before we can sent out the request we receive our missing membership over sync. Because we arleady have a SendDelayedEvent scheduled we do not need to do any special logic here. No new actions are scheduled even though our membership is missing. (which is correct)
- When finally sending the new State event we have not cleared the UpdateExpiry …

Fix possible unknown state (Test that reproduces the edgecase)

---

spec/unit/room-member.spec.ts
spec/unit/room-state.spec.ts
src/models/room-member.ts
src/models/room-state.ts
src/models/room.ts
src/utils/roomVersion.ts

Adds support for infinite power level specified by [MSC4289](https://github.com/matrix-org/matrix-spec-proposals/pull/4289).
This version removes powerLevelNorm which we only use in one place in Element Web (where we probably should not) and I'm not sure is generally that sensible, so I've removed it since it's a difficult concept to keep and would at best be a slight lie when one of the PLs is always infinity (eg. we'd have to say creator is also 100, probably). This makes this a BREAKING CHANGE.
I'll leave this as draft until I have a matching PR for element.

Support for creator power level

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/MatrixRTCSession.ts

Only process MatrixRTC sessions associated with calls for `callMembershipsForRoom`

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/matrixrtc/MatrixRTCSession.ts

This PR adds a new event to the MatrixRTC session. An event that is emitted once the session has taken over its responsibilty of sending the notification event.
Context:
Element call now sends the notificaition event (the matrix event that makes other clients ring) instead of the client that encapsuls element call.
In element call we need to know if the js-sdk decided to actually send this notification or not. One example why it might not send it is: There is already someone in the call -> we are not the call starter -> we will not send a ring notification.
If it did send the notification (ring) and this new event emits it allows EC to build a ux around it. Commuication to the user that they are in "waiting for other participants to join" state.

Make a MatrixRTCSession emit once the RTCNotification is sent

---

src/client.ts

It looked for the ".stable" suffixed feature to work out what URL to use but not to see whether the server supported it.
This will only be relevant until the next spec release but may as well fix it.
See also https://github.com/element-hq/element-web/pull/30649

Fix stable-suffixed MSC4133 support

---

spec/unit/matrixrtc/MatrixRTCSession.spec.ts
src/@types/event.ts
src/matrixrtc/MatrixRTCSession.ts

The MSC4075 now uses `m.reference` instead

Remove custom `org.matrix.msc4075.rtc.notification.parent` relation type

---

spec/unit/content-helpers.spec.ts
src/@types/topic.ts
src/content-helpers.ts

Fixes #4902
I don't think any kind of backwards compatibility makes sense. The existing topics are malformed and if rooms have such topics, it's better that they notice the formatting disappears and fix it. An automatic migration would probably also be too invasive (it'd require sending events as the user)

Fix `m.topic` format

---

spec/unit/sync-accumulator.spec.ts
src/sync-accumulator.ts

Signed-off-by: Svajunas Budrys <svajunas.budrys.sb@gmail.com>
PR suggests removing a knocked room on join, which happens in this scenario (also video attached)
- User A: knock on the room
- User A: reload
- User B: approve user A
- User A: join the room
- User A: reload a few times
- User A: sees "Request to join sent" view, but he has joined the room already
Used https://github.com/matrix-org/matrix-js-sdk/pull/3729 as a reference
https://github.com/user-attachments/assets/78499bdd-24ff-4da4-9fbc-77ff3e80521e

Remove knocked room when membership changes to join

---

spec/unit/matrix-client.spec.ts
src/client.ts

Adds a new client option `disableVoip` which prevents the SDK from fetching `/voip/turnServer` and disables VoIP-related features. This reduces unnecessary network requests for applications that only use Matrix for text messaging.

feat(client): allow disabling VoIP support

---

src/client.ts
src/models/profile-keys.ts
src/serverCapabilities.ts

Requires https://github.com/matrix-org/matrix-js-sdk/issues/5014
Part of the spec [since v1.16](https://spec.matrix.org/v1.16/changelog/v1.16/)

Stabilise extended profiles (now part of Matrix v1.16)

---

spec/integ/crypto/verification.spec.ts
spec/unit/rust-crypto/rust-crypto.spec.ts
src/rust-crypto/rust-crypto.ts

If we don't have the device info for a user when we receive their verification request, we ignore it. This change gives us the best possible chance of having the right device data before we try to process the verification.
* Fixes [#30693](https://github.com/element-hq/element-web/issues/30693)
* Fixes [#27819](https://github.com/element-hq/element-web/issues/27819)

Fetch the user's device info before processing a verification request

---

spec/unit/models/event.spec.ts
spec/unit/models/room-sticky-events.spec.ts
spec/unit/sync-accumulator.spec.ts
src/@types/requests.ts
src/client.ts
src/errors.ts
src/models/event.ts
src/models/room-sticky-events.ts
src/models/room.ts
src/sync-accumulator.ts
src/sync.ts

Split out from https://github.com/matrix-org/matrix-js-sdk/pull/5017 to allow for easy reviewing. Implements https://github.com/matrix-org/matrix-spec-proposals/pull/4354
As a brief overview of the MSC (though please do at least skim the MSC): This allows any member in a room to mark an event as "sticky" and ensure it gets delivered to other users *even* in the case of a gappy sync. This is useful for things like RTC where you want call member events to always reach clients, without having to bloat the room with state events that will contribute to overall DAG bloat. 
This implementation also deals with ensuring that some events will replace predecessors that share the same "sticky key", and emit the appropriate notices to users of the API.

Implement Sticky Events MSC4354
