lib/matrix.js
This is an experiment in adding a data store layer to let clients actually track all the events they receive and expose the state to clients in a sensible manner.
Events are wrapped up as MatrixEvent objects, which in practice do nothing useful at all other than possibly provide a way to annotate the events in future.  This feels deeply wrong, currently.
=> Experimental data store layer to aid tracking client state

examples/voip/README.md, examples/voip/browserTest.js, examples/voip/index.html, examples/voip/lib/matrix.js, lib/client.js, lib/http-api.js, lib/matrix.js, lib/webrtc/call.js, package.json
This PR adds in support for WebRTC in the JS SDK. This has been manually tested to work in Chrome using the example app also in this PR. There are currently no unit or integration tests for this component. This PR is based heavily on the angular SDK.
Overview:
* A new class `MatrixCall` has been added which is the main component of this PR. This class is not directly exposed to the end user. Instances of `MatrixCall` can emit `hangup`, `error` and `replaced` events. There are also public methods to `hangup()`, `answer()`, `placeVideoCall(remoteVideoElement, localVideoElement)` and `placeVoiceCall()`.
* A new global method `createNewMatrixCall` has been added. This is how end-users create outgoing calls. They specify the `roomId` they want to place the call in and a `MatrixClient` instance …
=> WebRTC support

lib/client.js, lib/matrix.js, package.json, spec/integ/matrix-client-crypto.spec.js
Remove olm from the package dependencies. If olm isn't installed then don't enable any of the end-to-end encryption features that depend on it.
=> Disable end-to-end encryption if olm isn't installed.

lib/client.js
Make `MatrixClient.startClient` take `opts` instead of `historyLen` in a backwards compatible way. Add `opts.includeArchivedRooms` as an option.
=> Add support for archived=true in initial sync

lib/client.js, lib/models/room.js, spec/unit/room.spec.js
Read `invite_room_state` key from the `m.room.member` event if it exists and create fake state events to make invited rooms display the room name.
Has unit tests.
=> Invite room state

lib/webrtc/call.js
This PR adds the following methods to `MatrixCall`:
- `isLocalVideoMuted()`
- `setLocalVideoMuted(muted)`
- `isMicrophoneMuted()`
- `setMicrophoneMuted(muted)`
Each method has been manually tested against an Android device.
=> VoIP local muting

lib/models/room-member.js, lib/models/room-state.js, spec/unit/room-member.spec.js
Reduces initial sync times from ~30s to ~1s on accounts with heavily
populated rooms.
The problem was that f.e. RoomMember it would try to calculate the
display name, which involved looping each RoomMember to get their
display name to check for disambiguation. We now cache display names
to user IDs so we don't need to loop every member when disambiguating.
Updated tests.
=> Change calculating display names from O(n^2) to O(n)

lib/client.js, spec/integ/matrix-client-syncing.spec.js, spec/mock-request.js
This PR adds the ability for the SDK to fetch profile information for invitees. This is gated behind the flag `resolveInvitesToProfiles` which is set on `MatrixClient.startClient(opts)`.
If this flag is set to `true`, every incoming `m.room.member` **invite** event will be resolved. This resolution has the following steps:
- Check for existing profile info in the store via `getUser(userId)`. If exists, use that. If not:
- Hit `/profile/$user_id` to get their profile information. Set profile info from that.
- Setting profile info involves munging the `m.room.member` `content` to include the `avatar_url` and `displayname`. This is preferable as it reduces the number of extraneous code paths this PR adds.
This has integration tests.
=> Retrieving profile info for invites

lib/client.js
This allows developers to gracefully degrade their UIs if VoIP is not supported.
Pre-requisite for https://github.com/vector-im/vector-web/issues/291
=> Add MatrixClient.supportsVoip()

lib/client.js, lib/models/room.js, spec/integ/matrix-client-room-timeline.spec.js, spec/unit/matrix-client.spec.js
This PR adds the necessary structures for https://github.com/vector-im/vector-web/issues/197 to be implemented.
This PR fixes all the issues in SYJS-11:
- We need to retry `/initialSync` if it fails. Currently we get wedged.
- We need to emit an event when we recover from a `syncError` to let clients remove banners/warnings saying 'bad connection'.
- We need to exp backoff on `/events` in the event of a failure.
- We need to have a manual prod function to kick either `/initialSync` and/or `/events` if they are backing off.
- We need to expose `/events?timeout=` to clients.
- Room initial sync should be using `historyLen`.
This PR makes a breaking change:
- `syncError` and `syncComplete` are no longer emitted, and are combined into a `sync` event with `state` arguments.
This PR has unit …
=> Syncing bugs/fixes

lib/models/room.js
Generate implicit read receipts in recalculateRoom so they're correct when the room is loaded and addReceipt only has to worry about adding them for events appended to the timeline which is fairly trivial logic.
=> Synthesize implicit read receipts in recalculateRoom

lib/client.js, spec/unit/matrix-client.spec.js
This adds the following functions required for guest access:
- `MatrixClient.registerGuest()` - Flexible registration endpoint `?kind=guest`.
- `MatrixClient.setGuestRooms(roomIds)` - Sets stuff which is given to `/events` as query params. Provided here rather than in `startClient(opts)` because rooms will be added whilst the client is running.
=> Guest access endpoints

lib/client.js, spec/integ/matrix-client-room-timeline.spec.js, spec/mock-request.js
Add a 3s delay between scrollback requests if the previous scrollback request
failed.
Return the same promise if scrollback() is called multiple times whilst a
scrollback request is ongoing.
=> Scrollback improvements

lib/client.js, lib/models/room.js, lib/store/webstorage.js, spec/unit/room.spec.js
Specifically, consumers of the SDK can now do:
```javascript
client.startClient({
pendingEventOrdering: "end"
});
```
to sort SENDING/QUEUED/NOT_SENT events to the **end** of the `room.timeline` always. The default value for `pendingEventOrdering` is `chronological` which is the current behaviour before this PR (pending events are ordered chronologically with other events).
=> Add config option to control how pending events are ordered

lib/client.js, lib/http-api.js, lib/matrix.js, lib/models/event.js, lib/models/room.js, lib/pushprocessor.js, lib/store/memory.js, lib/store/stub.js, lib/sync.js, lib/utils.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-event-emitter.spec.js, spec/integ/matrix-client-opts.spec.js, spec/integ/matrix-client-room-timeline.spec.js, spec/integ/matrix-client-syncing.spec.js, spec/test-utils.js, spec/unit/matrix-client.spec.js
The PR converts the JS SDK to use v2 `/sync` rather than v1 `/initialSync` and `/events`.
A brief overview of the changes:
- All the syncing code has been moved from `client.js` to a new file: `sync.js`. A nice interface has not yet been written, so `sync.js` horribly gut wrenches `MatrixClient` currently.
- `MatrixEvent` now supports v2-style events *in addition* to v1.
- v2 transaction ID matching has been implemented (so the JS SDK does not need to do a linear scan for duplicate suppression on *every event* anymore!)
- v2 catchup has been implemented (so if you put your computer to sleep overnight and start it back up, it won't lock up your browser!)
- `/sync` call processing has been made more robust (read: paranoid) - we don't assume keys exists which we did in v1 and we set the sync …
=> Use /sync instead of /initialSync and /events

lib/client.js
Check to see if the call was answered or hung up in addition to having a valid
lifetime before emitting the event. Fixes vector-im/vector-web#344
=> Do not erroneously emit Call.incoming events on startup

lib/sync.js
This fixes vector-web/vector-im#536
The bug here is that we were assuming `setTimeout` would fire after the
requested time. This is not true when the machine is asleep. We now timestamp
before and after `setTimeout` and reset the attempt count if we have waited
more than twice what we originally requested. This allows for some jitter which
is to be expected. This also reduces the max waiting time to 32s from 2.1min,
because 2 minutes was deemed excessive given "regular" clients would be polling
with a `timeout=30secs`.
=> Reset /sync backoff if setTimeout takes a long time to fire

lib/client.js, lib/sync.js
Implemented for https://github.com/vector-im/vector-web/issues/348
This adds `MatrixClient.syncLeftRooms()` which fetches left rooms and dumps them into the store. Everything Just Works. Multiple calls to `syncLeftRooms()` will return the same promise if the request is ongoing, or NOP if the request was successful. If the request failed, it will be retried. Manually tested these cases.
See also:
- https://github.com/vector-im/vector-web/pull/541
- https://github.com/matrix-org/matrix-react-sdk/pull/62
=> Add syncLeftRooms()

lib/sync.js
Requires https://github.com/matrix-org/synapse/pull/456 to work sensibly (without it will just set the unread count to undefined).
=> Propagate the unread count from sync onto rooms

lib/client.js, lib/models/event-context.js, lib/models/search-result.js
This change adds support to the JDK for processing the results of a room
search, as well as back-paginating the results.
It treats each search result as a 'context' object, which can itself be
backwards or forward-paginated.
=> Enhancements to search results, and event context implementation

lib/client.js, lib/sync.js, spec/unit/matrix-client.spec.js
Fixes https://github.com/vector-im/vector-web/issues/81
Specifically this adds:
- The ability to peek on a single room. `MatrixClient.peekInRoom`
- The ability to set guest access rules on a room. `MatrixClient.setGuestAccess`
- Helpful getters for the access_token and user ID localpart (to submit in order to upgrade accounts). `MatrixClient.getAccessToken` and `MatrixClient.getUserIdLocalpart`
This modifies `MatrixClient.register` to accept another arg `guestAccessToken` to get upgrades working. Manually tested.
=> Add constructs for guest access

lib/client.js, lib/models/room.js, lib/sync.js
add a Room.getImplicitRoomName so clients can know what a room would be named if it had no explicit m.room.name.
(This seems to also be pulling in matthew/accountdata - oops)
=> Room.getImplicitRoomName

lib/client.js, lib/http-api.js, lib/models/room.js, lib/sync.js, spec/unit/matrix-client.spec.js
When a `/sync` request fails, we spin up a keep-alive poll to `/_matrix/client/r0`
which `400`s. We treat any HTTP response code as a success for the purposes of
polling the server. When a successful poll is done, we shoot the current `/sync`
request in the head immediately (via a hacky `abort()` on the promise) and retry
the `/sync`.
The point of this is to fix the problem where OSX can black-hole connections when waking. This would normally hit the 110s client-side timeout for `/sync` which is way too long for a timeout. We effectively now use the keep alive request to check for connectivity now (which has a 5s client-side timeout) and then resend the `/sync` request when it succeeds.
=> Implement a keep-alive timer for /sync requests 

lib/client.js, lib/matrix.js, lib/models/event-timeline.js, lib/models/room.js, lib/sync.js, package.json, spec/integ/matrix-client-event-timeline.spec.js, spec/integ/matrix-client-room-timeline.spec.js, spec/test-utils.js, spec/unit/event-timeline.spec.js, spec/unit/room.spec.js
This provides optional support for fetching old events via the /context API,
and paginating backwards and forwards from them, eventually merging into the
live timeline.
To support it, events are now stored in an EventTimeline, rather than directly
in an array in the Room; the old names are maintained as references for
compatibility.
The feature has to be enabled explicitly, otherwise it would be impossible for
existing clients to back-paginate to the old events after a gappy /sync.
Still TODO here:
* An object which provides a window into the timelines to make them possible to
use. (This is pr #64) .
* Rewrite the 'EventContext' used by the searchRoomEvents API in terms of an
EventTimeline - it is essentially a subset. This isn't urgent, and can wait until this lump has landed.
=> Support for non-contiguous event timelines

lib/sync.js
This should be functionally identical: doing this as separate PR to make the diffs a bit more digestible.
=> Separate the actual processing of the sync response from the loop doing the requests.

lib/timeline-window.js
If we somehow end up in a situation where calling /messages returns a load
of messages, but none of them are new, then currently we start calling
/messages again and again in a tight loop. This is bad, so fix it.
=> Make sure we don't end up calling /messages in a loop if things go weird

lib/models/room.js, spec/integ/matrix-client-event-timeline.spec.js
Make sure that the timeline index is kept consistent when the id of an event
changes when we receive the remote echo of a message we sent.
=> Fix a bug which made the timelines get confused about local messages

lib/client.js, lib/models/room.js, spec/integ/matrix-client-syncing.spec.js, spec/unit/room.spec.js
In order to resolve the conflict between local and remote read-receipts, try to
give precedence to the read-receipt which refers to the most recent event.
Also fix the read-receipt synthesis in _addLiveEvents so that it actually works
(drop the spurious MatrixEvent wrapper), and remove the synthesis in
recalculate() (which appears to be redundant).
=> Give precedence to later Read Receipts

lib/client.js
After /send completes, we check the room to see if the echo has already come
back via /sync. It's a bit of an edge-case, but we ought to check all
timelines, not just the live one.
Furthermore, we now have a map from eventId to timeline, so we can handle the
case where the echo has *not* yet come back more efficiently than searching
through the whole timeline.
=> Check old timelines when looking for echoes of sent messages

lib/client.js, lib/sync.js, spec/unit/matrix-client.spec.js
Just only the /versions keepalive logic to recover from lost internet connections.
* This should fix the problem where we could end up with two concurrent syncs
due to both retrying /sync and hitting /versions. There is now one and only
one mechanism for connection recovery.
* Hit /versions a little less often as I think every 2 seconds is a little
over-aggressive. Also introduce randomness to minimize possibility of
thundering herds.
* Add a listener for the 'online' event in case any browser is nice enough
to ever fire it.
* Treat a 400 response from /versions as successful since older synapses
will not support it.
Should fix root cause of https://github.com/vector-im/vector-web/issues/719
=> Use only /versions requests for connection recovery

lib/models/event-timeline.js, spec/unit/event-timeline.spec.js
Removing the last event in an EventTimeline (as we might, for instance, if it
was a local echo in an empty timeline) got us into a state where the baseIndex
would increment when adding events to the end of the timeline, causing much
confusion.
This should fix https://github.com/vector-im/vector-web/issues/937.
=> EventTimeline: Fix baseIndex after removing the last event

lib/models/event.js, lib/models/room.js, lib/sync.js
Everything gets confused when we remove events from timelines, so keep
redacted events in there, and mark them as redacted instead.
=> Keep redacted events in the timeline

lib/client.js, spec/integ/matrix-client-event-timeline.spec.js
events_before are backwards
Fixes https://github.com/vector-im/vector-web/issues/963
=> Interpret the response from /context correctly

lib/sync.js, spec/unit/matrix-client.spec.js
Make sure that we check the content of existing filters before we blindly reuse
them.
This feels a bit nasty because the chances are that we could reuse an existing
filter. But taking advantage of that would mean changing the synapse API, which I have little appetite right at the moment.
Fixes https://github.com/vector-im/vector-web/issues/988
=> Check filters before we reuse them

lib/timeline-window.js
Avoid doing a loop round the reactor if we are just loading the live timeline.
=> TimelineWindow.load: make the livetimeline case quicker

lib/sync.js
If we've already got all the events in a limited sync, there is no need to reset
the timeline.
This fixes a bug where, if you peek into a world-readable room, and then join it, we get stuck paginating in a tight loop until an event arrives (or you change room).
I think this is probably also responsible for a number of other bugs, like https://github.com/vector-im/vector-web/issues/1045 and https://github.com/vector-im/vector-web/issues/943, though I haven't yet reproduced those fully.
=> Don't reset the timeline when we join a room after peeking

lib/models/room.js, lib/sync.js, spec/integ/matrix-client-syncing.spec.js, spec/unit/room.spec.js
This fixes another race condition on gappy syncs, wherein we weren't
back-paginating back from the start of the gappy sync.
=> Set the back-pagination token before raising Room.timelineReset

lib/models/room.js
Look out for us getting stuck in a loop of using the same pagination token,
and use something else next time.
Hopefully this will fix https://github.com/vector-im/vector-web/issues/1089.
=> Work around confused timelines causing pagination loops

lib/models/room.js, lib/sync.js, spec/unit/room.spec.js
We need to trigger an update of the timeline when this happens, so raise an
event for it.
=> Emit an event when a local-echo is turned into a proper event

lib/client.js, lib/models/room.js
We need to know about more transitions for local-echo status changes, so raise
localEchoUpdated events for each transition.
Fixes an issue where we weren't turning failed transmissions red, because the
timeline wasn't being updated.
=> Raise localEchoUpdated events in more places

lib/timeline-window.js
This is basically a workaround for https://matrix.org/jira/browse/SYN-645: if
we knew about all of the events already, we want to try again.
Fixes the second half of https://github.com/vector-im/vector-web/issues/1014
=> Try again if a pagination request gives us no new messages

lib/sync.js, spec/unit/matrix-client.spec.js
…to avoid tightlooping if the conn check succeeds but /sync etc fails.
=> Add a delay before we start polling the connectivity check endpoint

lib/client.js, lib/models/room.js, spec/integ/matrix-client-room-timeline.spec.js
Transmission of encrypted messages was happening somewhat differently to
normal messages. In particular, we weren't copying the 'unsigned' field when we
got the remote-echo, which meant the 'sync' code didn't correctly match up the
echo with the original.
The separate codepath was becoming a thorn in my side, so fix things up to
bring it back in line.
=> Clean up a codepath that was only used for crypto messages

lib/models/room-state.js, spec/unit/room-state.spec.js
=> Add maySendStateEvent method, ported from react-sdk (but fixed).

lib/client.js, lib/http-api.js, spec/integ/matrix-client-event-emitter.spec.js
Session.logged_out fires whenever the current session is no longer valid and the user needs to log in again.
Also null check _syncApi before trying to stop it.
https://github.com/vector-im/vector-web/issues/414
=> Add Session.logged_out event

lib/sync.js
If we have the stack for an exception in the /sync loop, we should log it.
=> Log the stack when we get a sync error

lib/client.js, lib/models/event.js, lib/models/room.js, spec/unit/room.spec.js
This is some preparatory work for fixing up the problems with the timeline ordering of unsent messages
(https://github.com/vector-im/vector-web/issues/1120). The functional changes here should be minimal (bar an extra `Room.localEchoUpdated` when the local echo is first added to the timeline).
Give `MatrixClient.sendEvent` its own entry point `Room.addPendingMessage` instead of pushing it through `addEventsToTimeline`; this considerably simplifies the implementation of the latter and also means that we can contain the `_txnId` ming to MatrixClient.
Move the code which deals with a successful `/send` response from `MatrixClient` into `Room.updatePendingEvent`, since it involves fiddling with the innards of the Room.
Also adds a new EventStatus 'SENT' for events which have been successfully …
=> Refactor transmitted-messages code

lib/client.js, lib/http-api.js
This also moves the manual json decoding for the ID server into the common ID server block, since we'll have to do it for all ID server requests, rather than doing it in requestEmailToken.
=> Add a method to the js sdk to look up 3pids on the ID server.

CHANGELOG.md, lib/client.js, lib/models/event-timeline.js, lib/models/room.js, spec/unit/room.spec.js
The existing 'pendingEventOrdering'=='end' semantics had been substantially
broken by the introduction of timelines and gappy syncs: after a gappy
sync, pending events would get stuck in the old timeline section. (Part of
https://github.com/vector-im/vector-web/issues/1120).
This is a breaking change; PR for matrix-react-sdk will follow.
=> Implement 'pendingEventList'

lib/client.js, lib/models/event.js, lib/models/room.js, spec/integ/matrix-client-retrying.spec.js, spec/unit/room.spec.js
Implement client.cancelPendingEvent which will cancel queued or not_sent events
This won't work properly until https://github.com/matrix-org/matrix-js-sdk/pull/111 is landed.
=> Support for cancelling pending events

lib/client.js
Fixes a flaky test which sometimes failed due to sending two events in the same
millisecond.
=> Include a counter in generated transaction IDs

lib/models/room-state.js, spec/unit/room-state.spec.js
Make them use the same function internally. Also add convenience maySendMessage. Also tests.
=> Add maySendEvent to match maySendStateEvent

lib/http-api.js, lib/realtime-callbacks.js, spec/unit/realtime-callbacks.spec.js
Hopefully this will improve our recovery time after a laptop is suspended. The
idea is to treat the timeouts on the http apis as being in realtime, rather
than in elapsed time while the machine is awake.
To do this, we add a layer on top of window.setTimeout. We run a callback every
second, which then checks the wallclock time and runs any pending callbacks.
(Hopefully a fix to https://github.com/vector-im/vector-web/issues/1288).
=> Implement HTTP callbacks in realtime

lib/timeline-window.js, spec/unit/timeline-window.spec.js
In TimelineWindow.paginate, keep a count of the number of API requests we have
made, and bail out if it gets too high, to ensure that we don't get stuck in a
loop of paginating right back to the start of the room.
=> Avoid paginating forever in private rooms

lib/client.js, lib/http-api.js
* Add client.getUrlPreview() method to wrap the new /preview_url endpoint, which attempts to get a preview of a URL as of a given point in time.
* Add a basic in-memory cache to avoid hammering synapse unnecessarily
This is part of a set of PRs spanning vector-web, matrix-react-sdk, matrix-js-sdk and synapse.
See also vector-im/vector-web#1343 and https://github.com/matrix-org/matrix-react-sdk/pull/260
=> URL previewing support

lib/sync.js, package.json, spec/integ/matrix-client-event-emitter.spec.js, spec/integ/matrix-client-event-timeline.spec.js, spec/integ/matrix-client-opts.spec.js, spec/integ/matrix-client-room-timeline.spec.js, spec/integ/matrix-client-syncing.spec.js, spec/mock-request.js
Make sure that the integration tests actually kill off all of their timers, so
that jasmine exits cleanly.
This probably also fixes https://github.com/vector-im/vector-web/issues/1365.
=> Clean up test shutdown

lib/client.js, lib/models/room.js, lib/store/webstorage.js, lib/sync.js, spec/integ/matrix-client-methods.spec.js, spec/unit/room.spec.js
... and add some sanity checks
Two things here:
1. Clean up the Room API for adding new events to the timeline. Where before
we had addEvents and addEventsToTimeline, whose purposes were unclear, we now
have addLiveEvents which must be used for adding events to the end of the live
timeline, and addEventsToTimeline which should be used for pagination (either
back-pagination of the live timeline, or pagination of an old timeline).
2. Add some sanity checks for the live timeline. Today we have seen problems
where somehow the live timeline had gained a forward pagination token, or the
live timeline had got joined to another timeline, leading to much confusion -
and I would like to notice these sooner.
=> Refactor the addition of events to rooms

lib/models/room.js, lib/models/user.js
=> Track the absolute time that presence events are received, so that the relative lastActiveAgo value is meaningful.

lib/client.js, lib/models/event.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-methods.spec.js
Changes the format of data stored for user devices in the session store (in a
backwards-compatible way), to include a 'verified' key (and get rid of a lot of
extraneous crap we don't use).
When we decrypt an event, keep the content we need to do a verification in the
MatrixEvent.
Add methods which allow us to flag a device as verified, and to verify the
sender of an event.
=> Support for marking devices as verified

lib/client.js, spec/integ/matrix-client-retrying.spec.js
If an exception was thrown by the encryption process, the event would be queued, but the exception would not be handled. This meant that the event got stuck as a grey 'sending' event in the UI.
Fixing this correctly is slightly more complex than just handling the exception correctly. A naive approach would mean that the event would be shown as a red 'unsent' message, and clicking 'resend' would then send the message *in the clear*. Hence, move the encryption to _sendEvent, where it will be called again
when the event is resent.
=> Catch exceptions when encrypting events

lib/client.js, lib/models/event.js, lib/models/room.js, lib/pushprocessor.js, spec/unit/pushprocessor.spec.js
Make `MatrixEvent.event` contain the *encrypted* event, and keep the plaintext
payload in a separate `_clearEvent` property.
This achieves several aims:
* means that we have a record of the actual object which was received over
the wire, which can be shown by clients for 'view source'.
* makes sent and received encrypted MatrixEvents more consistent (previously
sent ones had `encryptedType` and `encryptedContent` properties, whereas
received ones threw away the ciphertext).
* Avoids having to make two MatrixEvents in the receive path, and copying
fields from one to the other.
*Hopefully* most clients have followed the advice given in the jsdoc of not
relying on MatrixEvent.event to get at events. If they haven't, I guess they'll
break in the face of encrypted events.
(The pushprocessor …
=> Change how MatrixEvent manages encrypted events

package.json
We have optional support for olm, so it makes sense to add it as an
optionalDependency here.
(I think this will mean that Olm ends up enabled on vector.im/develop)
=> Add Olm as an optionalDependency

lib/client.js
Mostly because it's useful for testing, to be honest.
=> Support for marking devices as unverified

lib/client.js, spec/integ/matrix-client-crypto.spec.js
When we send an encrypted message with Olm, we need to know who to send it
to. Currently that is based on a user list passed to setRoomEncryption. We want
to be able to change the list as people join and leave the room; I also want to
not have to keep the member list in local storage.
So, use the member list at the point of enabling encryption to set up sessions,
and at the point of sending a message to encrypt the message.
Further work here includes:
* updating the react-sdk not to bother setting the member list
* monitoring for new users/devices in the room, and setting up new sessions
with them
=> crypto: use memberlist to derive recipient list

lib/client.js
We want to be able to 'block' devices, so that they are not sent copies of our
text. Implement that change, and exclude blocked devices when encrypting
messages.
THis changes the name of the 'deviceVerified' event to
'deviceVerificationChanged', but that just means that the UI won't update
correctly until the changes to react-sdk arrive.
=> Implement device blocking

lib/client.js
This is the first step in having a cross-room "enable encryption" button.
If encryption is enabled, add an event handler which will set up encryption
when we receive an m.room.encryption event (either at initial /sync, or in
subsequent syncs.)
=> Configure encryption on m.room.encryption events

package.json
When I installed the package dependencies with npm I got the following warning:
```
npm WARN matrix-js-sdk@0.5.4 license should be a valid SPDX license expression
```
This is because the license value in package.json was not a valid SPDX identifier. And because of this, the license also isn't displayed on https://www.npmjs.com/package/matrix-js-sdk
So I fixed it to be the SPDX identifier for the Apache License 2.0 according to https://spdx.org/licenses/
Signed-off-by: Thanos Lefteris <alefteris@gmail.com>
=> Set a valid SPDX license identifier in package.json

CHANGELOG.md, lib/models/user.js, lib/sync.js
There was no way of observing changes to fields like currentlyActive, so add this and add one for lastPresenceTs that will be fired whenever we get a presence event.
This will hopefully help fix https://github.com/vector-im/vector-web/issues/1740
=> Add more events to User

lib/client.js
To help test the forthcoming device_id support for /login and /register, add
the device_id and initial_device_display_name parameters to those calls. Allow
the app to specify the default device displayname when creating the client (as
well as the device_id).
Also, don't try initialising the Olm layer unless a userId is
provided. Currently this isn't a problem because react-sdk doesn't provide a
sessionStore when it doesn't provide a userId, but that is a bad thing to rely
on (and I am going to break it with a react-sdk PR).
=> /login, /register: Add device_id and initial_device_display_name

lib/client.js
A couple of changes to support bigger changes in the react-sdk:
1. Add getDeviceId() to MatrixClient
2. Don't attempt to upload e2e keys if deviceId wasn't set.
=> deviceId-related fixes

lib/client.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-methods.spec.js
A number of the tests appear to have been broken since 90c919e without anyone
noticing; fix them.
=> Fix some broken tests

lib/base-apis.js, lib/client.js, lib/utils.js, spec/unit/utils.spec.js
Starts work on a class which is intended to just wrap the Matrix apis with very
simple functions.
There is a lot more work to be done here. For now, I have just taken methods
which don't refer to anything in MatrixClient except _http. This excludes a
bunch of things which refer to $userId, as well as the login stuff because of
the deviceId stuff I've just added :/.
For now, it's an internal class. I don't really see any reason it can't be
exposed to applications, though.
=> Factor out MatrixClient methods to MatrixBaseApis

lib/client.js
Synapse now (or will, after https://github.com/matrix-org/synapse/pull/978) returns the display_name in an e2e device query; we need to return it to the app.
=> client.listDeviceKeys: Expose device display name

lib/base-apis.js, lib/client.js, package.json, spec/integ/matrix-client-crypto.spec.js
Use another-json instead of awful manual json building. Sign the device keys at the point of upload, instead of having to keep the signed string in memory. Only upload device keys once (they are correctly merged with the one-time keys by synapse).
=> Refactor device key upload

lib/client.js
We no longer rely on js-sdk setting the initial_device_display_name and login_id on login, so remove them to make `login` simpler and allow the HS to impose its default behaviour on device display names (which is to leave them as null).
=> Remove defaultDeviceDisplayName from MatrixClient options

lib/base-apis.js, lib/client.js
login no longer relies on fields within MatrixClient, so we can move it down to BaseApis.
(includes changes from https://github.com/matrix-org/matrix-js-sdk/pull/168)
=> Move login and register methods into base-apis

lib/crypto.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-methods.spec.js
This is a prerequisite for a forthcoming refactor of _encryptMessage out to a
separate class.
=> Make DeviceInfo more useful, and refactor crypto methods to use it

lib/OlmDevice.js, lib/client.js, lib/crypto-algorithms/base.js, lib/crypto-algorithms/index.js, lib/crypto-algorithms/olm.js, lib/crypto.js, lib/matrix.js, lib/models/room.js, lib/timeline-window.js
- to make way for alternative encryption algorithms. We now store an encryption
object for each room, rather than referring to sessionstore on each event.
Also a little light tidying to the jsdocs.
=> Factor Olm encryption/decryption out to new classes

lib/OlmDevice.js, lib/crypto-algorithms/index.js, lib/crypto-algorithms/megolm.js, lib/store/session/webstorage.js
Very early attempt at encryption/decryption implementation via megolm. You have
to c&p the keys manually.
=> Implement megolm encryption/decryption

lib/crypto-algorithms/base.js, lib/crypto-algorithms/megolm.js, lib/crypto-algorithms/olm.js, lib/crypto.js
It is possible for `room` to be null when passed to `MegolmEncryption.encryptMessage`; we need to avoid dereferencing it. Instead, make sure that the `EncryptionAlgorithm` knows about the roomId it is targeting, and use that.
Replace the increasingly-long argument list on the `EncryptionAlgorithm` constructor with a params list, and update `DecryptionAlgorithm` to match.
=> Megolm: don't dereference nullable object

lib/client.js, lib/models/user.js
(Old PR was broken in horrible ways, thanks git)
Signed-off-by: Will Hunt half-shot@molrams.com
=> Added ability to set and get status_msg for presence.

lib/OlmDevice.js, lib/crypto-algorithms/megolm.js, lib/crypto-algorithms/olm.js, lib/crypto.js, lib/olmlib.js
Make a library file with some constants and a function to pack olm-encrypted
events (which we are going to use from megolm)
=> Factor out a function for doing olm encryption

lib/crypto-deviceinfo.js, lib/crypto.js, spec/integ/matrix-client-crypto.spec.js
Nothing was using the results (except the tests), and it's more useful to have
the devices we *do* have a session for than the ones we don't.
=> Change the result structure for ensureOlmSessionsForUsers

lib/crypto-algorithms/olm.js, spec/integ/matrix-client-crypto.spec.js
Commit 4cde51b3 broke device blocking such that we were encrypting for all
devices, including blocked ones. Reinstate it, and add a test.
=> Reinstate device blocking for simple Olm

lib/models/event.js, spec/integ/matrix-client-event-timeline.spec.js, spec/test-utils.js
When we got a redaction event, we were adding the entire (circular) MatrixEvent
object for the redaction to the redacted event, which would then cause
exceptions down the line (particularly when dealing with gappy timelines).
We should only be adding the raw event.
Fixes (hopefully) https://github.com/vector-im/vector-web/issues/1389.
=> Fix exceptions when dealing with redactions

lib/webrtc/call.js
fixes https://github.com/vector-im/vector-web/issues/1271 and https://github.com/vector-im/vector-web/issues/621
=> always play audio out of the remoteAudioElement if it exists.

package.json
Olm 1.0.0 had broken OlmAccounts; upgrade to a more recent one.
When we try to restore the old OlmAccount, we'll get an error; detect this and
create a new OlmAccount.
Because we do this, we will see key changes on other devices; we want to
tolerate this, so we define a new algorithm tag,
m.olm.v2.curve25519-aes-sha2. If we see a device which previously didn't
support that algorithm, but now does, we tolerate a key change (but reset the
device to unverified).
=> Update to fixed olmlib

lib/OlmDevice.js, lib/client.js, lib/crypto.js
A couple of small refactors which fell out of the aborted stuff for upgrading
to secure Ed25519 keys, but are useful in their own right.
The main functional change here is to calculate the "algorithms" list from
DECRYPTION_CLASSES (and hence include megolm in the list).
=> Olm-related cleanups

lib/client.js, lib/crypto-deviceinfo.js, lib/crypto.js
Implement MatrixClient.getStoredDevicesForUser which uses
Crypto.getStoredDevicesForUser, which is more powerful than listDeviceKeys, and
isn't deprecated.
Also a couple of accessors for DeviceInfo.
=> MatrixClient.getStoredDevicesForUser

lib/OlmDevice.js, lib/crypto.js
I've been trying to track down issues with the OlmSessions getting out of sync
between two devices. To help with this, add a method which can be used from the
JS console to inspect the state of OlmSessions.
(Requires https://github.com/matrix-org/olm-backup/pull/15 to actually work)
=> Add debug methods to get the state of OlmSessions

lib/crypto-algorithms/megolm.js
Apparently `body` is going to be special.
=> Use `ciphertext` instead of `body` in megolm events

lib/crypto.js
Turns out all we need to do is to make sure we use the Olm device table when we
look up megolm senders.
=> Fix sender verification for megolm messages

lib/base-apis.js, lib/client.js, lib/crypto-algorithms/megolm.js, lib/sync.js
Synapse now supports out-of-band messages, so use them instead of sending the
key-sharing messages in-band.
=> Use to-device events for key sharing

lib/client.js, lib/crypto-algorithms/base.js, lib/crypto-algorithms/olm.js, lib/crypto.js, spec/integ/matrix-client-crypto.spec.js
In what I hoped would be a five-minute refactor to help clean up an annoying not-really-used codepath, but turned into a bit of a hackathon on the tests, create Olm sessions lazily in Olm rooms, just as we do in megolm rooms, which allows us to avoid having to get the member list before configuring e2e in a room.
=> Don't create Olm sessions proactively

lib/crypto/algorithms/base.js, lib/crypto/algorithms/megolm.js, lib/crypto/index.js, lib/models/room-member.js
When a new member joins the room, we don't need to reset the megolm session;
instead we can just share the current state with the new user.
=> Share the current ratchet with new members

lib/crypto/algorithms/olm.js, lib/sync.js
If we can't decrypt a to-device message, show a warning about it, rather than swallowing the error.
=> Show warnings on to-device decryption fail

lib/crypto/index.js
Might fix vector-im/vector-web#2160
=> Wrap the crypto event handlers in try/catch blocks

lib/crypto/OlmDevice.js, lib/crypto/algorithms/megolm.js, lib/crypto/algorithms/olm.js, lib/crypto/index.js
This should reduce the risk of a device getting permanently stuck unable
to receive encrypted group messages.
TODO:
=> Send a 'm.new_device' when we get a message for an unknown group session

lib/crypto/OlmDevice.js, lib/crypto/algorithms/megolm.js, lib/crypto/algorithms/olm.js, lib/crypto/index.js, lib/models/event.js
These list the keys that sender of the event must have ownership
of and the keys of that the sender claims ownership of.
All olm and megolm messages prove ownership of a curve25519 key.
All new olm and megolm message will now claim ownership of a
ed25519 key.
This allows us to detect if an attacker claims ownership of a curve25519
key they don't own when advertising their device keys, because when we
receive an event from the original user it will have a different ed25519 key
to the attackers.
=> Add getKeysProved and getKeysClaimed methods to MatrixEvent.

lib/crypto/index.js
Otherwise we will use a value from a previous iteration of the loop.
=> Reset oneTimeKey to null on each loop iteration.

lib/crypto/index.js
Fix a bunch of bugs in the code which tried to send an oh_hai message when we
got a message with an unknown megolm session.
=> Fix sending of oh_hais on bad sessions

lib/crypto/algorithms/megolm.js, lib/crypto/index.js
When a new user joins a room, make sure we download their device list if we
don't already have it.
This should fix at least one cause of
https://github.com/vector-im/vector-web/issues/2249.
=> Pull user device list on join

lib/client.js, lib/crypto/OlmDevice.js, lib/crypto/algorithms/base.js, lib/crypto/algorithms/megolm.js, lib/crypto/algorithms/olm.js, lib/crypto/index.js, lib/crypto/olmlib.js, lib/models/event.js
This completes the work Mark started in https://github.com/matrix-org/matrix-js-sdk/pull/206 on fixing https://github.com/vector-im/vector-web/issues/2215.
* Include the Ed25519 key in all outgoing olm messages, including those used to  establish megolm sessions.
* In MatrixEvent, keep the claimed and proved keys as separate properties rather than stuffing them into _clearEvent
* Make sure we store the claimed Ed25519 key correctly in the megolm sessions.
(Includes https://github.com/matrix-org/matrix-js-sdk/pull/214)
=> Fix the ed25519 key checking

lib/sync.js, spec/unit/matrix-client.spec.js
A `/sync` request may spuriously fail on occasion, without the "connection" actually being lost. To avoid spurious "Connection Lost" warning messages we ignore the first `/sync` and immediately retry, and only if that fails do we enter an ERROR state.
Is this sensible? Should we emit an event to indicate we *may* have lost a connection?
=> Handle the first /sync failure differently.

lib/crypto/index.js
Only call SessionStore.storeEndToEndDevicesForUser once per user, rather than
once per device.
(Probably also fixes a bug where, when a user removes all devices, the store
isn't updated)
=> crypto: remove duplicate code

lib/http-api.js
After an upload completed, we were failing to delete the details of the upload from the list (because the comparison was bogus), meaning we leaked an object each time.
While we're in the area:
- make the request methods take an opts object (instead of a localTimeout param), and deprecate the WithPrefix versions.
- make the non-xhr path for uploadContent use authedRequest instead of rolling its own.
- make cancelUpload use the promise.abort() hack for simplicity
=> Fix leak of file upload objects

lib/client.js
Remember to cancel the checkTurnServers callback when we stop the client.
=> Fix checkTurnServers leak on logout

lib/sync.js, spec/unit/matrix-client.spec.js
Reverts matrix-org/matrix-js-sdk#216
=> Revert "Handle the first /sync failure differently."

CHANGELOG.md, lib/client.js, lib/http-api.js, lib/sync.js, spec/unit/matrix-client.spec.js
This accomplishes the same as
https://github.com/matrix-org/matrix-js-sdk/pull/216/files, but
without the client waiting 110 seconds for a sync request to time
out. That is, don't display an error message a soon as a sync
request fails, since we should accept that sometimes long lived
HTTP connections will go away and that's fine.
Also:
* Use request rather than deprecated requestWithPrefix
* http-api: The empty string may be falsy, but it's a valid prefix
* Update the tests to mock keepalive behaviour appropriately, and change one to assert it just keeps emiting ERROR events if it keeps failing, rather than specifically if subsequent sync requests fail.
=> Don't emit ERROR until a keepalive poke fails

lib/client.js, spec/unit/matrix-client.spec.js
* if getFilter fails for a filterId, null out the localStorage id and redirect to the createFilter path. 
Currently it keeps retrying at `keepAlive` without invalidating: https://github.com/matrix-org/matrix-js-sdk/blob/master/lib/sync.js#L386 (Probably this should actually check whether it is an error that can be recovered through retry or not, rather than looping endlessly?) 
* add spec
* fix unit/matrix-client.spec.js http response not matching synapse
Here is what a response looks like (note that httpStatus was missing from the mock response in the beforeEach() setup of the spec): 
```es6
{
"errcode":"M_UNKNOWN",
"name":"M_UNKNOWN",
"message":"No row found",
"data":{"errcode":"M_UNKNOWN","error":"No row found"},
"httpStatus":404
}
```
=> Fix sync breaking when an invalid filterId is in localStorage

lib/http-api.js, spec/integ/matrix-client-methods.spec.js, spec/mock-request.js
9e89e71e broke uploadContent, making it set 'json=true' on the request, so that we would try to turn raw content into JSON. It also misguidedly set a client-side timeout of 30s.
Fix that, and add some tests to check `uploadContent` works.
In mock-request: distinguish between an expectation (`ExpectedRequest`) and an actual request (`Request`). Add support for checking the headers, and the request options in general, to `Request`.
=> Fix uploadContent for node.js

lib/http-api.js, spec/integ/matrix-client-methods.spec.js
Make sure we parse the json content of errors from `uploadContent` before trying to turn them into `MatrixErrors`.
=> Fix error handling on uploadContent

lib/base-apis.js, lib/http-api.js, spec/integ/matrix-client-methods.spec.js
Previously, the API for uploadContent differed wildly depending on whether you were on a browser with XMLHttpRequest or node.js with the HTTP system library. This lead to great confusion, as well as making it hard to test the browser behaviour.
The browser version expected a File, which could be sent straight to XMLHttpRequest, whereas the node.js version expected an object with a `stream` property. Now, we no longer recommend the `stream` property (though maintain it for backwards compatibility) and instead expect the first argument to be the thing to upload. To support the different ways of passing `type` and `name`, they can now either be properties of the first argument (which will probably suit browsers), or passed in as explicit `opts` (which will suit the node.js users).
Even more …
=> uploadContent: Attempt some consistency between browser and node

lib/sync.js
After a connection glitch we would normally sync with zero timeout
so the connection comes back faster, but we didn't if the first
keepalive succeeds since we never marked the connection as failed.
This makes the behaviour more consistent.
Also get rid of the connectionLost flag which was only used in
one place anyway.
=> Fix potential 30s delay on reconnect

lib/base-apis.js
The react-sdk sets guest access token to null sometimes, but we
previously added anything that was not 'undefined' to the params,
causing us to send parameters which overwrite the previous actual
parameters with the useless, {guest_access_token: null} which
caused registrations from an email link to break.
We should have no reason to send null, at least for these
particular params, so don't.
=> Fix params getting replaced on register calls

lib/crypto/index.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-methods.spec.js
Check that the user_id and device_id in device query responses match those that
we expect.
This resolves an unknown-key attack whereby Eve can re-sign Bob's keys with her
own key, thus getting Alice to send her messages which she can then forward to
Bob, making Bob think that Alice sent the messages to him.
=> Consistency checks for E2E device downloads

lib/crypto/OlmDevice.js, lib/crypto/algorithms/base.js, lib/crypto/algorithms/megolm.js, lib/crypto/algorithms/olm.js, lib/crypto/index.js, lib/crypto/olmlib.js, spec/integ/matrix-client-crypto.spec.js
Embed the sender, recipient, and recipient keys in the plaintext of Olm
messages, and check those fields on receipt.
Fixes https://github.com/vector-im/vector-web/issues/2483
=> Check recipient and sender in Olm messages

lib/crypto/algorithms/base.js, lib/crypto/algorithms/megolm.js, lib/crypto/index.js
In order to mitigate backward-secrecy concerns, make sure that we rotate the
outbound megolm session at regular intervals (every week/100 msgs by default).
=> Rotate megolm sessions

lib/base-apis.js, lib/crypto/index.js, spec/integ/matrix-client-crypto.spec.js
We have decided that signing one-time keys is the lesser of two evils;
accordingly, use a new key algorithm type (`signed_curve25519`), sign the
one-time keys that we upload to the server, and verify the signatures on those
we download.
This will mean that develop won't be able to talk to master, but hey, we're in
beta.
=> Sign one-time keys, and verify their signatures

lib/client.js, lib/sync.js
Useful for only syncing with a subset of joined rooms or only retrieving certain types of events.
=> Add ability to set a filter prior to the first /sync

release.sh
* Don't create a new release branch if the current branch starts
with 'release'
* This is definitely a bash script at this point
* Fix update_changelog test
* Tabs
=> More fixes to the release script

lib/matrix.js
SDK provides a way to set a new `request` function but doesn't make it easy to enquire what the current value is, meaning that if two layers of code both try to set it, they'll collide and one of them will lose. E.g. a current precedent 
https://github.com/matrix-org/matrix-appservice-bridge/blob/master/lib/components/client-factory.js#L39
Nicer would be if user code could obtain the currently-prevailing `request` function, apply some wrapping around it, and set that back, meaning that two pieces of code don't have to collide, and both of their effects will apply.
Right now there's no easy way to ask the SDK what its current `request` function is, requiring such evil hackery as
https://github.com/matrix-org/matrix-appservice-bridge/commit/91f12676629af1b1879c2312bbe217396a0100e1#diff-5af80 …
=> Make it easier for SDK users to wrap prevailing the 'request' function

lib/crypto/OlmDevice.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/megolm.spec.js, spec/test-utils.js
If we get a second key for a known megolm session, ignore it.
Fixes https://github.com/vector-im/vector-web/issues/2326, one hopes.
=> Ignore reshares of known megolm sessions

lib/utils.js
I was trying to use the matrix-js-sdk inside Mozilla chat client (https://bugzilla.mozilla.org/show_bug.cgi?id=1199855) and for some reason the utils.isArray function fails (it seems that two different Array constructors are involved in the comparison). Using the native Array.isArray function solves the problem and it seems well supported in modern browsers:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray
Note that the definition of isArray is more sophisticated in Ecmascript 2015:
http://www.ecma-international.org/ecma-262/5.1/#sec-15.4.3.2
http://www.ecma-international.org/ecma-262/6.0/#sec-isarray
=> Use native Array.isArray when available.

lib/utils.js
Reverts matrix-org/matrix-js-sdk#282 - this should have been against develop
=> Revert "Use native Array.isArray when available."

lib/client.js, lib/crypto/algorithms/base.js, lib/crypto/algorithms/megolm.js, lib/crypto/algorithms/olm.js, lib/crypto/index.js, lib/models/event.js
If we don't have the crypto keys available to decrypt an event when it first arrives, add it to a list, so that we can have another go at decrypting it. We raise an event when this happens so that applications can handle it appropriately.
Also remove the workaround that sends m.new_device messages when we get an unknown session; it's just a bandaid which is obscuring more meaningful problems.
You might find it more digestible to look at each commit separately.
(There will be a react-sdk PR to follow)
=> Handle decryption of events after they arrive

lib/crypto/algorithms/megolm.js
1a03e534bda introduced a bug which mixed up the keys_proved and the
keys_claimed. Switch them around again so that megolm messages are correctly
tied back to the sending device.
=> Fix bug in verifying megolm event senders

lib/sync.js
If no "old" timeline data is required when starting the client, it should be possible to set initialSyncLimit to 0 when calling startClient. See http://bit.ly/2f49Kbs for corresponding discussion.
=> Allows to start client with initialSyncLimit = 0

lib/crypto/algorithms/megolm.js, lib/crypto/index.js, lib/crypto/olmlib.js, spec/integ/megolm.spec.js
Instead of trying to maintain a list of devices we need to share with, just check all the devices for all the users on each send.
This should fix https://github.com/vector-im/vector-web/issues/2568, and generally mean we're less likely to get out of sync.
=> E2E: Check devices to share keys with on each send

lib/crypto/algorithms/base.js, lib/crypto/index.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-methods.spec.js
Two main changes here:
* when we get an m.new_device event for a device we know about, ignore it
* Batch up the m.new_device events received during initialsync and spam out all the queries at once.
This fixes https://github.com/vector-im/vector-web/issues/2274.
It also removes EncryptionAlgorithm.onNewDevice, so will break develop unless
https://github.com/matrix-org/matrix-js-sdk/pull/295 is landed.
=> Avoid a packetstorm of device queries on startup

lib/crypto/index.js, lib/crypto/olmlib.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/megolm.spec.js
Make sure we get a list of our own devices when starting a new client.
Fixes https://github.com/vector-im/riot-web/issues/2676.
=> E2E: Download our own devicelist on startup

lib/crypto/algorithms/megolm.js, spec/integ/megolm.spec.js
If we have shared the session with a device which is subsequently blacklisted,
we need to start a new session for the next message.
Rather than doing this proactively (which would be subject to false-positives
and require slightly awkward tracking of who we had shared the session with),
we check the list of who we have shared the session with on each send, and
start a new session if any of them are blocked.
Fixes https://github.com/vector-im/riot-web/issues/2146.
=> Start a new megolm session when devices are blacklisted

release.sh, scripts/changelog_head.py
if a signing ID is set in release_config.yaml
Also set the release text to the relevant changelog entry
=> Update release script to do signed releases

lib/base-apis.js
Add a function for setting the publicity of a room that is bridged to a 3rd party network. This change reflects the second bullet point of matrix-org/synapse#1676
=> Add setRoomDirectoryVisibilityAppService

package.json, spec/integ/megolm.spec.js, spec/unit/crypto.spec.js
... since the code requires it. Also update the tests.
=> Bump to Olm 2.0

lib/models/event.js, lib/models/room.js
This is useful because clients may often wish to construct Date instances using `getTs
()`, but `origin_server_ts` should never change and thus a Date instance can be created at construction time.
=> Add `getDate` function to MatrixEvent

lib/base-apis.js, lib/client.js, lib/http-api.js
Will be used to fix matrix-org/matrix-appservice-irc#328
=> Allow clients the ability to set a default local timeout

release.sh
This catches both things that are visible on `git diff` as well as staged (added) files. Cargo-culted from http://stackoverflow.com/questions/2657935/checking-for-a-dirty-index-or-untracked-files-with-git and manually tested both scenarios.
=> release.sh: Bail early if there are uncommitted changes

lib/webrtc/call.js
Because the https check only applies in the browser
Moved to https://github.com/matrix-org/matrix-react-sdk/pull/608
=> Move screen sharing check/error

package.json
and so is just redundant as you have babel-cli which is what you
actually want.
=> 'babel' is not a babel package anymore

browser-index.js, index.js, package.json
react-sdk's tests are failing because babel-polyfill is being
pulled in twice.
As per https://babeljs.io/docs/usage/polyfill/ babel-polyfill is
"intended to be used in an application rather than a library/tool".
From a library, we're limited to things that don't modify globals,
since the js env is not ours to start screwing around with.
=> Remove babel-polyfill

.eslintrc.js
As we sometimes use (x) => {foo = x;}, especially for react
components, but probably no reason not to allow it generally.
=> Allow single line brace-style

package.json, src/crypto/OlmDevice.js
We want to avoid distributing olm as part of the js-sdk, so we exclude it from
the browserified build. Previously this meant that you couldn't use olm this
way.
We can do better though: if the web page includes olm.js via a separate script
tag, that will set global.Olm, which we can get browserify to shim in.
=> Make Olm work with browserified js-sdk

src/crypto/index.js
I can't quite remember what the logic behind only recording the algorithm in
localstorage was, but the upshot is that if you try to set any e2e config
options (such as the megolm rotation periods) via the room state, then the
state gets rejected and you can't send any events.
=> Record all e2e room settings in localstorage

package.json
* use sourceify to read the sourcemaps written by babel
* use {browserify, watchify} -d to write sourcemap
* use exorcist to write the sourcemap to a separate file
* add some uglifyjs incantations to read and write sourcefiles
* simples
=> Enable sourcemaps in browserified distro

.travis.yml, docs/warning-on-unverified-devices.txt, jenkins.sh, package.json, src/crypto/algorithms/base.js, src/crypto/algorithms/megolm.js, src/crypto/deviceinfo.js, src/crypto/index.js
This adds a new crypto.DeviceInfo field called `known` which tracks whether the user has ever been made aware of a device's existence.
If the user tries to send a message into a room with unknown devices present, it throws a custom exception to the app with the details of the devices so the app can warn the user.  It also marks the devices as `known` given the user now knows they exist.
`known` is implemented as a flag on DeviceInfo rather than part of the verification enum as it's slightly semantically distinct from the concept of whether a device is verified or blocked (although it's questionable as to how a user would be able to verify or block a device without knowing it existed!).
The first draft of this tried to track `m.new_device` events as they came in, and warn the user if they …
=> Support for warning users when unknown devices show up

src/crypto/DeviceList.js, src/crypto/index.js
crypto/index.js was getting huge, so move the device list update management out
to a separate file.
This shouldn't have any effect on functionality.
=> Factor out device list management

src/client.js, src/models/event.js
so we can generate better error msgs in the app
=> track errors when events can't be sent

src/client.js, src/crypto/algorithms/megolm.js, src/crypto/index.js, src/models/room.js, src/sync.js
Builds on #335, which should be landed before this review makes any sense.
Twinned with https://github.com/matrix-org/matrix-react-sdk/pull/636.
Hopefully solves https://github.com/vector-im/riot-web/issues/2313
=> Support for blacklisting unverified devices, both per-room and globally

spec/integ/matrix-client-methods.spec.js, src/base-apis.js, src/client.js, src/crypto/DeviceList.js, src/crypto/index.js, src/store/session/webstorage.js, src/sync.js
Listen to the notifications from /sync to tell us when a user's devices are out
of date. We're leaving the `m.new_device` stuff in place for now, for
compatibility with old homeservers/clients.
Builds on https://github.com/matrix-org/matrix-js-sdk/pull/347.
Fixes (together with the server-side support) https://github.com/vector-im/riot-web/issues/2305.
=> Use the device change notifications interface

release.sh
This assumes that we'll eventually do a proper release (or merge the prerel
manually), and saves twiddling the package.json on downstream projects for each
prerelease.
=> When doing a pre-release, don't bother merging to master and develop.

release.sh
When we are doing a signed release, also create a sig for the 'archive' tarball
which github creates for us.
Fixes https://github.com/vector-im/riot-web/issues/3024.
=> Make a sig for source tarballs when releasing

spec/unit/crypto.spec.js
Olm is an optional dependency, so the tests should work without it.
=> Make the tests work without olm

src/realtime-callbacks.js
We had a test for this, but apparently it wasn't testing it right...
=> realtime-callbacks: pass `global` as `this`

src/client.js
This doesn't make any difference to the JSON, but it upsets `expect`.
=> searchMessageText: avoid setting keys=undefined

package.json, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-event-emitter.spec.js, spec/integ/matrix-client-event-timeline.spec.js, spec/integ/matrix-client-methods.spec.js, spec/integ/matrix-client-opts.spec.js, spec/integ/matrix-client-retrying.spec.js, spec/integ/matrix-client-room-timeline.spec.js, spec/integ/matrix-client-syncing.spec.js, spec/integ/megolm.spec.js, spec/unit/content-repo.spec.js, spec/unit/crypto.spec.js, spec/unit/event-timeline.spec.js, spec/unit/filter.spec.js, spec/unit/interactive-auth.spec.js, spec/unit/matrix-client.spec.js, spec/unit/pushprocessor.spec.js, spec/unit/realtime-callbacks.spec.js, spec/unit/room-member.spec.js, spec/unit/room-state.spec.js, spec/unit/room.spec.js, spec/unit/scheduler.spec.js, spec/unit/timeline-window.spec.js, spec/unit/user.spec.js, spec/unit/utils.spec.js
This makes exception traces use the source map, which is much more helpful when
debugging.
=> Install source-map-support in each test

spec/TestClient.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-methods.spec.js, spec/integ/megolm.spec.js, spec/mock-request.js, src/crypto/DeviceList.js, src/crypto/algorithms/olm.js, src/crypto/index.js
... and other stories.
Most of this was cleanup work to get to a state where this change didn't break all the tests inexplicably. The commits might make some sense on their own - or I can pull it into separate PRs if you like.
=> Invalidate device lists when encryption is enabled in a room

src/client.js, src/crypto/DeviceList.js, src/crypto/algorithms/base.js, src/crypto/algorithms/megolm.js, src/crypto/algorithms/olm.js, src/sync.js
In an attempt to make the rageshake logs a bit more useful, try to make the
logging a bit saner. Firstly, make sure we log every decryption failure, and
log it exactly once, rather than in several places. Also record when we receive
megolm keys. Also add some more explicit logging in the sync loop.
=> Clean up/improve e2e logging

spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-room-timeline.spec.js, spec/integ/megolm.spec.js, spec/mock-request.js, src/crypto/DeviceList.js
Avoid a big freeze when we process the results of a device query, by splitting
the work up by user.
Fixes https://github.com/vector-im/riot-web/issues/3158
=> Spread out device verification work

src/client.js
Which didn't work because of
https://github.com/matrix-org/synapse/issues/1860
=> Fix the unban method

spec/integ/megolm.spec.js, src/crypto/DeviceList.js, src/crypto/index.js
Hopefully this fixes both the races described in https://github.com/vector-im/riot-web/issues/3126. Suggest reviewing the commits separately.
=> Fix race conditions in device list download

src/crypto/DeviceList.js
Update the sync token whenever the device list is in sync. Fixes
https://github.com/vector-im/riot-web/issues/3127.
=> Keep the device-sync token more up-to-date

src/client.js, src/sync.js
On first connect, or after a disconnection, poll /sync with timeout=0 until
we get no to_device messages back. This will allow us to figure out whether
we have more to_device messages queued up for us on the server, which in
turn will help us fix https://github.com/vector-im/riot-web/issues/2782.
=> Poll /sync with a short timeout while catching up

src/store/indexeddb.js, src/store/memory.js, src/store/stub.js
It's required for the 'clear cache' button since we only want to refresh the
page after the transaction has gone through.
=> Make deleteAllData() return a Promise

src/store/indexeddb.js
Longer term we might want to consider fragmenting the /sync response from being a single row into multiple rows and then recombine them on startup (similar to how we do for riot-web logs) to reduce pause times.
=> Increase the WRITE_DELAY on database syncing

spec/TestClient.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/megolm.spec.js, src/client.js, src/crypto/index.js
Delay the upload of one-time keys until we have received a sync *without any to-device messages*. Doing so means that we can try to avoid throwing away our private keys just before we receive the to-device messages which use them.
Once we've decided to go ahead and upload them, we keep uploading them in batches of 5 until we get to the desired 50 keys on the server. We then periodically check that there are still enough on the server.
Fixes https://github.com/vector-im/riot-web/issues/2782.
=> Upload one-time keys on /sync rather than a timer

spec/unit/sync-accumulator.spec.js, src/store/indexeddb.js, src/sync-accumulator.js, src/sync.js
Previously, we treated the `MatrixEvents` that were in `this.accountData` in
`MatrixInMemoryStore` as the ground truth and saved those to disk and restored
them back upon load. This did not consider that there are **no emitted events**
when they are restored. Riot-Web was listening for a specific account data
event in order to dynamically update the theme. When the page was reloaded, we
dutifully put the right event in `MatrixInMemoryStore`, but failed to emit an
event to tell Riot-Web this. This led to vector-im/riot-web#3247
This patch fixes it by treating the `/sync` response as the ground truth and
ignoring `this.accountData` entirely. This means that upon load, we will be
injecting an `account_data` key into the initial `/sync` response. This will
cause it to be added to …
=> Store account data in the same way as room data

src/client.js
MatrixCall has a `roomId` property, but not a `room_id` property.
=> src/client.js: Fix incorrect roomId reference in VoIP glare code

spec/unit/interactive-auth.spec.js, src/base-apis.js, src/interactive-auth.js
Extends the interactive-auth to support m.login.email.identity
This also includes the ability to resume a UI auth session given
the appropriate information (ie. to resume the auth flow having
clicked a link in a verification email) and supports polling for
the auth session having been completed elsewhere.
=> Add m.login.email.identity support to UI auth

src/interactive-auth.js
Other places sometimes need to re-use the email sid to send proof
of ownership of a email address to somewhere else.
=> Add getEmailSid

src/interactive-auth.js
Otherwise we get very confused and go back to the start when given
a response with no flows etc.
=> Save the completed flows

src/http-api.js
Instead of just using a timeout to reject ongoing requests, reset the timeout when progress is observed (at least when requests are done from browsers).
This is to fix https://github.com/vector-im/riot-web/issues/2737
Supersedes https://github.com/matrix-org/matrix-js-sdk/pull/390
=> Use XHR onprogress to debounce http._request timeout

spec/unit/sync-accumulator.spec.js, src/sync-accumulator.js
With a regression test now included..
Fixes vector-im/riot-web#3375
=> Handle 'limited' timeline responses in the SyncAccumulator

src/models/event.js
Required for fixing https://github.com/matrix-org/matrix-js-sdk/issues/387
=> Update event redaction to keep sender and origin_server_ts

src/base-apis.js
Request the msisdn stages in the register UI auth, as commented
=> Add x_show_msisdn parameter to register calls

src/interactive-auth.js
This allows us to also use it to decide whether or not to show
the app as busy in the UI. We pass this flag up into the
makeRequest callback so it can use it as such.
=> Extend 'ignoreFailure' to be 'background'

src/http-api.js
Put the check for 'onprogress' within the check to see if req is
defined, because sometimes it isn't, apparently.
=> Fix undefined reference in http-api

src/webrtc/call.js
video.src = URL.createObjectURL(stream) is on the way out. Firefox will
complain with errors about not being able to play media of type
"text/html" for example.
=> webrtc/call: Assign MediaStream to video element srcObject

src/store/indexeddb.js
The console will maintain a strong ref to this object, which may exacerbate
memory leaks.
=> Don't log the entire /sync response

src/sync.js
Syncing should probably mean the stream is up to date and
streaming messages in real-time from the server, which is not the
case if we've only loaded the cached response. Stay PREPARED until
we actually get the latest from the server.
=> Don't be SYNCING until updating from the server

src/store/indexeddb.js
Hide the IndexedDBBackend and SyncAccumulator objects and have
indexeddbstore instaniate them itself, rather than making the app
instantiate them. Pass the approipriate options through. This
gives us much more flexibility to move things around under the
hood.
=> Change interface of IndexedDBStore: hide internals

spec/unit/matrix-client.spec.js, src/client.js, src/store/indexeddb.js, src/store/memory.js, src/store/stub.js, src/sync.js
* Make sync communicate with the sync accumulator via the store
* Consequently get rid of getSyncAccumulator as it's now
unnecessary.
* Make the bit that gets the saved sync response async, because
we'll need it to be when it's coming over postMessage from a
webworker.
Based off of https://github.com/matrix-org/matrix-js-sdk/pull/406
=> Further reorganising of indexeddb sync code

src/sync.js
when a /sync leads to an error, increase a counter and use the counter to decide which state to be in when starting keepAlives. If the count is above a certain threshold (arbitrary 3 chosen here), switch from RECONNECTING to ERROR to show that the server is facing difficulties that aren't affeting is ability to return on /versions.
Attempts to fix https://github.com/vector-im/riot-web/issues/3336
=> Indicate syncState ERROR after many failed /syncs

src/store/indexeddb-local-backend.js, src/store/indexeddb-remote-backend.js, src/store/indexeddb-remote-worker.js, src/store/indexeddb-store-worker.js, src/store/indexeddb.js
Don't needlessly transfer data from the worker to the main script
only to immediately transfer it right back again.
This is based off https://github.com/matrix-org/matrix-js-sdk/pull/412
=> Make indexeddb startup faster

src/store/indexeddb.js, src/sync.js
Save the sync data to indexeddb after the first catch-up
Fixes vector-im/riot-web#3527
This is based off of https://github.com/matrix-org/matrix-js-sdk/pull/413
=> Make indexeddb save after the first sync

release.sh
Publish to npm before switching to the doc branch: previously we
published from master, but since we now now longer merge
pre-releases to master, publish from the release branch (just
not the doc branch because that won't work).
=> Fix release script

src/store/indexeddb-remote-backend.js, src/store/indexeddb.js
Only use web worker store if we have web workers available
=> Add feature detection for webworkers

release.sh
After a pre-release, check out the release branch again rather
than leaving the working copy on the gh-pages branch
=> Don't leave the gh-pages branch checked out

src/interactive-auth.js
Dummy auth flows, by definition, do not require a response from
the user, and so should just be completed automatically by
interactive-auth.
Fixes https://github.com/vector-im/riot-web/issues/3621
=> Automatically complete dummy auth

src/webrtc/call.js
Previously if two calls were constructed within 1ms they could have the
same id.
=> webrtc/call: Make it much less likely that callIds collide locally

src/base-apis.js, src/client.js
This is now stored on the server with similar treatment to RRs. The server will only store the specified eventId as the current read marker for a room if the event is ahead in the stream when compared to the existing RM. The exception is when the RM has never been set for this room for this user, in which case the event ID will be stored as the RM without any comparison.
This API also allows for an optional RR event ID to be sent in the same request. This is because it might be the common case for some clients to update the RM at the same time as updating the RR.
See design: https://docs.google.com/document/d/1UWqdS-e1sdwkLDUY0wA4gZyIkRp-ekjsLZ8k6g_Zvso/edit
See server-side PR: https://github.com/matrix-org/synapse/pull/2120
=> Implement API for setting RM

spec/TestClient.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/megolm.spec.js, src/crypto/DeviceList.js, src/crypto/index.js, src/store/session/webstorage.js
Yet another attempt at fixing https://github.com/vector-im/riot-web/issues/2305.
This now implements the algorithm described at http://matrix.org/speculator/spec/HEAD/client_server/unstable.html#tracking-the-device-list-for-a-user:
* We now keep a flag to tell us which users' device lists we are tracking. That makes it much easier to figure out whether we should care about device-update notifications from /sync (thereby fixing https://github.com/vector-im/riot-web/issues/3588).
* We use the same flag to indicate whether the device list for a particular user is out of date. Previously we did this implicitly by only updating the stored sync token when the list had been updated, but that was somewhat complicated, and in any case didn't help in cases where we initiated the key download due to …
=> Rework device list tracking logic

src/webrtc/call.js
When making video calls, if the caller or callee did not have a microphone, the call would fail. These changes make video callers/callees always offer to receive audio and video, regardless of what they are able to send. This allows one person to send audio and video and the other to send only audio, for example. Technically it is more flexible than that, in that the peer can send anything from nothing to both audio and video, but that is the primary purpose.
There is a commit that explicitly unmutes the remote audio element when setting it. This is so that one can re-use a remote video element also for remote audio, which is useful in some cases and probably a no-op in most others. It could unmute a muted remote audio element, but that can easily be handled externally after setting the …
=> WebRTC: Support recvonly for video for those without a webcam

spec/unit/crypto/DeviceList.spec.js, src/crypto/DeviceList.js
Don't consider device lists up-to-date when we have another request for the
relevant user in the queue.
Fixes https://github.com/vector-im/riot-web/issues/3796.
=> Fix race in device list updates

src/base-apis.js
Requires synapse with https://github.com/matrix-org/synapse/pull/2183 and https://github.com/matrix-org/synapse/pull/2209 
**Update**: this needs to be changed to reflect https://github.com/matrix-org/synapse/pull/2213
=> Implement API for username availability

src/webrtc/call.js
FF is uber nice that it lets us select the display
does not seem to allow the composite ALL displays though like chromium does by default
=> make screen sharing call FF friendly :D

src/client.js
Expose the `crypto.getStoredDevice(userId, deviceId)` api publically
=> Add in a public api getStoredDevice allowing clients to get a specific device

.gitignore, package.json
jsdoc can't read our raw source, because of our dangling commas in function
calls. On the other hand, running on /lib means that a lot of the useful
information about exports is lost and you end up having to jump through hoops
to get jsdoc to generate the right thing.
This uses a separate run of babel (with all the presets turned off) to generate
source which is almost identical to the input, but lacks trailing commas.
(https://babeljs.io/blog/2015/10/31/setting-up-babel-6 says 'Babel 6 ships
without any default transforms, so when you run Babel on a file it will just
print it back out to you without changing anything.' - however, that is,
empirically, not entirely true.)
=> Run jsdoc on a custom babeling of the source

src/models/room-state.js
allows to more nicely fix vector-im/riot-web/issues/273
edit:
d182fd6 means can't redact things with that string/enum set as they're not really complete
=> maySendRedactionForEvent for userId

src/client.js, src/crypto/algorithms/base.js, src/crypto/index.js
Convert base to an es6 module with es6 classes, for clarity and to help with
jsdoccing.
Complications are:
* jsdoc gets confused by `export class`, so the exports are separated.
* turns out that extending Error is a bit difficult, so instanceof doesn't work
on derived Error classes. This only really affects us in one place (app-side
code shouldn't be doing instanceofs anyway), so just use `name` instead.
=> crypto/algorithms/base.js: Convert to es6

browser-index.js, src/client.js, src/crypto/index.js, src/crypto/store/base.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/memory-crypto-store.js, src/matrix.js
Doesn't do anything useful yet - just demonstrates a framework for how I hope it will fit into the sdk.
The idea here is that you can configure a factory to build a crypto store whenever you call `createClient` (if you don't pass one in explicitly). The default is an in-memory store, but `browser-index.js` sets the factory to the indexeddb impl.
=> Initial framework for indexeddb-backed crypto store

CHANGELOG.md, README.md, package.json, spec/integ/matrix-client-methods.spec.js, src/client.js, src/crypto/OlmDevice.js
This means that we can avoid confusing everybody in the world about how to
webpack js-sdk apps.
=> Load Olm from the global rather than requiring it.

README.md
Olm is not available via the npm registry, so ``npm install olm`` doesn't work. What's worse, it has been available in the past but is now unpublished, which combined with an issue in npm leads to a confusing error message when trying to do the install.
The approach used by Riot Web (which I assume is the "right" approach) is to use the tarball notation of npm to install the latest olm tarball and (if needed) add it to the project dependencies while doing so.
This PR hopes to clarify the README in this regard.
(Also, just using ``require('olm');`` didn't work for me, I needed to explicitly assign it to the ``global.Olm`` object via ``global.Olm = require('olm');``. I have clarified this as well.)
Signed-off-by: Alexander Rudyk (ar-git@mailbox.org)
=> Update README: Clarify how to install libolm

src/client.js, src/sync.js
Otherwise we get very confused when the peek poll returns after
the client is stopped.
=> Stop peeking when a matrix client is stopped

src/sync.js
Instead of getting the room by ID every time the room is polled for events, which could cause issues if the state of the room is modified from under the peeking logic (if the user joined the room or registered etc.)
=> Use single room object for duration of peek

src/client.js, src/crypto/algorithms/base.js, src/crypto/index.js
Doesn't actually do any of the crypto magic yet.
=> Process received room key requests

src/crypto/OlmDevice.js, src/crypto/algorithms/base.js, src/crypto/algorithms/megolm.js, src/crypto/index.js
This builds on previously-landed code (specifically #449) to implement sharing of megolm keys.
When we get a request from one of our other devices we check (via the existing hook https://github.com/matrix-org/matrix-js-sdk/blob/665ed057e364ec54f20513c489749cc1e985fbac/src/crypto/index.js#L1158) whether we have the keys for that session. If the device is verified, or the user accepts the request, we then send an m.forwarded_room_key event with the keys to the session.
=> Implement sharing of megolm keys

src/base-apis.js
This takes a JSON body of the form:
```json
{
"term": "search term",
"limit": 42,
}
```
where "term" is the term to match against user IDs, display names and domains and "limit" is the maximum number of results to return.
The response body looks like
```json
{
"results ": [
{ "user_id": "@someid:mydomain.com", "display_name": "Some Name", "avatar_url": "mx://..." },
...
],
"limited": false
}
```
where "limited" indicates whether the "limit" was used to truncate the list.
=> Add API for POST /user_directory/search

src/timeline-window.js
If we have the events in memory, let TimelineWindow.load() return
a resolved promise, so that the UI can show the view straight away instead
of showing the spinner.
=> Make TimelineWindow.load resolve quicker if we have the events

src/webrtc/call.js
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection#RTCIceTransportPolicy_enum
=> allow setting iceTransportPolicy to relay through forceTURN option

src/crypto/OutgoingRoomKeyRequestManager.js, src/crypto/store/indexeddb-crypto-store.js
Hopefully this will fix the vector-web test failures (the
OutgoingRoomRequestManager throws an exception because the indexeddb is being
deleted just as it's getting started).
=> Avoid throwing an unhandled error when the indexeddb is deleted

src/crypto/store/indexeddb-crypto-store.js, src/store/indexeddb-local-backend.js, src/store/indexeddb-remote-backend.js
Treat errors when deleting indexeddb as non-fatal
also let the webworker be used for deleting the indexeddb without it having previously been used for syncing.
(part of the fix to https://github.com/vector-im/riot-web/issues/4340)
=> Fix issues with firefox private browsing

spec/TestClient.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-event-timeline.spec.js, spec/integ/matrix-client-opts.spec.js, spec/integ/matrix-client-room-timeline.spec.js, spec/integ/megolm-integ.spec.js
There is a common pattern in the tests which is, when we want to mock a /sync,
to flush it, and then, in the next tick of the promise loop, to wait for the
syncing event. However, this is racy: there is no guarantee that the syncing
event will not happen before the next tick of the promise loop.
Instead, we should set the expectation of the syncing event, then do the flush.
(Technically we only need to wait for the syncing event, but by waiting for
both we'll catch any errors thrown by the flush, and make sure we don't have
any outstanding flushes before proceeding).
Add a utility method to TestClient to do the above, and use it where we have a
TestClient.
(Also fixes a couple of other minor buglets in the tests).
=> Fix some races in the tests

src/base-apis.js
Check that /thirdparty/protocols gives us an object (rather than a string, for
instance). I saw a test explode, apparently because it gave us a string. Which
is odd, but in general we ought to be sanity-checking the things coming back
from the server.
=> Sanity-check response from /thirdparty/protocols

spec/integ/matrix-client-crypto.spec.js, src/crypto/index.js, src/store/session/webstorage.js
We now rely on the server to track new devices, and tell us about them when
users add them, rather than forcing devices to announce themselves (see
https://github.com/vector-im/riot-web/issues/2305 for the whole backstory
there).
The necessary support for that has now been in all the clients and the server
for several months (since March or so). I now want to get rid of the
localstorage store, which this code is relying on, so now seems like a good
time to get rid of it. Yay.
=> Remove m.new_device support

.babelrc, package.json, src/matrix.js
Enables the babel plugin that transpiles async/await to generator functions,
and load the regenerator runtime so that generator functions work.
=> Make it possible to use async/await

spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-event-timeline.spec.js, spec/integ/matrix-client-methods.spec.js, spec/integ/matrix-client-retrying.spec.js, spec/integ/matrix-client-syncing.spec.js, spec/integ/megolm-integ.spec.js, spec/test-utils.js, spec/unit/interactive-auth.spec.js, spec/unit/timeline-window.spec.js
This was a helper function I wrote for testing asynchronous tests before I knew better. It turns out there are better ways of doing what it did badly:
* using `nodeify` to turn promise results into nodejs-style callbacks, which is what `done` wants
* or, now that we use mocha rather than jasmine, just returning a promise from the test function.
`failTest` obfuscates the actual source of the failure, so let's kill it off.
=> Remove testUtils.failTest

spec/integ/matrix-client-crypto.spec.js, src/client.js
(as well as a similar bug in the test suite)
Turns out that `q.all(a, b)` === `q.all([a])`, rather than `q.all([a,b])`: it
only waits for the *first* promise - which means that `client.setGuestAccess`
would swallow any errors returned from the API.
=> Fix early return in MatrixClient.setGuestAccess

package.json, spec/TestClient.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-event-emitter.spec.js, spec/integ/matrix-client-syncing.spec.js, spec/integ/megolm-integ.spec.js
Once we switch to bluebird, suddenly a load of timing issues come out of the
woodwork. Basically, we need to try harder when flushing requests. Bump to
matrix-mock-request 1.1.0, which provides `flushAllExpected`, and waits for
requests to arrive when given a `numToFlush`; then use `flushAllExpected` in
various places to make the tests more resilient.
=> Fix a bunch of races in the tests

spec/integ/matrix-client-event-timeline.spec.js
Call `flushAllExpected()` from some more places. In a couple of places, we were
apparently calling `flush()` redundantly, so remove it altogether.
=> More test deflakifying

spec/integ/matrix-client-syncing.spec.js
All of these tests were vulnerable to a race wherein we would flush the /sync
request, but the client had not yet processed the results before we checked
them. We can solve all of this by waiting for the client to emit a "sync"
event.
=> Deflake the matrixclient syncing tests

src/base-apis.js, src/http-api.js
bluebird doesn't support promise progression (or rather, it does, but it's
heavily deprecated and doesn't use the same API as q), so replace the
(undocumented) promise progression on uploadFile with a callback.
=> Add progress handler to `uploadContent`

src/crypto/store/memory-crypto-store.js
Fixes a race in the memory-backed crypto store which meant that we would spam
out multiple key-share-requests for the same session.
(This didn't happen very often in practice, because normally we use the
indexeddb-backed store, which is race-free. Or at least, doesn't have this
race.)
=> Fix spamming of key-share-requests

spec/integ/matrix-client-retrying.spec.js, src/scheduler.js
when a message send fails, the promise returned by `sendMessage` is
rejected. Until we switched to bluebird, the rejection was happily being
swallowed, but with bluebird, there's a better chance of the unhandled
rejection being caught by the runtime and mocha and failing the test.
=> Fix racy 'matrixclient retrying' test

package.json, spec/integ/matrix-client-room-timeline.spec.js, spec/integ/megolm-integ.spec.js, spec/unit/crypto/algorithms/megolm.spec.js
Requires a version of matrix-mock-request including https://github.com/matrix-org/matrix-mock-request/pull/5, so this won't build yet.
=> Yet more js-sdk test deflakification

spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-syncing.spec.js, src/crypto/index.js, src/sync.js
As of matrix-org/synapse#2237 the server sends `"device_one_time_keys_count"` as part of the `/sync`-response.
But currently this is nowhere used.
This PR changes this.
Another change: While uploading `one_time_keys` now the response will be used to measure how many keys to upload are left over. Especially useful when trying to abort uploading in tests.
Signed-off-by: Matthias Kesler <krombel@krombel.de>
=> use device_one_time_keys_count transmitted by /sync

CHANGELOG.md, README.md, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-methods.spec.js, spec/integ/megolm-integ.spec.js, src/client.js, src/crypto/index.js
We're going to need to make a bunch of these APIs asynchronous, so that we can do indexeddb stuff within them.
Add MatrixClient.initCrypto: initialising the crypto layer needs to become
asynchronous. Rather than making `sdk.createClient` asynchronous, which would
break every single app in the world, add `initCrypto`, which will only break
those attempting to do e2e (and in a way which will fall back to only
supporting unencrypted events).
Make the following return Promises:
* `MatrixClient.getStoredDevicesForUser`
* `MatrixClient.getStoredDevice`
* `MatrixClient.setDeviceVerified`
* `MatrixClient.setDeviceBlocked`
* `MatrixClient.setDeviceKnown`
* `MatrixClient.getEventSenderDeviceInfo`
* `MatrixClient.isEventSenderVerified`
* `MatrixClient.importRoomKeys`
Remove `listDeviceKeys` …
=> Make bits of the js-sdk api asynchronous

.babelrc, package.json, src/matrix.js
Attempting to use the regnerator-runtime ourselves led to a fight with riot-web about whether `global.regeneratorRuntime` could be defined. By using the transform-runtime plugin, references to `global.regeneratorRuntime` which are created by the transform-regenerator plugin are turned into references to an imported module, which works much better.
(The full tragic tale went as follows:
- riot-web uses transform-runtime, which adds an import of `regenerator-runtime` to index.js
- `regenerator-runtime`:
- loads `regenerator-runtime/runtime`, which defines `global.regeneratorRuntime`
- then clears the global property and returns the regeneratorRuntime object as the exported value from the module
- later, the js-sdk tried to import `regenerator-runtime/runtime`, which then did nothing because …
=> Use babel transform-runtime instead of regenerator-runtime

package.json
We need jsdoc 3.5 to support the async/await syntax.
=> Fix jsdoc failure on async code

spec/unit/room.spec.js, src/client.js, src/models/event-timeline-set.js, src/models/room.js, src/sync.js
Re-use the same RoomState from the old live timeline so we re-use
all the same member objects etc, so all the listeners stay attached
=> Fix member events breaking on timeline reset, 2

spec/integ/matrix-client-retrying.spec.js
We need to wait for the js-sdk to have an opportunity to process the 400 from
the /send/ request before checking the event state
=> Retrying test: wait for localEchoUpdated event

src/models/room-member.js
This will at first be the `userId`, but when the members membership event is set, `rawDisplayName` will be assigned to the raw `displayname` of the membership event. This deliberately avoids disambiguation so that clients can disambiguate themselves (via a tooltip or otherwise).
=> Add rawDisplayName to RoomMember

package.json, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-event-emitter.spec.js, src/crypto/index.js, src/sync.js
We're going to need to handle m.room.crypto events asynchronously, so restructure the way we do that.
=> Refactor handling of crypto events for async

src/models/room-member.js
This mirrors the behaviour of `name` such that the default is always `userId` but if the membership event has a `displayname`, we use that.
(As reported and theorised by @krombel, thanks!)
=> Set `rawDisplayName` to `userId` if membership has `displayname=null`

spec/TestClient.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-event-emitter.spec.js, spec/integ/matrix-client-event-timeline.spec.js, spec/integ/matrix-client-syncing.spec.js, spec/test-utils.js, src/crypto/index.js
Add lots of calls to `syncPromise` to cope with the fact that sync responses
are now handled asynchronously, which makes them prone to races otherwise.
Also a quick sanity-check in crypto to make one of the test failures less
cryptic.
=> Make tests wait for syncs to happen

src/client.js, src/crypto/index.js
Reshuffle the logic for determining whether to encrypt a message so that it can
run independently of whether our app actually supports e2e - and then throw an
error if it looks like we should be encrypting but don't support it.
This seems a preferable situation to just falling back to plain text if we get
a dodgy build.
=> Avoid sending unencrypted messages in e2e room

spec/integ/matrix-client-crypto.spec.js, spec/integ/megolm-integ.spec.js, spec/test-utils.js, spec/unit/crypto/algorithms/megolm.spec.js, spec/unit/event.spec.js, src/crypto/algorithms/base.js, src/crypto/algorithms/megolm.js, src/crypto/algorithms/olm.js, src/crypto/index.js, src/models/event.js
... instead of having it call event.setClearData.
The main advantage of this is that it fixes a race condition, wherein apps
could see `event.isDecrypting()` to be true, but in fact the event had been
decrypted (and there was no `Event.decrypted` event on its way).
We're also fixing another race, wherein if the first attempt to decrypt failed,
a call to `attemptDecryption` would race against the first call and a second
attempt to decrypt would never happen.
It also gives a cleaner interface to MatrixEvent, at the expense of making the
`megolm` unit test a bit more hoop-jumpy.
=> Make crypto.decryptMessage return decryption results

spec/integ/matrix-client-crypto.spec.js, spec/integ/megolm-integ.spec.js, spec/test-utils.js, spec/unit/crypto/algorithms/megolm.spec.js, src/crypto/OlmDevice.js, src/crypto/algorithms/megolm.js, src/crypto/algorithms/olm.js, src/crypto/index.js, src/crypto/olmlib.js
A whole series of commits, each making a different method of OlmDevice asynchronous.
The tests in this code suffer from the races fixed in #523, so the tests are failing until that lands.
=> Make lots of OlmDevice asynchronous

src/interactive-auth.js
Now that we are using bluebird, `defer.reject` is not implicitly bound, so we
need to call it properly rather than just passing it into the catch handler.
This fixes an error:
promise.js:711 Uncaught TypeError: Cannot read property 'promise' of undefined
=> Fix error handling in interactive-auth

src/base-apis.js, src/client.js, src/models/group.js, src/store/indexeddb-local-backend.js, src/store/memory.js, src/store/stub.js, src/sync-accumulator.js, src/sync.js
* API wrappers for accepting invites and leaving rooms (reject invite == leave)
* Parse groups that come down in the sync stream and store them in the JS SDK
* Make the sync accumulator support groups
* Add new events for groups
* Methods to get groups out of the js-sdk store
=> Groups: Sync Stream, Accept Invite & Leave

src/client.js
We do create Events in more places, but this is probably the only
place that matters since the only event is 'decrypted' which won't
fire for, eg. events we send.
=> Re-emit events from, er, Event objects

src/client.js, src/models/event.js
Handle the case where received m.call.* events are not decrypted at the point
of the 'event' notification by adding an 'Event.decrypted' listener for them.
=> Handle m.call.* events which are decrypted asynchronously

src/sync.js
This stuff is much more clearly expressed as an async function than as a
promise chain, and I'm about to add more stuff to the chain, so let's refactor
now.
~~There is plenty more that could be done here (self -> this, for instance), but
I've gone for keeping the diff minimal.~~
I've done the self->this refactor in a separate commit.
=> Refactor sync._sync as an async function

spec/TestClient.js, spec/integ/devicelist-integ-spec.js, src/crypto/DeviceList.js, src/crypto/index.js, src/sync.js
When we no longer share any rooms with a given user, the server will stop sending us updates on their device list, and will (once synapse is updated) send us a notification of that fact via the 'left' field in the device_lists field in /sync, or the response from /keys/changes.
Fixes https://github.com/vector-im/riot-web/issues/4983
=> Handle 'left' users in the deviceList mananagement

src/client.js
The only event an Event emits is 'Event.decrypted', so don't
bother to add listeners if the event isn't encrypted.
=> Only re-emit events from Event objects if needed

src/client.js
Required for https://github.com/matrix-org/matrix-react-sdk/pull/1389
These are just convenience methods to hide developers from the underlying API.
=> Add ignore users API

src/client.js
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/334
=> consume trailing slash when creating Matrix Client in HS and IS urls

src/crypto/algorithms/megolm.js
This fixes a race wherein it was possible for us to fail to decrypt a message,
if the keys arrived immediately after our attempt to decrypt it. In that case,
a retry *should* have been scheduled, but was not.
Fixes https://github.com/vector-im/riot-web/issues/5001.
=> Fix a race in decrypting megolm messages

package.json
Otherwise you can make broken releases on case insensitive file
systems
=> Clean on prepublish

src/sync.js
Otherwise we emit events when we set properties on the group but
getGroup() for that group returns null which is very confusing.
=> Store group when it's created

src/pushprocessor.js
Unknown conditions previously were assumed to match, but given rules
can be added on the server as base rules, it's probably better to not
match unknown conditions.
=> Make unknown pushrule conditions not match

src/pushprocessor.js
It was only making one replacement so would fail for anything with
more than ine glob special char (eg. \*foo would be fine, but \*foo\*
was broken)
=> Fix the glob-to-regex code

src/pushprocessor.js, src/sync.js
Specifically, add support for the sender_notification_permission
push rule condition. Also delays calculating notification events
until after they're added to the timeline, as per comment.
NB. there is a bug that causes this to be wrong in some circumstances because the power level for the sentinel member is incorrect, but this is just a general bug in the js-sdk and doesn't need to be part of this PR.
=> Support room notifs

src/models/room-member.js, src/models/room-state.js
When a ppower_levels event arrived, the current member objects were
being updated but the sentinel members were not, meaning that the
power levels of RoomMember objects associated with events had stale
power levels. This was causing power level based push rules to
be wrong.
=> Fix power level of sentinel members

src/sync.js
We were previously computing notifEvents at the point where we
processed them but before the room they belong to was stored.
This was problematic because some push conditions try to get the
room and therefore failed. Since the push actions are cached, this
spurious calculation also got cached.
This moves the calculation out to a separate function that gets
called only after the room has been stored.
=> Fix notifEvent computation

spec/unit/crypto/algorithms/megolm.spec.js, src/crypto/OlmDevice.js, src/crypto/algorithms/megolm.js
This is to avoid false positives when detecting replay attacks.
fixes: vector-im/riot-web#3712
Signed-off-by: Hubert Chathi <hubert@uhoreg.ca>
@richvdh PTAL
=> keep track of event ID and timestamp of decrypted messages

src/base-apis.js
The API on synapse was modified to be an upsert, which means the same API call for adding a room to a group can be used to update the visibility of that association.
=> Modify addRoomToGroup to allow setting isPublic, create alias updateGroupRoomAssociation

package.json
This is a missing dependency. Everything that uses the js-sdk appears to break at runtime due to the lack of dependency. 
Riot appears to be okay because it installs the dependency on its own.
=> Install babel-runtime, as it is required for operation

src/base-apis.js
This is now a generic API on the homeserver. This is wrapped in a non-generic js-sdk function for now. In future, other group server implementations may want specific configuration and the configuration keys are namespaced to prevent collisions there.
See https://github.com/matrix-org/synapse/pull/2657 and https://github.com/matrix-org/synapse/pull/2651
=> Update API wrapper for group room association configuration

src/base-apis.js
To be able to send things like `{"m.visibility": { type: 'private ' }}`
Signed-off-by: Travis Ralston <travpc@gmail.com>
=> Support sending additional options with group acceptance

src/models/room-state.js
Just because they sent the event does not mean they'll be able to actually redact it.
=> Consider cases where the sender may not redact their own event

src/client.js, src/sync.js
see https://github.com/matrix-org/matrix-react-sdk/pull/1482
=> Support set_presence=offline for syncing

src/client.js, src/crypto/algorithms/megolm.js, src/crypto/index.js, src/models/room.js
Previously the global flag was used as a way to completely ignore the per-room option. This commit makes the per-room and global settings be more flexible to allow users to, for example, blacklist unverified devices in all room with the exception of one or two. This is done by making the global setting a device-level default and the per-room option allowing for 3 states: true, false, and unset (use device default).
Signed-off-by: Travis Ralston <travpc@gmail.com>
=> [BREAKING] Change the behaviour of the unverfied devices blacklist flag

src/client.js, src/webrtc/call.js
Option needed to be passed in when creating a webrtc call, but for
incoming calls the js-sdk creates the call itself, so the app never
gets a chance to set the option.
=> Fix the force TURN option

src/crypto/algorithms/base.js, src/models/event.js
We were relying on being able to override toString in DecryptionError, which
(a) doesn't work thanks to https://github.com/babel/babel/issues/3083, and (b)
was a bit naughty anyway. Instead, just add a detailedString property and use
that.
=> Fix logging of DecryptionErrors to be more useful

src/crypto/OlmDevice.js, src/crypto/index.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js, src/store/session/webstorage.js
Migrates the Olm account storage from the session store to the crypto store, backed by indexedDB. This allows us to lock access to it in a transaction, so multiple tabs can't overwrite each other's data.
Also adds a localstorage-backed crypto store to prevent people using Firefox in ones of its modes where IndexedDB support is broken from losing all their e2e data. It still uses the in-memory store for key requests as before, but saves the Olm account to localstorage. We may want to kick the app to warn the user that they're running in a degraded mode?
Olm accounts in the old session store are migrated into the crypto store seamlessly.
=> Move Olm account to IndexedDB

package.json, src/crypto/OlmDevice.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js
To allow multiple things to be fetched/stored in a single
transaction.
Currently it is still just the account that's actually in
indexeddb though.
=> Change crypto store transaction API

src/crypto/OlmDevice.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js, src/store/session/webstorage.js
Migrates the olm sessions to the crypto store. On startup, looks for any sessions still in the session store and moves them over to the crypto store.
Also moves the account migration into the same function to keep all the migration code together.
=> Move sessions to the crypto store

src/client.js, src/webrtc/call.js
This is mostly a lot of VoIP fixes to make the flow of trying to place or answer a call when there are unknown devices in the room. We don't want to stack up VoIP events in the pending events and then fire them all out later: we should just abort the call and place a new one once the user has reviewed the new devices.
Reviewing this commit-by-commit may make more sense: the commits are fairly well contained, functionality-wise, but all in the same commit because they'd otherwise leave things a bit broken.
=> Supporting fixes For making UnknownDeviceDialog not pop up automatically

src/client.js, src/crypto/OlmDevice.js, src/crypto/index.js
As we may want to warn the user to not go back to an older version.
Merge https://github.com/matrix-org/matrix-react-sdk/pull/1654 before this one otherwise nothing will be listening for the events (and they only happen once).
=> Emit an event for crypto store migration

src/models/room-member.js
If a display name contains an mxid it is quite likely that someone tries to pretend to be someone they are not. Better disambiguate in that case.
=> Disambiguate names if they contain an mxid

spec/unit/crypto/algorithms/megolm.spec.js, src/crypto/OlmDevice.js, src/crypto/algorithms/megolm.js, src/crypto/index.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js, src/store/session/webstorage.js
Same deal as usual, this time for inbound group sessions.
=> Migrate inbound sessions to cryptostore

src/client.js
So the event object properties are in a consistent state when we
the event is emitted.
Fixes first part of https://github.com/vector-im/riot-web/issues/5936
=> Set event error before emitting

spec/TestClient.js, spec/integ/devicelist-integ-spec.js, spec/integ/matrix-client-crypto.spec.js, spec/unit/crypto/DeviceList.spec.js, src/crypto/DeviceList.js, src/crypto/index.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js, src/store/session/webstorage.js, src/sync.js
Moves the device tracking to the crypto store.
Most of the cross-tab safety here works by writing all the device data atomically, so it's all stored in one big object, much as it feels like an abuse of indexeddb.
This also changes the API a little (in particular there's an explicit save to avoid multiple writes when we mark a room full of devices as known)
=> Move Device Tracking Data to Crypto Store

src/base-apis.js, src/client.js
use new getIdentityServerUrl param in inviteByThreePid
=> add parameter to getIdentityServerUrl to strip the protocol for invites

package.json, src/client.js, src/crypto/RoomList.js, src/crypto/index.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js, src/store/session/webstorage.js
Final cryptostore migration PR!
Based on https://github.com/matrix-org/matrix-js-sdk/pull/594 so probably want to get that merge before trying to review.
=> Migrate room encryption store to crypto store

src/models/room.js
Use their name as we did before rather than 'Empty Room'
Fixes https://github.com/vector-im/riot-web/issues/6083
=> Fix name of 1:1s other person has left

src/sync.js
Instead of blocking the first sync on getting the push rules and
filter, load sync data from disc.
When the client comes online, the push rules will be acquired and
a sync cycle started. This could be immediate if the client is
already online.
This could be a breaking change for clients that get push rules
before a successful sync has been done.
=> Allow a mode of operation without HS connection

src/sync.js
otherwise we risk doing a full sync by using the null token.
This must be done synchronously before we `getPushRules` and start
incrementally syncing.
=> Set sync token before incrementally syncing

src/sync.js
so that we have push rules loaded into the client after doing
a cached sync (so that the client can assume that we do have
push rules, even if it was loaded from a cached sync).
These rules will be updated once `getPushRules` is completed
prior to the first networked sync.
=> Honour cached push rules

src/models/room-state.js
We only need sentinel members for things like the 'sender' field
of events, so we previously created sentinels for everyone in the
room, but a large number of them were never used.
Instead, create them on-demand and cache them.
=> Create sentinel members on-demand

spec/integ/matrix-client-syncing.spec.js, src/sync.js
This should behave identically, but the code here appeared to be
identical to the code in initialiseState, so let's use it (it also
has an extra sanity check in there that we only init empty timelines).
Edit: I take back what I said about this being functionally identical: it isn't. It appears that previously we were applying any events in the `state` field of the join room to both the old state and the new state, which is surely wrong. Although these are normally only ever sent in a limited or initial sync (so it wouldn't matter) they are well-defined in other syncs as events that precede the timeline events, so we should process them as we would timeline events, before we process the timeline events. The tests send sync responses with state changes in `state` rather than `timeline`.
=> De-dup code: use the initialiseState function

spec/unit/room.spec.js, src/models/event-timeline.js
As comment hopefully explains.
On my test account:
Before: 394657 MatrixEvents, 53MB shallow size
After: 198863 MatrixEvents, 27MB shallow size
=> Stop cloning events when adding to state

src/models/event.js
My test account had 37MB (shallow) of Date objects knocking around
in memory. This gets rid of them. I can't see any appreciable
difference in the time taken to switch rooms (where now we recreate
a bunch of Dates that previously would have been cached).
=> Make Events create Dates on demand

src/models/room.js
Fixes https://github.com/vector-im/riot-web/issues/3511
Signed-off-by: Michael Telatynski 7t3chguy@gmail.com
=> Don't synthesize RR for m.room.redaction as causes the RR to go missing.

src/models/event.js
There is a legacy top-level 'membership' field on events. We were
interning the normal one in 'content', but not this one, so the
legacy field was still keeping a copy of the string 'join' / 'leave'
etc in memory for every member event.
This make the interning code know about this field.
=> Intern legacy top-level 'membership' field

src/client.js, src/crypto/algorithms/megolm.js
- Emit `crypto.initComplete` for apps that need to execute code that requires crypto to have initialised
- Fix overriding `undefined` per-room unverified devices setting
Codep https://github.com/matrix-org/matrix-react-sdk/pull/1772
=> Fix bug where global "Never send to unverified..." is ignored

src/sync.js
State events get froze now, so we can't write to the push actions
cache after having done so: precompute the push actions to work
around this.
=> Precompute push actions for state events

spec/unit/pushprocessor.spec.js, src/models/room-state.js, src/pushprocessor.js
Pushrule evaluation needs the count of joined room members and
filtering the list for joined members takes a nontrivial amount
of time, but caching it is trivial, both code and memory wise.
=> Cache the joined member count for a room state

src/crypto/DeviceList.js
This was marking the device list as dirty even when nothing had
actually changed, causing unnecessary saves.
=> Don't mark devicelist dirty unnecessarily

spec/unit/matrix-client.spec.js, src/crypto/DeviceList.js, src/crypto/index.js, src/store/indexeddb.js, src/store/memory.js, src/store/stub.js, src/sync.js
Remove the call to /keys/changes when we do an incremental syn
where the old sync token doesn't match the one in the device list
store. To allow us to do this, always save the device list store
before saving the sync data, so we can safely assume the device
list store is at least as fresh as the sync token in the sync store.
Thread save functions through to allow this, add a delay parameter
so the sync can save the device list immediately and skip the wait,
and add a wantsSave() method so the sync can skip saving the device
list if the sync store isn't going to save anyway.
Fixes https://github.com/vector-im/riot-web/issues/6068
=> Don't do /keys/changes on incremental sync

src/store/indexeddb-local-backend.js
1. Fix double 'loaded' on sync data logging
2. Move the 'loaded' message into the bit where the data has
actually loaded rather than the promise try block.
3. Add '...' to the 'loading' messages so they're easier to tell
apart from the 'loaded' messages.
=> Fix indexeddb logging

src/store/indexeddb-remote-backend.js
Rather than when creating it, otherwise we could potentially end
up starting workers unnecessarily.
=> Create indexeddb worker when starting the store

spec/integ/matrix-client-syncing.spec.js, src/sync.js
When joining a room we were peeking into, we duplicated all the
state events into the timeline. Put back the old behaviour of just
setting them as state events, with copious commentary on how wrong
this seems.
=> Fix duplicated state events in timeline from peek

src/client.js
@ara4n - Can you just confirm that you're happy with switching the m.room.sticker type to plain m.sticker (as discussed).
=> Switch event type to m.sticker.

src/base-apis.js
which is exposed in the summary API under `summary.profile.is_joinable`.
If true, anyone can join the group. If false, an invite is required.
=> Add wrapped to set group `is_joinable`

src/crypto/store/indexeddb-crypto-store-backend.js
Rather than aborting the whole txn
This is causing e2e migration fails in the wild
=> Ignore inserts of duplicate inbound group sessions

src/crypto/store/indexeddb-crypto-store-backend.js
Stop the error from propagating to the txn error handler and
aborting the rest of the transaction.
=> Ignore inserts of dup inbound group sessions, pt 2

src/base-apis.js
For erasing messages etc. after deactivation.
=> Add `erase` option to deactivateAccount

src/models/room-state.js, src/utils.js
so if you set `@room` notif=0, then js-sdk would think its actually 50 :(
=> check whether notif level is undefined, because `0` is falsey 

src/http-api.js
higher up this method copies `opts.headers` into `headers` and if `json && data` then sets the content-type to `application/json`
Whilst writing matrix-search I was left with js-sdk reaching out to the express server with some json payload but plain text content type
=> fix typo where `headers` was not being used and thus sent wrong content-type

src/matrix.js, src/webrtc/call.js
As with setting audio/video inputs, does not affect in-progress calls.
=> allow setting the output device for webrtc calls

src/base-apis.js, src/http-api.js
+ fix one instance where useAuthorizationHeader was ignored
+ fix filename=undefined on e2ee uploads because `name || file.name` = undefined
=> fix auth header and filename=undefined

src/crypto/algorithms/base.js, src/crypto/algorithms/megolm.js, src/crypto/algorithms/olm.js, src/crypto/index.js, src/models/event.js
These should roughly follow https://github.com/matrix-org/matrix-ios-sdk/blob/9732cf593206a10d2b60cd01151a759c88c1e9a2/MatrixSDK/Crypto/Algorithms/MXDecryptionResult.h#L21-L39
=> Add decryption error codes to base.DecryptionError

src/models/room-member.js, src/models/room-state.js, src/utils.js
+ fixes disambiguation occurring if someone's is set to `undefined` because javascript type coercion.
+ strips zero width chars and whitespace from displayName when doing disambiguation logic
+ if someone's displayname is just spaces/zero width chars show just their MXID instead.
=> displayname disambiguation fixes

src/crypto/algorithms/megolm.js, src/crypto/algorithms/olm.js, src/crypto/index.js, src/models/room.js
fixes https://github.com/vector-im/riot-web/issues/2713
=> encrypt for invited users if history visibility allows.

spec/unit/room-member.spec.js, spec/unit/room-state.spec.js, spec/unit/room.spec.js, src/base-apis.js, src/client.js, src/models/event-timeline-set.js, src/models/event-timeline.js, src/models/room-member.js, src/models/room-state.js, src/models/room.js, src/sync.js
Lazy loading of members, for now using the /joined_members endpoint until we have something better.
Parent issue: https://github.com/vector-im/riot-web/issues/6611
=> Lazy load room members - Part I

spec/unit/room-state.spec.js, src/models/room-state.js
Fixes https://github.com/vector-im/riot-web/issues/6679
The way the spinner is supposed to disappear when clicking join in the room preview bar is a bit convoluted, but as far as I could figure out it works like this:
1. `RoomView` listens for `"RoomMember.membership`
1. when this fires, it checks if its for the logged in user, if so, forces a rerender
1.  in render, we will lookup and check the membership of the logged in user, to determine if the aux panel with the spinner (if !join) and the composer should be shown (if join). Even if `state.joining` remains `true`, which it is in this case.
What went wrong is that the lookup in `render` failed because the event was emitted before the new member was added to `RoomState::members`, and not seeing the membership is now `join`. This PR …
=> Fix infinite spinner upon joining a room

src/models/room.js
See https://github.com/vector-im/riot-web/issues/7025
=> make sure room.tags is always a valid object to avoid crashes

src/client.js, src/models/room-state.js, src/store/indexeddb-local-backend.js, src/store/indexeddb-remote-backend.js, src/store/indexeddb-store-worker.js, src/store/indexeddb.js, src/store/memory.js, src/store/stub.js
This PR adds storing the lazy loaded members in indexeddb, so we don't have to call /members in every browser session (per browser session the members are already kept in memory once you've looked at the room).
It also stores a marker object in the same IDB store to know whether lazy loading was already done for a room even though it didn't yield any members to store (like in a DM where both members where active in the last 10 messages).
=> Lazy loading: store lazily loaded members in indexeddb

src/client.js
Fixup for https://github.com/matrix-org/matrix-js-sdk/commit/fe772ed84d46c91cdfa22ded8faa5fbf54cd7ec4
=> Fix: Lazy loading: missed call site while renaming prependStateEvents

spec/unit/room.spec.js, src/client.js, src/crypto/algorithms/megolm.js, src/crypto/algorithms/olm.js, src/crypto/index.js, src/models/room.js, src/sync.js, src/utils.js
=> Lazy loading: fix end-to-end encryption rooms

src/models/room.js
To get the version number of the room as per https://github.com/matrix-org/matrix-doc/issues/1425
=> Add getVersion to Room

src/models/room.js
On Room, because it's super confusing that Room has
getJoinedMembers() but not getJoinedMemberCount()
https://github.com/matrix-org/matrix-react-sdk/pull/2126 had assumed
that this method was on Room
=> Add wrapper around getJoinedMemberCount()

spec/unit/room.spec.js, src/crypto/RoomList.js, src/crypto/index.js, src/models/room.js, src/sync.js
setting up room crypto will load members in case of LL and could take quite some time
The two async actions performed by onCryptoEvent is saving the crypto config
to the roomlist store and fetching the room members to track.
Both are guarded against double calls so not awaiting this should be fine.
=> Lazy loading: don't block on setting up room crypto

spec/unit/room.spec.js, src/crypto/RoomList.js, src/crypto/index.js, src/models/room.js, src/sync.js
Reverts matrix-org/matrix-js-sdk#696
This isn't ready for prime-time yet, DeviceList tests are still failing and need to make sure all devices are always fetched before sending. Sorry for not making this clearer on the PR.
=> Revert "Lazy loading: don't block on setting up room crypto"

src/models/room.js
https://github.com/matrix-org/riot-web-rageshakes/issues/962
was hitting `Unhandled rejection TypeError: otherMember.getAvatarUrl is not a function` because in case of summary heroes it is returning a userid and not a member.
Also adds another fallback route for getting the avatar by looking up the user.
=> Fix for "otherMember.getAvatarUrl is not a function"

src/models/room.js
Fixes https://github.com/vector-im/riot-web/issues/7243
=> Fix: also load invited members when lazy loading members

CHANGELOG.md, spec/unit/matrix-client.spec.js, src/client.js, src/sync.js
Pass through PREPARED state after error, when keepalive returns succes.
This is according to the state diagram in client.js.
This will show a spinner at the bottom of a room again
while the catchup sync is in progress,
which seems to have broken at some point.
Addresses item 6 (We no longer show a spinner when recovering after losing connectivity) of https://github.com/vector-im/riot-web/issues/7182
=> Fix: show spinner again while recovering from connection error

src/client.js
Fixes https://github.com/vector-im/riot-web/issues/7262
=> Fix filepanel also filtering main timeline with LL turned on.

CHANGELOG.md, spec/unit/room-state.spec.js, spec/unit/room.spec.js, src/models/room-state.js, src/models/room.js
Required by https://github.com/matrix-org/matrix-react-sdk/pull/2145
=> Don't rely on members to query if syncing user can post to room

CHANGELOG.md, spec/unit/room-state.spec.js, spec/unit/room.spec.js, src/models/room-state.js, src/models/room.js
Reverts matrix-org/matrix-js-sdk#717
as it seems to be causing the tests to fail
=> Revert "Don't rely on members to query if syncing user can post to room"

CHANGELOG.md, spec/unit/room-state.spec.js, spec/unit/room.spec.js, src/models/room-state.js, src/models/room.js
Reverts matrix-org/matrix-js-sdk#721
Requires https://github.com/matrix-org/matrix-react-sdk/pull/2151 since that fixes the test that broke
=> Re-apply "Don't rely on members to query if syncing user can post to room"

src/client.js
=> Fix docstring for sync data.error

src/sync.js
Have the keepalive promise return a boolean indicating whether it
detected a connectivity failure or not. Use this to only emit
CATCHUP if there was a connectivity error, to try & suppress
the state flip-flopping back & forth between CATCHUP and ERROR
in the case where we have connectivity but the sync is returning
and error for whatever reason.
=> Only emit CATCHUP if recovering from conn error

src/models/room-state.js
Example of correct order: https://github.com/matrix-org/matrix-js-sdk/blob/9e02049b0551c1e9b068a03b1a91289285dc0e75/src/models/room-state.js#L356
=> RoomState.members emitted with wrong argument order for OOB members

src/store/indexeddb-local-backend.js
Instead of creating a promise for every member inserted, just create on for the transaction. This saves about 100ms for ~7500 members.
=> Reduce amount of promises created when inserting members

spec/unit/room.spec.js, src/models/room.js, src/sync.js
As you don't always have your own member with lazy loading
of members enabled, looking at the sync response section
where a room appears is the most reliable way of determining
the syncing user's membership in a room.
Before we already used this to read the
current room membership with `room.getMyMembership()`,
but we were still using the `RoomMember.membership` event
to detect when the syncing user's membership changed.
This event will help make those checks work well with LL enabled.
=> Introduce Room.myMembership event

src/client.js
Part of https://github.com/matrix-org/matrix-doc/pull/1189 and https://github.com/matrix-org/synapse/pull/3184
=> Add getMediaLimits to client

src/client.js
Fixes https://github.com/vector-im/riot-web/issues/7405
=> disable lazy loading for guests as they cant create filters

src/models/room.js
Fixes https://github.com/vector-im/riot-web/issues/7331
There is something to be worried about when there is no room create event, however. This should always be available, although due to cache problems or servers that don't provide the event we can't be sure of this.
=> Default to a room version of 1 when there is no room create event

src/store/indexeddb-remote-backend.js, src/store/indexeddb-store-worker.js
Gives more information in the logs, and will make it easier to handle idb errors on the main thread in the future.
=> throw error with same name and message over idb worker boundary

src/crypto/store/indexeddb-crypto-store.js
We were sucessfully opening indexeddb but any queries using compound
indicies were failing because Edge doesn't support them, so messages
were failing to decrypt with 'DataError'.
Try a dummy query at startup, so if it fails we fall back to a
different store (ie. end up using localstorage on Edge).
=> Make e2e work on Edge

package.json, spec/TestClient.js, spec/integ/devicelist-integ-spec.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-event-emitter.spec.js, spec/integ/matrix-client-event-timeline.spec.js, spec/integ/matrix-client-methods.spec.js, spec/integ/matrix-client-opts.spec.js, spec/integ/matrix-client-retrying.spec.js, spec/integ/matrix-client-room-timeline.spec.js, spec/integ/matrix-client-syncing.spec.js, spec/integ/megolm-integ.spec.js
To finish all pending flushes between tests. This stops the unit
tests from hanging on node 11 when run in certain combinations.
Requires https://github.com/matrix-org/matrix-mock-request/pull/6
(so will need a release of matrix-mock-request before merging)
For the record, one such combination was:
```
npx mocha specbuild/integ/devicelist-integ-spec.js specbuild/integ/matrix-client-methods.spec.js specbuild/integ/matrix-client-room-timeline.spec.js
```
This would complete all the tests but hang spinning a CPU core instead of exiting. Adding `--exit` (so mocha called process.exit once the tests were all done) made it exit. Adding `specbuild/integ/megolm-integ.spec.js` would cause it to hang before completing the tests.
=> Use new stop() method on matrix-mock-request

spec/unit/crypto/DeviceList.spec.js, src/crypto/DeviceList.js, src/crypto/index.js
To avoid the devicelist trying to save after the client has been
stopped
Hopefully will fix random test failures on node 11.
=> Stop devicelist when client is stopped

package.json
Required for https://github.com/vector-im/riot-web/pull/7490
=> Update babel-eslint to 8.1.1

browser-index.js, package.json, src/http-api.js
Because `request` just doesn't work for us in the browser, but `browser-request` is fine despite us having to do our own query strings.
Fixes https://github.com/vector-im/riot-web/issues/7620
=> Manually construct query strings for browser-request instances

package.json
Paired with (**please review all 3**):
* https://github.com/vector-im/riot-web/pull/7637
* https://github.com/matrix-org/matrix-react-sdk/pull/2263
----
This was introduced in https://github.com/matrix-org/matrix-react-sdk/pull/2250 but can be pulled out due to https://github.com/matrix-org/matrix-js-sdk/pull/770. See https://github.com/vector-im/riot-web/issues/7634 for more information about the future.
=> Remove the request-only stuff we don't need anymore

.travis.yml, src/crypto/OlmDevice.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js
Implements https://github.com/matrix-org/matrix-doc/pull/1596
For https://github.com/vector-im/riot-web/issues/3822
Requires https://github.com/matrix-org/olm-backup/pull/77 (+release)
=> Use the last olm session that got a message

.travis.yml, spec/unit/crypto.spec.js, spec/unit/crypto/algorithms/megolm.spec.js, src/crypto/OlmDevice.js, src/crypto/OutgoingRoomKeyRequestManager.js, src/crypto/algorithms/megolm.js, src/crypto/index.js, src/crypto/olmlib.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js
* Start a new Olm sessions with a device when we get an undecryptable
message on it.
* Send a dummy message on that sessions such that the other end knows
about it.
* Re-send any outstanding keyshare requests for that device.
Also includes a unit test for megolm that isn't very related but came
out as a result anyway.
Includes #776
Fixes vector-im/riot-web#3822
=> Restart broken Olm sessions

src/base-apis.js
This is in support of [MSC1721](https://github.com/matrix-org/matrix-doc/pull/1721).
=> Add 'getSsoLoginUrl' function

src/crypto/index.js
=> Don't re-establish sessions with unknown devices

src/pushprocessor.js, src/utils.js
So they can be used by other things.
=> Move glob regex utilities out of the pushprocessor and into a more generic place

spec/unit/crypto.spec.js, spec/unit/crypto/algorithms/megolm.spec.js, spec/unit/crypto/algorithms/olm.spec.js, spec/unit/crypto/backup.spec.js
Standardize on importing `olm-loader` rather than pasting the same boilerplate
in different tests.  Importantly, `spec/unit/crypto.spec.js` did not include any
loading approach, so it would only find Olm if some other test loaded it first.
Signed-off-by: J. Ryan Stinnett <jryans@gmail.com>
=> Use `olm-loader` in all crypto tests

src/client.js, src/models/room-state.js, src/models/user.js, src/sync.js
Part of https://github.com/vector-im/riot-web/issues/1528
Status messages are short strings of text that users can set to be visible to other users. The js-sdk bits here are for setting and reading the status message for a given user.
Status messages are completely unrelated to the presence status message in that they do not expire and have a different intent. Presence status messages are intended to be read as "Online reading documentation" whereas status messages would be just "Reading documentation" (no associative presence). 
This currently uses a state event in direct chats to represent the status. It is intended that in the future there will be extensible profiles which can better communicate this information. Because this is a feature we're trying out, the event type is …
=> Support custom status messages

src/base-apis.js
I investigated options to build a new bridge for XMPP and found that this API method would be very useful for it. My assumption is that it could be used to enhance the invite dialog in a way so that it also understands protocols and external IDs, similar to the way how the room directory currently works.
Signed-off-by: Johannes Bornhold <johannes@bornhold.name>
=> Add getThirdpartyUser to base api

package-lock.json, package.json
This avoids API changes in 3.0.5 (requiring `Buffer` instances), but more
importantly also avoids dealing with ES6 in dependencies for another day.
Signed-off-by: J. Ryan Stinnett <jryans@gmail.com>
=> Pin to base-x 3.0.4

package-lock.json, package.json, src/utils.js
to prevent homoglyph attacks
for riot-web requires https://github.com/vector-im/riot-web/pull/7093
Fixes https://github.com/vector-im/riot-web/issues/5826
=> take into account homoglyphs when calculating similar display names

src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js
So we can migrate them from place to place
=> Add a getAllEndToEndSessions to crypto store

src/crypto/index.js
This ensures we will report the updated status when consumer code asks for it.
Fixes part of https://github.com/vector-im/riot-web/issues/8048.
=> Re-check key backup status on version mismatch

src/client.js, src/crypto/index.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js
Alters the APIs used for initial key backup so that the actual upload happens in
the background after all session are marked for backup.
In addition, this also emits a counts of sessions remaining to backup to drive an upload progress UI.
Needed for https://github.com/vector-im/riot-web/issues/7863.
Used in https://github.com/matrix-org/matrix-react-sdk/pull/2416.
=> Change initial key backup to background

src/client.js, src/models/user.js
* Emits an event on `User` when custom status changes
* Ensure we have power to set status in a room
Needed for https://github.com/vector-im/riot-web/issues/8064.
Used in https://github.com/matrix-org/matrix-react-sdk/pull/2442.
=> Custom Status: Fix UX snag list

src/crypto/index.js
Not sure how this was missed, but anyway, guard against duplicate uploads with
the existing flag.
=> Set key backup guard flag to avoid duplicate uploads

src/models/room.js
We'll still need something like https://github.com/matrix-org/matrix-doc/pull/1804 to make this work correctly, but this fixes the immediate issue in https://github.com/vector-im/riot-web/issues/8154
=> Flag v2 rooms as "safe"

.eslintrc.js, package-lock.json, package.json
* Put back babel-eslint for class-properties
* Allow arrow functions without params
This makes the style more consistent with react-sdk.
NB. The line lengths are still inconsistent but it's not clear which
way to go on that yet.
=> Make linting rules more consistent

spec/TestClient.js, spec/integ/devicelist-integ-spec.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/megolm-integ.spec.js, src/crypto/index.js
It's generally a reasonable assumption that we'll be interested in
them, and important for key backup.
This requires adding the expected /keys/query to just about every place in the crypto integration tests. :( I would add it somewhere common like starting the test client but in theory the request could be aggregated with requesting keys for another user.
Fixes https://github.com/vector-im/riot-web/issues/8213
=> Always track our own devices

release.sh
Commit the package-lock.json when bumping the version, otherwise
the versions get out of sync, and this is going to matter more now
that jenkins runs `npm ci` which is fussy about these things.
=> Release script: commit package-lock.json

src/crypto/algorithms/megolm.js
Someone with a bit of knowledge around the state machine for encryption probably wants to review this.
=> Fix "e is undefined" masking the original error in MegolmDecryption

src/matrix.js, src/webrtc/call.js
We were using 'exact' which means we fail outright if the device
we wanted isn't available. This means if a user selects a specific
device then later unplugs it, we fail to open a capture device
the next time they make a call even if there's one available.
Using 'ideal' uses the chosen device in preference, but something
else if it isn't available.
Also log the name of the exception when we fail to open a capture
device to give us more of an idea of what's gone wrong.
Should help fix vector-im/riot-web#8993
=> Use 'ideal' rather than 'exact' for deviceid

spec/unit/crypto.spec.js, src/client.js, src/crypto/OutgoingRoomKeyRequestManager.js, src/crypto/algorithms/megolm.js, src/crypto/index.js, src/models/event.js
Make sure that key requests get sent when they're requested, even if there was no key request before.
fixes https://github.com/vector-im/riot-web/issues/6838 (hopefully)
=> make sure key requests get sent

src/client.js, src/models/event.js, src/models/room.js, src/pushprocessor.js
Fixes https://github.com/vector-im/riot-web/issues/7489
~~**Required by https://github.com/matrix-org/matrix-react-sdk/pull/2744**~~ Not needed.
~~I'm not entirely convinced that the changes here are the right place to shove this code, but it does work well enough to at least open a PR.~~ I've since shuffled things around.
My GIF recorder is broken, so here's a deconstructed 2 frame GIF:
=> Calculate encrypted notification counts

spec/unit/crypto/algorithms/olm.spec.js, src/crypto/OlmDevice.js, src/crypto/olmlib.js
fixes #671, fixes vector-im/riot-web#8795
=> only create one session at a time per device

README.md, spec/integ/matrix-client-methods.spec.js, spec/integ/matrix-client-opts.spec.js, src/matrix.js, src/store/indexeddb.js, src/store/memory.js
None of the other store classes use the `Matrix` prefix, and I find the mismatch
confusing (it leads me to think it might have a different purpose than the
others).
This change removes the prefix from the store for consistency. The old name is
left as an export for existing SDK consumers.
=> Rename `MatrixInMemoryStore` to `MemoryStore`

spec/unit/crypto/DeviceList.spec.js, spec/unit/crypto/algorithms/megolm.spec.js, spec/unit/crypto/algorithms/olm.spec.js, spec/unit/crypto/backup.spec.js, src/client.js, src/crypto/DeviceList.js, src/crypto/OlmDevice.js, src/crypto/RoomList.js, src/crypto/index.js
The code to migrate from the `sessionStore` to `cryptoStore` originally appeared in #584 (2017-12-06). At this point, it seems safe to assume most sessions that need migrating have already
done so. Removing this code simplifies store handling and removes the `sessionStore` from most places in JS SDK.
=> Remove `sessionStore` to `cryptoStore` migration path

CONTRIBUTING.rst
This applies the clarification already adopted by Synapse in https://github.com/matrix-org/synapse/pull/3467.
(I also reformatted the doc slightly in a separate commit.)
=> Clarify the meaning of 'real name' for contribution

src/sync.js
For https://github.com/vector-im/riot-web/issues/9260
**Please review with https://github.com/matrix-org/matrix-react-sdk/pull/2820**
=> Emit sync errors for capturing by clients

src/models/event-timeline-set.js
Credit to Matthew for basically solving this.
Theoretically fixes spontaneous timeline corruption: https://github.com/vector-im/riot-web/issues/8593
When the live timeline ends up in a position where it can no longer be live (such as becoming the second timeline in the set, rather than the first) we end up getting neighbouring timeline errors. By refusing to splice the live timeline into such a position, we hopefully keep the live timeline in a position of still being live for when it is next used.
The running theory that leads to this fix is multiple limited syncs coming in, causing holes in the timeline. When trying to patch up the holes, the timeline set would end up splicing all over the place, leading to potentially splicing the live timeline into a broken position.
Disclaimer: I've …
=> Refuse splicing the live timeline into a broken position

src/crypto/store/indexeddb-crypto-store-backend.js
According to https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction/abort_event
a txn can abort for any number of reasons, not just because of an
abort call, so we can't assume our abort error is set.
This should give us more info on https://github.com/vector-im/riot-web/issues/7769
=> Don't assume aborts are always from txn.abort()

src/models/event-timeline-set.js
See https://github.com/vector-im/riot-web/issues/8593#issuecomment-478681816
Previously (https://github.com/matrix-org/matrix-js-sdk/pull/873) we allowed half-linking timelines to each other if they satisfy the conditions, however this appears to not be helping. Instead, it seems like the timelines are getting stuck in a position where one direction is spliced but the other is broken. To avoid this case, we'll just avoid splicing in both directions when one of the directions is invalid.
=> Refuse to link live timelines into the forwards/backwards position when either is invalid

spec/unit/room.spec.js, src/models/room.js, src/store/indexeddb.js, src/store/memory.js
IndexedDB may fail at any moment with `QuoteExceededError` when space is low or
other random issues we can't control. Since `IndexedDBStore` is just a cache for
improving performance, we can give up on it if it fails.
This causes `IndexedDBStore` to degrade in place back to using memory only. This
allow (for example) login to complete even if IndexedDB is exploding.
Hopefully improves https://github.com/vector-im/riot-web/issues/7769
=> Degrade `IndexedDBStore` back to memory only on failure

package.json, spec/unit/crypto/verification/sas.spec.js, src/crypto/verification/SAS.js, yarn.lock
Note: setting the diff view to ignore whitespace changes will make the unit test diff easier to read
The new name of the MAC method is not yet finalised.
=> support both the incorrect and correct MAC methods

src/client.js, src/sync.js
Fixes https://github.com/vector-im/riot-web/issues/9280
The server is unable to calculate encrypted highlights for us, so we calculate them. This also means the server always sends a zero for highlight_count, and therefore in sync.js we now trust our judgement over the server's. In future, this check will need to be altered to support server-side encrypted notifications if that happens. This fixes the part of 9280 where the badge count ends up disappearing unless the message received also happens to be a mention.
The changes in client.js are more to support rooms which are mentions only. Because the server doesn't send an unread_count for these rooms, the total notifications will always be zero. Therefore, we try and calculate that. In order to do that, we need to assume that our …
=> Track e2e highlights better, particularly in 'Mentions Only' rooms

src/models/room.js
It's unclear what `hasUnverifiedDevices` should do when crypto is disabled on
the current device. Let's at least document that callers should first check
crypto status.
=> Document checking crypto state before using `hasUnverifiedDevices`

src/sync.js
A logic error introduced by https://github.com/matrix-org/matrix-js-sdk/pull/886 meant that all unencrypted rooms were not getting highlight notifications.
=> Fix highlight notifications for unencrypted rooms

src/sync.js
This adds explicit `try` blocks in the spots where we interact with the store
during sync startup. This shouldn't be necessary as the store should already be
catching this and degrading as of
https://github.com/matrix-org/matrix-js-sdk/pull/884, but that doesn't seem to
have been enough for the affected user in
https://github.com/vector-im/riot-web/issues/7769, as they are seeing sync just
stop when storing without any further detail.
=> Explicitly guard store usage during sync startup

src/sync.js
Fixes https://github.com/vector-im/riot-web/issues/9451
=> Stop syncing when the token is invalid

src/sync.js
otherwise the room state isn't updated yet (and we can't for
example distinguish a leave from a kick)
this is only used for updating the UI,
seems safe to emit this event at a later point
=> emit self-membership event at end of handling sync update

spec/unit/autodiscovery.spec.js, src/autodiscovery.js
Used by Riot to consume the user's provided config. This also includes a change to carry over custom keys on m.homeserver and m.identity_server which aren't intentionally controlled.
Required for https://github.com/vector-im/riot-web/issues/9290
=> Support being fed a .well-known config object for validation

src/pushprocessor.js
Part of vector-im/riot-web#8447
See also matrix-org/matrix-doc#1930
**Intended for https://github.com/matrix-org/matrix-react-sdk/pull/2798**
=> Add a concept of default push rules, using it for tombstone notifications

src/client.js, src/models/event-timeline-set.js, src/models/event.js, src/models/relations.js, src/models/room.js, src/sync.js
This adds a read path for relations (gated behind an unstable option). A few
basic client-side grouping and sorting operations are supported. Consumers are
expected to ask the `EventTimelineSet` for a relation container when desired.
See [MSC 1849](https://github.com/matrix-org/matrix-doc/blob/matthew/msc1849/proposals/1849-aggregations.md) to learn more about these events.
Part of https://github.com/vector-im/riot-web/issues/9485
=> Add basic read path for relations

src/autodiscovery.js
Applies to verification of the homeserver, identity server, and fetching of the .well-known objects. Does not affect other HTTP requests.
See https://github.com/vector-im/riot-web/issues/9290
=> Use a short timeout for .well-known requests

src/client.js, src/models/event-timeline-set.js, src/models/event-timeline.js, src/models/event.js, src/models/room.js, src/sync.js
Initial support for m.replace relationships. Doesn't do local echo yet, and only works if the original event is received before the replacements (e.g. like through sync). Follow-up PRs to follow.
https://github.com/vector-im/riot-web/issues/9671
Accompanying react-sdk PR: https://github.com/matrix-org/matrix-react-sdk/pull/2952
=> Support for replacing message through m.replace relationship.

src/models/event-timeline-set.js, src/models/event-timeline.js, src/models/event.js, src/models/room.js
this is more in line with what happens on the server-side,
and also doesn't break existing reply relations,
and is a simpler approach as well.
=> Message editing: mark original event as replaced instead of replacing the event object

src/client.js, src/models/event-timeline-set.js, src/models/event.js, src/models/relations.js, src/models/room.js
This adds new local relations to the pending event list, just like we do for messages. However, we still aggregate them into relation collections immediately for local echo. If they are later cancelled, the collection is updated to remove them.
Part of https://github.com/vector-im/riot-web/issues/9731
Required for https://github.com/matrix-org/matrix-react-sdk/pull/2981
=> Track relations as pending and remove when cancelled

src/client.js, src/models/event-timeline-set.js, src/models/event.js, src/models/relations.js, src/models/room.js, src/sync.js
Part of: https://github.com/vector-im/riot-web/issues/9671
React-SDK PR: https://github.com/matrix-org/matrix-react-sdk/pull/2982
=> Local echo for m.replace relations

src/content-repo.js
Issue described in: https://github.com/vector-im/riot-web/issues/9690
matrix-react-sdk was patched separately, so that it won't call `mxcUrlToHttp()`
(and in turn `getHttpUriForMxc()`) with non-integer sizes.
This patch fixes the JS SDK as well, hoping to prevent the same issue
from happening on other clients (besides matrix-react-sdk / riot-web).
Signed-off-by: Slavi Pantaleev <slavi@devture.com>
=> Do not try to request thumbnails with non-integer sizes

spec/unit/login.spec.js, src/base-apis.js
Signed-off-by: Sergii Stotskyi <sergiy.stotskiy@gmail.com>
Fixes #876
=> fix(login): saves access_token and user_id after login for all login types

package.json, src/crypto/recoverykey.js, yarn.lock
**Reviewer**: This is heading to release-v2.0.0 branch for immediate release.
This fixes our recovery key encoding to work with base-x 3.0.5, which requires the
encoding input to be in a `Buffer`. (base-x is a dependency of bs58.)
Unfortunately, base-x hasn't marked this as breaking change through a major
version increment, so semantic versioning can't help us here to ensure we get
particular version.
I have verified that the change to `Buffer` works with both old and new base-x,
so we should be okay no matter what version is actually selected.
For extra fun, base-x 3.0.5 also uses newer JS features, which `uglify-js`
doesn't support. I have migrated to `terser` instead, which is what we're using
for Riot these days (via Webpack).
Fixes https://github.com/vector-im/riot-web/issues/9901
=> Fix recovery key encoding for base-x 3.0.5

.eslintrc.js
The Google code style config for ESLint turns on `guard-for-in` to require
for-in loops to check own properties. This makes it annoying to iterate objects,
and we seem to disable the rule by line comments when it comes up anyway, so
this just disables it globally.
=> Disable guard-for-in rule

src/models/room.js
It's listed as stable in the spec, and this is for our fallback.
=> Add v4 as a safe room version

src/client.js, src/models/room.js
Fixes https://github.com/vector-im/riot-web/issues/9845
=> Refresh safe room versions when the server looks more modern than us

src/crypto/verification/Base.js
#939 adds a use of `logger`, but `logger` wasn't imported into that file.  This PR fixes that.
=> add missing logger

src/client.js
=> Encode event IDs when redacting events

src/interactive-auth.js
Otherwise we end up with more tokens than are strictly necessary
=> Don't send another token request while one's in flight

src/crypto/index.js
verifySignature modifies the object so we need to clone if we're
verifying more than one signature.
Fixes https://github.com/vector-im/riot-web/issues/9357
=> Fix backup sig validation with multiple sigs

src/interactive-auth.js
Wait for polls to complete before submitting auth dicts, otherwise
we risk the requests overlapping and both returning a 200.
Also introduces a setBusy interface to interactive-auth to explicitly
set the busy status, since otherwise it doesn't get set until the
request actually starts.
Requires https://github.com/matrix-org/matrix-react-sdk/pull/3085
=> Don't overlap auth submissions with polls

src/http-api.js
Modern browsers now expose a `stream` function on the Blob and File interfaces.
This conflicts with an older style of passing data to the `uploadContent` SDK
method, which supported supplying the data to upload in the `stream` property of
an object.
Since this old style is still in active use in the Matrix JS ecosystem, we
preserve the backwards compatibility for now by checking whether `stream` is a
function.
This fix has been tested in Firefox Nightly (69), Firefox Release (67), Chrome
Canary (77), and Chrome Stable (75).
Fixes https://github.com/vector-im/riot-web/issues/9913
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/949
=> Fix content uploads for modern browsers

spec/unit/scheduler.spec.js, src/client.js, src/models/event-timeline-set.js, src/models/event.js, src/models/relations.js, src/models/room.js, src/scheduler.js
PR does several things to make this work:
- fix scheduler assigning queue for redactions and relations
- ensure queued relations and redactions to an unsent target have their local id replaced with a remote id before being sent:
- have one method to return the related id for redactions and relations (getRelatedId) on Event
- emit event on MatrixEvent once remote id is known
- make the scheduler start sending a new event asynchronously, so the above code gets a chance to run before the next event is sent. (not entirely happy with this, we're relying on async implementation details that make this work, suggestions welcome)
- preserve the locally redacted state when receiving the remote echo
- don't re-add a locally redacted reaction when receiving remote echo
Hammering the react button now …
=>  Support redactions and relations of/with unsent events.

src/store/indexeddb.js, src/store/memory.js
Add a 'force' flag to to the save method of the store to force the
store to save its data even if it wouldn't normally.
=> Add flag to force saving sync store

src/client.js, src/crypto/index.js
- fix requestVerification in MatrixClient to match the function in crypto
- reorder the arguments so that the arguments actually do what they say they
do
- pass through the third argument, which was accidentally omitted
- ignore verification requests from ourselves
- also fix a comment
=> Key verification request fixes

src/models/event.js
Replacement PR for https://github.com/matrix-org/matrix-js-sdk/pull/959 to make branch names same as https://github.com/matrix-org/matrix-react-sdk/pull/3117, so karma tests can pass.
Related to https://github.com/vector-im/riot-web/issues/10080
=> return 'sending' status for an event that is only locally redacted

src/crypto/index.js, src/models/event.js, src/sync.js
Fixes https://github.com/vector-im/riot-web/issues/10083
Fixes https://github.com/vector-im/riot-web/issues/9197
Fixes https://github.com/vector-im/riot-web/issues/8629
The issue is partially fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3123 in that users would no longer see "Incoming request", but would launch their client to a bunch of "key verification cancelled" dialogs. To work around this, we just don't handle key verification requests which we know are cancelled.
The changes are a bit awkward (flagging the event as cancelled instead of filtering it) because:
* We probably don't want to prevent events getting sent over the EventEmitter because applications may still rely on them.
* The cypto side only has visibility of 1 event at a time, so it needs to have some kind …
=> Don't handle key verification requests which are immediately cancelled

src/crypto/verification/Base.js
Fixes https://github.com/vector-im/riot-web/issues/10117
Fixes https://github.com/vector-im/riot-web/issues/9103 (I think?)
=> Time out verification attempts after 10 minutes of inactivity

src/client.js
Fixes https://github.com/vector-im/riot-web/issues/9966
=> Check for lazy-loading support in the spec versions instead

src/models/room.js
The default room version in the spec is v4 due to widespread adoption. We should mirror that.
=> Change the known safe room version to version 4

src/client.js
For reactions, there is a very little gained by encrypting the entire event, as
relation data is already kept in the clear. Event encryption for a reaction
effectively only obscures the event type, but the purpose is still obvious from
the relation data, so nothing is really gained. It also causes quite a few
problems, such as:
* triggers notifications via default push rules
* prevents server-side bundling for reactions
The reaction key / content / emoji value does warrant encrypting, but this will
be handled separately by encrypting just this value.
See https://github.com/matrix-org/matrix-doc/pull/1849#pullrequestreview-248763642
Fixes https://github.com/vector-im/riot-web/issues/10130
=> Disable event encryption for reactions

src/base-apis.js, src/client.js
Needed for https://github.com/vector-im/riot-web/issues/9490
React-sdk PR: https://github.com/matrix-org/matrix-react-sdk/pull/3144
=> Relations endpoint support

src/client.js
Part of https://github.com/matrix-org/matrix-react-sdk/pull/3151
=> Handle relations in encrypted rooms

src/ReEmitter.js, src/client.js
Fixes https://github.com/vector-im/riot-web/issues/9421
This also adds a context to the ReEmitter so we have access to the Room at the time of read receipt. Without this, we have to bind handlers to every encrypted room (which is tedious to maintain) or figure out which room `$something` belong to (CPU intensive).
=> Handle self read receipts for fixing e2e notification counts

spec/integ/matrix-client-event-emitter.spec.js, src/client.js, src/http-api.js
**For https://github.com/matrix-org/matrix-react-sdk/pull/3177**
Note: The `call` argument previously defined in the SDK was never actually populated, and appears to be a documentation error when the definition was copied from `Call.incoming` directly above it.
=> Include the error object when raising Session.logged_out

src/client.js
event.getPushRules() may return null (for better or worse...).
Use client.getPushRulesForEvent which will calculate them if they
haven't already been calculated.
Fixes https://github.com/vector-im/riot-web/issues/10269
=> Fix exception whilst syncing

src/pushprocessor.js
This adds a default push rule to ignore reactions as proposed in
[MSC2153](https://github.com/matrix-org/matrix-doc/pull/2153). By adding it here
in the client directly, we can try out the idea early even if it hasn't appeared
in the user's HS yet.
Part of https://github.com/vector-im/riot-web/issues/10208
=> Add default push rule to ignore reactions

src/client.js, src/models/room.js
This changes the methods that update the read marker and read receipts to
prevent advancing into pending events.
Part of https://github.com/vector-im/riot-web/issues/9952
=> Block read marker and read receipt from advancing into pending events

src/client.js, src/crypto/index.js
For https://github.com/vector-im/riot-web/issues/10263 / https://github.com/matrix-org/matrix-react-sdk/pull/3187
Starting/scheduling the backup won't help us because the token would be invalid from a server perspective. Instead, we should update what needs to be done and return a count.
=> Add a function to flag keys for backup without scheduling a backup

src/models/event.js, src/models/relations.js
This will prevent riot showing the wrong content for an edit event if we have a later SSA edit. This *does* trigger https://github.com/vector-im/riot-web/issues/10290 when redacting the last edit but that is a lesser issue IMO, and needs fixing separately.
=> Don't accept any locally known edits earlier than the last known server-side aggregated edit

spec/integ/matrix-client-methods.spec.js, spec/unit/content-repo.spec.js, src/base-apis.js, src/client.js, src/content-repo.js, src/http-api.js, src/models/event.js, src/models/room-member.js, src/models/room.js
Fixes https://github.com/vector-im/riot-web/issues/5325
**Please review with https://github.com/matrix-org/matrix-react-sdk/pull/3202**
Done:
* Where stable, use stable over unstable
* Where unstable, use unstable (key backup; identicons)
* Deprecate identicon usage (I'm also pretty sure Synapse 1.0 doesn't have this support anymore - https://github.com/matrix-org/matrix-js-sdk/issues/992)
* Fix media URLs to use stable versions (v1 is technically valid, but we're on the v2 (r0) CS spec now)
=> Stabilize usage of stably stable APIs (in a stable way)

spec/unit/crypto/verification/request.spec.js, spec/unit/crypto/verification/sas.spec.js, src/crypto/verification/Base.js
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/980
This also improves cleanliness in the tests to cancel/terminate timers when needed. The tests have complicated mocks which prevent some conditions from hitting the `_endTimer` function in their test functionality, therefore we need to call it directly.
=> End the verification timer when verification is done

src/base-apis.js
Turns out `HTTP /devices undefined` is invalid.
Regressed in https://github.com/matrix-org/matrix-js-sdk/pull/990
=> Add a request method to /devices

src/client.js
This sets some limits on room upgrade history:
- Tombstones which self reference the room they are sent to cause the history fetching process to cease. 
- If the array which stores historical rooms ever contains two of the same room, the history fetcher returns early.
=> Tombstone bugfixes

src/base-apis.js, src/pushprocessor.js, src/sync.js
and change our internal default for tombstones
=> Support rewriting push rules when our internal defaults change

src/base-apis.js, src/http-api.js
This adds support for querying `/bulk_lookup` on the IS to check several 3PIDs
at the same time.
Part of https://github.com/vector-im/riot-web/issues/10159
=> Add API for bulk lookup on the Identity Server

src/base-apis.js
POST bodies for v2 IS requests must be sent as JSON.
Part of https://github.com/vector-im/riot-web/issues/10159
=> Fix POST body for v2 IS requests

src/base-apis.js, src/client.js, src/http-api.js, src/utils.js
Hopefully fairly self explanatory. The ID server URL can be changed
fairly readily, whereas the HS URL would require a different access
token etc.
=> Add setIdentityServerUrl

src/client.js, src/webrtc/call.js
This changes the STUN fallback server from a Google server to one hosted at
`turn.matrix.org`. This also changes the ICE server fallback to be disabled by default. The SDK consumer will receive a new event in case the homeserver has no ICE servers of its own,
and can prompt the user to agree to the fallback if desired.
Part of https://github.com/vector-im/riot-web/issues/10173
Used by https://github.com/matrix-org/matrix-react-sdk/pull/3309
=> Change ICE fallback server and make fallback opt-in

package.json, src/client.js
Hopefully with doc in appropriate functions
=> Make requestToken endpoints work without ID Server

src/client.js
Remove individual cache for lazy loading and just cache the whole
versions response, then we can cache both of these flags
=> Add getIdServer() & doesServerRequireIdServerParam()

src/base-apis.js, src/http-api.js
Fixes https://github.com/vector-im/riot-web/issues/10556
Implements [MSC2134](https://github.com/matrix-org/matrix-doc/pull/2134) with assistance from [MSC2140](https://github.com/matrix-org/matrix-doc/pull/2140) for auth.
Note: this also changes all identity server requests to use JSON as a request body. URL encoded forms were allowed in v1 but deprecated in favour of JSON. v2 APIs do not allow URL encoded forms.
=> Use the v2 (hashed) lookup for identity server queries

src/base-apis.js, src/http-api.js
JSON is JSON, so use JSON when dealing with JSON for JSON things because it's JSON.
=> Clean up JSON handling in identity server requests

src/base-apis.js, src/client.js
This passes along the `id_access_token` to the HS, which it will need when
speaking v2 IS APIs to the IS.
Unfortunately, some HSes seem to explode when given this new parameter, so we
only pass it along for the moment if an unstable feature `m.id_access_token` is
also set.
Part of https://github.com/vector-im/riot-web/issues/10525
Used by https://github.com/matrix-org/matrix-react-sdk/pull/3337
Defined in [MSC2140](https://github.com/matrix-org/matrix-doc/pull/2140)
=> Send id_access_token to HS for use in proxied IS requests

src/http-api.js
For example, if the identity server throws a 401 on `/account`, we end up here with a JSON object. Don't convert the string `object Object` to JSON because it'll fail: just use the object.
=> Don't convert errors to JSON if they are JSON already

src/client.js
For https://github.com/matrix-org/matrix-react-sdk/pull/3371
Note: they're all intentionally named to have "Synapse" somewhere in the function name. These are implementation-specific endpoints that we don't want to be perceived as Matrix spec.
=> Add Synapse admin functions for deactivating a user

src/base-apis.js, src/client.js
See https://github.com/matrix-org/matrix-react-sdk/pull/3395
=> Support hidden read receipts

src/models/room.js
If a member event was redacted, we weren't updating the current
state.
=> Update room members on member event redaction

src/models/room.js
https://github.com/matrix-org/matrix-js-sdk/pull/1026 to release
Fixes https://github.com/vector-im/riot-web/issues/10876
=> [Release] Fix addPendingEvent with pending event order == chronological

src/client.js
To avoid the same problem that happened with lazy-loading (see https://github.com/matrix-org/synapse/issues/5528).
Note that as of writing r0.6.0 is not yet released, however it is the next scheduled release of the client-server API.
Fixes https://github.com/vector-im/riot-web/issues/10883
=> Check for r0.6.0 support in addition to unstable feature flags

src/webrtc/call.js
Fixes https://github.com/vector-im/riot-web/issues/10898
In some restricted modes of Firefox, the WebRTC classes aren't super available: accessing them can cause SecurityErrors to be raised. In these conditions, we should just disable WebRTC support instead of falling apart.
=> Handle WebRTC security errors as non-fatal

src/client.js
This removes the IS details (server and access token) from `requestToken` calls
to the HS, as long as the HS supports the new separate add and bind mode. In
this mode, all of the 3PID validation is handled by the HS, so the IS details
are not used.
Fixes https://github.com/vector-im/riot-web/issues/10933
=> Remove IS details from requestToken to HS

src/interactive-auth.js
For HSes that do not require an IS, we can remove `id_server` from the auth
params.
Fixes https://github.com/vector-im/riot-web/issues/10959
=> Remove id_server from creds for interactive auth

release.sh
Always run `yarn cache clean` during the `dist` step to workaround a Yarn bug
with Git commit package dependencies.
=> Clean Yarn cache during release

src/crypto/index.js
Otherwise we throw massive exceptions on redacted crypto events which is a bit OTT.
=> Ignore crypto events with no content

README.md, package.json, src/crypto/OlmDevice.js, yarn.lock
...whenever we encrypt or decrypt a message on them. This adds
another line of logging for every device in the room, so will
be reasonably verbose if you're in large encrypted rooms, but
the information ought to be valuable.
Requires https://gitlab.matrix.org/matrix-org/olm/merge_requests/9
Don't merge before a new version of Olm is released with this merge
request (it won't work).
=> Log state of Olm sessions

src/crypto/store/localStorage-crypto-store.js
This removes a `.js` from one of the imports. This was causing me issues while trying to update the SDK used in Thunderbird and it seems unnecessary. Running the tests locally pass and I'm pretty sure there's no need for it since none of the other imports use it.
=> Don't include .js in the import string.

package.json, yarn.lock
Bluebird 3.6.0+ [currently breaks](https://github.com/petkaantonov/bluebird/issues/1623) in at least Firefox with errors in their
rejection tracking approach. For now, this retreats back to the version we had
used for a long time.
Regressed by https://github.com/matrix-org/matrix-js-sdk/pull/1053
Fixes https://github.com/vector-im/riot-web/issues/11148
=> Downgrade to Bluebird 3.5.5 to fix Firefox

spec/unit/crypto/verification/sas.spec.js, spec/unit/crypto/verification/util.js, src/client.js, src/crypto/index.js, src/crypto/verification/Base.js, src/crypto/verification/SAS.js
Fixes vector-im/riot-web#10793
implements [MSC2241](https://github.com/matrix-org/matrix-doc/pull/2241)
also cleans up some bits of code, and removes some obsolete (will no longer be used) code
=> verification in DMs

src/client.js, src/crypto/algorithms/megolm.js, src/http-api.js, src/interactive-auth.js, src/models/event-timeline-set.js, src/models/event.js, src/models/room-state.js, src/models/room.js, src/realtime-callbacks.js, src/scheduler.js, src/store/indexeddb-local-backend.js, src/store/indexeddb-remote-backend.js, src/store/indexeddb-store-worker.js, src/store/indexeddb.js, src/sync-accumulator.js, src/sync.js, src/timeline-window.js, src/webrtc/call.js
Currently, some logger imports force it to import the file from `/src`, which means that babel-ified code will try to import non-babel-ified code.  While `/src/logger.js` current doesn't have anything weird in it, it's probably not a good idea to depend on that, and we should drop the `../src` from the path.
=> fix the path in references to logger.js

src/base-apis.js, src/client.js
If the server advertises spec version r0.6.0, it must have the 3PID APIs
available under the stable API prefix.
Fixes https://github.com/vector-im/riot-web/issues/11246
=> Use stable API prefix for 3PID APIs when supported

src/crypto/verification/Base.js
This fixes the verifier not handling incoming `m.key.verification.cancel` events, and just treating them as unexpected and sending a `m.key.verification.cancel` event of its own with an error. These double `m.key.verification.cancel` events make it harder to detect which user actually pressed cancel.
Initial PR for verification over DM was https://github.com/matrix-org/matrix-js-sdk/pull/1050
=> Don't double cancel verification request

src/client.js
`/whois` is unreliable due to it returning 200 OK if you are requesting info about yourself.
=> Check the right Synapse endpoint for determining admin capabilities

src/client.js
We had a bunch of logic in place to suppress calls if the answer
or hangup had already arrived, but we only used it on startup.
This extends this logic to happen all the time, which means we'll
also do the same suppression if a call happenned while we were
offline.
=> Always process call events in batches

package.json
...whose only purpose was to run the tests without coverage because
the coverage tool was awful and ruined all the line numbers (moreso).
=> Remove 'check' npm script

src/client.js, src/crypto/index.js, src/models/event.js
And emit `crypto.verification.request` events for both verification over DM and mock it (see commit messages) for to_device verifications.
Required for https://github.com/matrix-org/matrix-react-sdk/pull/3661
=> Monitor verification request over DM as well

src/client.js
Events will be decrypted after the sync event, so we were having
to wait until the next sync event before they got processed.
=> Fix calls in e2e rooms

spec/unit/autodiscovery.spec.js, src/autodiscovery.js
As discussed in MSC2284, this relaxes the identity server discovery to a
`FAIL_PROMPT` state so that clients can choose to warn and continue.
Part of https://github.com/vector-im/riot-web/issues/11102
Implements https://github.com/matrix-org/matrix-doc/pull/2284
=> Relax identity server discovery checks to FAIL_PROMPT

src/pushprocessor.js, src/utils.js
Fixes https://github.com/vector-im/riot-web/issues/11460
Empty strings are falsey, and the state key match for a tombstone event is an empty string. Ergo, nothing happens because all the conditions fail. 
This PR also does a small amount of drive-by cleanup.
Evidence of this working:
=> Fix empty string handling in push notifications

spec/unit/crypto.spec.js
Deep within the crypto layers we call `getId()`, and when we don't have that function the async call on the emitter fails but doesn't fail the test. This manifests as a timeout because the code path that would call the thing blew up.
Part of https://github.com/vector-im/riot-web/issues/11520
=> Fix Olm unwedging test

spec/unit/crypto/verification/sas.spec.js
I don't know why it's broken, but the two errors I can get out of it are "unknown device for verification" and "user_signing key does not match". Someone who knows a bit more about cross-signing will probably need to take a look at this one.
Fixes https://github.com/vector-im/riot-web/issues/11520 (technically)
Opened https://github.com/vector-im/riot-web/issues/11545 to fix this correctly. After hours of trying to fix it, I'm giving up and disabling it in the interest of time.
=> Disable broken cross-signing test

spec/unit/crypto/verification/sas.spec.js
It took more than 0.1 seconds between when `bob.httpBackend.flush` is called and when the request is actually made, so `flush` stops trying to respond to the message, which means that when it does finally make the request, it never gets a response.  Increasing the timeout on `flush` makes it keep trying for longer.
Also the requests to `/keys/query` are apparently never made, so remove them.
fixes: vector-im/riot-web#11545
=> increase timeout on flush to fix failing unit test

src/crypto/DeviceList.js
Some variables were changed during the course of the initial cross-signing PR
(https://github.com/matrix-org/matrix-js-sdk/pull/832) without updating the
storage path to match, so we weren't storing / loading cross-signing info for
devices in the end.
This updates storage and loading to match where the data now lives in memory.
=> Fix device list's cross-signing storage path

spec/unit/crypto/verification/qr_code.spec.js, spec/unit/crypto/verification/sas.spec.js, spec/unit/crypto/verification/util.js, src/crypto/index.js, src/crypto/verification/Base.js, src/crypto/verification/Error.js, src/crypto/verification/SAS.js, src/crypto/verification/request/InRoomChannel.js, src/crypto/verification/request/RequestCallbackChannel.js, src/crypto/verification/request/ToDeviceChannel.js, src/crypto/verification/request/VerificationRequest.js
Part of https://github.com/vector-im/riot-web/issues/11224
This extracts most of the verification request code from `crypto/index` and puts it into it's own `VerificationRequest` class with the specificities of whether to use to_device verification or verification over DM into a `Channel` class. Care has been taken to maintain the same public API from the crypto module and the request object passed as an argument of the crypto.verification.request event.
The next step will be add support for the `m.key.verification.ready` event, and to decorate verification events with a `verificationRequest` property and use this to drive toasts and verification timeline tiles in the react-sdk, removing the `KeyVerificationStateObserver`.
=> Refactor verification request code

src/crypto/verification/request/VerificationRequest.js
Should fix https://github.com/vector-im/riot-web/issues/11639
Problem is that `sendRequest` already changes the phase, and when `_handleRequest` would process the remote echo of that event, it would cancel because the phase is not UNSENT anymore. We should not cancel if the phase is already REQUESTED and just ignore.
=> dont cancel on remote echo of own .request event

src/crypto/verification/Base.js, src/crypto/verification/SAS.js
This should fix some test flakiness.
=> ignore m.key.verification.done messages when we don't expect any more messages

src/crypto/index.js
This check for new keys was always true, instead of checking whether something
was added.
=> Fix check for private keys

src/client.js
This was added with cross-signing work, but nothing actually emits it. Let's
remove it until we find a need.
=> Remove unused user verification event

spec/unit/crypto/backup.spec.js, src/client.js, src/crypto/index.js, src/crypto/olmlib.js
This add various helpers for creating and restoring key backups where the private key is stored in secret storage.
Part of https://github.com/vector-im/riot-web/issues/11209
Used by https://github.com/matrix-org/matrix-react-sdk/pull/3720
=> Add support for key backups using secret storage

src/crypto/SecretStorage.js, src/crypto/index.js
So we can migrate key backup keys
Adding a passthrough secret itself isn't exposed outside of the
js-sdk: hopefully this should only ever be necessary for this
bootstrap process which the js-sdk handles.
=> Add support for passthrough SSSS secrets

src/matrix.js
**This is against `travis/sourcemaps` for safety.**
Split from https://github.com/matrix-org/matrix-js-sdk/pull/1130
`request` is a function in the context of this file, though it's the function to set the `request` function and not the `request` function itself. We store the `request` function under `requestInstance`.
----
This PR and others in the series have their overview covered here: https://gist.github.com/turt2live/a3fc7c9712b8ef0f1f758611aa33382d
=> Use the right request when creating clients

src/crypto/store/indexeddb-crypto-store.js
**This is against `travis/sourcemaps` for safety.**
Split from https://github.com/matrix-org/matrix-js-sdk/pull/1130
This is just a bug - we are using `IndexedDBCryptoStoreBackend.Backend` later in the file, so we should import the right value.
----
This PR and others in the series have their overview covered here: https://gist.github.com/turt2live/a3fc7c9712b8ef0f1f758611aa33382d
=> Fix import for indexeddb crypto store

package.json
**This is against `travis/sourcemaps` for safety.**
Split from https://github.com/matrix-org/matrix-js-sdk/pull/1130
See https://github.com/vector-im/riot-web/pull/11679/commits/a1c9551bc8a1a6d61afed7e87ff7cebb3042a5ac
----
This PR and others in the series have their overview covered here: https://gist.github.com/turt2live/a3fc7c9712b8ef0f1f758611aa33382d
=> Add additional properties to package.json for riot-web's webpack

src/crypto/index.js
We did check if it was signed with a cross signing key which should
be the norm going forward, but for completeness, use the proper
cross-signing ernabled check for sigs from individual devices too.
Also adds a deviceTrust member to the signature so the app can see
the cross-signing trust status ofthe device without having to
recalculate it.
=> Use checkDeviceTrust with key backup

src/client.js, src/crypto/index.js
It broke if no secret key callback was supplied but a cross-signing
identity did exist (as hopefully explained in comment).
Fixes https://github.com/vector-im/riot-web/issues/11763
=> Fix creating a key backup with cross signing diabled

src/scheduler.js
Part fix for https://github.com/vector-im/riot-web/issues/10585
=> stop trying to resend event if we get M_TOO_LARGE

src/models/room-member.js, src/utils.js
It may be a little too strict but better that than letting people pretend to be others
The exact push for this was someone with an invisible displayName which was just U+202E (RTL Override)
Before:
After:
=> Make displayName disambiguation more fuzzy especially against RTL/LTR content

spec/integ/megolm-integ.spec.js, spec/unit/crypto/algorithms/megolm.spec.js, src/crypto/OlmDevice.js, src/crypto/algorithms/megolm.js, src/crypto/index.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js
Implements part of [MSC2399](https://github.com/matrix-org/matrix-doc/pull/2399) (notifications on initial key sending, but not on keyshare requests, and does not properly handle `m.no_olm` yet -- the remaining functionality will come in a future PR).
=> notify devices when we don't send them keys

src/crypto/OlmDevice.js
make sure to exit the function when we detect an error, rather than continuing.
=> Fix error handling in decryptGroupMessage

spec/unit/content-repo.spec.js, src/client.js, src/content-repo.js, src/matrix.js, src/models/room-member.js, src/models/room.js
**This is against `travis/sourcemaps` for safety.**
Split from https://github.com/matrix-org/matrix-js-sdk/pull/1130
~~Exporting it the way we were was causing problems for webpack way down the line, so we export it differently here to get around that. We also have to fix all the import references so we import the right thing.~~
Per the comments later on in this PR we now use more standard exports for safety reasons.
----
This PR and others in the series have their overview covered here: https://gist.github.com/turt2live/a3fc7c9712b8ef0f1f758611aa33382d
=> Use a safer import/export scheme for the ContentRepo utilities

src/crypto/algorithms/megolm.js
so that we don't duplicate the ciphertext for everyone.
Because right now, we're sending everyone's ciphertext to everyone in the same batch, when we should only be sending the ciphertext that's encrypted for that one device.  Which means that our payload is 20x what it should be.
=> use a separate object for each encrypted content

src/crypto/index.js
Add a signature from the cross-signing master key to the key
backup when upgrading the key backup into cross-signing.
For https://github.com/vector-im/riot-web/issues/11747
=> Sign key backup with cross-signing key on upgrade

src/crypto/algorithms/megolm.js
Currently we split the device messages up to limit the number per call,
but that can end up splitting messages to a given users device over
separate API calls. This is fine, but means that the server can't e.g.
bundle them into a single EDU for remote users or sanity check that the
client is sending to the right set of devices (i.e. its device list
cache isn't wrong).
---
P.S. I have no idea what I'm doing.
=> Send device messages for the same user in same API call.

spec/unit/crypto/algorithms/megolm.spec.js, src/crypto/OlmDevice.js, src/crypto/algorithms/base.js, src/crypto/algorithms/megolm.js, src/crypto/index.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js
Implements the `no_olm` part of [MSC2399](https://github.com/matrix-org/matrix-doc/pull/2399), and tells the user when the olm session got wedged.
The general algorithm is that when there's a problem with the olm session (either it's wedged, or the sender tells us they can't establish a session), then we try to recover by creating a session ourselves.  Then we record the problem, timestamp, and whether we (think we) fixed the problem.  When we have a megolm event that we can't decrypt, we check if it was sent within the time that we had a problem, and if so, tell the user what the problem was, and whether we were able to fix it.
=> record, report, and notify about olm errors

src/client.js
This adds an API account data getter that bypasses the local store and goes
directly to the homeserver.
Part of https://github.com/vector-im/riot-web/issues/11214
Used in https://github.com/matrix-org/matrix-react-sdk/pull/3847
=> Add API to get account data from server

src/models/room.js
Might fix https://github.com/vector-im/riot-web/issues/11820 but I cannot reproduce
=> Add v5 as a safe room version

spec/unit/crypto/secrets.spec.js, src/client.js, src/crypto/CrossSigning.js, src/crypto/SecretStorage.js, src/crypto/index.js
This converts all secret storage to use a newer account data API which uses
cached data in stored when available, but also knows how to ask the homeserver
in case it's invoked during early client startup before the initial sync.
As a consequence, it means most secret storage APIs are now async.
Part of https://github.com/vector-im/riot-web/issues/11901
Used by https://github.com/matrix-org/matrix-react-sdk/pull/3864
=> Convert secret storage to new account data API

src/base-apis.js
This is useful for querying the supported auth methods.
=> Allow a device key upload request without auth

package.json
So we actually build the lib directory before publishing it
=> Add a prepare script

spec/unit/crypto/verification/request.spec.js, spec/unit/crypto/verification/verification_request.spec.js, src/crypto/verification/request/InRoomChannel.js, src/crypto/verification/request/ToDeviceChannel.js, src/crypto/verification/request/VerificationRequest.js
Fixes https://github.com/vector-im/riot-web/issues/11964
When another client send the .ready event, the observing client ended up putting it in the "their" event map, and therefore not entering observeOnly mode.
Also added unit tests.
=> For dm-verification, also consider events sent by other devices of same user as "our" events

src/crypto/index.js
As hopefully explained in the comment. The symptom of this was that
bootstrapping would work just fine the first time you called it
in any run of the app, but then if called a second time (eg. if you
cancelled by dismissing the password prompt) it would create keys and
upload the public parts but not store the private parts in SSSS,
leaving you with cross signing keys you don't have the private parts
of.
Also use object.assign in the save keys callback just in case we
ever reset a subset of the keys (and also because it makes it a
bit simpler to reason about what objects are where).
=> Fix bootstrap cleanup

spec/unit/crypto/secrets.spec.js, src/crypto/index.js
When checking cross-signing trust during login, we may not have downloaded keys
yet. This ensures we make an attempt first if needed.
Fixes https://github.com/vector-im/riot-web/issues/12068
=> Ensure cross-signing keys are downloaded when checking trust

release.sh
npm will install the newest version a package has published to the `latest` tag,
including pre-releases, which is not ideal since those may not be ready for
production use yet.
This uses an alternate tag (`next` is a common convention, but it can be
anything) for pre-releases so the default installs only get stable versions.
Fixes https://github.com/vector-im/riot-web/issues/12029
=> Publish pre-releases as a separate tag on npm

src/crypto/index.js
The key backup needs to be signed by the cross-signing key so
doing it here allows us to do it before we blow the private part
out of memory.
=> Add option to bootstrap to start new key backup

spec/unit/crypto/verification/verification_request.spec.js, src/crypto/verification/Base.js, src/crypto/verification/SAS.js, src/crypto/verification/request/VerificationRequest.js
Fixes https://github.com/vector-im/riot-web/issues/11991
React-SDK PR: https://github.com/matrix-org/matrix-react-sdk/pull/3976
During SAS verification, the messages sent back and forth are not symmetrical. There is the initiating side (sending the `.start` event) and the receiving side (sending the `.accept` event).
When both parties click "verify by emoji", they create a verifier and nominate themselves as the initiating side, resulting in a deadlock where both sides await the `.accept` event.
We can't just create a new verifier in this case, as we've already returned the verifier from `beginKeyVerification`, so we need to switch to the new `.start` internally, and retry, deciding as which side we should act depending on who sent the start event.
The …
=> Verification: resolve race between .start events from both parties

src/sync.js
As hopefully explained by comment.
Fixes https://github.com/vector-im/riot-web/issues/11120
=> Don't add ephemeral events to timeline when peeking

spec/unit/crypto/verification/qr_code.spec.js, src/crypto/index.js, src/crypto/verification/IllegalMethod.js, src/crypto/verification/QRCode.js, src/crypto/verification/request/VerificationRequest.js
**For https://github.com/matrix-org/matrix-react-sdk/pull/3959**
=> Update QR code handling for new spec

src/crypto/verification/request/VerificationRequest.js
I don't know why this is undefined at this point, or why membership events are ending up here, but this fixes develop for people.
See https://github.com/vector-im/riot-web/issues/12231
=> Don't explode verification validation if we don't have an event type

src/crypto/verification/request/VerificationRequest.js
so we can more easily see (especially for to_device requests)
why something was cancelled, to debug issues like https://github.com/vector-im/riot-web/issues/12226
=> add logging when a request is being cancelled

spec/unit/crypto/verification/InRoomChannel.spec.js, src/crypto/verification/request/InRoomChannel.js
More permanent fix for https://github.com/vector-im/riot-web/issues/12231, which is already fixed in https://github.com/matrix-org/matrix-js-sdk/pull/1194/
Regressed in https://github.com/matrix-org/matrix-js-sdk/pull/1193
=> Fix: always return a valid string from InRoomChannel.getEventType

examples/crypto-browser/lib/.gitignore, examples/crypto-browser/lib/matrix.js, examples/crypto-browser/olm-device-export-import.html, examples/crypto-browser/olm-device-export-import.js, examples/olm-device-export-import.html, spec/unit/crypto/algorithms/olm.spec.js, src/client.js, src/crypto/OlmDevice.js, src/crypto/index.js, src/crypto/store/memory-crypto-store.js
Adds an `export` method to Olm device that exports the device “account” and “sessions”.
Adds a parameter to the asynchronous initialization of the Olm device to import data that was exported with the said export method.
Adds methods to Matrix Client to expose these methods at a high level, including the device ID and user ID in the exported data (and using them during import).
Adds Jest tests for export/import at the Olm device level, and a HTML + JS document to try the mechanism in the browser at a high level in a non-automated way.
=> add export/import of Olm devices

src/crypto/index.js
relates to https://github.com/vector-im/riot-web/issues/12221
=> New option to fully reset Secret Storage keys in boostrapSecretStorage

spec/unit/crypto/verification/sas.spec.js, src/client.js, src/crypto/index.js
Fixes https://github.com/vector-im/riot-web/issues/12319
It's easy for all the calls in react-sdk to `requestVerification(DM)` to have a different set of methods they pass along. There is also little value to it, as clients built on top of js-sdk can already select the subset of methods they can provide an UI for through the `verificationMethods` option when creating the client.
This is sort of a breaking change, as the extra argument consumers of the js-sdk might still pass will be ignored.
=> Remove methods argument to verification

src/crypto/verification/SAS.js
To help debug https://github.com/vector-im/riot-web/issues/12226
=> log MAC calculation during SAS

src/client.js, src/crypto/index.js, src/crypto/verification/SAS.js, src/crypto/verification/request/InRoomChannel.js, src/crypto/verification/request/ToDeviceChannel.js, src/crypto/verification/request/VerificationRequest.js
Related to https://github.com/vector-im/riot-web/issues/11698
=> Find existing requests when starting a new verification request

release.sh
This ensures that anyone who wants the latest version (pre-release or final
release) can always use the `next` tag.
**Note:** Targetting the release branch.
=> Always publish to `next` tag

src/crypto/verification/request/VerificationRequest.js
Part of https://github.com/vector-im/riot-web/issues/12368
=> method for checking if other party supports verification method

src/crypto/verification/Base.js
had a local error that was seemingly caused by this
=> don't assume verify has been called when receiving a cancellation in verifier

src/client.js, src/crypto/DeviceList.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/memory-crypto-store.js
At least on Safari but perhaps other browsers as well, you must perform
IndexedDB operations in the same JS task as you start the transaction. As a
concrete example, you cannot open the transaction and await some promise before
actually using it.
This fixes the crypto store to meet this requirement.
Fixes https://github.com/vector-im/riot-web/issues/12207
=> Perform crypto store operations directly after transaction

src/crypto/verification/Base.js, src/crypto/verification/request/ToDeviceChannel.js, src/crypto/verification/request/VerificationRequest.js
Fixes https://github.com/vector-im/riot-web/issues/12358
Instead, call onVerifierFinished from the verifier on the request
so we can internally mark it as done. This flag is not persisted,
but we don't have historical (persisted) to-device requests anyway.
=> Don't require .done event for finishing self-verification

src/crypto/index.js
When sharing room keys with our own devices, this ensure we check both
cross-signing and local trust.
Fixes https://github.com/vector-im/riot-web/issues/12596
=> Check both cross-signing and local trust for key sharing

src/crypto/index.js
This changes to cross-signing trust as well as local trust when we decide
whether to tell the homeserver a session of room keys is verified.
Fixes https://github.com/vector-im/riot-web/issues/12599
=> Use cross-signing trust to mark backups verified

src/crypto/index.js
This converts the cross-signing trust to a boolean as required by the
homeserver.
Regressed by https://github.com/vector-im/riot-web/issues/12599
Fixes https://github.com/vector-im/riot-web/issues/12618
=> Fix regression in key backup request params

spec/unit/crypto/verification/secret_request.spec.js, src/client.js, src/crypto/CrossSigning.js, src/crypto/verification/Base.js
Fixes: https://github.com/vector-im/riot-web/issues/12302
To view the cache:
```
let { getCrossSigningKeyCache } = mxMatrixClientPeg.get()._crypto._crossSigningInfo._cacheCallbacks;
getCrossSigningKeyCache && await Promise.all([getCrossSigningKeyCache("self_signing"), getCrossSigningKeyCache("user_signing")])
```
=> For self-verifications, also request keys from the other device

spec/unit/crypto/verification/sas.spec.js, src/client.js, src/crypto/index.js
After https://github.com/matrix-org/matrix-react-sdk/pull/4180 is merged, this will not be used by the react-sdk anymore. Other users of the js-sdk might be using it (although I am not aware of any) so this is a breaking change.
=> Cleanup: remove crypto.verification.start event

src/crypto/verification/Base.js
When sharing keys, we should use `m.cross_signing` prefix.
Part of https://github.com/vector-im/riot-web/issues/12661
See also https://github.com/matrix-org/matrix-react-sdk/pull/4185
=> Fix secret sharing names to match spec

src/crypto/index.js
At the moment, uploading cross-signing key signatures is a slow process that can
potentially take many minutes (!) for large accounts / slow servers. This
changes to do the bootstrapping related versions of this in the background.
Note that key signature uploads for interactive flows like verification are
still blocking for now.
Fixes https://github.com/vector-im/riot-web/issues/12223
=> Upload cross-signing key signatures in the background

src/base-apis.js, src/http-api.js
Fixes https://github.com/vector-im/riot-web/issues/10443
**Review with https://github.com/matrix-org/matrix-react-sdk/pull/4191**
=> Remove v1 identity server fallbacks

spec/unit/crypto/algorithms/megolm.spec.js, src/base-apis.js, src/client.js, src/crypto/algorithms/base.js, src/crypto/algorithms/megolm.js, src/crypto/olmlib.js
- allow applications to pre-send decryption keys before the message is sent
- establish new olm sessions with a shorter timeout first, and then re-try in the background with a longer timeout without blocking message sending
fixes https://github.com/vector-im/riot-web/issues/11836
=> refactor megolm encryption to improve perceived speed

src/client.js, src/crypto/index.js
...rather than a verifier
Related to https://github.com/vector-im/riot-web/issues/12636
we need this method and can't use `beginKeyVerification` because react-sdk needs a request object to show in EncryptionPanel, and can't work with just a verifier anymore.
=> Add a method for legacy single device verification, returning a verification request

src/crypto/DeviceList.js, src/crypto/index.js
This both fixes the type to match what Synapse wants and uses the right user to compute trust.
Fixes https://github.com/vector-im/riot-web/issues/12693
=> Force `is_verified` for key backups to bool and fix computation

src/client.js
`tweaks` isn't guaranteed to be on the push actions, see for example `pushprocessor.js:352`. Might be related to https://github.com/vector-im/riot-web/issues/12677 (and good to fix anyway) as the logs contained this:
```
2020-03-11T00:20:33.614Z E Caught /sync error TypeError: Cannot read property 'highlight' of undefined
at MatrixClient.eval (webpack-internal:///40:412:68)
at MatrixClient.emit (webpack-internal:///38:157:7)
at ReEmitter._handleEvent (webpack-internal:///66:33:17)
at ReEmitter.forSource (webpack-internal:///66:41:24)
at Room.emit (webpack-internal:///38:152:5)
at Room.addReceipt (webpack-internal:///57:1708:8)
at Room.addEphemeralEvents (webpack-internal:///57:1508:12)
at eval (webpack-internal:///56:1253:10)
at Module.promiseMapSeries (webpack-internal:///33:894:11)
at …
```
=> Fix: prevent error being thrown during sync in some cases

src/crypto/index.js, src/errors.js
Relates to: https://github.com/vector-im/riot-web/issues/11574
I think the only user-visible change here is that when they fail to upload a key, a cancellation event now fires and so both sides see the change as cancelled. 
Inexplicably, the device that throws considers the other to be verified until it's refreshed.  I cannot track down why this is, and it looks like the way it's meant to work is that the key is uploaded and then retrieved in the next sync.
I think this task only half-completes the matter – the other is to surface it to the user.
=> If a key upload fails, throw an error and emit an event

src/crypto/algorithms/megolm.js
`devicesByUser` parameter should probably be userId => array of devices
In [a rageshake from Nad](https://github.com/matrix-org/riot-web-rageshakes/issues/2403) (which I requested just because there were a lot of errors in his console while he was sharing his screen) I saw quite a few of these:
```
TypeError: devices is not iterable
at Module.ensureOlmSessionsForDevices (webpack-internal:///74:197:30)
at MegolmEncryption.reshareKeyWithDevice (webpack-internal:///91:573:76)
at async Crypto._processReceivedRoomKeyRequest (webpack-internal:///85:2924:7)
at async Promise.all (index 0)
at async Crypto._processReceivedRoomKeyRequests (webpack-internal:///85:2885:5)
```
The `ensureOlmSessionsForDevices` implementation and other uses of it seem to assume that the devices come in an array, not in …
=> Fix: ensureOlmSessionsForDevices parameter format

src/crypto/index.js
This changes bootstrap to only upload the new device signature of the master
key. We were previously _adding_ the new signature, but then uploading both old
and new device key signatures of the master key.
This was particularly bad when re-uploading signatures from deleted devices, as
that would cause the homeserver to reject the entire upload.
Fixes https://github.com/vector-im/riot-web/issues/12752
=> Upload only new device signature of master key

spec/unit/crypto/CrossSigningInfo.spec.js, spec/unit/crypto/backup.spec.js, src/crypto/CrossSigning.js, src/crypto/store/indexeddb-crypto-store-backend.js, src/crypto/store/indexeddb-crypto-store.js, src/crypto/store/localStorage-crypto-store.js, src/crypto/store/memory-crypto-store.js
Relates to: https://github.com/vector-im/riot-web/issues/12704
=> Add a store for backup keys

spec/unit/crypto/algorithms/megolm.spec.js, src/crypto/algorithms/megolm.js
Apparently we missed using cross-signing trust in the js-sdk itself
Fixes https://github.com/vector-im/riot-web/issues/12245
=> Use checkDeviceTrust when computing untrusted devices

src/crypto/algorithms/megolm.js, src/crypto/olmlib.js
Don't need to do the shorter timeout and background retry when doing preparation to encrypt, and skip the second phase if the first phase already took longer than a normal otk claim.
Only retry claiming one-time key from servers that failed to respond the first time.
Correctly mark all failed devices as "handled" so we don't retry them.
Should help alleviate (or even fix) https://github.com/vector-im/riot-web/issues/12792
=> reduce number of one-time-key requests

spec/unit/crypto/backup.spec.js, src/client.js, src/crypto/index.js
Relates to https://github.com/vector-im/riot-web/issues/12704
=> Functions to cache session backups key automatically

src/client.js
This is already in an `await` so it didn't need to return a promise
=> remove unnecessary promise

src/crypto/SecretStorage.js, src/crypto/index.js
This series of changes causes us to cache the both the USK and SSK whenever we go through the bootstrap path. It also improves logging for secret sharing.
Fixes https://github.com/vector-im/riot-web/issues/12604
=> Cache user and self signing keys during bootstrap

src/client.js, src/crypto/CrossSigning.js, src/crypto/DeviceList.js, src/crypto/index.js
<del>TODO: Double check things are using the appropriate `isVerified / isCrossSigningVerified` for what they actually care about as this will only apply for things that check `isVerified()`.</del>
=> Add a flag for whether cross signing signatures are trusted

src/client.js
Allows guests to use the servers endpoint to try and fetch TURN servers. The configuration at the server decides if they are allowed to do this and either return the TURN servers or an GUEST_ACCESS_FORBIDDEN error.
Fixes #1274
=> Allow guests to fetch TURN servers

src/crypto/CrossSigning.js, src/crypto/index.js
which would cause key backups uploads to be missing is_verified
because it was set to `undefined` which would cause the backup to
fail
Fixes https://github.com/vector-im/riot-web/issues/12901
=> Fix isVerified returning false

src/webrtc/call.js
Screen sharing has never been working on recent versions of Chrome (fixes https://github.com/vector-im/riot-web/issues/6181).
This PR intends to use the new API getDisplayMedia() to make it works on all recent browsers : https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia
Signed-off-by: Maxime Jattiot <mjattiot@opensense.fr>
=> Make screen sharing works on Chrome using getDisplayMedia()

src/crypto/verification/request/InRoomChannel.js, src/crypto/verification/request/ToDeviceChannel.js, src/crypto/verification/request/VerificationRequest.js
Fixes https://github.com/vector-im/riot-web/issues/12733
We'll include .done events in the spec for to_device verification so later on we can signal with this event to the other party that we've successfully uploaded our cross-signing signature and are ready to respond to key gossiping requests.
For now, we're just sending the .done events and not delaying them until the signature upload completes, to be spec compliant when launching.
=> Send .done event for to_device verification

src/autodiscovery.js
Add null check for when there is no response. Seems like the tests were intermittently failing [here](https://buildkite.com/matrix-dot-org/matrix-react-sdk/builds/4676#c8bf091a-096c-4f11-901a-83072cb80c47/302-2039) (assuming because there was on network?).
=> Fix: error during tests

src/crypto/CrossSigning.js, src/crypto/DeviceList.js, src/crypto/index.js
This tracks whether we have ever cross-signing verified a user before (at least
as far as the current device has ever observed). This info helps to present an
alert in case the user subsequently becomes unverified.
Part of https://github.com/vector-im/riot-web/issues/12808
Used by https://github.com/matrix-org/matrix-react-sdk/pull/4303
=> Track whether we have verified a user before

spec/unit/crypto/secrets.spec.js, src/client.js, src/crypto/index.js
This passes through the new secret storage key as well as the key info so that
bootstrap can use it immediately without triggering an immediate prompt.
Part of https://github.com/vector-im/riot-web/issues/12867
Used by https://github.com/matrix-org/matrix-react-sdk/pull/4308
=> Receive private key for caching from the app layer

src/crypto/verification/request/InRoomChannel.js, src/crypto/verification/request/VerificationRequest.js
Fixes https://github.com/vector-im/riot-web/issues/12950
The `Room.timeline` event was being emitted twice, once when [adding the event to the notification timeline](https://github.com/matrix-org/matrix-js-sdk/blob/62bd41d/src/sync.js#L1340) and once [when adding live events](https://github.com/matrix-org/matrix-js-sdk/blob/62bd41d/src/sync.js#L1629).
Easiest solution was to have a look at the events already part of the request and see if the event_id is already in there.
=> Fix: spontanous verification request cancellation under some circumstances

src/client.js, src/crypto/SecretStorage.js, src/crypto/aes.js, src/crypto/index.js
fixes (partially) https://github.com/vector-im/riot-web/issues/12897 (along with https://github.com/matrix-org/matrix-react-sdk/pull/4309)
Only remaining question is if we need to migrate users who already have an existing Symmetric SSSS.
=> Add ability to check symmetric SSSS key before we try to use it

src/crypto/verification/QRCode.js, src/crypto/verification/request/VerificationRequest.js
This move the generation of the QR code from the react-sdk into the js-sdk. I did this to be able to keep the keys that are being verified attached on the verification request ([as we should not read the again from the store when signing](https://github.com/matrix-org/matrix-doc/pull/1544#discussion_r400787324)), and it also feels like a more natural place to put it.
The qr code data is now exposed on `VerificationRequest.qrCodeData` after moving into the ready phase if the other party can scan qr codes. `qrCodeData.buffer` is what needs to go into the QR code.
=> QR code reciprocation

src/crypto/index.js
For some reason, we were trying to cache the key backup key before it was
created, and as a result we wouldn't cache the key until perhaps a second time
through bootstrapping.
Fixes https://github.com/vector-im/riot-web/issues/13023
=> Move key backup key creation before caching

package.json
We apparently fixed 11 warnings at some point. Let's keep it that way.
=> Lower max-warnings to 81

src/interactive-auth.js
Ignore poll requests after a UIA session has finished. Sometimes
the app calls poll() even after the registration has succeeded
which causes the API call to happen again which, in the case of
registration, creates a phantom device.
Fixes https://github.com/vector-im/riot-web/issues/13040
=> Avoid creating two devices on registration

spec/TestClient.js, spec/integ/matrix-client-crypto.spec.js, spec/integ/matrix-client-methods.spec.js, src/base-apis.js
According to https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-keys-query
The request should contain:
```
{
"device_keys": {
"@alice:example.com": []
}
}
```
instead of
```
{
"device_keys": {
"@alice:example.com": {}
}
}
```
which currently gets send.
Signed-off-by: Marcel Radzio<mtrnord1@gmail.com>
=> Use the correct request body for the /keys/query endpoint.

src/crypto/CrossSigning.js, src/crypto/index.js, src/crypto/recoverykey.js, src/crypto/verification/Base.js
Bootstrap was incorrectly storing the key backup key as base64 encoded, when
instead it should be a Uint8Array.
Fixes https://github.com/vector-im/riot-web/issues/13057
=> Store key backup key in cache as Uint8Array

spec/unit/crypto/verification/sas.spec.js, src/crypto/verification/Base.js, src/crypto/verification/SAS.js, src/crypto/verification/request/VerificationRequest.js
Fixes https://github.com/vector-im/riot-web/issues/13106
Also marks the verification request as cancelled immediately if the verifier cancels (as that has a high risk of yielding an infinite spinner in case of SAS when sending fails).
=> Fix: catch send errors in SAS verifier

spec/unit/crypto/secrets.spec.js, src/client.js, src/crypto/SecretStorage.js, src/crypto/index.js
fixes https://github.com/vector-im/riot-web/issues/12970
I'm planning on tidying up the unit tests a bit, but otherwise this should be ready for review.
=> Fix incorrect backup key format in SSSS

src/client.js
This ensures our own user object is always available for tasks like
verification, even if you aren't in any rooms.
Fixes https://github.com/vector-im/riot-web/issues/13165
=> Always create our own user object

src/crypto/verification/QRCode.js
Fixes https://github.com/vector-im/riot-web/issues/13195
When doing self-verification with a QR code of a new web session (MSK still untrusted), we should mark our MSK as trusted.
=> Implement QR code reciprocate for self-verification with untrusted MSK

src/crypto/index.js
We re-used the old SSSS key even when resetting, meaning we prompted
the user to create a new passphrase but then ignored it and kept using
the old one.
Obviously this also needs to go to the 1.6 branch: I'll make another PR once approved.
Fixes https://github.com/vector-im/riot-web/issues/13212
=> Fix cross-signing/SSSS reset

src/crypto/OlmDevice.js, src/crypto/algorithms/olm.js
If they overlap, they can both try to create new sessions, but this
removes the OTK so it will only work once.
Fixes https://github.com/vector-im/riot-web/issues/13229
=> Serialise Olm prekey decryptions

spec/unit/interactive-auth.spec.js, src/interactive-auth.js
When there was no auth flow found, the attemptAuth promise didn't get rejected, which leads to the client not knowing that there was an error. This lead to issues like https://github.com/vector-im/riot-web/issues/13269, which should be fixed by this.
Due to my inexperience, I can't guarantee this won't break any flows in other clients though :/
Signed-off-by: Michael Kohler <me@michaelkohler.info>
Fixes https://github.com/vector-im/riot-web/issues/13269
=> Reject attemptAuth promise if no auth flow found

src/filter.js, src/sync.js
Fixes https://github.com/vector-im/riot-web/issues/13280
This had the side-effect that `room.timeline.limit` on the filter wasn't being set when using lazy loading. So since the introduction of lazy loading, we've been working with the default which is 10 IIRC. This will restore it to 20 as set in `MatrixClientPeg`.
=> Fix: don't do extra /filter request when enabling lazy loading of members

src/crypto/SecretStorage.js
It returned only when the echo came down the sync stream, but we
forgot to make it fail if the reuqest failed and it would just
never return in this case.
Fixes https://github.com/vector-im/riot-web/issues/13162
=> Fix setDefaultKeyId to fail if the request fails
